In [12]:
#How to calculate Currency conversion between 2 currencies

name= input("Enter your name: ")
amount_USD= float(input("Enter the amount in USD: "))
USD_CAD= 1.23

amount_CAD= amount_USD * USD_CAD

print('Welcome {}, the equivalent of USD${} is CAD${}'.format(name, amount_USD, amount_CAD))


#example

name= input("Welcome to the foreign currency exchange office, please enter your name: ")
amount_SGD= float(input("Enter the amount in SGD: "))
USD_SGD= 1.34
NZD_USD=0.62
NZD_SGD= NZD_USD * USD_SGD
amount_NZD= amount_SGD / NZD_SGD
print('Welcome to our office, {}, the amount you want to change is SGD {}, which will be converted to NZD{}'.format(name, amount_SGD, amount_NZD))

Welcome shan, the equivalent of USD$123.4 is CAD$151.782
Welcome to our office, shan, the amount you want to change is SGD 13700.0, which will be converted to NZD16490.12999518536

In [30]:
#python List, for Loops, and list Comprehension

#notation

#input_list= [1,2,3,4,5]
#input_list[0] #1
#input_list[1] #2
#input_list[-1] #5
#input_list[0:3] # [1,2,3]
#input_list[1:] # [2,3,4,5]

#and for loops notation
#for x in input_list:
    #output_list.append(x**2)        the output_list will be [1,4,9,16,25]

#other way we can use List comprehension to do the same thing instead using for loops  
#we define input_list= [1,2,3,4,5]
#output_list= [x**2 for x in input_list]  #the output_list will be [1,4,9,16,25]


#example
#Assume that we have 3 clients who invested the following amounts in stock earning 8% annually, and we need to calculate the client return using for loops and list comprehension.

client_investments=[400000 , 50000 , 60000]
annual_return= 0.08

client_returns= []
for x in client_investments:
    client_returns.append(x * annual_return)
print(client_returns)

client_returns_comp= [x * annual_return for x in client_investments]
print(client_returns_comp)


#compare the result between for loops and list comprehension
assert client_returns == client_returns_comp

[32000.0, 4000.0, 4800.0]
[32000.0, 4000.0, 4800.0]

In [39]:
#we learn about User-defined, lambda, and built-in functions in Python

#user-defined functions can encapsulate a block of code that can be reused multiple times in a program. They are defined using the 'def' keyword followed by the function name and parentheses.
#lambda functions are anonymous functions that can be defined in a single line using the 'lambda' keyword. They are often used for short, simple operations.
#built in functions are pre-defined functions that come with Python and can be used without any additional code. Examples include 'print()', 'len()', and 'sum()'.

#USER DEFINED FUNCTION EXAMPLE 
#def Function_name(parameters1, parameters2):
    #z=parameters1 * parameters2
    #return z
    #multiply(parameters1, parameters2)  #this is how we call the function

#LAMBA FUNCTIONS

#z=lambda parameters1, parameters2: parameters1 * parameters2
#multiply= z(parameters1, parameters2)  #this is how we call the function

def multiply(x, y):
    z= x * y
    return z
    multiply(x, y)
print(multiply(5, 40))  # Output: 50

z= lambda x, y: x * y
multiply= z(5, 40)

# so if i have a small, single expression without having to give them a name using def keyword then i better using lambda function.


#EXAMPLE

effective_interest_rate= lambda interest_rate,periods : ((1+(interest_rate/periods))**periods)-1
effective_rate= effective_interest_rate(0.06, 12)
print('The effective interest rate is={}'. format(effective_rate))

amount_0= 10000 #amount at year 0
print('The total interest rate earned by the end of year 1=${}'.format(effective_rate*amount_0))

200
The effective interest rate is=0.06167781186449828
The total interest rate earned by the end of year 1=$616.7781186449828

In [40]:
#Data collection, wrangling, and feature engineering in machine learning
#Data Wrangling involves cleaning and organizing raw data sets by merging multiple sources of data, handling missing values, and converting them from one format to another.
#Feature engineering involves transforming data set features, with the goal of improving the performance of downstream machine learning models
#Feature engineering involves feature selection, scaling and creating new features from existing ones.

#Get Financial Data Using SimFin Platform
#import simfin as sf
#income_df=sf.load_income(variant='annual', market='us').reset_index()

!pip install simfin

Collecting simfin
  Downloading simfin-1.0.2-py3-none-any.whl.metadata (637 bytes)
Requirement already satisfied: pandas in C:\Users\shann\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from simfin) (3.0.5)
Requirement already satisfied: numpy in C:\Users\shann\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from simfin) (2.5.3)
Requirement already satisfied: requests in C:\Users\shann\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from simfin) (2.34.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\shann\AppData\Roaming\Python\Python314\site-packages (from pandas->simfin) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\shann\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas->simfin) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\shann\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas->simfin) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\shann\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->simfin) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\shann\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->simfin) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\shann\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->simfin) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\shann\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->simfin) (2026.7.22)
Downloading simfin-1.0.2-py3-none-any.whl (61 kB)
Installing collected packages: simfin
Successfully installed simfin-1.0.2

In [43]:
import simfin as sf

In [42]:
import pandas as pd

In [44]:
sf.set_api_key('f1dec43a-3709-4b40-953a-460eb59d9d9d')
sf.set_data_dir('~/simfin_data/')

In [45]:
income_df=sf.load_income(variant='quarterly', market='us')
income_df

Dataset "us-income-quarterly" not on disk.
- Downloading ... 100.0%
- Extracting zip-file ... Done!
- Loading from disk ... Done!

                    SimFinId Currency  Fiscal Year Fiscal Period Publish Date  \
Ticker Report Date
A      2020-10-31      45846      USD         2020            Q4   2020-12-18
       2021-01-31      45846      USD         2021            Q1   2021-03-02
       2021-04-30      45846      USD         2021            Q2   2021-06-01
       2021-07-31      45846      USD         2021            Q3   2021-09-01
       2021-10-31      45846      USD         2021            Q4   2021-12-17
...                      ...      ...          ...           ...          ...
ZYXI   2024-09-30     171401      USD         2024            Q3   2024-10-24
       2024-12-31     171401      USD         2024            Q4   2025-03-11
       2025-03-31     171401      USD         2025            Q1   2025-04-29
       2025-06-30     171401      USD         2025            Q2   2025-07-31
       2025-09-30     171401      USD         2025            Q3   2025-11-17

                   Restated Date  Shares (Basic)  Shares (Diluted)  \
Ticker Report Date
A      2020-10-31     2021-09-01     308000000.0       311000000.0
       2021-01-31     2022-03-03     306000000.0       309000000.0
       2021-04-30     2022-05-31     306000000.0       306000000.0
       2021-07-31     2022-09-01     303000000.0       306000000.0
       2021-10-31     2022-09-01     305000000.0       307000000.0
...                          ...             ...               ...
ZYXI   2024-09-30     2025-11-17      31775000.0        32088000.0
       2024-12-31     2025-11-17      31883000.0        32077000.0
       2025-03-31     2025-04-29      31604000.0        31604000.0
       2025-06-30     2025-07-31      30258000.0        30258000.0
       2025-09-30     2025-11-17      30314000.0        30314000.0

                         Revenue  Cost of Revenue  ...  \
Ticker Report Date                                 ...
A      2020-10-31   1.483000e+09     -695000000.0  ...
       2021-01-31   1.548000e+09     -710000000.0  ...
       2021-04-30   1.525000e+09     -708000000.0  ...
       2021-07-31   1.586000e+09     -734000000.0  ...
       2021-10-31   1.660000e+09     -760000000.0  ...
...                          ...              ...  ...
ZYXI   2024-09-30   4.996600e+07      -10177000.0  ...
       2024-12-31   4.597400e+07       -9983000.0  ...
       2025-03-31   2.657800e+07       -8369000.0  ...
       2025-06-30   2.229000e+07       -7055000.0  ...
       2025-09-30   1.336000e+07       -5281000.0  ...

                    Non-Operating Income (Loss)  Interest Expense, Net  \
Ticker Report Date
A      2020-10-31                   -16000000.0            -18000000.0
       2021-01-31                   -16000000.0            -19000000.0
       2021-04-30                   -15000000.0            -19000000.0
       2021-07-31                    -9000000.0            -21000000.0
       2021-10-31                    53000000.0            -20000000.0
...                                         ...                    ...
ZYXI   2024-09-30                     -625000.0              -625000.0
       2024-12-31                     -615000.0              -615000.0
       2025-03-31                     -703000.0              -703000.0
       2025-06-30                     -834000.0              -834000.0
       2025-09-30                     -890000.0              -890000.0

                    Pretax Income (Loss), Adj.  Abnormal Gains (Losses)  \
Ticker Report Date
A      2020-10-31                  283000000.0                      NaN
       2021-01-31                  312000000.0                      NaN
       2021-04-30                  273000000.0                      NaN
       2021-07-31                  327000000.0                      NaN
       2021-10-31                  448000000.0                      NaN
...                                        ...                      ...
ZYXI   2024-09-30                    3177000.0                      NaN
       2024-12-31                   -1178000.0                      0.0
       2025-03-31                  -13800000.0                      NaN
       2025-06-30                  -11117000.0                      NaN
       2025-09-30                  -14112000.0              -30740000.0

                    Pretax Income (Loss)  Income Tax (Expense) Benefit, Net  \
Ticker Report Date
A      2020-10-31              283000000                        -61000000.0
       2021-01-31              312000000                        -24000000.0
       2021-04-30              273000000                        -57000000.0
       2021-07-31              327000000                        -63000000.0
       2021-10-31              448000000                         -6000000.0
...                                  ...                                ...
ZYXI   2024-09-30                3177000                          -795000.0
       2024-12-31               -1178000                           563000.0
       2025-03-31              -13800000                          3404000.0
       2025-06-30              -11117000                         -8916000.0
       2025-09-30              -44852000                          1938000.0

                    Income (Loss) from Continuing Operations  \
Ticker Report Date
A      2020-10-31                                  222000000
       2021-01-31                                  288000000
       2021-04-30                                  216000000
       2021-07-31                                  264000000
       2021-10-31                                  442000000
...                                                      ...
ZYXI   2024-09-30                                    2382000
       2024-12-31                                    -615000
       2025-03-31                                  -10396000
       2025-06-30                                  -20033000
       2025-09-30                                  -42914000

                    Net Extraordinary Gains (Losses)  Net Income  \
Ticker Report Date
A      2020-10-31                                NaN   222000000
       2021-01-31                                NaN   288000000
       2021-04-30                                NaN   216000000
       2021-07-31                                NaN   264000000
       2021-10-31                                NaN   442000000
...                                              ...         ...
ZYXI   2024-09-30                                NaN     2382000
       2024-12-31                                NaN     -615000
       2025-03-31                                NaN   -10396000
       2025-06-30                                NaN   -20033000
       2025-09-30                                NaN   -42914000

                    Net Income (Common)
Ticker Report Date
A      2020-10-31             222000000
       2021-01-31             288000000
       2021-04-30             216000000
       2021-07-31             264000000
       2021-10-31             442000000
...                                 ...
ZYXI   2024-09-30               2382000
       2024-12-31               -615000
       2025-03-31             -10396000
       2025-06-30             -20033000
       2025-09-30             -42914000

[47862 rows x 26 columns]

In [ ]:
income_df=sf.load_income(variant='annual', market='us').reset_index()    #reset.index() is used to remove one indexing level since the Pandas DataFrame has a multi-index, which can make it difficult to work with the data. By resetting the index, we can simplify the DataFrame and make it easier to manipulate and analyze the data is multi-indexed
income_df

Dataset "us-income-annual" on disk (0 days old).
- Loading from disk ... Done!

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Non-Operating Income (Loss),"Interest Expense, Net","Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common)
0,A,2020-10-31,45846,USD,2020,FY,2020-12-18,2022-12-21,309000000.0,312000000.0,...,-4000000.0,-70000000.0,8.420000e+08,NaN,8.420000e+08,-123000000.0,719000000,NaN,719000000,719000000
1,A,2021-10-31,45846,USD,2021,FY,2021-12-17,2023-12-20,305000000.0,307000000.0,...,13000000.0,-79000000.0,1.360000e+09,NaN,1.360000e+09,-150000000.0,1210000000,NaN,1210000000,1210000000
2,A,2022-10-31,45846,USD,2022,FY,2022-12-21,2024-12-20,304000000.0,307000000.0,...,-114000000.0,-75000000.0,1.504000e+09,NaN,1.504000e+09,-250000000.0,1254000000,NaN,1254000000,1254000000
3,A,2023-10-31,45846,USD,2023,FY,2023-12-20,2025-12-22,294000000.0,296000000.0,...,-11000000.0,-44000000.0,1.339000e+09,NaN,1.339000e+09,-99000000.0,1240000000,NaN,1240000000,1240000000
4,A,2024-10-31,45846,USD,2024,FY,2024-12-20,2025-12-22,290000000.0,291000000.0,...,33000000.0,-16000000.0,1.521000e+09,NaN,1.521000e+09,-232000000.0,1289000000,NaN,1289000000,1289000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16928,ZYXI,2022-12-31,171401,USD,2022,FY,2023-03-14,2024-03-12,38467000.0,39127000.0,...,-440000.0,-440000.0,2.249800e+07,-300000.0,2.219800e+07,-5150000.0,17048000,NaN,17048000,17048000
16929,ZYXI,2023-12-31,171401,USD,2023,FY,2024-03-12,2025-03-11,35555000.0,36142000.0,...,-1094000.0,-1094000.0,9.686000e+06,2893000.0,1.257900e+07,-2847000.0,9732000,NaN,9732000,9732000
16930,ZYXI,2024-12-31,171401,USD,2024,FY,2025-03-11,2025-03-11,31941000.0,32299000.0,...,-2382000.0,-2382000.0,3.608000e+06,19000.0,3.627000e+06,-633000.0,2994000,NaN,2994000,2994000
16931,NaN,2021-12-31,18728220,USD,2021,FY,2022-04-18,2024-04-08,8987798.0,8987798.0,...,595361.0,462700.0,-2.711386e+07,NaN,-2.711386e+07,NaN,-27113865,NaN,-27113865,-27113865
16932,NaN,2022-12-31,18728220,USD,2022,FY,2023-04-18,2025-04-11,10648900.0,10661521.0,...,1550615.0,952999.0,4.624337e+06,NaN,4.624337e+06,NaN,4624337,NaN,4624337,4624337

In [48]:
cashflow_df=sf.load_cashflow(variant='annual', market='us').reset_index()
cashflow_df

Dataset "us-cashflow-annual" not on disk.
- Downloading ... 100.0%
- Extracting zip-file ... Done!
- Loading from disk ... Done!

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash
0,A,2020-10-31,45846,USD,2020,FY,2020-12-18,2022-12-21,309000000.0,312000000.0,...,9.210000e+08,-118000000.0,NaN,NaN,-1.470000e+08,-222000000.0,-45000000.0,-4.090000e+08,-7.170000e+08,59000000
1,A,2021-10-31,45846,USD,2021,FY,2021-12-17,2023-12-20,305000000.0,307000000.0,...,1.485000e+09,-187000000.0,12000000.0,-547000000.0,-7.490000e+08,-236000000.0,356000000.0,-7.330000e+08,-6.960000e+08,43000000
2,A,2022-10-31,45846,USD,2022,FY,2022-12-21,2024-12-20,304000000.0,307000000.0,...,1.312000e+09,-291000000.0,9000000.0,-52000000.0,-3.340000e+08,-250000000.0,22000000.0,-1.081000e+09,-1.376000e+09,-434000000
3,A,2023-10-31,45846,USD,2023,FY,2023-12-20,2025-12-22,294000000.0,296000000.0,...,1.772000e+09,-298000000.0,-3000000.0,-1000000.0,-3.020000e+08,-265000000.0,-43000000.0,-5.080000e+08,-9.380000e+08,537000000
4,A,2024-10-31,45846,USD,2024,FY,2024-12-20,2025-12-22,290000000.0,291000000.0,...,1.751000e+09,-378000000.0,-5000000.0,-862000000.0,-1.245000e+09,-274000000.0,624000000.0,-1.073000e+09,-7.650000e+08,-261000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16926,ZYXI,2022-12-31,171401,USD,2022,FY,2023-03-14,2024-03-12,38467000.0,39127000.0,...,1.374600e+07,-418000.0,NaN,NaN,-4.180000e+05,-3613000.0,-5451000.0,-2.638000e+07,-3.579600e+07,-22468000
16927,ZYXI,2023-12-31,171401,USD,2023,FY,2024-03-12,2025-03-11,35555000.0,36142000.0,...,1.775600e+07,-1156000.0,NaN,NaN,-9.660000e+05,-3000.0,46223000.0,-3.783800e+07,7.645000e+06,24435000
16928,ZYXI,2024-12-31,171401,USD,2024,FY,2025-03-11,2025-03-11,31941000.0,32299000.0,...,1.272100e+07,-578000.0,NaN,NaN,-5.780000e+05,-9000.0,-807000.0,-1.560300e+07,-1.709100e+07,-4948000
16929,NaN,2021-12-31,18728220,USD,2021,FY,2022-04-18,2024-04-08,8987798.0,8987798.0,...,1.111756e+07,-1347240.0,NaN,NaN,-5.571129e+06,NaN,-774927.0,3.118309e+07,2.554102e+07,30767804
16930,NaN,2022-12-31,18728220,USD,2022,FY,2023-04-18,2025-04-11,10648900.0,10661521.0,...,-4.085683e+07,-9930106.0,NaN,NaN,-4.931050e+06,NaN,2519301.0,2.140515e+07,2.392445e+07,-21695083

In [49]:
balance_df=sf.load_balance(variant='annual', market='us').reset_index()
balance_df

Dataset "us-balance-annual" not on disk.
- Downloading ... 100.0%
- Extracting zip-file ... Done!
- Loading from disk ... Done!

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity
0,A,2020-10-31,45846,USD,2020,Q4,2020-12-18,2021-12-17,309000000.0,312000000.0,...,75000000.0,1.467000e+09,2.284000e+09,3.287000e+09,4.754000e+09,5.314000e+09,NaN,81000000.0,4873000000,9627000000
1,A,2021-10-31,45846,USD,2021,Q4,2021-12-17,2022-12-21,305000000.0,307000000.0,...,NaN,1.708000e+09,2.729000e+09,3.608000e+09,5.316000e+09,5.323000e+09,NaN,348000000.0,5389000000,10705000000
2,A,2022-10-31,45846,USD,2022,Q4,2022-12-21,2023-12-20,304000000.0,307000000.0,...,36000000.0,1.861000e+09,2.733000e+09,3.366000e+09,5.227000e+09,5.328000e+09,NaN,324000000.0,5305000000,10532000000
3,A,2023-10-31,45846,USD,2023,Q4,2023-12-20,2024-12-20,294000000.0,296000000.0,...,NaN,1.603000e+09,2.735000e+09,3.315000e+09,4.918000e+09,5.390000e+09,NaN,782000000.0,5845000000,10763000000
4,A,2024-10-31,45846,USD,2024,Q4,2024-12-20,2025-12-22,290000000.0,291000000.0,...,45000000.0,1.895000e+09,3.345000e+09,4.053000e+09,5.948000e+09,5.453000e+09,NaN,750000000.0,5898000000,11846000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16929,ZYXI,2022-12-31,171401,USD,2022,Q4,2023-03-14,2024-03-12,38467000.0,39127000.0,...,5333000.0,2.108600e+07,5.293000e+06,2.902200e+07,5.010800e+07,8.247000e+07,-33160000.0,17048000.0,66358000,116466000
16930,ZYXI,2023-12-31,171401,USD,2023,Q4,2024-03-12,2025-03-11,35555000.0,36142000.0,...,NaN,1.853200e+07,5.760500e+07,7.224300e+07,9.077500e+07,9.091100e+07,-71562000.0,26780000.0,46129000,136904000
16931,ZYXI,2024-12-31,171401,USD,2024,Q4,2025-03-11,2025-11-17,31941000.0,32299000.0,...,NaN,1.686400e+07,5.856700e+07,6.950700e+07,8.637100e+07,9.312000e+07,-87186000.0,29774000.0,35708000,122079000
16932,NaN,2021-12-31,18728220,USD,2021,Q4,2022-04-18,2023-04-18,8987798.0,8987798.0,...,NaN,1.458130e+08,NaN,3.319130e+05,1.461449e+08,3.151015e+07,NaN,-34981107.0,-3856821,142288086
16933,NaN,2022-12-31,18728220,USD,2022,Q4,2023-04-18,2024-04-08,10648900.0,10661521.0,...,39384.0,2.583056e+07,2.345235e+06,2.698866e+06,2.852942e+07,4.991614e+07,NaN,-28020192.0,23126204,51655627

In [50]:
income_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16933 entries, 0 to 16932
Data columns (total 28 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Ticker                                    16931 non-null  str
 1   Report Date                               16933 non-null  datetime64[us]
 2   SimFinId                                  16933 non-null  int64
 3   Currency                                  16933 non-null  str
 4   Fiscal Year                               16933 non-null  int64
 5   Fiscal Period                             16933 non-null  str
 6   Publish Date                              16933 non-null  datetime64[us]
 7   Restated Date                             16933 non-null  datetime64[us]
 8   Shares (Basic)                            16726 non-null  float64
 9   Shares (Diluted)                          16647 non-null  float64
 10  Revenue                                   15108 non-null  float64
 11  Cost of Revenue                           13175 non-null  float64
 12  Gross Profit                              13175 non-null  float64
 13  Operating Expenses                        16886 non-null  float64
 14  Selling, General & Administrative         15995 non-null  float64
 15  Research & Development                    8061 non-null   float64
 16  Depreciation & Amortization               6716 non-null   float64
 17  Operating Income (Loss)                   16928 non-null  float64
 18  Non-Operating Income (Loss)               16704 non-null  float64
 19  Interest Expense, Net                     14790 non-null  float64
 20  Pretax Income (Loss), Adj.                16928 non-null  float64
 21  Abnormal Gains (Losses)                   10957 non-null  float64
 22  Pretax Income (Loss)                      16929 non-null  float64
 23  Income Tax (Expense) Benefit, Net         13624 non-null  float64
 24  Income (Loss) from Continuing Operations  16933 non-null  int64
 25  Net Extraordinary Gains (Losses)          1403 non-null   float64
 26  Net Income                                16933 non-null  int64
 27  Net Income (Common)                       16933 non-null  int64
dtypes: datetime64[us](3), float64(17), int64(5), str(3)
memory usage: 3.6 MB

In [51]:
balance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16934 entries, 0 to 16933
Data columns (total 30 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Ticker                                           16932 non-null  str
 1   Report Date                                      16934 non-null  datetime64[us]
 2   SimFinId                                         16934 non-null  int64
 3   Currency                                         16934 non-null  str
 4   Fiscal Year                                      16934 non-null  int64
 5   Fiscal Period                                    16934 non-null  str
 6   Publish Date                                     16934 non-null  datetime64[us]
 7   Restated Date                                    16934 non-null  datetime64[us]
 8   Shares (Basic)                                   16727 non-null  float64
 9   Shares (Diluted)                                 16647 non-null  float64
 10  Cash, Cash Equivalents & Short Term Investments  16850 non-null  float64
 11  Accounts & Notes Receivable                      13269 non-null  float64
 12  Inventories                                      9199 non-null   float64
 13  Total Current Assets                             16920 non-null  float64
 14  Property, Plant & Equipment, Net                 15759 non-null  float64
 15  Long Term Investments & Receivables              3917 non-null   float64
 16  Other Long Term Assets                           16359 non-null  float64
 17  Total Noncurrent Assets                          16784 non-null  float64
 18  Total Assets                                     16934 non-null  int64
 19  Payables & Accruals                              16858 non-null  float64
 20  Short Term Debt                                  8967 non-null   float64
 21  Total Current Liabilities                        16912 non-null  float64
 22  Long Term Debt                                   11964 non-null  float64
 23  Total Noncurrent Liabilities                     16346 non-null  float64
 24  Total Liabilities                                16924 non-null  float64
 25  Share Capital & Additional Paid-In Capital       16763 non-null  float64
 26  Treasury Stock                                   5591 non-null   float64
 27  Retained Earnings                                16273 non-null  float64
 28  Total Equity                                     16934 non-null  int64
 29  Total Liabilities & Equity                       16934 non-null  int64
dtypes: datetime64[us](3), float64(19), int64(5), str(3)
memory usage: 3.9 MB

In [52]:
cashflow_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16931 entries, 0 to 16930
Data columns (total 28 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Ticker                                     16929 non-null  str
 1   Report Date                                16931 non-null  datetime64[us]
 2   SimFinId                                   16931 non-null  int64
 3   Currency                                   16931 non-null  str
 4   Fiscal Year                                16931 non-null  int64
 5   Fiscal Period                              16931 non-null  str
 6   Publish Date                               16931 non-null  datetime64[us]
 7   Restated Date                              16931 non-null  datetime64[us]
 8   Shares (Basic)                             16724 non-null  float64
 9   Shares (Diluted)                           16645 non-null  float64
 10  Net Income/Starting Line                   16782 non-null  float64
 11  Depreciation & Amortization                15997 non-null  float64
 12  Non-Cash Items                             16769 non-null  float64
 13  Change in Working Capital                  16839 non-null  float64
 14  Change in Accounts Receivable              126 non-null    float64
 15  Change in Inventories                      98 non-null     float64
 16  Change in Accounts Payable                 107 non-null    float64
 17  Change in Other                            171 non-null    float64
 18  Net Cash from Operating Activities         16915 non-null  float64
 19  Change in Fixed Assets & Intangibles       15539 non-null  float64
 20  Net Change in Long Term Investment         6008 non-null   float64
 21  Net Cash from Acquisitions & Divestitures  6602 non-null   float64
 22  Net Cash from Investing Activities         16470 non-null  float64
 23  Dividends Paid                             5859 non-null   float64
 24  Cash from (Repayment of) Debt              13224 non-null  float64
 25  Cash from (Repurchase of) Equity           13443 non-null  float64
 26  Net Cash from Financing Activities         16614 non-null  float64
 27  Net Change in Cash                         16931 non-null  int64
dtypes: datetime64[us](3), float64(19), int64(3), str(3)
memory usage: 3.6 MB

In [54]:
#load the annual cashflow statement for US companies using Simfin and store them in cashflow_annual_df Pandas DataFrame
#what is the memory usage of the cashflow_annual_df DataFrame? Use the info() method to check the memory usage of the DataFrame

cashflow_annual_df=sf.load_cashflow(variant='annual', market='us').reset_index()
cashflow_annual_df

Dataset "us-cashflow-annual" on disk (0 days old).
- Loading from disk ... Done!

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash
0,A,2020-10-31,45846,USD,2020,FY,2020-12-18,2022-12-21,309000000.0,312000000.0,...,9.210000e+08,-118000000.0,NaN,NaN,-1.470000e+08,-222000000.0,-45000000.0,-4.090000e+08,-7.170000e+08,59000000
1,A,2021-10-31,45846,USD,2021,FY,2021-12-17,2023-12-20,305000000.0,307000000.0,...,1.485000e+09,-187000000.0,12000000.0,-547000000.0,-7.490000e+08,-236000000.0,356000000.0,-7.330000e+08,-6.960000e+08,43000000
2,A,2022-10-31,45846,USD,2022,FY,2022-12-21,2024-12-20,304000000.0,307000000.0,...,1.312000e+09,-291000000.0,9000000.0,-52000000.0,-3.340000e+08,-250000000.0,22000000.0,-1.081000e+09,-1.376000e+09,-434000000
3,A,2023-10-31,45846,USD,2023,FY,2023-12-20,2025-12-22,294000000.0,296000000.0,...,1.772000e+09,-298000000.0,-3000000.0,-1000000.0,-3.020000e+08,-265000000.0,-43000000.0,-5.080000e+08,-9.380000e+08,537000000
4,A,2024-10-31,45846,USD,2024,FY,2024-12-20,2025-12-22,290000000.0,291000000.0,...,1.751000e+09,-378000000.0,-5000000.0,-862000000.0,-1.245000e+09,-274000000.0,624000000.0,-1.073000e+09,-7.650000e+08,-261000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16926,ZYXI,2022-12-31,171401,USD,2022,FY,2023-03-14,2024-03-12,38467000.0,39127000.0,...,1.374600e+07,-418000.0,NaN,NaN,-4.180000e+05,-3613000.0,-5451000.0,-2.638000e+07,-3.579600e+07,-22468000
16927,ZYXI,2023-12-31,171401,USD,2023,FY,2024-03-12,2025-03-11,35555000.0,36142000.0,...,1.775600e+07,-1156000.0,NaN,NaN,-9.660000e+05,-3000.0,46223000.0,-3.783800e+07,7.645000e+06,24435000
16928,ZYXI,2024-12-31,171401,USD,2024,FY,2025-03-11,2025-03-11,31941000.0,32299000.0,...,1.272100e+07,-578000.0,NaN,NaN,-5.780000e+05,-9000.0,-807000.0,-1.560300e+07,-1.709100e+07,-4948000
16929,NaN,2021-12-31,18728220,USD,2021,FY,2022-04-18,2024-04-08,8987798.0,8987798.0,...,1.111756e+07,-1347240.0,NaN,NaN,-5.571129e+06,NaN,-774927.0,3.118309e+07,2.554102e+07,30767804
16930,NaN,2022-12-31,18728220,USD,2022,FY,2023-04-18,2025-04-11,10648900.0,10661521.0,...,-4.085683e+07,-9930106.0,NaN,NaN,-4.931050e+06,NaN,2519301.0,2.140515e+07,2.392445e+07,-21695083

In [55]:
cashflow_annual_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16931 entries, 0 to 16930
Data columns (total 28 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Ticker                                     16929 non-null  str
 1   Report Date                                16931 non-null  datetime64[us]
 2   SimFinId                                   16931 non-null  int64
 3   Currency                                   16931 non-null  str
 4   Fiscal Year                                16931 non-null  int64
 5   Fiscal Period                              16931 non-null  str
 6   Publish Date                               16931 non-null  datetime64[us]
 7   Restated Date                              16931 non-null  datetime64[us]
 8   Shares (Basic)                             16724 non-null  float64
 9   Shares (Diluted)                           16645 non-null  float64
 10  Net Income/Starting Line                   16782 non-null  float64
 11  Depreciation & Amortization                15997 non-null  float64
 12  Non-Cash Items                             16769 non-null  float64
 13  Change in Working Capital                  16839 non-null  float64
 14  Change in Accounts Receivable              126 non-null    float64
 15  Change in Inventories                      98 non-null     float64
 16  Change in Accounts Payable                 107 non-null    float64
 17  Change in Other                            171 non-null    float64
 18  Net Cash from Operating Activities         16915 non-null  float64
 19  Change in Fixed Assets & Intangibles       15539 non-null  float64
 20  Net Change in Long Term Investment         6008 non-null   float64
 21  Net Cash from Acquisitions & Divestitures  6602 non-null   float64
 22  Net Cash from Investing Activities         16470 non-null  float64
 23  Dividends Paid                             5859 non-null   float64
 24  Cash from (Repayment of) Debt              13224 non-null  float64
 25  Cash from (Repurchase of) Equity           13443 non-null  float64
 26  Net Cash from Financing Activities         16614 non-null  float64
 27  Net Change in Cash                         16931 non-null  int64
dtypes: datetime64[us](3), float64(19), int64(3), str(3)
memory usage: 3.6 MB

In [57]:
import os
os.getcwd()

'c:\\Users\\shann\\AppData\\Local\\Programs\\Microsoft VS Code'

In [62]:
#READ CSV FILES USING PANDAS
#income_df= pd.read_csv('income_annual_us.csv') example syntax

import pandas as pd
income_df=pd.read_csv('income_statement.csv')
income_df

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Non-Operating Income (Loss),"Interest Expense, Net","Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common)
0,A,1/31/2017,45846,USD,2017,Q1,3/8/2017,3/6/2018,322000000.0,326000000.0,...,-13000000.0,-16000000.0,193000000,NaN,193000000,-25000000.0,168000000,NaN,168000000,168000000
1,A,4/30/2017,45846,USD,2017,Q2,6/6/2017,5/31/2018,321000000.0,325000000.0,...,-10000000.0,-15000000.0,191000000,NaN,191000000,-27000000.0,164000000,NaN,164000000,164000000
2,A,7/31/2017,45846,USD,2017,Q3,9/6/2017,8/30/2018,321000000.0,326000000.0,...,-8000000.0,-13000000.0,193000000,NaN,193000000,-18000000.0,175000000,NaN,175000000,175000000
3,A,10/31/2017,45846,USD,2017,Q4,12/21/2017,12/20/2018,324000000.0,327000000.0,...,-7000000.0,-13000000.0,226000000,NaN,226000000,-49000000.0,177000000,NaN,177000000,177000000
4,A,1/31/2018,45846,USD,2018,Q1,3/6/2018,3/5/2019,323000000.0,323000000.0,...,4000000.0,-11000000.0,233000000,NaN,233000000,-553000000.0,-320000000,NaN,-320000000,-320000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41574,ZYXI,9/30/2020,171401,USD,2020,Q3,10/27/2020,7/29/2021,37945600.0,39035700.0,...,-5000.0,-5000.0,1404000,NaN,1404000,-71000.0,1333000,NaN,1333000,1333000
41575,ZYXI,12/31/2020,171401,USD,2020,Q4,2/25/2021,11/2/2021,38262400.0,39189700.0,...,-5000.0,-5000.0,2292000,-77000.0,2215000,-428000.0,1787000,NaN,1787000,1787000
41576,ZYXI,3/31/2021,171401,USD,2021,Q1,4/29/2021,4/28/2022,38320700.0,38320700.0,...,-9000.0,-9000.0,-1090000,NaN,-1090000,384000.0,-706000,NaN,-706000,-706000
41577,ZYXI,6/30/2021,171401,USD,2021,Q2,7/29/2021,4/28/2022,38320700.0,38320700.0,...,-45000.0,-45000.0,3770000,NaN,3770000,-962000.0,2808000,NaN,2808000,2808000
41578,ZYXI,9/30/2021,171401,USD,2021,Q3,11/2/2021,10/27/2022,38285500.0,39141300.0,...,-18000.0,-18000.0,8028000,NaN,8028000,-1921000.0,6107000,NaN,6107000,6107000

In [64]:
balance_df=pd.read_csv('balance_sheet.csv')
balance_df

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity
0,A,1/31/2017,45846,USD,2017,Q1,3/8/2017,3/8/2017,322000000.0,326000000.0,...,190000000.0,1.089000e+09,1.802000e+09,2.483000e+09,3.572000e+09,5.239000e+09,0.0,-453000000.0,4.300000e+09,7.872000e+09
1,A,4/30/2017,45846,USD,2017,Q2,6/6/2017,6/6/2017,321000000.0,325000000.0,...,241000000.0,1.187000e+09,1.802000e+09,2.454000e+09,3.641000e+09,5.242000e+09,0.0,-393000000.0,4.375000e+09,8.016000e+09
2,A,7/31/2017,45846,USD,2017,Q3,9/6/2017,9/6/2017,321000000.0,326000000.0,...,280000000.0,1.241000e+09,1.801000e+09,2.409000e+09,3.650000e+09,5.285000e+09,0.0,-260000000.0,4.611000e+09,8.261000e+09
3,A,10/31/2017,45846,USD,2017,Q4,12/21/2017,12/20/2018,324000000.0,327000000.0,...,210000000.0,1.263000e+09,1.801000e+09,2.328000e+09,3.591000e+09,5.303000e+09,NaN,-126000000.0,4.835000e+09,8.426000e+09
4,A,1/31/2018,45846,USD,2018,Q1,3/6/2018,3/6/2018,323000000.0,323000000.0,...,345000000.0,1.361000e+09,1.800000e+09,2.811000e+09,4.172000e+09,5.323000e+09,-3000000.0,-529000000.0,4.526000e+09,8.698000e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41574,ZYXI,9/30/2020,171401,USD,2020,Q3,10/27/2020,10/27/2020,37945600.0,39035700.0,...,NaN,7.295000e+06,NaN,3.448000e+06,1.074300e+07,3.651400e+07,-3846000.0,21643000.0,5.422200e+07,6.496500e+07
41575,ZYXI,12/31/2020,171401,USD,2020,Q4,2/25/2021,3/22/2022,38262400.0,39189700.0,...,NaN,1.011700e+07,NaN,5.203000e+06,1.532000e+07,3.723500e+07,-3846000.0,23430000.0,5.685500e+07,7.217500e+07
41576,ZYXI,3/31/2021,171401,USD,2021,Q1,4/29/2021,4/29/2021,38320700.0,38320700.0,...,NaN,9.315000e+06,NaN,4.768000e+06,1.408300e+07,3.735000e+07,-3921000.0,22724000.0,5.615300e+07,7.023600e+07
41577,ZYXI,6/30/2021,171401,USD,2021,Q2,7/29/2021,7/29/2021,38320700.0,38320700.0,...,NaN,8.891000e+06,NaN,1.750700e+07,2.639800e+07,3.773400e+07,-5966000.0,25532000.0,5.730000e+07,8.369800e+07
41578,ZYXI,9/30/2021,171401,USD,2021,Q3,11/2/2021,11/2/2021,38285500.0,39141300.0,...,NaN,1.029200e+07,NaN,1.704800e+07,2.734000e+07,3.825700e+07,-6513000.0,31639000.0,6.338300e+07,9.072300e+07

In [65]:
cashflow_df=pd.read_csv('cashflow_statement.csv')
cashflow_df

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash
0,A,1/31/2017,45846,USD,2017,Q1,3/8/2017,3/6/2018,322000000.0,326000000.0,...,116000000.0,-32000000.0,NaN,-69000000.0,-101000000.0,-42000000.0,89000000.0,-93000000.0,-58000000.0,-48000000
1,A,4/30/2017,45846,USD,2017,Q2,6/6/2017,5/31/2018,321000000.0,325000000.0,...,257000000.0,-43000000.0,NaN,0.0,-43000000.0,-43000000.0,52000000.0,-75000000.0,-67000000.0,148000000
2,A,7/31/2017,45846,USD,2017,Q3,9/6/2017,8/30/2018,321000000.0,326000000.0,...,228000000.0,-43000000.0,NaN,-57000000.0,-101000000.0,-42000000.0,39000000.0,32000000.0,29000000.0,174000000
3,A,10/31/2017,45846,USD,2017,Q4,12/21/2017,12/20/2018,324000000.0,327000000.0,...,288000000.0,-58000000.0,0.0,0.0,-60000000.0,-43000000.0,-70000000.0,8000000.0,-106000000.0,115000000
4,A,1/31/2018,45846,USD,2018,Q1,3/6/2018,3/5/2019,323000000.0,323000000.0,...,215000000.0,-60000000.0,NaN,-6000000.0,-67000000.0,-48000000.0,135000000.0,-22000000.0,37000000.0,210000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41574,ZYXI,9/30/2020,171401,USD,2020,Q3,10/27/2020,7/29/2021,37945600.0,39035700.0,...,-769000.0,-105000.0,NaN,NaN,-105000.0,NaN,-15000.0,25202000.0,25187000.0,24313000
41575,ZYXI,12/31/2020,171401,USD,2020,Q4,2/25/2021,11/2/2021,38262400.0,39189700.0,...,-1696000.0,-226000.0,NaN,NaN,-226000.0,NaN,-15000.0,293000.0,-134000.0,-2056000
41576,ZYXI,3/31/2021,171401,USD,2021,Q1,4/29/2021,4/28/2022,38320700.0,38320700.0,...,-5305000.0,-299000.0,NaN,NaN,-299000.0,NaN,-23000.0,-48000.0,-130000.0,-5734000
41577,ZYXI,6/30/2021,171401,USD,2021,Q2,7/29/2021,4/28/2022,38320700.0,38320700.0,...,1027000.0,-55000.0,NaN,NaN,-55000.0,NaN,-21000.0,-1984000.0,-2081000.0,-1109000
41578,ZYXI,9/30/2021,171401,USD,2021,Q3,11/2/2021,7/28/2022,38285500.0,39141300.0,...,3689000.0,-66000.0,NaN,NaN,-66000.0,NaN,-29000.0,-508000.0,-585000.0,3038000

In [67]:
companies_info_df=pd.read_csv('companies_information.csv')
companies_info_df

     Ticker  SimFinId                      Company Name  IndustryId
0         A     45846          AGILENT TECHNOLOGIES INC    106001.0
1       A21   1333027                      Li Auto Inc.         NaN
2        AA    367153                        Alcoa Corp    110004.0
3       AAL     68568      American Airlines Group Inc.    100006.0
4      AAMC    847094  Altisource Asset Management Corp    104001.0
...     ...       ...                               ...         ...
3117    ZUO    994625                         ZUORA INC    101003.0
3118    ZVO    901866                         Zovio Inc    102006.0
3119     ZY   1243193                     Zymergen Inc.    106002.0
3120   ZYNE    901704     Zynerba Pharmaceuticals, Inc.    106002.0
3121   ZYXI    171401                         ZYNEX INC    106004.0

[3122 rows x 4 columns]

In [68]:
companies_info_df.head(10)

  Ticker  SimFinId                      Company Name  IndustryId
0      A     45846          AGILENT TECHNOLOGIES INC    106001.0
1    A21   1333027                      Li Auto Inc.         NaN
2     AA    367153                        Alcoa Corp    110004.0
3    AAL     68568      American Airlines Group Inc.    100006.0
4   AAMC    847094  Altisource Asset Management Corp    104001.0
5   AAME    450021            ATLANTIC AMERICAN CORP    104004.0
6    AAN    441241             Aaron's Company, Inc.    100007.0
7   AAOI    671827     APPLIED OPTOELECTRONICS, INC.    101004.0
8   AAON    919501                          AAON INC    100001.0
9    AAP    184955            ADVANCE AUTO PARTS INC    103002.0

In [69]:
companies_info_df.tail(10)

     Ticker  SimFinId                   Company Name  IndustryId
3112   ZNGA    418866                      ZYNGA INC    101003.0
3113    ZOM   1164823                 Zomedica Corp.    106001.0
3114     ZS    896477                  Zscaler, Inc.    101003.0
3115    ZTS    378251                         Zoetis    106005.0
3116   ZUMZ     45730                     Zumiez Inc    103002.0
3117    ZUO    994625                      ZUORA INC    101003.0
3118    ZVO    901866                      Zovio Inc    102006.0
3119     ZY   1243193                  Zymergen Inc.    106002.0
3120   ZYNE    901704  Zynerba Pharmaceuticals, Inc.    106002.0
3121   ZYXI    171401                      ZYNEX INC    106004.0

In [70]:
industries_info_df=pd.read_csv('industries_information.csv')
industries_info_df

    IndustryId           Sector                    Industry
0       100001      Industrials         Industrial Products
1       100002      Industrials           Business Services
2       100003      Industrials  Engineering & Construction
3       100004      Industrials            Waste Management
4       100005      Industrials     Industrial Distribution
..         ...              ...                         ...
69      110004  Basic Materials             Metals & Mining
70      110005  Basic Materials          Building Materials
71      110006  Basic Materials                        Coal
72      110007  Basic Materials                       Steel
73      111001            Other        Diversified Holdings

[74 rows x 3 columns]

In [71]:
industries_info_df.head(70)

    IndustryId           Sector                    Industry
0       100001      Industrials         Industrial Products
1       100002      Industrials           Business Services
2       100003      Industrials  Engineering & Construction
3       100004      Industrials            Waste Management
4       100005      Industrials     Industrial Distribution
..         ...              ...                         ...
65      109002      Real Estate        Real Estate Services
66      110001  Basic Materials                   Chemicals
67      110002  Basic Materials             Forest Products
68      110003  Basic Materials                 Agriculture
69      110004  Basic Materials             Metals & Mining

[70 rows x 3 columns]

In [73]:
pd.options.display.max_rows= 70
industries_info_df.head(70)

    IndustryId              Sector                                 Industry
0       100001         Industrials                      Industrial Products
1       100002         Industrials                        Business Services
2       100003         Industrials               Engineering & Construction
3       100004         Industrials                         Waste Management
4       100005         Industrials                  Industrial Distribution
5       100006         Industrials                                 Airlines
6       100007         Industrials                 Consulting & Outsourcing
7       100008         Industrials                      Aerospace & Defense
8       100009         Industrials            Farm & Construction Machinery
9       100010         Industrials               Transportation & Logistics
10      100011         Industrials                      Employment Services
11      100012         Industrials                      Truck Manufacturing
12      100013         Industrials                            Conglomerates
13      101001          Technology                        Computer Hardware
14      101002          Technology                             Online Media
15      101003          Technology                     Application Software
16      101004          Technology                           Semiconductors
17      101005          Technology                  Communication Equipment
18      102001  Consumer Defensive                       Retail - Defensive
19      102002  Consumer Defensive                  Consumer Packaged Goods
20      102003  Consumer Defensive                         Tobacco Products
21      102004  Consumer Defensive                    Beverages - Alcoholic
22      102005  Consumer Defensive                Beverages - Non-Alcoholic
23      102006  Consumer Defensive                                Education
24      103001   Consumer Cyclical                            Entertainment
25      103002   Consumer Cyclical             Retail - Apparel & Specialty
26      103003   Consumer Cyclical                              Restaurants
27      103004   Consumer Cyclical      Manufacturing - Apparel & Furniture
28      103005   Consumer Cyclical                                    Autos
29      103011   Consumer Cyclical         Advertising & Marketing Services
30      103013   Consumer Cyclical              Homebuilding & Construction
31      103015   Consumer Cyclical                         Travel & Leisure
32      103018   Consumer Cyclical                   Packaging & Containers
33      103020   Consumer Cyclical                        Personal Services
34      103026   Consumer Cyclical                               Publishing
35      104001  Financial Services                         Asset Management
36      104002  Financial Services                                    Banks
37      104003  Financial Services               Brokers, Exchanges & Other
38      104004  Financial Services                         Insurance - Life
39      104005  Financial Services                                Insurance
40      104006  Financial Services          Insurance - Property & Casualty
41      104007  Financial Services                          Credit Services
42      104013  Financial Services                    Insurance - Specialty
43      105001           Utilities                    Utilities - Regulated
44      105002           Utilities  Utilities - Independent Power Producers
45      106001          Healthcare           Medical Diagnostics & Research
46      106002          Healthcare                            Biotechnology
47      106003          Healthcare          Medical Instruments & Equipment
48      106004          Healthcare                          Medical Devices
49      106005          Healthcare                       Drug Manufacturers
50      106006          Healthcare                        Health Care Plans
51      106011          Healthcare                    Health Care Providers
52      106014          Healthcare                     Medical Distribution
53      107001              Energy         Oil & Gas - Refining & Marketing
54      107002              Energy                          Oil & Gas - E&P
55      107003              Energy                    Oil & Gas - Midstream
56      107004              Energy                     Oil & Gas - Services
57      107005              Energy                   Oil & Gas - Integrated
58      107006              Energy                     Oil & Gas - Drilling
59      107007              Energy       Alternative Energy Sources & Other
60      108001   Business Services                   Communication Services
61      108002   Business Services                               Consulting
62      108003   Business Services                            HR & Staffing
63      108004   Business Services                                    Other
64      109001         Real Estate                                    REITs
65      109002         Real Estate                     Real Estate Services
66      110001     Basic Materials                                Chemicals
67      110002     Basic Materials                          Forest Products
68      110003     Basic Materials                              Agriculture
69      110004     Basic Materials                          Metals & Mining

In [76]:
companies_info_df[companies_info_df['Company Name']== 'APPLE INC']

   Ticker  SimFinId Company Name  IndustryId
10   AAPL    111052    APPLE INC    101001.0

In [77]:
companies_info_df[companies_info_df['Ticker'].isin(['AAPL', 'MSFT', 'GOOGL'])]

     Ticker  SimFinId    Company Name  IndustryId
10     AAPL    111052       APPLE INC    101001.0
1841   MSFT     59265  MICROSOFT CORP    101003.0

In [80]:
#PERFORM DATA MERGING

companies_info_df
industries_info_df.head(70)

#how to merge two dataframes in pandas using the merge() function. 

companies_industries_df=pd.merge(companies_info_df, industries_info_df, on ='IndustryId',how='left')
companies_industries_df

,Ticker,SimFinId,Company Name,IndustryId,Sector,Industry
0,A,45846,AGILENT TECHNOLOGIES INC,106001.0,Healthcare,Medical Diagnostics & Research
1,A21,1333027,Li Auto Inc.,NaN,NaN,NaN
2,AA,367153,Alcoa Corp,110004.0,Basic Materials,Metals & Mining
3,AAL,68568,American Airlines Group Inc.,100006.0,Industrials,Airlines
4,AAMC,847094,Altisource Asset Management Corp,104001.0,Financial Services,Asset Management
...,...,...,...,...,...,...
3117,ZUO,994625,ZUORA INC,101003.0,Technology,Application Software
3118,ZVO,901866,Zovio Inc,102006.0,Consumer Defensive,Education
3119,ZY,1243193,Zymergen Inc.,106002.0,Healthcare,Biotechnology
3120,ZYNE,901704,"Zynerba Pharmaceuticals, Inc.",106002.0,Healthcare,Biotechnology
3121,ZYXI,171401,ZYNEX INC,106004.0,Healthcare,Medical Devices

In [82]:
eps_df=pd.read_csv('eps_df.csv')
eps_df

       Earnings Per Share, Basic Ticker  Fiscal Year Fiscal Period
0                        0.52174      A         2017            Q1
1                        0.51090      A         2017            Q2
2                        0.54517      A         2017            Q3
3                        0.54630      A         2017            Q4
4                       -0.99071      A         2018            Q1
...                          ...    ...          ...           ...
51199                    0.15951   ZYXI         2021            Q3
51200                    0.26031   ZYXI         2021            Q4
51201                    0.03259   ZYXI         2022            Q1
51202                    0.08612   ZYXI         2022            Q2
51203                    0.12808   ZYXI         2022            Q3

[51204 rows x 4 columns]

In [83]:
cashflow_df=cashflow_df.drop(columns=['Report Date', 'Currency', 'Publish Date', 'Restated Date', 'Shares (Basic)', 'Shares (Diluted)', 'Depreciation & Amortization'])
cashflow_df

,Ticker,SimFinId,Fiscal Year,Fiscal Period,Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Change in Accounts Receivable,Change in Inventories,Change in Accounts Payable,...,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash
0,A,45846,2017,Q1,168000000.0,45000000.0,-152000000.0,-31000000.0,-26000000.0,9000000.0,...,116000000.0,-32000000.0,NaN,-69000000.0,-101000000.0,-42000000.0,89000000.0,-93000000.0,-58000000.0,-48000000
1,A,45846,2017,Q2,164000000.0,27000000.0,12000000.0,-17000000.0,-3000000.0,-3000000.0,...,257000000.0,-43000000.0,NaN,0.0,-43000000.0,-43000000.0,52000000.0,-75000000.0,-67000000.0,148000000
2,A,45846,2017,Q3,175000000.0,83000000.0,-81000000.0,19000000.0,-17000000.0,5000000.0,...,228000000.0,-43000000.0,NaN,-57000000.0,-101000000.0,-42000000.0,39000000.0,32000000.0,29000000.0,174000000
3,A,45846,2017,Q4,177000000.0,38000000.0,21000000.0,-52000000.0,-15000000.0,-9000000.0,...,288000000.0,-58000000.0,0.0,0.0,-60000000.0,-43000000.0,-70000000.0,8000000.0,-106000000.0,115000000
4,A,45846,2018,Q1,-320000000.0,564000000.0,-80000000.0,-5000000.0,-34000000.0,-3000000.0,...,215000000.0,-60000000.0,NaN,-6000000.0,-67000000.0,-48000000.0,135000000.0,-22000000.0,37000000.0,210000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41574,ZYXI,171401,2020,Q3,1333000.0,180000.0,-2787000.0,NaN,NaN,NaN,...,-769000.0,-105000.0,NaN,NaN,-105000.0,NaN,-15000.0,25202000.0,25187000.0,24313000
41575,ZYXI,171401,2020,Q4,1787000.0,1327000.0,-5340000.0,NaN,NaN,NaN,...,-1696000.0,-226000.0,NaN,NaN,-226000.0,NaN,-15000.0,293000.0,-134000.0,-2056000
41576,ZYXI,171401,2021,Q1,-706000.0,-213000.0,-4873000.0,NaN,NaN,NaN,...,-5305000.0,-299000.0,NaN,NaN,-299000.0,NaN,-23000.0,-48000.0,-130000.0,-5734000
41577,ZYXI,171401,2021,Q2,2808000.0,1227000.0,-3615000.0,NaN,NaN,NaN,...,1027000.0,-55000.0,NaN,NaN,-55000.0,NaN,-21000.0,-1984000.0,-2081000.0,-1109000
41578,ZYXI,171401,2021,Q3,6107000.0,1040000.0,-4053000.0,NaN,NaN,NaN,...,3689000.0,-66000.0,NaN,NaN,-66000.0,NaN,-29000.0,-508000.0,-585000.0,3038000

In [84]:
balance_df= balance_df.drop(columns=['Report Date', 'Currency', 'Publish Date', 'Restated Date', 'Shares (Basic)', 'Shares (Diluted)'])
balance_df

,Ticker,SimFinId,Fiscal Year,Fiscal Period,"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,...,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity
0,A,45846,2017,Q1,2.241000e+09,653000000.0,551000000.0,3.635000e+09,653000000.0,133000000.0,...,190000000.0,1.089000e+09,1.802000e+09,2.483000e+09,3.572000e+09,5.239000e+09,0.0,-453000000.0,4.300000e+09,7.872000e+09
1,A,45846,2017,Q2,2.389000e+09,677000000.0,548000000.0,3.800000e+09,675000000.0,134000000.0,...,241000000.0,1.187000e+09,1.802000e+09,2.454000e+09,3.641000e+09,5.242000e+09,0.0,-393000000.0,4.375000e+09,8.016000e+09
2,A,45846,2017,Q3,2.563000e+09,678000000.0,566000000.0,3.996000e+09,716000000.0,137000000.0,...,280000000.0,1.241000e+09,1.801000e+09,2.409000e+09,3.650000e+09,5.285000e+09,0.0,-260000000.0,4.611000e+09,8.261000e+09
3,A,45846,2017,Q4,2.678000e+09,724000000.0,575000000.0,4.169000e+09,757000000.0,138000000.0,...,210000000.0,1.263000e+09,1.801000e+09,2.328000e+09,3.591000e+09,5.303000e+09,NaN,-126000000.0,4.835000e+09,8.426000e+09
4,A,45846,2018,Q1,2.887000e+09,751000000.0,608000000.0,4.397000e+09,792000000.0,140000000.0,...,345000000.0,1.361000e+09,1.800000e+09,2.811000e+09,4.172000e+09,5.323000e+09,-3000000.0,-529000000.0,4.526000e+09,8.698000e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41574,ZYXI,171401,2020,Q3,4.122900e+07,9365000.0,5898000.0,5.755300e+07,1670000.0,NaN,...,NaN,7.295000e+06,NaN,3.448000e+06,1.074300e+07,3.651400e+07,-3846000.0,21643000.0,5.422200e+07,6.496500e+07
41575,ZYXI,171401,2020,Q4,3.917300e+07,13837000.0,8635000.0,6.302300e+07,1925000.0,NaN,...,NaN,1.011700e+07,NaN,5.203000e+06,1.532000e+07,3.723500e+07,-3846000.0,23430000.0,5.685500e+07,7.217500e+07
41576,ZYXI,171401,2021,Q1,3.343900e+07,14874000.0,10957000.0,6.082900e+07,2299000.0,NaN,...,NaN,9.315000e+06,NaN,4.768000e+06,1.408300e+07,3.735000e+07,-3921000.0,22724000.0,5.615300e+07,7.023600e+07
41577,ZYXI,171401,2021,Q2,3.233000e+07,18310000.0,9951000.0,6.177900e+07,2355000.0,NaN,...,NaN,8.891000e+06,NaN,1.750700e+07,2.639800e+07,3.773400e+07,-5966000.0,25532000.0,5.730000e+07,8.369800e+07
41578,ZYXI,171401,2021,Q3,3.536800e+07,24234000.0,9154000.0,6.985800e+07,2253000.0,NaN,...,NaN,1.029200e+07,NaN,1.704800e+07,2.734000e+07,3.825700e+07,-6513000.0,31639000.0,6.338300e+07,9.072300e+07

In [85]:
income_df

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Non-Operating Income (Loss),"Interest Expense, Net","Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common)
0,A,1/31/2017,45846,USD,2017,Q1,3/8/2017,3/6/2018,322000000.0,326000000.0,...,-13000000.0,-16000000.0,193000000,NaN,193000000,-25000000.0,168000000,NaN,168000000,168000000
1,A,4/30/2017,45846,USD,2017,Q2,6/6/2017,5/31/2018,321000000.0,325000000.0,...,-10000000.0,-15000000.0,191000000,NaN,191000000,-27000000.0,164000000,NaN,164000000,164000000
2,A,7/31/2017,45846,USD,2017,Q3,9/6/2017,8/30/2018,321000000.0,326000000.0,...,-8000000.0,-13000000.0,193000000,NaN,193000000,-18000000.0,175000000,NaN,175000000,175000000
3,A,10/31/2017,45846,USD,2017,Q4,12/21/2017,12/20/2018,324000000.0,327000000.0,...,-7000000.0,-13000000.0,226000000,NaN,226000000,-49000000.0,177000000,NaN,177000000,177000000
4,A,1/31/2018,45846,USD,2018,Q1,3/6/2018,3/5/2019,323000000.0,323000000.0,...,4000000.0,-11000000.0,233000000,NaN,233000000,-553000000.0,-320000000,NaN,-320000000,-320000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41574,ZYXI,9/30/2020,171401,USD,2020,Q3,10/27/2020,7/29/2021,37945600.0,39035700.0,...,-5000.0,-5000.0,1404000,NaN,1404000,-71000.0,1333000,NaN,1333000,1333000
41575,ZYXI,12/31/2020,171401,USD,2020,Q4,2/25/2021,11/2/2021,38262400.0,39189700.0,...,-5000.0,-5000.0,2292000,-77000.0,2215000,-428000.0,1787000,NaN,1787000,1787000
41576,ZYXI,3/31/2021,171401,USD,2021,Q1,4/29/2021,4/28/2022,38320700.0,38320700.0,...,-9000.0,-9000.0,-1090000,NaN,-1090000,384000.0,-706000,NaN,-706000,-706000
41577,ZYXI,6/30/2021,171401,USD,2021,Q2,7/29/2021,4/28/2022,38320700.0,38320700.0,...,-45000.0,-45000.0,3770000,NaN,3770000,-962000.0,2808000,NaN,2808000,2808000
41578,ZYXI,9/30/2021,171401,USD,2021,Q3,11/2/2021,10/27/2022,38285500.0,39141300.0,...,-18000.0,-18000.0,8028000,NaN,8028000,-1921000.0,6107000,NaN,6107000,6107000

In [86]:
merged_df = companies_industries_df.merge(income_df, on = ['Ticker','SimFinId'], how = 'left')\
                                   .merge(cashflow_df, on = ['Ticker','SimFinId', 'Fiscal Year','Fiscal Period'], how = 'left')\
                                   .merge(balance_df, on = ['Ticker','SimFinId','Fiscal Year','Fiscal Period'], how = 'left')\
                                   .merge(eps_df, on = ['Ticker','Fiscal Year','Fiscal Period'], how = 'left')
merged_df

,Ticker,SimFinId,Company Name,IndustryId,Sector,Industry,Report Date,Currency,Fiscal Year,Fiscal Period,...,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic"
0,A,45846,AGILENT TECHNOLOGIES INC,106001.0,Healthcare,Medical Diagnostics & Research,1/31/2017,USD,2017.0,Q1,...,1.089000e+09,1.802000e+09,2.483000e+09,3.572000e+09,5.239000e+09,0.0,-453000000.0,4.300000e+09,7.872000e+09,0.52174
1,A,45846,AGILENT TECHNOLOGIES INC,106001.0,Healthcare,Medical Diagnostics & Research,4/30/2017,USD,2017.0,Q2,...,1.187000e+09,1.802000e+09,2.454000e+09,3.641000e+09,5.242000e+09,0.0,-393000000.0,4.375000e+09,8.016000e+09,0.51090
2,A,45846,AGILENT TECHNOLOGIES INC,106001.0,Healthcare,Medical Diagnostics & Research,7/31/2017,USD,2017.0,Q3,...,1.241000e+09,1.801000e+09,2.409000e+09,3.650000e+09,5.285000e+09,0.0,-260000000.0,4.611000e+09,8.261000e+09,0.54517
3,A,45846,AGILENT TECHNOLOGIES INC,106001.0,Healthcare,Medical Diagnostics & Research,10/31/2017,USD,2017.0,Q4,...,1.263000e+09,1.801000e+09,2.328000e+09,3.591000e+09,5.303000e+09,NaN,-126000000.0,4.835000e+09,8.426000e+09,0.54630
4,A,45846,AGILENT TECHNOLOGIES INC,106001.0,Healthcare,Medical Diagnostics & Research,1/31/2018,USD,2018.0,Q1,...,1.361000e+09,1.800000e+09,2.811000e+09,4.172000e+09,5.323000e+09,-3000000.0,-529000000.0,4.526000e+09,8.698000e+09,-0.99071
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42157,ZYXI,171401,ZYNEX INC,106004.0,Healthcare,Medical Devices,9/30/2020,USD,2020.0,Q3,...,7.295000e+06,NaN,3.448000e+06,1.074300e+07,3.651400e+07,-3846000.0,21643000.0,5.422200e+07,6.496500e+07,0.03513
42158,ZYXI,171401,ZYNEX INC,106004.0,Healthcare,Medical Devices,12/31/2020,USD,2020.0,Q4,...,1.011700e+07,NaN,5.203000e+06,1.532000e+07,3.723500e+07,-3846000.0,23430000.0,5.685500e+07,7.217500e+07,0.04670
42159,ZYXI,171401,ZYNEX INC,106004.0,Healthcare,Medical Devices,3/31/2021,USD,2021.0,Q1,...,9.315000e+06,NaN,4.768000e+06,1.408300e+07,3.735000e+07,-3921000.0,22724000.0,5.615300e+07,7.023600e+07,-0.01842
42160,ZYXI,171401,ZYNEX INC,106004.0,Healthcare,Medical Devices,6/30/2021,USD,2021.0,Q2,...,8.891000e+06,NaN,1.750700e+07,2.639800e+07,3.773400e+07,-5966000.0,25532000.0,5.730000e+07,8.369800e+07,0.07328
42161,ZYXI,171401,ZYNEX INC,106004.0,Healthcare,Medical Devices,9/30/2021,USD,2021.0,Q3,...,1.029200e+07,NaN,1.704800e+07,2.734000e+07,3.825700e+07,-6513000.0,31639000.0,6.338300e+07,9.072300e+07,0.15951

In [88]:
merged_df=merged_df.drop(columns=['SimFinId', 'IndustryId'])
merged_df.shape

(42162, 68)

In [89]:
len(merged_df['Ticker'].unique().tolist())

3122

In [90]:
merged_df['Ticker'].unique().tolist()

['A',
 'A21',
 'AA',
 'AAL',
 'AAMC',
 'AAME',
 'AAN',
 'AAOI',
 'AAON',
 'AAP',
 'AAPL',
 'AAT',
 'AAWW',
 'ABAX',
 'ABBV',
 'ABC',
 'ABCB',
 'ABCD',
 'ABCL',
 'ABEO',
 'ABG',
 'ABIO',
 'ABM',
 'ABMC',
 'ABMD',
 'ABNB',
 'ABR',
 'ABSI',
 'ABT',
 'ABTL',
 'ABTX',
 'ABUS',
 'ABX',
 'AC',
 'ACA',
 'ACAD',
 'ACAN',
 'ACAT',
 'ACC',
 'ACCO',
 'ACER',
 'ACET',
 'ACET_delis',
 'ACGL',
 'ACHC',
 'ACI',
 'ACIA',
 'ACIW',
 'ACLS',
 'ACLX',
 'ACM',
 'ACN',
 'ACPW',
 'ACRX',
 'ACT',
 'ACU',
 'ACW',
 'ADBE',
 'ADES',
 'ADI',
 'ADIL',
 'ADM',
 'ADMA',
 'ADNT',
 'ADOM',
 'ADP',
 'ADPT',
 'ADPT_delis',
 'ADSK',
 'ADT',
 'ADTM',
 'ADTN',
 'ADUS',
 'ADV',
 'ADVM',
 'ADXS',
 'AE',
 'AEE',
 'AEHR',
 'AEIS',
 'AEO',
 'AEP',
 'AEPI',
 'AES',
 'AET',
 'AFG',
 'AFGS',
 'AFI',
 'AFL',
 'AFRM',
 'AFSI',
 'AGCO',
 'AGHI',
 'AGI',
 'AGIO',
 'AGLE',
 'AGN',
 'AGNC',
 'AGN_old',
 'AGO',
 'AGR',
 'AGS',
 'AGX',
 'AGYS',
 'AH',
 'AHFD',
 'AHH',
 'AHL',
 'AHPI',
 'AI',
 'AIG',
 'AIMC',
 'AINC',
 'AIR',
 'AIRC',
 'AIRI',
 'AIT',
 'AIV',
 'AIZ',
 'AJBI',
 'AJG',
 'AJRD',
 'AJX',
 'AKAM',
 'AKR',
 'AKRX',
 'AKS',
 'AKYA',
 'AL',
 'ALB',
 'ALCO',
 'ALE',
 'ALEX',
 'ALG',
 'ALGN',
 'ALGT',
 'ALJ',
 'ALJJ',
 'ALK',
 'ALKS',
 'ALL',
 'ALLE',
 'ALLK',
 'ALLY',
 'ALNY',
 'ALOT',
 'ALPN',
 'ALR',
 'ALRM',
 'ALRN',
 'ALSK',
 'ALSN',
 'ALT',
 'ALTA',
 'ALTM',
 'ALTMS',
 'ALTR',
 'ALTR_delis',
 'ALV',
 'ALX',
 'ALXN',
 'AMAT',
 'AMBA',
 'AMC',
 'AMCX',
 'AMD',
 'AME',
 'AMED',
 'AMG',
 'AMGN',
 'AMH',
 'AMHCU',
 'AMKR',
 'AMN',
 'AMOT',
 'AMP',
 'AMPL',
 'AMR',
 'AMRK',
 'AMRS',
 'AMRU',
 'AMSC',
 'AMSWA',
 'AMT',
 'AMTD',
 'AMWD',
 'AMZN',
 'AN',
 'ANDV',
 'ANDX',
 'ANET',
 'ANF',
 'ANGI',
 'ANIK',
 'ANSS',
 'ANVS',
 'ANY',
 'AON',
 'AORT',
 'AOS',
 'AOSL',
 'AP',
 'APA',
 'APAM',
 'APC',
 'APD',
 'APEI',
 'APH',
 'APIC',
 'APLD',
 'APLS',
 'APO',
 'APOG',
 'APPF',
 'APPS',
 'APRE',
 'APRN',
 'APTI',
 'APTV',
 'APU',
 'APVO',
 'APY',
 'AR',
 'ARA',
 'ARAY',
 'ARCB',
 'ARCH',
 'ARCW',
 'ARE',
 'AREX',
 'ARG',
 'ARHS',
 'ARI',
 'ARKR',
 'ARLO',
 'ARLP',
 'ARMK',
 'ARMK_old',
 'ARNA',
 'ARNC',
 'ARO',
 'AROC',
 'ARPO',
 'ARQL',
 'ARRS',
 'ARRY',
 'ARTEC',
 'ARTX',
 'ARVN',
 'ARW',
 'ARWR',
 'ASAN',
 'ASB',
 'ASCMA',
 'ASGN',
 'ASH',
 'ASNA',
 'ASO',
 'ASPN',
 'ASPU',
 'ASTC',
 'ASYS',
 'ATHN_delis',
 'ATI',
 'ATKR',
 'ATNX',
 'ATO',
 'ATOM',
 'ATR',
 'ATRO',
 'ATUS',
 'ATVI',
 'ATW',
 'AUDH',
 'AUGX',
 'AURA',
 'AVA',
 'AVAV',
 'AVB',
 'AVD',
 'AVEO',
 'AVGO',
 'AVGO_old',
 'AVGR',
 'AVLR',
 'AVNS',
 'AVNT',
 'AVNW',
 'AVO',
 'AVP',
 'AVT',
 'AVTR',
 'AVXL',
 'AVY',
 'AVYA',
 'AWI',
 'AWK',
 'AWRE',
 'AWX',
 'AXAS',
 'AXDX',
 'AXGN',
 'AXL',
 'AXN',
 'AXON',
 'AXP',
 'AXS',
 'AXTA',
 'AXTI',
 'AY',
 'AYI',
 'AYX',
 'AZEK',
 'AZO',
 'AZPN',
 'AZZ',
 'BA',
 'BABL',
 'BAC',
 'BAH',
 'BATL',
 'BAX',
 'BB',
 'BBBI',
 'BBBY',
 'BBGI',
 'BBRG',
 'BBSI',
 'BBWI',
 'BBY',
 'BC',
 'BCAB',
 'BCC',
 'BCEI',
 'BCLR',
 'BCO',
 'BCOR',
 'BCPC',
 'BCR',
 'BCSI',
 'BDC',
 'BDN',
 'BDSX',
 'BDX',
 'BE',
 'BEAM',
 'BEBE',
 'BEN',
 'BEP',
 'BERK',
 'BERY',
 'BF-A',
 'BFAM',
 'BFH',
 'BFLD',
 'BFLY',
 'BFS',
 'BG',
 'BGCP',
 'BGFV',
 'BGG',
 'BGNE',
 'BGS',
 'BGSF',
 'BH',
 'BHC',
 'BHE',
 'BHF',
 'BHI',
 'BHIL',
 'BHLB',
 'BHR',
 'BID',
 'BIG',
 'BIIB',
 'BILL',
 'BIO',
 'BJ',
 'BJRI',
 'BK',
 'BKD',
 'BKE',
 'BKH',
 'BKI',
 'BKNG',
 'BKR',
 'BKS',
 'BKTI',
 'BKU',
 'BL',
 'BLCM',
 'BLD',
 'BLDR',
 'BLFS',
 'BLI',
 'BLK',
 'BLKB',
 'BLL',
 'BLOX',
 'BLUD',
 'BLUE',
 'BMBL',
 'BMI',
 'BMRA',
 'BMRN',
 'BMS',
 'BMY',
 'BNCL',
 'BNED',
 'BNFT',
 'BNGO',
 'BOH',
 'BOJA',
 'BOKF',
 'BOMN',
 'BONT',
 'BOOM',
 'BOOT',
 'BOX',
 'BOXL',
 'BPL',
 'BPMC',
 'BPMP',
 'BPOP',
 'BR',
 'BRBR',
 'BRC',
 'BRCD',
 'BRCM',
 'BREW',
 'BRID',
 'BRK-A',
 'BRKR',
 'BRKS',
 'BRMK',
 'BRO',
 'BROS',
 'BRRE',
 'BRS',
 'BRSP',
 'BRSS',
 'BRX',
 'BRY',
 'BSET',
 'BSIG',
 'BSM',
 'BSPM',
 'BSQR',
 'BSTC',
 'BSTG',
 'BSX',
 'BSY',
 'BTAI',
 'BTU',
 'BURL',
 'BV',
 'BVS',
 'BVSN',
 'BV_old',
 'BWA',
 'BWLA',
 'BWV',
 'BWXT',
 'BX',
 'BXC',
 'BXP',
 'BYD',
 'BYND',
 'BZH',
 'BZUN',
 'C',
 'C649',
 'CA',
 'CABO',
 'CACC',
 'CACI',
 'CAG',
 'CAGU',
 'CAH',
 'CAKE',
 'CAL',
 'CALA',
 'CALD',
 'CALL',
 'CALM',
 'CALX',
 'CAMP',
 'CANO',
 'CAPC',
 'CAPL',
 'CAR',
 'CARG',
 'CARR',
 'CARS',
 'CASA',
 'CASI',
 'CASY',
 'CAT',
 'CATO',
 'CAVM',
 'CB',
 'CBB',
 'CBI',
 'CBKCQ',
 'CBKM',
 'CBLK',
 'CBM',
 'CBOE',
 'CBRE',
 'CBRL',
 'CBSH',
 'CBT',
 'CBZ',
 'CC',
 'CCE',
 'CCF',
 'CCFI',
 'CCH',
 'CCI',
 'CCK',
 'CCL',
 'CCMP',
 'CCO',
 'CCOI',
 'CCS',
 'CCXI',
 'CDAY',
 'CDE',
 'CDI',
 'CDK',
 'CDMO',
 'CDNA',
 'CDNS',
 'CDR',
 'CDRE',
 'CDW',
 'CDXS',
 'CDZI',
 'CE',
 'CEG',
 'CELC',
 'CELG',
 'CELH',
 'CEMI',
 'CENN',
 'CENT',
 'CENX',
 'CEQP',
 'CERBE',
 'CERN',
 'CERS',
 'CETV',
 'CETX',
 'CEVA',
 'CF',
 'CFG',
 'CFLT',
 'CFMS',
 'CFR',
 'CFRX',
 'CFX',
 'CG',
 'CGA',
 'CGEM',
 'CGNX',
 'CGRN',
 'CHAA',
 'CHAP',
 'CHAQ',
 'CHART',
 'CHD',
 'CHDN',
 'CHE',
 'CHEF',
 'CHGG',
 'CHH',
 'CHK',
 'CHKE',
 'CHKP',
 'CHNG',
 'CHPT',
 'CHRS',
 'CHRW',
 'CHSP',
 'CHTR',
 'CHWY',
 'CI',
 'CICC',
 'CIDM',
 'CIE',
 'CIEN',
 'CIK',
 'CIK0001446',
 'CIK0001536',
 'CIK1479320',
 'CINF',
 'CIO',
 'CIT',
 'CIVI',
 'CK00007861',
 'CK00011568',
 'CK00015317',
 'CK00015503',
 'CK00015847',
 'CKP',
 'CL',
 'CLAR',
 'CLBK',
 'CLBS',
 'CLC',
 'CLCT',
 'CLDR',
 'CLDT',
 'CLF',
 'CLFD',
 'CLGX',
 'CLH',
 'CLNE',
 'CLR',
 'CLRB',
 'CLSK',
 'CLVT',
 'CLX',
 'CMA',
 'CMBG',
 'CMBM',
 'CMC',
 'CMCO',
 'CMCSA',
 'CMD',
 'CME',
 'CMG',
 'CMI',
 'CMLS',
 'CMND',
 'CMP',
 'CMPR',
 'CMPX',
 'CMRO',
 'CMS',
 'CMT',
 'CMTL',
 'CNA',
 'CNC',
 'CNDT',
 'CNFR',
 'CNK',
 'CNM',
 'CNMD',
 'CNND',
 'CNNX',
 'CNO',
 'CNP',
 'CNR',
 'CNS',
 'CNSL',
 'CNTG',
 'CNVR',
 'CNX',
 'CNXC',
 'CNXR',
 'CNXT',
 'COCO',
 'CODA',
 'CODI',
 'CODX',
 'COF',
 'COG',
 'COGT',
 'COHR',
 'COIN',
 'COKE',
 'COL',
 'COLM',
 'COMM',
 'CONE',
 'CONN',
 'COO',
 'COP',
 'COR',
 'CORR',
 'CORT',
 'COST',
 'COT',
 'COTV',
 'COTY',
 'COUP',
 'COVS',
 'CP',
 'CPB',
 'CPE',
 'CPLG',
 'CPN',
 'CPRI',
 'CPRT',
 'CPS',
 'CPSI',
 'CPT',
 'CPXX',
 'CQH',
 'CQP',
 'CR',
 'CRAY',
 'CRBU',
 'CRC',
 'CRD-A',
 'CRDF',
 'CRDO',
 'CRI',
 'CRIS',
 'CRL',
 'CRM',
 'CRNC',
 'CROX',
 'CRR',
 'CRS',
 'CRSP',
 'CRSR',
 'CRTO',
 'CRUS',
 'CRVS',
 'CRWD',
 'CRWS',
 'CRZO',
 'CSBR',
 'CSC',
 'CSCO',
 'CSGP',
 'CSGS',
 'CSII',
 'CSL',
 'CSLT',
 'CSOD',
 'CSPR',
 'CSR',
 'CSRA',
 'CSS',
 'CST',
 'CSTL',
 'CSU',
 'CSV',
 'CSWG',
 'CSWI',
 'CSX',
 'CTAS',
 'CTIC',
 'CTLP',
 'CTLT',
 'CTMX',
 'CTOP',
 'CTRE',
 'CTS',
 'CTSH',
 'CTT',
 'CTVA',
 'CTXR',
 'CTXS',
 'CUB',
 'CUBE',
 'CULP',
 'CUO',
 'CUTR',
 'CUZ',
 'CVA',
 'CVCO',
 'CVGI',
 'CVLT',
 'CVNA',
 'CVS',
 'CVSI',
 'CVT',
 'CVX',
 'CW',
 'CWEN',
 'CWH',
 'CWRL',
 'CWT',
 'CXBS',
 'CXM',
 'CXO',
 'CXP',
 'CXW',
 'CY',
 'CYAN',
 'CYCA',
 'CYCC',
 'CYIG',
 'CYNK',
 'CYNX',
 'CYRP',
 'CZOO',
 'CZR',
 'D',
 'DAL',
 'DALN',
 'DAN',
 'DAR',
 'DASH',
 'DATA',
 'DBD',
 'DBI',
 'DBRG',
 'DBTX',
 'DBX',
 'DCI',
 'DCPH',
 'DD',
 'DDD',
 'DDE',
 'DDMG',
 'DDOG',
 'DDS',
 'DE',
 'DEA',
 'DECK',
 'DEI',
 'DELL',
 'DEN',
 'DENN',
 'DESTQ',
 'DEVV',
 'DFCO',
 'DFODQ',
 'DFS',
 'DFT',
 'DG',
 'DGTC',
 'DGX',
 'DHI',
 'DHR',
 'DHRM',
 'DHX',
 'DIA',
 'DIN',
 'DIS',
 'DISCA',
 'DISH',
 'DIT',
 'DJCO',
 'DK',
 'DKNG',
 'DKS',
 'DLB',
 'DLPH',
 'DLR',
 'DLTH',
 'DLTR',
 'DLX',
 'DM',
 'DMDW',
 'DMLP',
 'DMRC',
 'DMTK',
 'DNAY',
 'DNB',
 'DNKN',
 'DNOW',
 'DOC',
 'DOCN',
 'DOCU',
 'DOMO',
 'DORM',
 'DOV',
 'DOW',
 'DPLO',
 'DPW',
 'DPZ',
 'DRE',
 'DRI',
 'DRIO',
 'DRQ',
 'DRTT',
 'DRVN',
 'DS',
 'DSKE',
 'DT',
 'DTE',
 'DTEA',
 'DTIL',
 'DTM',
 'DTRM',
 'DUK',
 'DUOL',
 'DVA',
 'DVAX',
 'DVN',
 'DWACU',
 'DX',
 'DXC',
 'DXCM',
 'DXLG',
 'DXPE',
 'DY',
 'DYN',
 'DYNT',
 'DYN_delist',
 'DZSI',
 'EA',
 'EAF',
 'EAR',
 'EAST',
 'EAT',
 'EB',
 'EBAY',
 'EBF',
 'EBIX',
 'EBS',
 'ECA',
 'ECL',
 'ECYT',
 'ED',
 'EDIT',
 'EDNT',
 'EE',
 'EEFT',
 'EEI',
 'EEP',
 'EFCT',
 'EFOI',
 'EFX',
 'EGAN',
 'EGHT',
 'EGLT',
 'EGP',
 'EGY',
 'EHC',
 'EHTH',
 'EIGI',
 'EIGR',
 'EIX',
 'EL',
 'ELAN',
 'ELLI',
 'ELMD',
 'ELOX',
 'ELS',
 'ELV',
 'ELY',
 'ELYM',
 'ELYS',
 'EMC',
 'EME',
 'EMIS',
 'EMMS',
 'EMN',
 'EMR',
 'ENB',
 'ENBL',
 'ENDP',
 'ENDP_old',
 'ENG',
 'ENPH',
 'ENR',
 'ENS',
 'ENSG',
 'ENV',
 'ENVA',
 'ENZ',
 'ENZB',
 'EOG',
 'EPAC',
 'EPAM',
 'EPAY',
 'EPD',
 'EPE',
 'EPM',
 'EPR',
 'EPRT',
 'EPZM',
 'EQ',
 'EQIX',
 'EQM',
 'EQR',
 'EQRX',
 'EQT',
 'ERIE',
 'ERS',
 'ES',
 'ESCA',
 'ESGR',
 'ESI',
 'ESI_delist',
 'ESL',
 'ESNT',
 'ESP',
 'ESRT',
 'ESRX',
 'ESS',
 'ESTA',
 'ESTC',
 'ESTE',
 'ES_old',
 'ET',
 'ETD',
 'ETEC',
 'ETFC',
 'ETM',
 'ETN',
 'ETR',
 'ETRN',
 ...]

In [91]:
#PRACTICE OPPORTUNITY:**
#Display the first 70 rows in "industries_info_df" and "companies_info_df" Pandas DataFrames**
#Merge the "industries_info_df" and "companies_info_df" Pandas DataFrames using "right" join type instead of "left" and place the answer in a new Pandas DataFrame titled "companies_industries_right_df"**

industries_info_df.head(70)

    IndustryId              Sector                                 Industry
0       100001         Industrials                      Industrial Products
1       100002         Industrials                        Business Services
2       100003         Industrials               Engineering & Construction
3       100004         Industrials                         Waste Management
4       100005         Industrials                  Industrial Distribution
5       100006         Industrials                                 Airlines
6       100007         Industrials                 Consulting & Outsourcing
7       100008         Industrials                      Aerospace & Defense
8       100009         Industrials            Farm & Construction Machinery
9       100010         Industrials               Transportation & Logistics
10      100011         Industrials                      Employment Services
11      100012         Industrials                      Truck Manufacturing
12      100013         Industrials                            Conglomerates
13      101001          Technology                        Computer Hardware
14      101002          Technology                             Online Media
15      101003          Technology                     Application Software
16      101004          Technology                           Semiconductors
17      101005          Technology                  Communication Equipment
18      102001  Consumer Defensive                       Retail - Defensive
19      102002  Consumer Defensive                  Consumer Packaged Goods
20      102003  Consumer Defensive                         Tobacco Products
21      102004  Consumer Defensive                    Beverages - Alcoholic
22      102005  Consumer Defensive                Beverages - Non-Alcoholic
23      102006  Consumer Defensive                                Education
24      103001   Consumer Cyclical                            Entertainment
25      103002   Consumer Cyclical             Retail - Apparel & Specialty
26      103003   Consumer Cyclical                              Restaurants
27      103004   Consumer Cyclical      Manufacturing - Apparel & Furniture
28      103005   Consumer Cyclical                                    Autos
29      103011   Consumer Cyclical         Advertising & Marketing Services
30      103013   Consumer Cyclical              Homebuilding & Construction
31      103015   Consumer Cyclical                         Travel & Leisure
32      103018   Consumer Cyclical                   Packaging & Containers
33      103020   Consumer Cyclical                        Personal Services
34      103026   Consumer Cyclical                               Publishing
35      104001  Financial Services                         Asset Management
36      104002  Financial Services                                    Banks
37      104003  Financial Services               Brokers, Exchanges & Other
38      104004  Financial Services                         Insurance - Life
39      104005  Financial Services                                Insurance
40      104006  Financial Services          Insurance - Property & Casualty
41      104007  Financial Services                          Credit Services
42      104013  Financial Services                    Insurance - Specialty
43      105001           Utilities                    Utilities - Regulated
44      105002           Utilities  Utilities - Independent Power Producers
45      106001          Healthcare           Medical Diagnostics & Research
46      106002          Healthcare                            Biotechnology
47      106003          Healthcare          Medical Instruments & Equipment
48      106004          Healthcare                          Medical Devices
49      106005          Healthcare                       Drug Manufacturers
50      106006          Healthcare                        Health Care Plans
51      106011          Healthcare                    Health Care Providers
52      106014          Healthcare                     Medical Distribution
53      107001              Energy         Oil & Gas - Refining & Marketing
54      107002              Energy                          Oil & Gas - E&P
55      107003              Energy                    Oil & Gas - Midstream
56      107004              Energy                     Oil & Gas - Services
57      107005              Energy                   Oil & Gas - Integrated
58      107006              Energy                     Oil & Gas - Drilling
59      107007              Energy       Alternative Energy Sources & Other
60      108001   Business Services                   Communication Services
61      108002   Business Services                               Consulting
62      108003   Business Services                            HR & Staffing
63      108004   Business Services                                    Other
64      109001         Real Estate                                    REITs
65      109002         Real Estate                     Real Estate Services
66      110001     Basic Materials                                Chemicals
67      110002     Basic Materials                          Forest Products
68      110003     Basic Materials                              Agriculture
69      110004     Basic Materials                          Metals & Mining

In [92]:
companies_info_df.head(70)

        Ticker  SimFinId                        Company Name  IndustryId
0            A     45846            AGILENT TECHNOLOGIES INC    106001.0
1          A21   1333027                        Li Auto Inc.         NaN
2           AA    367153                          Alcoa Corp    110004.0
3          AAL     68568        American Airlines Group Inc.    100006.0
4         AAMC    847094    Altisource Asset Management Corp    104001.0
5         AAME    450021              ATLANTIC AMERICAN CORP    104004.0
6          AAN    441241               Aaron's Company, Inc.    100007.0
7         AAOI    671827       APPLIED OPTOELECTRONICS, INC.    101004.0
8         AAON    919501                            AAON INC    100001.0
9          AAP    184955              ADVANCE AUTO PARTS INC    103002.0
10        AAPL    111052                           APPLE INC    101001.0
11         AAT    919944         American Assets Trust, Inc.    109001.0
12        AAWW    762204    ATLAS AIR WORLDWIDE HOLDINGS INC    100010.0
13        ABAX     36105                          ABAXIS INC    106001.0
14        ABBV     61199                         AbbVie Inc.    106005.0
15         ABC    187024              AMERISOURCEBERGEN CORP    106014.0
16        ABCB    919504                      Ameris Bancorp    104002.0
17        ABCD    358762        CAMBIUM LEARNING GROUP, INC.    102006.0
18        ABCL   1250893            AbCellera Biologics Inc.    106002.0
19        ABEO    953884            ABEONA THERAPEUTICS INC.         NaN
20         ABG    545489         ASBURY AUTOMOTIVE GROUP INC    103005.0
21        ABIO    953886                ARCA biopharma, Inc.         NaN
22         ABM    199984             ABM INDUSTRIES INC /DE/    100002.0
23        ABMC    160965            AMERICAN BIO MEDICA CORP    106002.0
24        ABMD    445587                         Abiomed Inc    106004.0
25        ABNB   1214552                        Airbnb, Inc.    103015.0
26         ABR    638468              ARBOR REALTY TRUST INC    109001.0
27        ABSI   1250894                          Absci Corp    106002.0
28         ABT     63877                 ABBOTT LABORATORIES    106004.0
29        ABTL    445589                       AutoWeb, Inc.    101002.0
30        ABTX    953887         Allegiance Bancshares, Inc.    104002.0
31        ABUS    953888              Arbutus Biopharma Corp    106002.0
32         ABX   1271527                   BARRICK GOLD CORP         NaN
33          AC    919941      Associated Capital Group, Inc.    104003.0
34         ACA    919864                        Arcosa, Inc.    100003.0
35        ACAD    445591          Acadia Pharmaceuticals Inc    106002.0
36        ACAN    654226                     AmeriCann, Inc.    106005.0
37        ACAT     33956                      ARCTIC CAT INC    103005.0
38         ACC    445593     American Campus Communities Inc    109001.0
39        ACCO    120923                    ACCO BRANDS Corp    100001.0
40        ACER   1053636              Acer Therapeutics Inc.    106002.0
41        ACET   1154966                    Adicet Bio, Inc.    106002.0
42  ACET_delis    191612                          ACETO CORP    106005.0
43        ACGL    445596              Arch Capital Group LTD    104013.0
44        ACHC    445598       Acadia Healthcare Company Inc    106011.0
45         ACI   1077533          Albertsons Companies, Inc.    102001.0
46        ACIA    353923         Acacia Communications, Inc.    101005.0
47        ACIW   1057787                 ACI WORLDWIDE, INC.    101003.0
48        ACLS    670942            AXCELIS TECHNOLOGIES INC    101004.0
49        ACLX   1342109                       Arcellx, Inc.    106002.0
50         ACM    445606               Aecom Technology Corp    100003.0
51         ACN     61372                       Accenture plc    108002.0
52        ACPW     95192                    ACTIVE POWER INC         NaN
53        ACRX    113247          ACELRX PHARMACEUTICALS INC    106004.0
54         ACT    353702                       Actavis, Inc.    106002.0
55         ACU    998436                    ACME UNITED CORP    102001.0
56         ACW    671043                       ACCURIDE CORP    100012.0
57        ADBE     14099                       Adobe Systems    101003.0
58        ADES    619745  Advanced Emissions Solutions, Inc.    100001.0
59         ADI     65917                  ANALOG DEVICES INC    101004.0
60        ADIL    807531         ADIAL PHARMACEUTICALS, INC.    106002.0
61         ADM     66997           ARCHER DANIELS MIDLAND CO    102002.0
62        ADMA    976582                ADMA BIOLOGICS, INC.    106002.0
63        ADNT    675558                          Adient plc    103005.0
64        ADOM    807727           Envirotech Vehicles, Inc.    103005.0
65         ADP    591496       AUTOMATIC DATA PROCESSING INC    100002.0
66        ADPT   1147630       Adaptive Biotechnologies Corp    106002.0
67  ADPT_delis    118952                 Adeptus Health Inc.    106002.0
68        ADSK    185035                        AUTODESK INC    101003.0
69         ADT     54871                            ADT Inc.    101001.0

In [93]:
companies_industries_right_df=pd.merge(companies_info_df, industries_info_df, on ='IndustryId',how='right')
companies_industries_right_df

,Ticker,SimFinId,Company Name,IndustryId,Sector,Industry
0,AAON,919501,AAON INC,100001.0,Industrials,Industrial Products
1,ACCO,120923,ACCO BRANDS Corp,100001.0,Industrials,Industrial Products
2,ADES,619745,"Advanced Emissions Solutions, Inc.",100001.0,Industrials,Industrial Products
3,AIMC,773555,Altra Industrial Motion Corp.,100001.0,Industrials,Industrial Products
4,ALOT,995248,"AstroNova, Inc.",100001.0,Industrials,Industrial Products
...,...,...,...,...,...,...
2721,BRK-A,71306,BERKSHIRE HATHAWAY INC,111001.0,Other,Diversified Holdings
2722,CW,1057791,CURTISS WRIGHT CORP,111001.0,Other,Diversified Holdings
2723,DFCO,1077526,DALRADA FINANCIAL CORP,111001.0,Other,Diversified Holdings
2724,MARA,914944,"Marathon Patent Group, Inc.",111001.0,Other,Diversified Holdings
2725,RIOT,1072404,"Riot Blockchain, Inc.",111001.0,Other,Diversified Holdings

In [94]:
companies_industries_right_df.head(70)

,Ticker,SimFinId,Company Name,IndustryId,Sector,Industry
0,AAON,919501,AAON INC,100001.0,Industrials,Industrial Products
1,ACCO,120923,ACCO BRANDS Corp,100001.0,Industrials,Industrial Products
2,ADES,619745,"Advanced Emissions Solutions, Inc.",100001.0,Industrials,Industrial Products
3,AIMC,773555,Altra Industrial Motion Corp.,100001.0,Industrials,Industrial Products
4,ALOT,995248,"AstroNova, Inc.",100001.0,Industrials,Industrial Products
5,AME,67669,AMETEK INC/,100001.0,Industrials,Industrial Products
6,AOS,445771,Smith A O Corp,100001.0,Industrials,Industrial Products
7,AP,995247,AMPCO PITTSBURGH CORP,100001.0,Industrials,Industrial Products
8,ARCW,674718,"ARC Group Worldwide, Inc.",100001.0,Industrials,Industrial Products
9,ARNC,1195675,Arconic Corp,100001.0,Industrials,Industrial Products
10,ARTX,739639,AROTECH CORP,100001.0,Industrials,Industrial Products
11,ATI,442346,Allegheny Technologies Inc.,100001.0,Industrials,Industrial Products
12,ATKR,368117,Atkore International Group Inc.,100001.0,Industrials,Industrial Products
13,AVTR,1033572,"Avantor, Inc.",100001.0,Industrials,Industrial Products
14,AVY,66346,Avery Dennison Corp,100001.0,Industrials,Industrial Products
15,AYI,61705,ACUITY BRANDS INC,100001.0,Industrials,Industrial Products
16,AZZ,82401,AZZ INC,100001.0,Industrials,Industrial Products
17,BDC,1234039,BELDEN INC.,100001.0,Industrials,Industrial Products
18,BGG,252726,BRIGGS & STRATTON CORP,100001.0,Industrials,Industrial Products
19,BRSS,778121,"GLOBAL BRASS & COPPER HOLDINGS, INC.",100001.0,Industrials,Industrial Products
20,CARR,1169063,Carrier Global Corp,100001.0,Industrials,Industrial Products
21,CCF,90312,CHASE CORP,100001.0,Industrials,Industrial Products
22,CETX,178699,CEMTREX INC,100001.0,Industrials,Industrial Products
23,CGRN,51961,Capstone Green Energy Corp,100001.0,Industrials,Industrial Products
24,CLC,57096,CLARCOR INC.,100001.0,Industrials,Industrial Products
25,CMI,120498,CUMMINS INC,100001.0,Industrials,Industrial Products
26,CNM,1298294,"Core & Main, Inc.",100001.0,Industrials,Industrial Products
27,CR,355869,CRANE CO /DE/,100001.0,Industrials,Industrial Products
28,CSWI,49347,"CSW INDUSTRIALS, INC.",100001.0,Industrials,Industrial Products
29,CULP,209337,CULP INC,100001.0,Industrials,Industrial Products
30,CUO,884109,CONTINENTAL MATERIALS CORP,100001.0,Industrials,Industrial Products
31,DAR,1234767,DARLING INGREDIENTS INC.,100001.0,Industrials,Industrial Products
32,DCI,50564,DONALDSON CO INC,100001.0,Industrials,Industrial Products
33,DOV,336327,DOVER Corp,100001.0,Industrials,Industrial Products
34,EAF,910562,GRAFTECH INTERNATIONAL LTD,100001.0,Industrials,Industrial Products
35,EBF,90209,"ENNIS, INC.",100001.0,Industrials,Industrial Products
36,EMR,255983,EMERSON ELECTRIC CO,100001.0,Industrials,Industrial Products
37,EPAC,89259,ENERPAC TOOL GROUP CORP,100001.0,Industrials,Industrial Products
38,ETN,124922,Eaton Corp plc,100001.0,Industrials,Industrial Products
39,FELE,124153,FRANKLIN ELECTRIC CO INC,100001.0,Industrials,Industrial Products
40,FLS,378147,Flowserve Corporation,100001.0,Industrials,Industrial Products
41,FSS,968229,FEDERAL SIGNAL CORP /DE/,100001.0,Industrials,Industrial Products
42,FTEK,144208,"FUEL TECH, INC.",100001.0,Industrials,Industrial Products
43,GE,244314,GENERAL ELECTRIC CO,100001.0,Industrials,Industrial Products
44,GEF,998535,"GREIF, INC",100001.0,Industrials,Industrial Products
45,GGG,103052,GRACO INC,100001.0,Industrials,Industrial Products
46,GLGI,178127,"GREYSTONE LOGISTICS, INC.",100001.0,Industrials,Industrial Products
47,GRC,122864,GORMAN RUPP CO,100001.0,Industrials,Industrial Products
48,HAYN,358061,HAYNES INTERNATIONAL INC,100001.0,Industrials,Industrial Products
49,HCCI,861202,"Heritage-Crystal Clean, Inc.",100001.0,Industrials,Industrial Products
50,HDSN,346795,HUDSON TECHNOLOGIES INC /NY,100001.0,Industrials,Industrial Products
51,HI,361523,"Hillenbrand, Inc.",100001.0,Industrials,Industrial Products
52,HLIO,126033,"HELIOS TECHNOLOGIES, INC.",100001.0,Industrials,Industrial Products
53,HNI,123823,HNI CORP,100001.0,Industrials,Industrial Products
54,HON,105257,HONEYWELL INTERNATIONAL INC,100001.0,Industrials,Industrial Products
55,HUBB,628038,HUBBELL INC,100001.0,Industrials,Industrial Products
56,HWM,195506,Howmet Aerospace Inc.,100001.0,Industrials,Industrial Products
57,ICHR,926863,"ICHOR HOLDINGS, LTD.",100001.0,Industrials,Industrial Products
58,ICPW,161289,IRONCLAD PERFORMANCE WEAR CORP,100001.0,Industrials,Industrial Products
59,IEX,824090,IDEX CORP /DE/,100001.0,Industrials,Industrial Products
60,IIIN,1338982,INSTEEL INDUSTRIES INC,100001.0,Industrials,Industrial Products
61,ITW,378165,Illinois Tool Works,100001.0,Industrials,Industrial Products
62,JRSH,1348020,"Jerash Holdings (US), Inc.",100001.0,Industrials,Industrial Products
63,KN,996259,Knowles Corp,100001.0,Industrials,Industrial Products
64,KTEC_delis,368599,KEY TECHNOLOGY INC,100001.0,Industrials,Industrial Products
65,LECO,1056278,LINCOLN ELECTRIC HOLDINGS INC,100001.0,Industrials,Industrial Products
66,LII,98304,LENNOX INTERNATIONAL INC,100001.0,Industrials,Industrial Products
67,MCF,684099,CONTANGO OIL & GAS CO,100001.0,Industrials,Industrial Products
68,MIDD,993573,MIDDLEBY CORP,100001.0,Industrials,Industrial Products
69,MLI,1338979,MUELLER INDUSTRIES INC,100001.0,Industrials,Industrial Products

In [95]:
#LOCATE, COUNT, and HANDLE MISSING DATASETS

#.isnull() method is used to locate missing values in Pandas DataFrames.

merged_df

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,...,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic"
0,A,AGILENT TECHNOLOGIES INC,Healthcare,Medical Diagnostics & Research,1/31/2017,USD,2017.0,Q1,3/8/2017,3/6/2018,...,1.089000e+09,1.802000e+09,2.483000e+09,3.572000e+09,5.239000e+09,0.0,-453000000.0,4.300000e+09,7.872000e+09,0.52174
1,A,AGILENT TECHNOLOGIES INC,Healthcare,Medical Diagnostics & Research,4/30/2017,USD,2017.0,Q2,6/6/2017,5/31/2018,...,1.187000e+09,1.802000e+09,2.454000e+09,3.641000e+09,5.242000e+09,0.0,-393000000.0,4.375000e+09,8.016000e+09,0.51090
2,A,AGILENT TECHNOLOGIES INC,Healthcare,Medical Diagnostics & Research,7/31/2017,USD,2017.0,Q3,9/6/2017,8/30/2018,...,1.241000e+09,1.801000e+09,2.409000e+09,3.650000e+09,5.285000e+09,0.0,-260000000.0,4.611000e+09,8.261000e+09,0.54517
3,A,AGILENT TECHNOLOGIES INC,Healthcare,Medical Diagnostics & Research,10/31/2017,USD,2017.0,Q4,12/21/2017,12/20/2018,...,1.263000e+09,1.801000e+09,2.328000e+09,3.591000e+09,5.303000e+09,NaN,-126000000.0,4.835000e+09,8.426000e+09,0.54630
4,A,AGILENT TECHNOLOGIES INC,Healthcare,Medical Diagnostics & Research,1/31/2018,USD,2018.0,Q1,3/6/2018,3/5/2019,...,1.361000e+09,1.800000e+09,2.811000e+09,4.172000e+09,5.323000e+09,-3000000.0,-529000000.0,4.526000e+09,8.698000e+09,-0.99071
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42157,ZYXI,ZYNEX INC,Healthcare,Medical Devices,9/30/2020,USD,2020.0,Q3,10/27/2020,7/29/2021,...,7.295000e+06,NaN,3.448000e+06,1.074300e+07,3.651400e+07,-3846000.0,21643000.0,5.422200e+07,6.496500e+07,0.03513
42158,ZYXI,ZYNEX INC,Healthcare,Medical Devices,12/31/2020,USD,2020.0,Q4,2/25/2021,11/2/2021,...,1.011700e+07,NaN,5.203000e+06,1.532000e+07,3.723500e+07,-3846000.0,23430000.0,5.685500e+07,7.217500e+07,0.04670
42159,ZYXI,ZYNEX INC,Healthcare,Medical Devices,3/31/2021,USD,2021.0,Q1,4/29/2021,4/28/2022,...,9.315000e+06,NaN,4.768000e+06,1.408300e+07,3.735000e+07,-3921000.0,22724000.0,5.615300e+07,7.023600e+07,-0.01842
42160,ZYXI,ZYNEX INC,Healthcare,Medical Devices,6/30/2021,USD,2021.0,Q2,7/29/2021,4/28/2022,...,8.891000e+06,NaN,1.750700e+07,2.639800e+07,3.773400e+07,-5966000.0,25532000.0,5.730000e+07,8.369800e+07,0.07328
42161,ZYXI,ZYNEX INC,Healthcare,Medical Devices,9/30/2021,USD,2021.0,Q3,11/2/2021,10/27/2022,...,1.029200e+07,NaN,1.704800e+07,2.734000e+07,3.825700e+07,-6513000.0,31639000.0,6.338300e+07,9.072300e+07,0.15951

In [96]:
#for demonstration purpose, I am going to perform data cleaning operation on one ticker symbol ''AAPL'', similar process can be applied to all ticker symbols
#the objective is to find the location of missing values

pd.options.display.max_columns=70
apple_df = merged_df[merged_df['Ticker']=='AAPL'].reset_index(drop=True)
apple_df

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Research & Development,Depreciation & Amortization,Operating Income (Loss),Non-Operating Income (Loss),"Interest Expense, Net","Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common),Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Change in Accounts Receivable,Change in Inventories,Change in Accounts Payable,Change in Other,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic"
0,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2016,USD,2017.0,Q1,2/1/2017,2/2/2018,2.119464e+10,2.131198e+10,7.835100e+10,-4.817500e+10,3.017600e+10,-6.817000e+09,-3.946000e+09,-2.871000e+09,NaN,2.335900e+10,821000000.0,NaN,2.418000e+10,NaN,2.418000e+10,-6.289000e+09,1.789100e+10,NaN,1.789100e+10,1.789100e+10,1.789100e+10,2.708000e+09,3.648000e+09,NaN,NaN,NaN,NaN,2.723400e+10,-3.420000e+09,-1.558100e+10,-17000000.0,-1.912200e+10,-3.130000e+09,2.385000e+09,-1.085100e+10,-1.222500e+10,-4.113000e+09,6.045200e+10,1.405700e+10,2.712000e+09,1.033320e+11,2.651000e+10,1.856380e+11,1.566100e+10,2.278090e+11,3.311410e+11,6.224900e+10,1.399200e+10,8.413000e+10,7.355700e+10,1.146210e+11,1.987510e+11,3.214400e+10,NaN,1.000010e+11,1.323900e+11,3.311410e+11,0.84413
1,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2017,USD,2017.0,Q2,5/3/2017,5/2/2018,2.090316e+10,2.104675e+10,5.289600e+10,-3.230500e+10,2.059100e+10,-6.494000e+09,-3.718000e+09,-2.776000e+09,NaN,1.409700e+10,587000000.0,NaN,1.468400e+10,NaN,1.468400e+10,-3.655000e+09,1.102900e+10,NaN,1.102900e+10,1.102900e+10,1.102900e+10,2.587000e+09,-3.378000e+09,NaN,NaN,NaN,NaN,1.257000e+10,-2.889000e+09,-1.135700e+10,-50000000.0,-1.420200e+10,-3.004000e+09,1.046900e+10,-6.888000e+09,4.180000e+08,-1.214000e+09,6.710100e+10,1.157900e+10,2.910000e+09,1.019900e+11,2.716300e+10,1.897400e+11,1.563900e+10,2.325420e+11,3.345320e+11,5.166900e+10,1.399100e+10,7.334200e+10,8.453100e+10,1.271080e+11,2.004500e+11,3.357900e+10,NaN,1.009250e+11,1.340820e+11,3.345320e+11,0.52762
2,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2017,USD,2017.0,Q3,8/2/2017,8/1/2018,2.078035e+10,2.093400e+10,4.540800e+10,-2.792000e+10,1.748800e+10,-6.720000e+09,-3.783000e+09,-2.937000e+09,NaN,1.076800e+10,540000000.0,NaN,1.130800e+10,NaN,1.130800e+10,-2.591000e+09,8.717000e+09,NaN,8.717000e+09,8.717000e+09,8.717000e+09,3.135000e+09,-5.534000e+09,NaN,NaN,NaN,NaN,8.672000e+09,-2.277000e+09,-8.360000e+08,-181000000.0,-3.180000e+09,-3.365000e+09,9.237000e+09,-7.092000e+09,-2.078000e+09,3.414000e+09,7.675900e+10,1.239900e+10,3.146000e+09,1.128750e+11,2.928600e+10,1.847570e+11,1.825500e+10,2.322980e+11,3.451730e+11,5.521900e+10,1.847500e+10,8.130200e+10,8.986400e+10,1.314460e+11,2.127480e+11,3.444500e+10,NaN,9.852500e+10,1.324250e+11,3.451730e+11,0.41948
3,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2017,USD,2017.0,Q4,11/3/2017,10/31/2019,2.059771e+10,2.073434e+10,5.257900e+10,-3.264800e+10,1.993100e+10,-6.811000e+09,-3.814000e+09,-2.997000e+09,NaN,1.312000e+10,797000000.0,NaN,1.391700e+10,NaN,1.391700e+10,-3.203000e+09,1.071400e+10,NaN,1.071400e+10,1.071400e+10,1.071400e+10,2.376000e+09,1.750000e+08,NaN,NaN,NaN,NaN,1.574900e+10,-3.865000e+09,-5.768000e+09,-81000000.0,-9.942000e+09,-3.270000e+09,6.923000e+09,-7.514000e+09,-4.089000e+09,1.718000e+09,7.418100e+10,1.787400e+10,4.855000e+09,1.286450e+11,3.378300e+10,1.947140e+11,1.817700e+10,2.466740e+11,3.753190e+11,4.424200e+10,1.847300e+10,1.008140e+11,9.720700e+10,1.404580e+11,2.412720e+11,3.586700e+10,NaN,9.833000e+10,1.340470e+11,3.753190e+11,0.52015
4,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2017,USD,2018.0,Q1,2/2/2018,1/30/2019,2.045151e+10,2.063115e+10,8.829300e+10,-5.438100e+10,3.391200e+10,-7.638000e+09,-4.231000e+09,-3.407000e+09,NaN,2.627400e+10,756000000.0,NaN,2.703000e+10,NaN,2.703000e+10,-6.965000e+09,2.006500e+10,NaN,2.006500e+10,2.006500e+10,2.006500e+10,-3.244100e+10,3.792400e+10,NaN,NaN,NaN,NaN,2.829300e+10,-2.810000e+09,-1.056400e+10,-173000000.0,-1.359000e+10,-3.339000e+09,6.971000e+09,-1.009500e+10,-7.501000e+09,7.202000e+09,7.715300e+10,2.344000e+10,4.421000e+09,1.438100e+11,3.367900e+10,2.079440e+11,2.136100e+10,2.629840e+11,4.067940e+11,8.926600e+10,1.847800e+10,1.157880e+11,1.039220e+11,1.508070e+11,2.665950e+11,3.644700e+10,NaN,1.045930e+11,1.401990e+11,4.067940e+11,0.98110
5,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2018,USD,2018.0,Q2,5/2/2018,5/1/2019,2.009951e+10,2.027397e+10,6.113700e+10,-3.771500e+10,2.342200e+10,-7.528000e+09,-4.150000e+09,-3.378000e+09,NaN,1.589400e+10,274000000.0,NaN,1.616800e+10,NaN,1.616800e+10,-2.346000e+09,1.382200e+10,NaN,1.382200e+10,1.382200e+10,1.382200e+10,8.500000e+08,-2.281000e+09,NaN,NaN,NaN,NaN,1.513000e+10,-4.195000e+09,3.277800e+10,-132000000.0,2.871000e+10,-3.190000e+09,-5.020000e+08,-2.242900e+10,-2.627200e+10,1.756800e+10,8.794000e+10,1.432400e+10,7.662000e+09,1.300530e+11,3.507700e+10,1.792860e+11,2.308600e+10,2.374490e+11,3.675020e+11,6.106700e+10,2.047800e+10,8.932000e+10,1.013620e+11,1.513040e+11,2.406240e+11,3.804400e+10,NaN,9.189800e+10,1.268780e+11,3.675020e+11,0.68768
6,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2018,USD,2018.0,Q3,8/1/2018,7/31/2019,1.952867e+10,1.970644e+10,5.326500e+10,-3.284400e+10,2.042100e+10,-7.809000e+09,-4.108000e+09,-3.701000e+09,NaN,1.261200e+10,672000000.0,NaN,1.328400e+10,NaN,1.328400e+10,-1.765000e+09,1.151900e+10,NaN,1.151900e+10,1.151900e+10,1.151900e+10,2.477000e+09,-2.173000e+09,NaN,NaN,NaN,NaN,1.448800e+10,-3.267000e+09,8.079000e+09,-126000000.0,3.947000e+09,-3.653000e+09,-6.010000e+09,-2.078200e+10,-3.152300e+10,-1.308800e+10,7.097000e+10,1.410400e+10,5.936000e+09,1.157610e+11,3.811700e+10,1.727730e+11,2.254600e+10,2.334360e+11,3.491970e+11,6.367300e+10,1.747200e+10,8.854800e+10,9.712800e+10,1.457000e+11,2.342480e+11,3.862400e+10,NaN,7.943600e+10,1.149490e+11,3.491970e+11,0.58985
7,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2018,USD,2018.0,Q4,11/5/2018,10/30/2020,1.920635e+10,1.939019e+10,6.290000e+10,-3.881600e+10,2.408400e+10,-7.966000e+09,-4.216000e+09,-3.750000e+09,NaN,1.611800e+10,303000000.0,NaN,1.642100e+10,NaN,1.642100e+10,-2.296000e+09,1.412500e+10,NaN,1.412500e+10,1.412500e+10,1.412500e+10,1.864000e+09,7.800000e+08,NaN,NaN,NaN,NaN,1.952300e+10,-3.041000e+09,5.520000e+08,-290000000.0,-3.001000e+09,-3.530000e+09,-2.700000e+07,-1.876300e+10,-2.258000e+10,-6.058000e+09,6.630100e+10,2.318600e+10,3.956000e+09,1.313390e+11,4.130400e+10,1.707990e+11,2.228300e+10,2.343860e+11,3.657250e+11,5.588800e+10,2.074800e+10,1.159290e+11,9.373500e+10,1.426490e+11,2.585780e+11,4.020100e+10,NaN,7.040000e+10,1.071470e+11,3.657250e+11,0.73543
8,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2018,USD,2019.0,Q1,1/30/2019,1/29/2020,1.894328e+10,1.909301e+10,8.431000e+10,-5.227900e+10,3.203100e+10,-8.685000e+09,-4.783000e+09,-3.902000e+09,NaN,2.334600e+10,560000000.0,NaN,2.390600e+10,NaN,2.390600e+10,-3.941000e+09,1.996500e+10,NaN,1.996500e+10,1.996500e+10,1.996500e+10,1.612000e+09,1.718000e+09,NaN,NaN,NaN,NaN,2.669000e+10,-3.355000e+09,9.422000e+09,-167000000.0,5.844000e+09,-3.568000e+09,6.000000e+06,-8.796000e+09,-1.367600e+10,1.885800e+10,8.642700e+10,1.807700e+10,4.988000e+09,1.408280e+11,3.959700e+10,1.586080e+11,3.468600e+10,2.328910e+11,3.737190e+11,4.429300e+10,2.174100e+10,1.082830e+11,9.298900e+10,1.475440e+11,2.558270e+11,4.097000e+10,NaN,8.051000e+10,1.178920e+11,3.737190e+11,1.05394
9,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2019,USD,2019.0,Q2,5/1/2019,5/1/2020,1.869628e+10,1.880258e+10,5.801500e+10,-3.619400e+10,2.182100e+10,-8.406000e+09,-4.458000e+09,-3.948000e+09,NaN,1.341500e+10,378000000.0,NaN,1.379300e+10,NaN,1.379300e+10,-2.232000e+09,1.156100e+10,NaN,1.156100e+10,1.156100e+10,1.156100e+10,1.337000e+09,-4.783000e+09,NaN,NaN,NaN,NaN,1.115500e+10,-2.363000e+09,1.574900e+10,-124000000.0,1.334800e+10,-3.443000e+09,-2.542000e+09,-2.331200e+10,-2.945700e+10,-4.954000e+09,8.009200e+10,1.508500e+10,4.884000e+09,1.233460e+11,3.874600e+10,1.453190e+11,3.458700e+10,2.186520e+11,3.419980e+11,3.044300e+10,2.242900e+10,9.377200e+10,9.020100e+10,1.423660e+11,2.361380e+11,4.280100e+10,NaN,6.455800e+10,1.058600e+11,3.419980e+11,0.61836
10,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2019,USD,2019.0,Q3,7/31/2019,7/31/2020,1.828254e+10,1.840552e+10,5.380900e+10,-3.358200e+10,2.022700e+10,-8.683000e+09,-4.426000e+09,-4.257000e+09,NaN,1.154400e+10,367000000.0,NaN,1.191100e+10,NaN,1.191100e+10,-1.867000e+09,1.004400e+10,NaN,1.004400e+10,1.004400e+10,1.004400e+10,1.582000e+09,-2.923000e+09,NaN,NaN,NaN,NaN,1.163600e+10,-2.000000e+09,3.012000e+10,-320000000.0,2.750200e+10,-3.629000e+09,-4.990000e+09,-1.695400e+10,-2.680400e+10,1.233400e+10,9.461400e+10,1.414800e+10,3.355000e+09,1.349730e+11,3.763600e+10,1.159960e+11,3.363400e+10,1.872660e+11,3.222390e+11,2.911500e+10,2.348200e+10,8.970400e+10,8.493600e+10,1.360790e+11,2.257830e+11,4.337100e+10,NaN,5.372400e+10,9.645600e+10,3.222390e+11,0.54938
11,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2019,USD,2019.0,Q4,10/31/2019,10/29/2021,1.796324e+10,1.808150e+10,6.404000e+10,-3.972700e+10,2.431300e+10,-8.688000e+09,-4.578000e+09,-4.110000e+09,NaN,1.562500e+10,502000000.0,NaN,1.612700e+10,NaN,1.612700e+10,-2.441000e+09,1.368600e+10,NaN,1.368600e+10,1.368600e+10,1.368600e+10,5.450000e+08,2.500000e+09,NaN,NaN,NaN,NaN,1.991000e+10,-2.777000e+09,2.802000e+09,-13000000.0,-7.980000e+08,-3.479000e+09,-2.930000e+08,-1.705400e+10,-2.103900e+10,-1.927000e+09,1.005570e+11,2.292600e+10,4.106000e+09,1.628190e+11,3.737800e+10,1.053410e+11,3.297800e+10,1.756970e+11,3.385160e+11,4.623600e+10,1.624000e+10,1.057180e+11,9.180700e+10,1.423100e+11,2.480280e+11,4.517400e+10,NaN,4.589800e+10,9.048800e+10,3.385160e+11,0.76189
12,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2019,USD,2020.0,Q1,1/29/2020,1/28/2021,1.766016e+10,1.781842e+10,9.181900e+10,-5.660200e+10,3.521700e+10,-9.648000e+09,-5.197000e+09,-4.451000e+09,NaN,2.556900e+10,349000000.0,NaN,2.591800e+10,NaN,2.591800e+10,-3.682000e+09,2.223600e+10,NaN,2.223600e+10,2.223600e+10,2.223600e+10,1.219000e+09,4.245000e+09,NaN,NaN,NaN,NaN,3.051600e+10,-2.107000e+09,-1.039600e+10,-958000000.0,-1.366800e+10,-3.539000e+09,2.310000e+08,-2.070400e+10,-2.540700e+10,-8.559000e+09,1.071620e+11,2.097000e+10,4.097000e+09,1.632310e+11,3.703100e+10,9.989900e+10,4.045700e+10,1.773870e+11,3.406180e+11,4.511100e+10,1.521400e+10,1.021610e+11,9.307800e+10,1.489260e+11,2.510870e+11,4.597200e+10,NaN,4.397700e+10,8.953100e+10,3.406180e+11,1.25911
13,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2020,USD,2020.0,Q2,5/1/2020,4/29/2021,1.744040e+10,1.761877e+10,5.831300e+10,-3.594300e+10,2.237000e+10,-9.517000e+09,-4.952000e+09,-4.565000e+09,NaN,1.285300e+10,282000000.0,NaN,1.313500e+10,NaN,1.313500e+10,-1.886000e+09,1.124900e+10,NaN,1.124900e+10,1.124900e+10,1.124900e+10,1.278000e+09,-2.002000e+09,NaN,NaN,NaN,NaN,1.331100e+10,-1.853000e+09,1.140700e+10,-176000000.0,9.013000e+09,-3.375000e+09,-1.753000e+09,-1.814600e+10,-2.094000e+10,1.384000e+09,9.405100e+10,1.572200e+10,3.334000e+09,1.437530e+11,3.588900e+10,9.879300e+10,4.196500e+10,1.766470e+11,3.204000e+11,3.242100e+10,2.042100e+10,9.609400e+10,8.908600e+10,1.458810e+11,2.419750e+11,4.803200e+10,NaN,3.318200e+10,7.842500e+10,3.204000e+11,0.64500
14,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2020,USD,2020.0,Q3,7/31/2020,7/28/2021,1.725029e+10,1.741916e+10,5.968500e+10,-3.700500e+10,2.268000e+10,-9.589000e+09,-4.831000e+09,-4.758000e+09,NaN,1.309100e+10,46000000.0,NaN,1.313700e+10,NaN,1.313700e+10,-1.884000e+09,1.125300e+10,NaN,1.125300e+10,1.125300e+10,1.125300e+10,2.696000e+09,-4.300000e+08,NaN,NaN,NaN,NaN,1.627100e+10,-1.565000e+09,-2.992000e+09,-339000000.0,-5.165000e+09,-3.656000e+09,-4.410000e+08,-1.589100e+10,-1.911600e+10,-8.010000e+09,9.302500e+10,1.788200e+10,3.978000e+09,1.400650e+11,3.568700e+10,1.005920e+11,4.100000e+10,1.772790e+11,3.173440e+11,3.532500e+10,1.867500e+10,9.531800e+10,9.404800e+10,1.497440e+11,2.450620e+11,4.869600e+10,NaN,2.413600e+10,7.228200e+10,3.173440e+11,0.65234
15,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2020,USD,2020.0,Q4,10/30/2020,7/28/2021,1.705762e+10,1.725652e+10,6.469800e+10,-4.000900e+10,2.468900e+10,-9.914000e+09,-4.936000e+09,-4.978000e+09,NaN,1.477500e+10,126000000.0,NaN,1.490100e+10,NaN,1.490100e+10,-2.228000e+09,1.267300e+10,NaN,1.267300e+10,1.267300e+10,1.267300e+10,1.324000e+09,3.877000e+09,NaN,NaN,NaN,NaN,2.057600e+10,-1.784000e+09,7.434000e+09,-51000000.0,5.531000e+09,-3.511000e+09,4.462000e+09,-1.761700e+10,-2.135700e+10,4.750000e+09,9.094300e+10,1.612000e+10,4.061000e+09,1.437130e+11,3.676600e+10,1.008870e+11,4.252200e+10,1.801750e+11,3.238880e+11,4.229600e+10,1.376900e+10,1.053920e+11,9.866700e+10,1.531570e+11,2.585490e+11,5.077900e+10,NaN,1.496600e+10,6.533900e+10,3.238880e+11,0.74295
16,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2020,USD,2021.0,Q1,1/28/2021,1/28/2022,1.693512e+10,1.711369e+10,1.114390e+11,-6.711100e+10,4.432800e+10,-1.079400e+10,-5.631000e+09,-5.163000e+09,NaN,3.353400e+10,45000000.0,NaN,3.357900e+10,NaN,3.357900e+10,-4.824000e+09,2.875500e+10,NaN,2.875500e+10,2.875500e+10,2.875500e+10,1.987000e+09,5.355000e+09,NaN,NaN,NaN,NaN,3.876300e+10,-3.500000e+09,-5.279000e+09,NaN,-8.584000e+09,-3.613000e+09,-9.780000e+08,-2.477500e+10,-3.224900e+10,-2.070000e+09,7.682600e+10,2.710100e+10,4.973000e+09,1.541060e+11,3.793300e+10,1.187450e+11,4.327000e+10,1.999480e+11,3.540540e+11,6.384600e+10,1.276200e+10,1.325070e+11,9.928100e+10,1.553230e+11,2.878300e+11,5.174400e+10,NaN,1.430100e+10,6.622400e+10,3.540540e+11,1.69795
17,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2021,USD,2021.0,Q2,4/29/2021,1/28/2022,1.675348e+10,1.692916e+10,8.958400e+10,-5.150500e+10,3.807900e+10,-1.057600e+10,-5.314000e+09,-5.262000e+09,NaN,2.750300e+10,508000000.0,NaN,2.801100e+10,NaN,2.801100e+10,-4.381000e+09,2.363000e+10,NaN,2.363000e+10,2.363000e+10,2.363000e+10,1.333000e+09,-3.779000e+09,NaN,NaN,NaN,NaN,2.398100e+10,-2.269000e+09,-7.895000e+09,-9000000.0,-1.036800e+10,-3.447000e+09,1.042300e+10,-1.854800e+10,-1.132600e+10,2.287000e+09,6.983400e+10,1.850300e+10,5.219000e+09,1.214650e+11,3.781500e+10,1.345390e+11,4.333900e+10,2.156930e+11,3.371580e+11,4.012700e+10,1.300300e+10,1.063850e+11,1.086420e+11,1.615950e+11,2.679800e+11,5.420300e+10,NaN,1.526100e+10,6.917800e+10,3.371580e+11,1.41045
18,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2021,USD,2021.0,Q3,7/28/2021,4/29/2022,1.684430e+10,1.702142e+10,8.143400e+10,-4.617900e+10,3.525500e+10,-1.112900e+10,-5.412000e+09,-5.717000e+09,NaN,2.412600e+10,243000000.0,NaN,2.436900e+10,NaN,2.436900e+10,-2.625000e+09,2.174400e+10,NaN,2.174400e+10,2.174400e+10,2.174400e+10,1.215000e+09,-4.697000e+09,NaN,NaN,NaN,NaN,2.109400e+10,-2.093000e+09,5.747000e+09,-4000000.0,3.572000e+09,-3.767000e+09,0.000000e+00,-2.290000e+10,-2.939600e+10,-4.730000e+09,6.169600e+10,1.747500e+10,5.178000e+09,1.144230e+11,3.861500e+10,1.319480e+11,4.485400e+10,2.154170e+11,3.298400e+11,4.040900e+10,1.603900e+10,1.077540e+11,1.057520e+11,1.578060e+11,2.655600e+11,5.498900e+10,NaN,9.233000e+09,6.428000e+10,3.298400e+11,1.29088
19,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2021,USD,2021.0,Q4,10/29/2021,7/29/2022,1.639172e+10,1.651929e+10,8.336000e+10,-4.818600e+10,3.517400e+10,-1.138800e+10,-5.616000e+09,-5.772000e+09,NaN,2.378600e+10,-538000000.0,NaN,2.324800e+10,NaN,2.324800e+10,-2.697000e+09,2.055100e+10,NaN,2.055100e+10,2.055100e+10,2.055100e+10,-1.550000e+09,-1.790000e+09,NaN,NaN,NaN,NaN,2.020000e+10,-3.223000e+09,4.352000e+09,-20000000.0,8.350000e+08,-3.640000e+09,3.220000e+09,-1.974800e+10,-2.038200e+10,6.530000e+08,6.263900e+10,2.627800e+10,6.580000e+09,1.348360e+11,3.944000e+10,1.278770e+11,4.884900e+10,2.161660e+11,3.510020e+11,5.476300e+10,6.000000e+09,1.158680e+11,1.187190e+11,1.720440e+11,2.879120e+11,5.736500e+10,NaN,5.562000e+09,6.309000e+10,3.510020e+11,1.25374

In [97]:
# lets use the .isnull() method to locate missing values in the apple_df DataFrame. The .isnull() method to find missing values in the Pandas DataFrame

apple_df.isnull()

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Research & Development,Depreciation & Amortization,Operating Income (Loss),Non-Operating Income (Loss),"Interest Expense, Net","Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common),Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Change in Accounts Receivable,Change in Inventories,Change in Accounts Payable,Change in Other,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic"
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,True,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False

In [98]:
#sum up all missing values
apple_df.isnull().sum()

Ticker                                              0
Company Name                                        0
Sector                                              0
Industry                                            0
Report Date                                         0
Currency                                            0
Fiscal Year                                         0
Fiscal Period                                       0
Publish Date                                        0
Restated Date                                       0
Shares (Basic)                                      0
Shares (Diluted)                                    0
Revenue                                             0
Cost of Revenue                                     0
Gross Profit                                        0
Operating Expenses                                  0
Selling, General & Administrative                   0
Research & Development                              0
Depreciation & Amortization                        20
Operating Income (Loss)                             0
Non-Operating Income (Loss)                         0
Interest Expense, Net                              20
Pretax Income (Loss), Adj.                          0
Abnormal Gains (Losses)                            20
Pretax Income (Loss)                                0
Income Tax (Expense) Benefit, Net                   0
Income (Loss) from Continuing Operations            0
Net Extraordinary Gains (Losses)                   20
Net Income                                          0
Net Income (Common)                                 0
Net Income/Starting Line                            0
Non-Cash Items                                      0
Change in Working Capital                           0
Change in Accounts Receivable                      20
Change in Inventories                              20
Change in Accounts Payable                         20
Change in Other                                    20
Net Cash from Operating Activities                  0
Change in Fixed Assets & Intangibles                0
Net Change in Long Term Investment                  0
Net Cash from Acquisitions & Divestitures           1
Net Cash from Investing Activities                  0
Dividends Paid                                      0
Cash from (Repayment of) Debt                       0
Cash from (Repurchase of) Equity                    0
Net Cash from Financing Activities                  0
Net Change in Cash                                  0
Cash, Cash Equivalents & Short Term Investments     0
Accounts & Notes Receivable                         0
Inventories                                         0
Total Current Assets                                0
Property, Plant & Equipment, Net                    0
Long Term Investments & Receivables                 0
Other Long Term Assets                              0
Total Noncurrent Assets                             0
Total Assets                                        0
Payables & Accruals                                 0
Short Term Debt                                     0
Total Current Liabilities                           0
Long Term Debt                                      0
Total Noncurrent Liabilities                        0
Total Liabilities                                   0
Share Capital & Additional Paid-In Capital          0
Treasury Stock                                     20
Retained Earnings                                   0
Total Equity                                        0
Total Liabilities & Equity                          0
Earnings Per Share, Basic                           0
dtype: int64

In [99]:
#calculate the percentage of missing values in each column and place it in a pandas DataFrame

percentage_missing = apple_df.isnull().sum() * 100 / len(apple_df)
percentage_missing_df= pd.DataFrame({'%Missing': percentage_missing}).reset_index()
percentage_missing_df

                                              index  %Missing
0                                            Ticker       0.0
1                                      Company Name       0.0
2                                            Sector       0.0
3                                          Industry       0.0
4                                       Report Date       0.0
5                                          Currency       0.0
6                                       Fiscal Year       0.0
7                                     Fiscal Period       0.0
8                                      Publish Date       0.0
9                                     Restated Date       0.0
10                                   Shares (Basic)       0.0
11                                 Shares (Diluted)       0.0
12                                          Revenue       0.0
13                                  Cost of Revenue       0.0
14                                     Gross Profit       0.0
15                               Operating Expenses       0.0
16                Selling, General & Administrative       0.0
17                           Research & Development       0.0
18                      Depreciation & Amortization     100.0
19                          Operating Income (Loss)       0.0
20                      Non-Operating Income (Loss)       0.0
21                            Interest Expense, Net     100.0
22                       Pretax Income (Loss), Adj.       0.0
23                          Abnormal Gains (Losses)     100.0
24                             Pretax Income (Loss)       0.0
25                Income Tax (Expense) Benefit, Net       0.0
26         Income (Loss) from Continuing Operations       0.0
27                 Net Extraordinary Gains (Losses)     100.0
28                                       Net Income       0.0
29                              Net Income (Common)       0.0
30                         Net Income/Starting Line       0.0
31                                   Non-Cash Items       0.0
32                        Change in Working Capital       0.0
33                    Change in Accounts Receivable     100.0
34                            Change in Inventories     100.0
35                       Change in Accounts Payable     100.0
36                                  Change in Other     100.0
37               Net Cash from Operating Activities       0.0
38             Change in Fixed Assets & Intangibles       0.0
39               Net Change in Long Term Investment       0.0
40        Net Cash from Acquisitions & Divestitures       5.0
41               Net Cash from Investing Activities       0.0
42                                   Dividends Paid       0.0
43                    Cash from (Repayment of) Debt       0.0
44                 Cash from (Repurchase of) Equity       0.0
45               Net Cash from Financing Activities       0.0
46                               Net Change in Cash       0.0
47  Cash, Cash Equivalents & Short Term Investments       0.0
48                      Accounts & Notes Receivable       0.0
49                                      Inventories       0.0
50                             Total Current Assets       0.0
51                 Property, Plant & Equipment, Net       0.0
52              Long Term Investments & Receivables       0.0
53                           Other Long Term Assets       0.0
54                          Total Noncurrent Assets       0.0
55                                     Total Assets       0.0
56                              Payables & Accruals       0.0
57                                  Short Term Debt       0.0
58                        Total Current Liabilities       0.0
59                                   Long Term Debt       0.0
60                     Total Noncurrent Liabilities       0.0
61                                Total Liabilities       0.0
62       Share Capital & Additional Paid-In Capital       0.0
63                                   Treasury Stock     100.0
64                                Retained Earnings       0.0
65                                     Total Equity       0.0
66                       Total Liabilities & Equity       0.0
67                        Earnings Per Share, Basic       0.0

In [100]:
#sort out the percentage of missing values in a descending order

percentage_missing_df= percentage_missing_df.sort_values(by='%Missing', ascending=False)
percentage_missing_df

                                              index  %Missing
35                       Change in Accounts Payable     100.0
33                    Change in Accounts Receivable     100.0
27                 Net Extraordinary Gains (Losses)     100.0
18                      Depreciation & Amortization     100.0
63                                   Treasury Stock     100.0
21                            Interest Expense, Net     100.0
23                          Abnormal Gains (Losses)     100.0
36                                  Change in Other     100.0
34                            Change in Inventories     100.0
40        Net Cash from Acquisitions & Divestitures       5.0
1                                      Company Name       0.0
0                                            Ticker       0.0
3                                          Industry       0.0
2                                            Sector       0.0
11                                 Shares (Diluted)       0.0
5                                          Currency       0.0
8                                      Publish Date       0.0
12                                          Revenue       0.0
6                                       Fiscal Year       0.0
4                                       Report Date       0.0
19                          Operating Income (Loss)       0.0
17                           Research & Development       0.0
16                Selling, General & Administrative       0.0
15                               Operating Expenses       0.0
13                                  Cost of Revenue       0.0
14                                     Gross Profit       0.0
22                       Pretax Income (Loss), Adj.       0.0
20                      Non-Operating Income (Loss)       0.0
26         Income (Loss) from Continuing Operations       0.0
25                Income Tax (Expense) Benefit, Net       0.0
24                             Pretax Income (Loss)       0.0
28                                       Net Income       0.0
31                                   Non-Cash Items       0.0
9                                     Restated Date       0.0
10                                   Shares (Basic)       0.0
7                                     Fiscal Period       0.0
32                        Change in Working Capital       0.0
29                              Net Income (Common)       0.0
30                         Net Income/Starting Line       0.0
38             Change in Fixed Assets & Intangibles       0.0
39               Net Change in Long Term Investment       0.0
41               Net Cash from Investing Activities       0.0
42                                   Dividends Paid       0.0
37               Net Cash from Operating Activities       0.0
44                 Cash from (Repurchase of) Equity       0.0
45               Net Cash from Financing Activities       0.0
46                               Net Change in Cash       0.0
47  Cash, Cash Equivalents & Short Term Investments       0.0
48                      Accounts & Notes Receivable       0.0
49                                      Inventories       0.0
50                             Total Current Assets       0.0
43                    Cash from (Repayment of) Debt       0.0
51                 Property, Plant & Equipment, Net       0.0
52              Long Term Investments & Receivables       0.0
54                          Total Noncurrent Assets       0.0
53                           Other Long Term Assets       0.0
56                              Payables & Accruals       0.0
57                                  Short Term Debt       0.0
58                        Total Current Liabilities       0.0
55                                     Total Assets       0.0
59                                   Long Term Debt       0.0
60                     Total Noncurrent Liabilities       0.0
61                                Total Liabilities       0.0
62       Share Capital & Additional Paid-In Capital       0.0
64                                Retained Earnings       0.0
65                                     Total Equity       0.0
66                       Total Liabilities & Equity       0.0
67                        Earnings Per Share, Basic       0.0

In [101]:
#Import plotly Express which is used for data Visualization

!pip install plotly
import plotly.express as px

Requirement already satisfied: plotly in C:\Users\shann\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (7.0.0)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\shann\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from plotly) (2.26.0)
Requirement already satisfied: packaging in C:\Users\shann\AppData\Roaming\Python\Python314\site-packages (from plotly) (26.3)

In [105]:
#use Plotly Express to view missing values

fig = px.bar(percentage_missing_df, x = 'index', y = '%Missing')
fig.update_layout(title = dict(text = 'Column Names Vs. % Missing Values'),\
                  xaxis = dict(title = 'Index', tickmode = 'linear'))
fig.show()

In [112]:
#columns thath contain a large number of missing values above 50%
columns_to_drop= percentage_missing_df[percentage_missing_df['%Missing']>50]['index'].tolist()
columns_to_drop

['Change in Accounts Payable',
 'Change in Accounts Receivable',
 'Net Extraordinary Gains (Losses)',
 'Depreciation & Amortization',
 'Treasury Stock',
 'Interest Expense, Net',
 'Abnormal Gains (Losses)',
 'Change in Other',
 'Change in Inventories']

In [114]:
apple_df.isnull().sum()

Ticker                                             0
Company Name                                       0
Sector                                             0
Industry                                           0
Report Date                                        0
Currency                                           0
Fiscal Year                                        0
Fiscal Period                                      0
Publish Date                                       0
Restated Date                                      0
Shares (Basic)                                     0
Shares (Diluted)                                   0
Revenue                                            0
Cost of Revenue                                    0
Gross Profit                                       0
Operating Expenses                                 0
Selling, General & Administrative                  0
Research & Development                             0
Operating Income (Loss)                            0
Non-Operating Income (Loss)                        0
Pretax Income (Loss), Adj.                         0
Pretax Income (Loss)                               0
Income Tax (Expense) Benefit, Net                  0
Income (Loss) from Continuing Operations           0
Net Income                                         0
Net Income (Common)                                0
Net Income/Starting Line                           0
Non-Cash Items                                     0
Change in Working Capital                          0
Net Cash from Operating Activities                 0
Change in Fixed Assets & Intangibles               0
Net Change in Long Term Investment                 0
Net Cash from Acquisitions & Divestitures          1
Net Cash from Investing Activities                 0
Dividends Paid                                     0
Cash from (Repayment of) Debt                      0
Cash from (Repurchase of) Equity                   0
Net Cash from Financing Activities                 0
Net Change in Cash                                 0
Cash, Cash Equivalents & Short Term Investments    0
Accounts & Notes Receivable                        0
Inventories                                        0
Total Current Assets                               0
Property, Plant & Equipment, Net                   0
Long Term Investments & Receivables                0
Other Long Term Assets                             0
Total Noncurrent Assets                            0
Total Assets                                       0
Payables & Accruals                                0
Short Term Debt                                    0
Total Current Liabilities                          0
Long Term Debt                                     0
Total Noncurrent Liabilities                       0
Total Liabilities                                  0
Share Capital & Additional Paid-In Capital         0
Retained Earnings                                  0
Total Equity                                       0
Total Liabilities & Equity                         0
Earnings Per Share, Basic                          0
dtype: int64

In [115]:
#calculate the average Net Cash From Acquisitions & Divestitures
apple_df['Net Cash from Acquisitions & Divestitures'].mean()

np.float64(-170052631.57894737)

In [116]:
#we can use fillna() to fill a given column with a certain value
apple_df['Net Cash from Acquisitions & Divestitures'].fillna(apple_df['Net Cash from Acquisitions & Divestitures'].mean(), inplace=True)
apple_df

C:\Users\shann\AppData\Local\Temp\ipykernel_73988\2806006983.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  apple_df['Net Cash from Acquisitions & Divestitures'].fillna(apple_df['Net Cash from Acquisitions & Divestitures'].mean(), inplace=True)

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Research & Development,Operating Income (Loss),Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Income,Net Income (Common),Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic"
0,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2016,USD,2017.0,Q1,2/1/2017,2/2/2018,2.119464e+10,2.131198e+10,7.835100e+10,-4.817500e+10,3.017600e+10,-6.817000e+09,-3.946000e+09,-2.871000e+09,2.335900e+10,821000000.0,2.418000e+10,2.418000e+10,-6.289000e+09,1.789100e+10,1.789100e+10,1.789100e+10,1.789100e+10,2.708000e+09,3.648000e+09,2.723400e+10,-3.420000e+09,-1.558100e+10,-17000000.0,-1.912200e+10,-3.130000e+09,2.385000e+09,-1.085100e+10,-1.222500e+10,-4.113000e+09,6.045200e+10,1.405700e+10,2.712000e+09,1.033320e+11,2.651000e+10,1.856380e+11,1.566100e+10,2.278090e+11,3.311410e+11,6.224900e+10,1.399200e+10,8.413000e+10,7.355700e+10,1.146210e+11,1.987510e+11,3.214400e+10,1.000010e+11,1.323900e+11,3.311410e+11,0.84413
1,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2017,USD,2017.0,Q2,5/3/2017,5/2/2018,2.090316e+10,2.104675e+10,5.289600e+10,-3.230500e+10,2.059100e+10,-6.494000e+09,-3.718000e+09,-2.776000e+09,1.409700e+10,587000000.0,1.468400e+10,1.468400e+10,-3.655000e+09,1.102900e+10,1.102900e+10,1.102900e+10,1.102900e+10,2.587000e+09,-3.378000e+09,1.257000e+10,-2.889000e+09,-1.135700e+10,-50000000.0,-1.420200e+10,-3.004000e+09,1.046900e+10,-6.888000e+09,4.180000e+08,-1.214000e+09,6.710100e+10,1.157900e+10,2.910000e+09,1.019900e+11,2.716300e+10,1.897400e+11,1.563900e+10,2.325420e+11,3.345320e+11,5.166900e+10,1.399100e+10,7.334200e+10,8.453100e+10,1.271080e+11,2.004500e+11,3.357900e+10,1.009250e+11,1.340820e+11,3.345320e+11,0.52762
2,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2017,USD,2017.0,Q3,8/2/2017,8/1/2018,2.078035e+10,2.093400e+10,4.540800e+10,-2.792000e+10,1.748800e+10,-6.720000e+09,-3.783000e+09,-2.937000e+09,1.076800e+10,540000000.0,1.130800e+10,1.130800e+10,-2.591000e+09,8.717000e+09,8.717000e+09,8.717000e+09,8.717000e+09,3.135000e+09,-5.534000e+09,8.672000e+09,-2.277000e+09,-8.360000e+08,-181000000.0,-3.180000e+09,-3.365000e+09,9.237000e+09,-7.092000e+09,-2.078000e+09,3.414000e+09,7.675900e+10,1.239900e+10,3.146000e+09,1.128750e+11,2.928600e+10,1.847570e+11,1.825500e+10,2.322980e+11,3.451730e+11,5.521900e+10,1.847500e+10,8.130200e+10,8.986400e+10,1.314460e+11,2.127480e+11,3.444500e+10,9.852500e+10,1.324250e+11,3.451730e+11,0.41948
3,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2017,USD,2017.0,Q4,11/3/2017,10/31/2019,2.059771e+10,2.073434e+10,5.257900e+10,-3.264800e+10,1.993100e+10,-6.811000e+09,-3.814000e+09,-2.997000e+09,1.312000e+10,797000000.0,1.391700e+10,1.391700e+10,-3.203000e+09,1.071400e+10,1.071400e+10,1.071400e+10,1.071400e+10,2.376000e+09,1.750000e+08,1.574900e+10,-3.865000e+09,-5.768000e+09,-81000000.0,-9.942000e+09,-3.270000e+09,6.923000e+09,-7.514000e+09,-4.089000e+09,1.718000e+09,7.418100e+10,1.787400e+10,4.855000e+09,1.286450e+11,3.378300e+10,1.947140e+11,1.817700e+10,2.466740e+11,3.753190e+11,4.424200e+10,1.847300e+10,1.008140e+11,9.720700e+10,1.404580e+11,2.412720e+11,3.586700e+10,9.833000e+10,1.340470e+11,3.753190e+11,0.52015
4,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2017,USD,2018.0,Q1,2/2/2018,1/30/2019,2.045151e+10,2.063115e+10,8.829300e+10,-5.438100e+10,3.391200e+10,-7.638000e+09,-4.231000e+09,-3.407000e+09,2.627400e+10,756000000.0,2.703000e+10,2.703000e+10,-6.965000e+09,2.006500e+10,2.006500e+10,2.006500e+10,2.006500e+10,-3.244100e+10,3.792400e+10,2.829300e+10,-2.810000e+09,-1.056400e+10,-173000000.0,-1.359000e+10,-3.339000e+09,6.971000e+09,-1.009500e+10,-7.501000e+09,7.202000e+09,7.715300e+10,2.344000e+10,4.421000e+09,1.438100e+11,3.367900e+10,2.079440e+11,2.136100e+10,2.629840e+11,4.067940e+11,8.926600e+10,1.847800e+10,1.157880e+11,1.039220e+11,1.508070e+11,2.665950e+11,3.644700e+10,1.045930e+11,1.401990e+11,4.067940e+11,0.98110
5,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2018,USD,2018.0,Q2,5/2/2018,5/1/2019,2.009951e+10,2.027397e+10,6.113700e+10,-3.771500e+10,2.342200e+10,-7.528000e+09,-4.150000e+09,-3.378000e+09,1.589400e+10,274000000.0,1.616800e+10,1.616800e+10,-2.346000e+09,1.382200e+10,1.382200e+10,1.382200e+10,1.382200e+10,8.500000e+08,-2.281000e+09,1.513000e+10,-4.195000e+09,3.277800e+10,-132000000.0,2.871000e+10,-3.190000e+09,-5.020000e+08,-2.242900e+10,-2.627200e+10,1.756800e+10,8.794000e+10,1.432400e+10,7.662000e+09,1.300530e+11,3.507700e+10,1.792860e+11,2.308600e+10,2.374490e+11,3.675020e+11,6.106700e+10,2.047800e+10,8.932000e+10,1.013620e+11,1.513040e+11,2.406240e+11,3.804400e+10,9.189800e+10,1.268780e+11,3.675020e+11,0.68768
6,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2018,USD,2018.0,Q3,8/1/2018,7/31/2019,1.952867e+10,1.970644e+10,5.326500e+10,-3.284400e+10,2.042100e+10,-7.809000e+09,-4.108000e+09,-3.701000e+09,1.261200e+10,672000000.0,1.328400e+10,1.328400e+10,-1.765000e+09,1.151900e+10,1.151900e+10,1.151900e+10,1.151900e+10,2.477000e+09,-2.173000e+09,1.448800e+10,-3.267000e+09,8.079000e+09,-126000000.0,3.947000e+09,-3.653000e+09,-6.010000e+09,-2.078200e+10,-3.152300e+10,-1.308800e+10,7.097000e+10,1.410400e+10,5.936000e+09,1.157610e+11,3.811700e+10,1.727730e+11,2.254600e+10,2.334360e+11,3.491970e+11,6.367300e+10,1.747200e+10,8.854800e+10,9.712800e+10,1.457000e+11,2.342480e+11,3.862400e+10,7.943600e+10,1.149490e+11,3.491970e+11,0.58985
7,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2018,USD,2018.0,Q4,11/5/2018,10/30/2020,1.920635e+10,1.939019e+10,6.290000e+10,-3.881600e+10,2.408400e+10,-7.966000e+09,-4.216000e+09,-3.750000e+09,1.611800e+10,303000000.0,1.642100e+10,1.642100e+10,-2.296000e+09,1.412500e+10,1.412500e+10,1.412500e+10,1.412500e+10,1.864000e+09,7.800000e+08,1.952300e+10,-3.041000e+09,5.520000e+08,-290000000.0,-3.001000e+09,-3.530000e+09,-2.700000e+07,-1.876300e+10,-2.258000e+10,-6.058000e+09,6.630100e+10,2.318600e+10,3.956000e+09,1.313390e+11,4.130400e+10,1.707990e+11,2.228300e+10,2.343860e+11,3.657250e+11,5.588800e+10,2.074800e+10,1.159290e+11,9.373500e+10,1.426490e+11,2.585780e+11,4.020100e+10,7.040000e+10,1.071470e+11,3.657250e+11,0.73543
8,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2018,USD,2019.0,Q1,1/30/2019,1/29/2020,1.894328e+10,1.909301e+10,8.431000e+10,-5.227900e+10,3.203100e+10,-8.685000e+09,-4.783000e+09,-3.902000e+09,2.334600e+10,560000000.0,2.390600e+10,2.390600e+10,-3.941000e+09,1.996500e+10,1.996500e+10,1.996500e+10,1.996500e+10,1.612000e+09,1.718000e+09,2.669000e+10,-3.355000e+09,9.422000e+09,-167000000.0,5.844000e+09,-3.568000e+09,6.000000e+06,-8.796000e+09,-1.367600e+10,1.885800e+10,8.642700e+10,1.807700e+10,4.988000e+09,1.408280e+11,3.959700e+10,1.586080e+11,3.468600e+10,2.328910e+11,3.737190e+11,4.429300e+10,2.174100e+10,1.082830e+11,9.298900e+10,1.475440e+11,2.558270e+11,4.097000e+10,8.051000e+10,1.178920e+11,3.737190e+11,1.05394
9,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2019,USD,2019.0,Q2,5/1/2019,5/1/2020,1.869628e+10,1.880258e+10,5.801500e+10,-3.619400e+10,2.182100e+10,-8.406000e+09,-4.458000e+09,-3.948000e+09,1.341500e+10,378000000.0,1.379300e+10,1.379300e+10,-2.232000e+09,1.156100e+10,1.156100e+10,1.156100e+10,1.156100e+10,1.337000e+09,-4.783000e+09,1.115500e+10,-2.363000e+09,1.574900e+10,-124000000.0,1.334800e+10,-3.443000e+09,-2.542000e+09,-2.331200e+10,-2.945700e+10,-4.954000e+09,8.009200e+10,1.508500e+10,4.884000e+09,1.233460e+11,3.874600e+10,1.453190e+11,3.458700e+10,2.186520e+11,3.419980e+11,3.044300e+10,2.242900e+10,9.377200e+10,9.020100e+10,1.423660e+11,2.361380e+11,4.280100e+10,6.455800e+10,1.058600e+11,3.419980e+11,0.61836
10,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2019,USD,2019.0,Q3,7/31/2019,7/31/2020,1.828254e+10,1.840552e+10,5.380900e+10,-3.358200e+10,2.022700e+10,-8.683000e+09,-4.426000e+09,-4.257000e+09,1.154400e+10,367000000.0,1.191100e+10,1.191100e+10,-1.867000e+09,1.004400e+10,1.004400e+10,1.004400e+10,1.004400e+10,1.582000e+09,-2.923000e+09,1.163600e+10,-2.000000e+09,3.012000e+10,-320000000.0,2.750200e+10,-3.629000e+09,-4.990000e+09,-1.695400e+10,-2.680400e+10,1.233400e+10,9.461400e+10,1.414800e+10,3.355000e+09,1.349730e+11,3.763600e+10,1.159960e+11,3.363400e+10,1.872660e+11,3.222390e+11,2.911500e+10,2.348200e+10,8.970400e+10,8.493600e+10,1.360790e+11,2.257830e+11,4.337100e+10,5.372400e+10,9.645600e+10,3.222390e+11,0.54938
11,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2019,USD,2019.0,Q4,10/31/2019,10/29/2021,1.796324e+10,1.808150e+10,6.404000e+10,-3.972700e+10,2.431300e+10,-8.688000e+09,-4.578000e+09,-4.110000e+09,1.562500e+10,502000000.0,1.612700e+10,1.612700e+10,-2.441000e+09,1.368600e+10,1.368600e+10,1.368600e+10,1.368600e+10,5.450000e+08,2.500000e+09,1.991000e+10,-2.777000e+09,2.802000e+09,-13000000.0,-7.980000e+08,-3.479000e+09,-2.930000e+08,-1.705400e+10,-2.103900e+10,-1.927000e+09,1.005570e+11,2.292600e+10,4.106000e+09,1.628190e+11,3.737800e+10,1.053410e+11,3.297800e+10,1.756970e+11,3.385160e+11,4.623600e+10,1.624000e+10,1.057180e+11,9.180700e+10,1.423100e+11,2.480280e+11,4.517400e+10,4.589800e+10,9.048800e+10,3.385160e+11,0.76189
12,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2019,USD,2020.0,Q1,1/29/2020,1/28/2021,1.766016e+10,1.781842e+10,9.181900e+10,-5.660200e+10,3.521700e+10,-9.648000e+09,-5.197000e+09,-4.451000e+09,2.556900e+10,349000000.0,2.591800e+10,2.591800e+10,-3.682000e+09,2.223600e+10,2.223600e+10,2.223600e+10,2.223600e+10,1.219000e+09,4.245000e+09,3.051600e+10,-2.107000e+09,-1.039600e+10,-958000000.0,-1.366800e+10,-3.539000e+09,2.310000e+08,-2.070400e+10,-2.540700e+10,-8.559000e+09,1.071620e+11,2.097000e+10,4.097000e+09,1.632310e+11,3.703100e+10,9.989900e+10,4.045700e+10,1.773870e+11,3.406180e+11,4.511100e+10,1.521400e+10,1.021610e+11,9.307800e+10,1.489260e+11,2.510870e+11,4.597200e+10,4.397700e+10,8.953100e+10,3.406180e+11,1.25911
13,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2020,USD,2020.0,Q2,5/1/2020,4/29/2021,1.744040e+10,1.761877e+10,5.831300e+10,-3.594300e+10,2.237000e+10,-9.517000e+09,-4.952000e+09,-4.565000e+09,1.285300e+10,282000000.0,1.313500e+10,1.313500e+10,-1.886000e+09,1.124900e+10,1.124900e+10,1.124900e+10,1.124900e+10,1.278000e+09,-2.002000e+09,1.331100e+10,-1.853000e+09,1.140700e+10,-176000000.0,9.013000e+09,-3.375000e+09,-1.753000e+09,-1.814600e+10,-2.094000e+10,1.384000e+09,9.405100e+10,1.572200e+10,3.334000e+09,1.437530e+11,3.588900e+10,9.879300e+10,4.196500e+10,1.766470e+11,3.204000e+11,3.242100e+10,2.042100e+10,9.609400e+10,8.908600e+10,1.458810e+11,2.419750e+11,4.803200e+10,3.318200e+10,7.842500e+10,3.204000e+11,0.64500
14,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2020,USD,2020.0,Q3,7/31/2020,7/28/2021,1.725029e+10,1.741916e+10,5.968500e+10,-3.700500e+10,2.268000e+10,-9.589000e+09,-4.831000e+09,-4.758000e+09,1.309100e+10,46000000.0,1.313700e+10,1.313700e+10,-1.884000e+09,1.125300e+10,1.125300e+10,1.125300e+10,1.125300e+10,2.696000e+09,-4.300000e+08,1.627100e+10,-1.565000e+09,-2.992000e+09,-339000000.0,-5.165000e+09,-3.656000e+09,-4.410000e+08,-1.589100e+10,-1.911600e+10,-8.010000e+09,9.302500e+10,1.788200e+10,3.978000e+09,1.400650e+11,3.568700e+10,1.005920e+11,4.100000e+10,1.772790e+11,3.173440e+11,3.532500e+10,1.867500e+10,9.531800e+10,9.404800e+10,1.497440e+11,2.450620e+11,4.869600e+10,2.413600e+10,7.228200e+10,3.173440e+11,0.65234
15,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2020,USD,2020.0,Q4,10/30/2020,7/28/2021,1.705762e+10,1.725652e+10,6.469800e+10,-4.000900e+10,2.468900e+10,-9.914000e+09,-4.936000e+09,-4.978000e+09,1.477500e+10,126000000.0,1.490100e+10,1.490100e+10,-2.228000e+09,1.267300e+10,1.267300e+10,1.267300e+10,1.267300e+10,1.324000e+09,3.877000e+09,2.057600e+10,-1.784000e+09,7.434000e+09,-51000000.0,5.531000e+09,-3.511000e+09,4.462000e+09,-1.761700e+10,-2.135700e+10,4.750000e+09,9.094300e+10,1.612000e+10,4.061000e+09,1.437130e+11,3.676600e+10,1.008870e+11,4.252200e+10,1.801750e+11,3.238880e+11,4.229600e+10,1.376900e+10,1.053920e+11,9.866700e+10,1.531570e+11,2.585490e+11,5.077900e+10,1.496600e+10,6.533900e+10,3.238880e+11,0.74295
16,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2020,USD,2021.0,Q1,1/28/2021,1/28/2022,1.693512e+10,1.711369e+10,1.114390e+11,-6.711100e+10,4.432800e+10,-1.079400e+10,-5.631000e+09,-5.163000e+09,3.353400e+10,45000000.0,3.357900e+10,3.357900e+10,-4.824000e+09,2.875500e+10,2.875500e+10,2.875500e+10,2.875500e+10,1.987000e+09,5.355000e+09,3.876300e+10,-3.500000e+09,-5.279000e+09,NaN,-8.584000e+09,-3.613000e+09,-9.780000e+08,-2.477500e+10,-3.224900e+10,-2.070000e+09,7.682600e+10,2.710100e+10,4.973000e+09,1.541060e+11,3.793300e+10,1.187450e+11,4.327000e+10,1.999480e+11,3.540540e+11,6.384600e+10,1.276200e+10,1.325070e+11,9.928100e+10,1.553230e+11,2.878300e+11,5.174400e+10,1.430100e+10,6.622400e+10,3.540540e+11,1.69795
17,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2021,USD,2021.0,Q2,4/29/2021,1/28/2022,1.675348e+10,1.692916e+10,8.958400e+10,-5.150500e+10,3.807900e+10,-1.057600e+10,-5.314000e+09,-5.262000e+09,2.750300e+10,508000000.0,2.801100e+10,2.801100e+10,-4.381000e+09,2.363000e+10,2.363000e+10,2.363000e+10,2.363000e+10,1.333000e+09,-3.779000e+09,2.398100e+10,-2.269000e+09,-7.895000e+09,-9000000.0,-1.036800e+10,-3.447000e+09,1.042300e+10,-1.854800e+10,-1.132600e+10,2.287000e+09,6.983400e+10,1.850300e+10,5.219000e+09,1.214650e+11,3.781500e+10,1.345390e+11,4.333900e+10,2.156930e+11,3.371580e+11,4.012700e+10,1.300300e+10,1.063850e+11,1.086420e+11,1.615950e+11,2.679800e+11,5.420300e+10,1.526100e+10,6.917800e+10,3.371580e+11,1.41045
18,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2021,USD,2021.0,Q3,7/28/2021,4/29/2022,1.684430e+10,1.702142e+10,8.143400e+10,-4.617900e+10,3.525500e+10,-1.112900e+10,-5.412000e+09,-5.717000e+09,2.412600e+10,243000000.0,2.436900e+10,2.436900e+10,-2.625000e+09,2.174400e+10,2.174400e+10,2.174400e+10,2.174400e+10,1.215000e+09,-4.697000e+09,2.109400e+10,-2.093000e+09,5.747000e+09,-4000000.0,3.572000e+09,-3.767000e+09,0.000000e+00,-2.290000e+10,-2.939600e+10,-4.730000e+09,6.169600e+10,1.747500e+10,5.178000e+09,1.144230e+11,3.861500e+10,1.319480e+11,4.485400e+10,2.154170e+11,3.298400e+11,4.040900e+10,1.603900e+10,1.077540e+11,1.057520e+11,1.578060e+11,2.655600e+11,5.498900e+10,9.233000e+09,6.428000e+10,3.298400e+11,1.29088
19,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2021,USD,2021.0,Q4,10/29/2021,7/29/2022,1.639172e+10,1.651929e+10,8.336000e+10,-4.818600e+10,3.517400e+10,-1.138800e+10,-5.616000e+09,-5.772000e+09,2.378600e+10,-538000000.0,2.324800e+10,2.324800e+10,-2.697000e+09,2.055100e+10,2.055100e+10,2.055100e+10,2.055100e+10,-1.550000e+09,-1.790000e+09,2.020000e+10,-3.223000e+09,4.352000e+09,-20000000.0,8.350000e+08,-3.640000e+09,3.220000e+09,-1.974800e+10,-2.038200e+10,6.530000e+08,6.263900e+10,2.627800e+10,6.580000e+09,1.348360e+11,3.944000e+10,1.278770e+11,4.884900e+10,2.161660e+11,3.510020e+11,5.476300e+10,6.000000e+09,1.158680e+11,1.187190e+11,1.720440e+11,2.879120e+11,5.736500e+10,5.562000e+09,6.309000e+10,3.510020e+11,1.25374

In [117]:
apple_df.isnull().sum()

Ticker                                             0
Company Name                                       0
Sector                                             0
Industry                                           0
Report Date                                        0
Currency                                           0
Fiscal Year                                        0
Fiscal Period                                      0
Publish Date                                       0
Restated Date                                      0
Shares (Basic)                                     0
Shares (Diluted)                                   0
Revenue                                            0
Cost of Revenue                                    0
Gross Profit                                       0
Operating Expenses                                 0
Selling, General & Administrative                  0
Research & Development                             0
Operating Income (Loss)                            0
Non-Operating Income (Loss)                        0
Pretax Income (Loss), Adj.                         0
Pretax Income (Loss)                               0
Income Tax (Expense) Benefit, Net                  0
Income (Loss) from Continuing Operations           0
Net Income                                         0
Net Income (Common)                                0
Net Income/Starting Line                           0
Non-Cash Items                                     0
Change in Working Capital                          0
Net Cash from Operating Activities                 0
Change in Fixed Assets & Intangibles               0
Net Change in Long Term Investment                 0
Net Cash from Acquisitions & Divestitures          1
Net Cash from Investing Activities                 0
Dividends Paid                                     0
Cash from (Repayment of) Debt                      0
Cash from (Repurchase of) Equity                   0
Net Cash from Financing Activities                 0
Net Change in Cash                                 0
Cash, Cash Equivalents & Short Term Investments    0
Accounts & Notes Receivable                        0
Inventories                                        0
Total Current Assets                               0
Property, Plant & Equipment, Net                   0
Long Term Investments & Receivables                0
Other Long Term Assets                             0
Total Noncurrent Assets                            0
Total Assets                                       0
Payables & Accruals                                0
Short Term Debt                                    0
Total Current Liabilities                          0
Long Term Debt                                     0
Total Noncurrent Liabilities                       0
Total Liabilities                                  0
Share Capital & Additional Paid-In Capital         0
Retained Earnings                                  0
Total Equity                                       0
Total Liabilities & Equity                         0
Earnings Per Share, Basic                          0
dtype: int64

In [118]:
#**PRACTICE OPPORTUNITY:** 
# **Write a Python code that performs the following tasks:**
#**Filter rows in "merged_df" Pandas DataFrame to only include Amazon data with Ticker Symbol 'AMZN'. Place the output in a Pandas DataFrame titled "amazon_df"**
# **Count the number of missing values in every column in "amazon_df" Pandas DataFrame**
# **Calculate the percentage of missing values in every column in "amazon_df" Pandas DataFrame**
# **Handle missing values in "amazon_df" Pandas DataFrame by dropping columns containing more than 50% of Null values** 
#**Replace missing values with the median column value if missing values represent less than 50% of a given column** 
#**Perform a sanity check to ensure that all missing values have been properly handled**

amazon_df = merged_df[merged_df['Ticker']== 'AMZN'].reset_index(drop=True)
amazon_df

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Research & Development,Depreciation & Amortization,Operating Income (Loss),Non-Operating Income (Loss),"Interest Expense, Net","Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common),Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Change in Accounts Receivable,Change in Inventories,Change in Accounts Payable,Change in Other,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic"
0,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2016,USD,2016.0,Q4,2/10/2017,2/1/2019,9.560000e+09,9.740000e+09,4.374100e+10,-2.895900e+10,1.478200e+10,-1.352700e+10,-3.230000e+09,NaN,NaN,1.255000e+09,-8.900000e+07,-104000000.0,1.166000e+09,NaN,1.166000e+09,-4.130000e+08,7.490000e+08,NaN,7.490000e+08,7.490000e+08,7.490000e+08,7.373000e+09,5.000000e+08,-1.993000e+09,-1.043000e+09,7.282000e+09,-3.746000e+09,1.091900e+10,-2.006000e+09,-1.805000e+09,-3.000000e+06,-3.814000e+09,NaN,-5.680000e+08,NaN,-5.680000e+08,5.993000e+09,2.598100e+10,NaN,1.146100e+10,4.578100e+10,2.911400e+10,NaN,8.507000e+09,3.762100e+10,8.340200e+10,3.904800e+10,NaN,4.381600e+10,7.694000e+09,2.030100e+10,6.411700e+10,1.719100e+10,-1.837000e+09,4.916000e+09,1.928500e+10,8.340200e+10,0.07835
1,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2017,USD,2017.0,Q1,4/28/2017,4/27/2018,9.540000e+09,9.800000e+09,3.571400e+10,-2.244000e+10,1.327400e+10,-1.226900e+10,-2.715000e+09,NaN,NaN,1.005000e+09,-5.200000e+07,-100000000.0,9.530000e+08,NaN,9.530000e+08,-2.290000e+08,7.240000e+08,NaN,7.240000e+08,7.240000e+08,7.240000e+08,7.720000e+08,-5.550000e+09,9.650000e+08,9.470000e+08,-6.865000e+09,-5.970000e+08,-1.619000e+09,-1.861000e+09,5.560000e+08,-4.500000e+07,-1.350000e+09,NaN,-8.880000e+08,NaN,-8.880000e+08,-3.633000e+09,2.153100e+10,NaN,1.060000e+10,3.946000e+10,3.263200e+10,NaN,8.877000e+09,4.150900e+10,8.096900e+10,3.194500e+10,NaN,3.739900e+10,7.691000e+09,2.189600e+10,5.929500e+10,1.798100e+10,-1.837000e+09,6.327000e+09,2.167400e+10,8.096900e+10,0.07589
2,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2017,USD,2017.0,Q2,7/28/2017,7/27/2018,9.580000e+09,9.840000e+09,3.795500e+10,-2.345100e+10,1.450400e+10,-1.387700e+10,-3.104000e+09,NaN,NaN,6.270000e+08,3.800000e+07,-99000000.0,6.650000e+08,NaN,6.650000e+08,-4.660000e+08,1.970000e+08,NaN,1.970000e+08,1.970000e+08,1.970000e+08,1.476000e+09,-4.570000e+08,-1.222000e+09,-6.820000e+08,2.088000e+09,-6.410000e+08,3.849000e+09,-2.501000e+09,-2.140000e+09,-6.330000e+08,-5.274000e+09,NaN,-1.275000e+09,NaN,-1.275000e+09,-2.450000e+09,2.145100e+10,NaN,1.151000e+10,4.100700e+10,3.708300e+10,NaN,9.691000e+09,4.677400e+10,8.778100e+10,3.545500e+10,NaN,4.052000e+10,7.683000e+09,2.404700e+10,6.456700e+10,1.913400e+10,-1.837000e+09,6.524000e+09,2.321400e+10,8.778100e+10,0.02056
3,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2017,USD,2017.0,Q3,10/27/2017,10/26/2018,9.620000e+09,9.880000e+09,4.374400e+10,-2.754800e+10,1.619600e+10,-1.584900e+10,-3.440000e+09,NaN,NaN,3.470000e+08,-3.000000e+07,-174000000.0,3.170000e+08,NaN,3.170000e+08,-6.000000e+07,2.550000e+08,NaN,2.550000e+08,2.550000e+08,2.550000e+08,9.250000e+08,-3.150000e+08,-1.759000e+09,-1.593000e+09,2.974000e+09,6.300000e+07,3.777000e+09,-2.660000e+09,-2.606000e+09,-1.321300e+10,-1.847900e+10,NaN,1.466200e+10,NaN,1.466200e+10,1.090000e+08,2.431000e+10,NaN,1.371100e+10,4.857800e+10,4.533500e+10,NaN,2.135400e+10,6.668900e+10,1.152670e+11,4.191900e+10,NaN,4.707200e+10,2.471000e+10,4.353700e+10,9.060900e+10,2.021700e+10,-1.837000e+09,6.779000e+09,2.465800e+10,1.152670e+11,0.02651
4,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2017,USD,2017.0,Q4,2/2/2018,1/31/2020,9.660000e+09,9.920000e+09,6.045300e+10,-3.849500e+10,2.195800e+10,-1.983100e+10,-4.484000e+09,NaN,NaN,2.127000e+09,-2.560000e+08,-273000000.0,1.871000e+09,NaN,1.871000e+09,-1.400000e+07,1.857000e+09,NaN,1.857000e+09,1.857000e+09,1.857000e+09,9.230000e+08,6.080000e+09,-2.764000e+09,-2.255000e+09,8.903000e+09,2.196000e+09,1.235800e+10,-3.036000e+09,1.136000e+09,-8.100000e+07,-1.981000e+09,NaN,-2.571000e+09,NaN,-2.571000e+09,7.896000e+09,3.098600e+10,NaN,1.604700e+10,6.019700e+10,4.886600e+10,NaN,2.224700e+10,7.111300e+10,1.313100e+11,5.278600e+10,NaN,5.788300e+10,2.474300e+10,4.571800e+10,1.036010e+11,2.139400e+10,-1.837000e+09,8.636000e+09,2.770900e+10,1.313100e+11,0.19224
5,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2018,USD,2018.0,Q1,4/27/2018,4/26/2019,9.680000e+09,9.960000e+09,5.104200e+10,-3.073500e+10,2.030700e+10,-1.838000e+10,-3.766000e+09,NaN,NaN,1.927000e+09,-1.100000e+07,-250000000.0,1.916000e+09,NaN,1.916000e+09,-2.870000e+08,1.629000e+09,NaN,1.629000e+09,1.629000e+09,1.629000e+09,1.195000e+09,-8.286000e+09,1.029000e+09,2.220000e+09,-1.021600e+10,-1.319000e+09,-1.791000e+09,-2.727000e+09,2.207000e+09,-1.300000e+07,-5.330000e+08,NaN,-2.164000e+09,NaN,-2.164000e+09,-4.240000e+09,2.496300e+10,NaN,1.384000e+10,5.082900e+10,5.233100e+10,NaN,2.320200e+10,7.553300e+10,1.263620e+11,4.186300e+10,NaN,4.804500e+10,2.464000e+10,4.685400e+10,9.489900e+10,2.256800e+10,-1.837000e+09,1.119900e+10,3.146300e+10,1.263620e+11,0.16829
6,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2018,USD,2018.0,Q2,7/27/2018,7/26/2019,9.720000e+09,1.000000e+10,5.288600e+10,-3.063200e+10,2.225400e+10,-1.927000e+10,-4.011000e+09,NaN,NaN,2.984000e+09,-3.800000e+08,-250000000.0,2.604000e+09,NaN,2.604000e+09,-7.400000e+07,2.534000e+09,NaN,2.534000e+09,2.534000e+09,2.534000e+09,1.525000e+09,-2.400000e+08,-1.365000e+09,-1.090000e+09,2.703000e+09,-4.880000e+08,7.449000e+09,-2.949000e+09,1.123000e+09,-8.660000e+08,-2.692000e+09,NaN,-1.392000e+09,NaN,-1.392000e+09,2.920000e+09,2.705000e+10,NaN,1.482400e+10,5.448100e+10,5.476800e+10,NaN,2.485100e+10,7.961900e+10,1.341000e+11,4.479700e+10,NaN,5.080100e+10,2.463800e+10,4.830400e+10,9.910500e+10,2.403300e+10,-1.837000e+09,1.373300e+10,3.499500e+10,1.341000e+11,0.26070
7,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2018,USD,2018.0,Q3,10/26/2018,10/25/2019,9.760000e+09,1.002000e+10,5.657600e+10,-3.300300e+10,2.357300e+10,-1.984900e+10,-4.344000e+09,NaN,NaN,3.724000e+09,-3.330000e+08,-240000000.0,3.391000e+09,NaN,3.391000e+09,-5.090000e+08,2.883000e+09,NaN,2.883000e+09,2.883000e+09,2.883000e+09,1.773000e+09,1.540000e+08,-2.884000e+09,-1.094000e+09,3.895000e+09,2.370000e+08,8.588000e+09,-2.527000e+09,-2.069000e+09,-9.760000e+08,-5.572000e+09,NaN,-2.369000e+09,NaN,-2.369000e+09,4.960000e+08,2.976500e+10,NaN,1.586200e+10,5.988500e+10,5.801900e+10,NaN,2.579100e+10,8.381000e+10,1.436950e+11,4.932400e+10,NaN,5.532400e+10,2.468400e+10,4.924600e+10,1.045700e+11,2.538000e+10,-1.837000e+09,1.661600e+10,3.912500e+10,1.436950e+11,0.29539
8,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2018,USD,2018.0,Q4,2/1/2019,2/3/2021,9.800000e+09,1.002000e+10,7.238300e+10,-4.478600e+10,2.759700e+10,-2.381100e+10,-6.029000e+09,NaN,NaN,3.786000e+09,-4.360000e+08,-237000000.0,3.350000e+09,NaN,3.350000e+09,-3.270000e+08,3.027000e+09,NaN,3.027000e+09,3.027000e+09,3.027000e+09,1.859000e+09,7.329000e+09,-1.395000e+09,-1.350000e+09,6.881000e+09,3.193000e+09,1.647700e+10,-3.120000e+09,-1.210000e+08,-3.310000e+08,-3.572000e+09,NaN,-1.761000e+09,NaN,-1.761000e+09,1.114100e+10,4.125000e+10,NaN,1.717400e+10,7.510100e+10,6.179700e+10,NaN,2.575000e+10,8.754700e+10,1.626480e+11,6.185500e+10,NaN,6.839100e+10,2.349500e+10,5.070800e+10,1.190990e+11,2.679600e+10,-1.837000e+09,1.962500e+10,4.354900e+10,1.626480e+11,0.30888
9,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2019,USD,2019.0,Q1,4/26/2019,5/1/2020,9.820000e+09,1.004000e+10,5.970000e+10,-3.392000e+10,2.578000e+10,-2.136000e+10,-4.837000e+09,NaN,NaN,4.420000e+09,-1.900000e+07,-183000000.0,4.401000e+09,NaN,4.401000e+09,-8.360000e+08,3.561000e+09,NaN,3.561000e+09,3.561000e+09,3.561000e+09,1.541000e+09,-8.110000e+09,-4.010000e+08,7.190000e+08,-6.384000e+09,-2.044000e+09,1.846000e+09,-2.721000e+09,-4.233000e+09,-1.169000e+09,-8.123000e+09,NaN,-2.377000e+09,NaN,-2.377000e+09,-8.666000e+09,3.702000e+10,NaN,1.643200e+10,6.943100e+10,6.104800e+10,NaN,4.762300e+10,1.086710e+11,1.781020e+11,5.639700e+10,NaN,6.369500e+10,2.332200e+10,6.599700e+10,1.296920e+11,2.806400e+10,-1.837000e+09,2.319300e+10,4.841000e+10,1.781020e+11,0.36263
10,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2019,USD,2019.0,Q2,7/26/2019,7/31/2020,9.860000e+09,1.008000e+10,6.340400e+10,-3.633700e+10,2.706700e+10,-2.398300e+10,-5.562000e+09,NaN,NaN,3.084000e+09,-1.940000e+08,-168000000.0,2.890000e+09,NaN,2.890000e+09,-2.580000e+08,2.625000e+09,NaN,2.625000e+09,2.625000e+09,2.625000e+09,2.149000e+09,-8.590000e+08,-2.193000e+09,-2.100000e+09,3.668000e+09,-2.340000e+08,9.117000e+09,-2.643000e+09,-4.790000e+09,-1.160000e+08,-7.549000e+09,NaN,-2.158000e+09,NaN,-2.158000e+09,-5.420000e+08,4.146300e+10,NaN,1.858000e+10,7.679000e+10,6.472300e+10,NaN,4.983800e+10,1.145610e+11,1.913510e+11,6.220300e+10,NaN,6.967800e+10,2.332900e+10,6.861200e+10,1.382900e+11,3.004000e+10,-1.837000e+09,2.581800e+10,5.306100e+10,1.913510e+11,0.26623
11,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2019,USD,2019.0,Q3,10/25/2019,10/30/2020,9.900000e+09,1.006000e+10,6.998200e+10,-4.130200e+10,2.868000e+10,-2.552200e+10,-6.099000e+09,NaN,NaN,3.158000e+09,-5.260000e+08,-173000000.0,2.632000e+09,NaN,2.632000e+09,-4.940000e+08,2.134000e+09,NaN,2.134000e+09,2.134000e+09,2.134000e+09,2.306000e+09,-2.111000e+09,-1.182000e+09,-3.810000e+08,2.260000e+08,-7.740000e+08,7.892000e+09,-3.385000e+09,-1.289000e+09,-3.990000e+08,-5.073000e+09,NaN,-1.960000e+09,NaN,-1.960000e+09,5.890000e+08,4.340100e+10,NaN,1.876600e+10,7.905400e+10,6.766200e+10,NaN,5.238300e+10,1.200450e+11,1.990990e+11,6.475500e+10,NaN,7.213600e+10,2.247200e+10,7.045500e+10,1.425910e+11,3.182200e+10,-1.837000e+09,2.795200e+10,5.650800e+10,1.990990e+11,0.21556
12,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2019,USD,2019.0,Q4,1/31/2020,2/4/2022,9.940000e+09,1.014000e+10,8.743600e+10,-5.397700e+10,3.345900e+10,-2.958000e+10,-7.583000e+09,NaN,NaN,3.879000e+09,1.740000e+08,-244000000.0,4.053000e+09,NaN,4.053000e+09,-7.860000e+08,3.268000e+09,NaN,3.268000e+09,3.268000e+09,3.268000e+09,1.579000e+09,8.642000e+09,-3.905000e+09,-1.516000e+09,1.068300e+10,3.380000e+09,1.965900e+10,-3.940000e+09,1.181000e+09,-7.770000e+08,-3.536000e+09,NaN,-3.571000e+09,NaN,-3.571000e+09,1.285600e+10,5.502100e+10,2.081600e+10,2.049700e+10,9.633400e+10,7.270500e+10,NaN,5.620900e+10,1.289140e+11,2.252480e+11,7.962200e+10,NaN,8.781200e+10,2.341400e+10,7.537600e+10,1.631880e+11,3.366300e+10,-1.837000e+09,3.122000e+10,6.206000e+10,2.252480e+11,0.32877
13,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2020,USD,2020.0,Q1,5/1/2020,4/30/2021,9.960000e+09,1.012000e+10,7.545200e+10,-4.425700e+10,3.119500e+10,-2.720600e+10,-6.280000e+09,NaN,NaN,3.989000e+09,-6.060000e+08,-200000000.0,3.383000e+09,NaN,3.383000e+09,-7.440000e+08,2.535000e+09,NaN,2.535000e+09,2.535000e+09,2.535000e+09,2.711000e+09,-7.544000e+09,1.262000e+09,1.392000e+09,-8.044000e+09,-2.154000e+09,3.064000e+09,-5.428000e+09,-3.375000e+09,-9.100000e+07,-8.894000e+09,NaN,-2.591000e+09,NaN,-2.591000e+09,-8.905000e+09,4.929200e+10,NaN,1.885700e+10,8.598500e+10,7.777900e+10,NaN,5.747400e+10,1.352530e+11,2.212380e+11,7.084700e+10,NaN,7.971100e+10,2.343700e+10,7.625500e+10,1.559660e+11,3.541700e+10,-1.837000e+09,3.375500e+10,6.527200e+10,2.212380e+11,0.25452
14,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2020,USD,2020.0,Q2,7/31/2020,7/30/2021,1.000000e+10,1.020000e+10,8.891200e+10,-5.266000e+10,3.625200e+10,-3.040900e+10,-5.925000e+09,NaN,NaN,5.843000e+09,3.780000e+08,-268000000.0,6.221000e+09,NaN,6.221000e+09,-9.850000e+08,5.243000e+09,NaN,5.243000e+09,5.243000e+09,5.243000e+09,2.578000e+09,7.036000e+09,-2.854000e+09,-6.720000e+08,8.617000e+09,1.945000e+09,2.060500e+10,-6.614000e+09,-1.107100e+10,-1.190000e+08,-1.780400e+10,NaN,7.408000e+09,NaN,7.408000e+09,1.033700e+10,7.139100e+10,NaN,1.959900e+10,1.109080e+11,8.651700e+10,NaN,6.088900e+10,1.474060e+11,2.583140e+11,8.489900e+10,NaN,9.389600e+10,3.312800e+10,9.069000e+10,1.845860e+11,3.802200e+10,-1.837000e+09,3.899800e+10,7.372800e+10,2.583140e+11,0.52430
15,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2020,USD,2020.0,Q3,10/30/2020,7/30/2021,1.004000e+10,1.022000e+10,9.614500e+10,-5.710600e+10,3.903900e+10,-3.284500e+10,-7.100000e+09,NaN,NaN,6.194000e+09,6.150000e+08,-310000000.0,6.809000e+09,NaN,6.809000e+09,-5.690000e+08,6.331000e+09,NaN,6.331000e+09,6.331000e+09,6.331000e+09,1.600000e+09,-2.490000e+09,-2.016000e+09,-3.898000e+09,3.658000e+09,-2.340000e+08,1.196400e+10,-9.808000e+09,-4.333000e+09,-1.735000e+09,-1.587600e+10,NaN,-4.105000e+09,NaN,-4.105000e+09,-7.640000e+09,6.840200e+10,2.083200e+10,2.373500e+10,1.129690e+11,9.998100e+10,NaN,6.922900e+10,1.692100e+11,2.821790e+11,9.266100e+10,NaN,1.019120e+11,3.292900e+10,9.749200e+10,1.994040e+11,4.031200e+10,-1.837000e+09,4.532900e+10,8.277500e+10,2.821790e+11,0.63058
16,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2020,USD,2020.0,Q4,2/3/2021,10/29/2021,1.000000e+10,1.026000e+10,1.255550e+11,-7.928400e+10,4.627100e+10,-3.939800e+10,-9.371000e+09,NaN,NaN,6.873000e+09,8.920000e+08,-314000000.0,7.765000e+09,NaN,7.765000e+09,-5.650000e+08,7.222000e+09,NaN,7.222000e+09,7.222000e+09,7.222000e+09,-8.880000e+08,1.647900e+10,-4.561000e+09,3.290000e+08,1.324900e+10,7.462000e+09,3.043100e+10,-1.319400e+10,-3.463000e+09,-3.800000e+08,-1.703700e+10,NaN,-1.816000e+09,NaN,-1.816000e+09,1.217500e+10,8.439600e+10,2.454200e+10,2.379500e+10,1.327330e+11,1.131140e+11,NaN,7.534800e+10,1.884620e+11,3.211950e+11,1.166770e+11,NaN,1.263850e+11,3.181600e+10,1.014060e+11,2.277910e+11,4.287000e+10,-1.837000e+09,5.255100e+10,9.340400e+10,3.211950e+11,0.72220
17,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2021,USD,2021.0,Q1,4/30/2021,4/29/2022,1.008000e+10,1.026000e+10,1.085180e+11,-6.240300e+10,4.611500e+10,-3.725000e+10,-8.194000e+09,NaN,NaN,8.865000e+09,1.403000e+09,-294000000.0,1.026800e+10,NaN,1.026800e+10,-2.156000e+09,8.107000e+09,NaN,8.107000e+09,8.107000e+09,8.107000e+09,2.583000e+09,-1.398500e+10,-2.255000e+09,-3.040000e+08,-8.266000e+09,-3.160000e+09,4.213000e+09,-1.118700e+10,3.151000e+09,-6.300000e+08,-8.666000e+09,NaN,-3.476000e+09,NaN,-3.476000e+09,-8.222000e+09,7.327000e+10,2.428900e+10,2.384900e+10,1.214080e+11,1.214610e+11,NaN,8.020800e+10,2.016690e+11,3.230770e+11,1.048650e+11,NaN,1.154040e+11,3.186800e+10,1.043530e+11,2.197570e+11,4.516500e+10,-1.837000e+09,6.065800e+10,1.033200e+11,3.230770e+11,0.80427
18,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2021,USD,2021.0,Q2,7/30/2021,4/29/2022,1.008000e+10,1.026000e+10,1.130800e+11,-6.417600e+10,4.890400e+10,-4.120200e+10,-9.682000e+09,NaN,NaN,7.702000e+09,9.320000e+08,-329000000.0,8.634000e+09,NaN,8.634000e+09,-8.680000e+08,7.778000e+09,NaN,7.778000e+09,7.778000e+09,7.778000e+09,3.052000e+09,-6.153000e+09,-4.462000e+09,-2.090000e+08,4.700000e+07,-1.529000e+09,1.271500e+10,-1.298800e+10,-8.772000e+09,-3.200000e+08,-2.208000e+10,NaN,1.564300e+10,NaN,1.564300e+10,6.512000e+09,8.989400e+10,2.683500e+10,2.411900e+10,1.408480e+11,1.335020e+11,NaN,8.596900e+10,2.194710e+11,3.603190e+11,1.070970e+11,NaN,1.177920e+11,5.027900e+10,1.277240e+11,2.455160e+11,4.872900e+10,-1.837000e+09,6.843600e+10,1.148030e+11,3.603190e+11,0.77163
19,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2021,USD,2021.0,Q3,10/29/2021,10/28/2022,1.010000e+10,1.028000e+10,1.108120e+11,-6.293000e+10,4.788200e+10,-4.303000e+10,-1.016300e+10,NaN,NaN,4.852000e+09,-5.370000e+08,-374000000.0,4.315000e+09,NaN,4.315000e+09,-1.155000e+09,3.156000e+09,NaN,3.156000e+09,3.156000e+09,3.156000e+09,4.453000e+09,-9.244000e+09,NaN,NaN,NaN,NaN,7.313000e+09,-1.574800e+10,5.770000e+08,-6.540000e+08,-1.482800e+10,NaN,-2.776000e+09,NaN,-2.776000e+09,-1.049000e+10,7.898800e+10,2.861000e+10,3.093300e+10,1.385310e+11,1.471520e+11,NaN,9.672300e+10,2.438750e+11,3.824060e+11,1.130200e+11,NaN,1.239940e+11,5.005500e+10,1.378480e+11,2.618420e+11,5.188400e+10,-1.837000e+09,7.159200e+10,1.205640e+11,3.824060e+11,0.31248

In [119]:
amazon_df.isnull().sum()

Ticker                                              0
Company Name                                        0
Sector                                              0
Industry                                            0
Report Date                                         0
Currency                                            0
Fiscal Year                                         0
Fiscal Period                                       0
Publish Date                                        0
Restated Date                                       0
Shares (Basic)                                      0
Shares (Diluted)                                    0
Revenue                                             0
Cost of Revenue                                     0
Gross Profit                                        0
Operating Expenses                                  0
Selling, General & Administrative                   0
Research & Development                             20
Depreciation & Amortization                        20
Operating Income (Loss)                             0
Non-Operating Income (Loss)                         0
Interest Expense, Net                               0
Pretax Income (Loss), Adj.                          0
Abnormal Gains (Losses)                            20
Pretax Income (Loss)                                0
Income Tax (Expense) Benefit, Net                   0
Income (Loss) from Continuing Operations            0
Net Extraordinary Gains (Losses)                   20
Net Income                                          0
Net Income (Common)                                 0
Net Income/Starting Line                            0
Non-Cash Items                                      0
Change in Working Capital                           0
Change in Accounts Receivable                       1
Change in Inventories                               1
Change in Accounts Payable                          1
Change in Other                                     1
Net Cash from Operating Activities                  0
Change in Fixed Assets & Intangibles                0
Net Change in Long Term Investment                  0
Net Cash from Acquisitions & Divestitures           0
Net Cash from Investing Activities                  0
Dividends Paid                                     20
Cash from (Repayment of) Debt                       0
Cash from (Repurchase of) Equity                   20
Net Cash from Financing Activities                  0
Net Change in Cash                                  0
Cash, Cash Equivalents & Short Term Investments     0
Accounts & Notes Receivable                        14
Inventories                                         0
Total Current Assets                                0
Property, Plant & Equipment, Net                    0
Long Term Investments & Receivables                20
Other Long Term Assets                              0
Total Noncurrent Assets                             0
Total Assets                                        0
Payables & Accruals                                 0
Short Term Debt                                    20
Total Current Liabilities                           0
Long Term Debt                                      0
Total Noncurrent Liabilities                        0
Total Liabilities                                   0
Share Capital & Additional Paid-In Capital          0
Treasury Stock                                      0
Retained Earnings                                   0
Total Equity                                        0
Total Liabilities & Equity                          0
Earnings Per Share, Basic                           0
dtype: int64

In [120]:
percentage_missing = amazon_df.isnull().sum() * 100 / len(amazon_df)
percentage_missing_df= pd.DataFrame({'%Missing': percentage_missing}).reset_index()
percentage_missing_df

                                              index  %Missing
0                                            Ticker       0.0
1                                      Company Name       0.0
2                                            Sector       0.0
3                                          Industry       0.0
4                                       Report Date       0.0
5                                          Currency       0.0
6                                       Fiscal Year       0.0
7                                     Fiscal Period       0.0
8                                      Publish Date       0.0
9                                     Restated Date       0.0
10                                   Shares (Basic)       0.0
11                                 Shares (Diluted)       0.0
12                                          Revenue       0.0
13                                  Cost of Revenue       0.0
14                                     Gross Profit       0.0
15                               Operating Expenses       0.0
16                Selling, General & Administrative       0.0
17                           Research & Development     100.0
18                      Depreciation & Amortization     100.0
19                          Operating Income (Loss)       0.0
20                      Non-Operating Income (Loss)       0.0
21                            Interest Expense, Net       0.0
22                       Pretax Income (Loss), Adj.       0.0
23                          Abnormal Gains (Losses)     100.0
24                             Pretax Income (Loss)       0.0
25                Income Tax (Expense) Benefit, Net       0.0
26         Income (Loss) from Continuing Operations       0.0
27                 Net Extraordinary Gains (Losses)     100.0
28                                       Net Income       0.0
29                              Net Income (Common)       0.0
30                         Net Income/Starting Line       0.0
31                                   Non-Cash Items       0.0
32                        Change in Working Capital       0.0
33                    Change in Accounts Receivable       5.0
34                            Change in Inventories       5.0
35                       Change in Accounts Payable       5.0
36                                  Change in Other       5.0
37               Net Cash from Operating Activities       0.0
38             Change in Fixed Assets & Intangibles       0.0
39               Net Change in Long Term Investment       0.0
40        Net Cash from Acquisitions & Divestitures       0.0
41               Net Cash from Investing Activities       0.0
42                                   Dividends Paid     100.0
43                    Cash from (Repayment of) Debt       0.0
44                 Cash from (Repurchase of) Equity     100.0
45               Net Cash from Financing Activities       0.0
46                               Net Change in Cash       0.0
47  Cash, Cash Equivalents & Short Term Investments       0.0
48                      Accounts & Notes Receivable      70.0
49                                      Inventories       0.0
50                             Total Current Assets       0.0
51                 Property, Plant & Equipment, Net       0.0
52              Long Term Investments & Receivables     100.0
53                           Other Long Term Assets       0.0
54                          Total Noncurrent Assets       0.0
55                                     Total Assets       0.0
56                              Payables & Accruals       0.0
57                                  Short Term Debt     100.0
58                        Total Current Liabilities       0.0
59                                   Long Term Debt       0.0
60                     Total Noncurrent Liabilities       0.0
61                                Total Liabilities       0.0
62       Share Capital & Additional Paid-In Capital       0.0
63                                   Treasury Stock       0.0
64                                Retained Earnings       0.0
65                                     Total Equity       0.0
66                       Total Liabilities & Equity       0.0
67                        Earnings Per Share, Basic       0.0

In [122]:
columns_to_drop= percentage_missing_df[ percentage_missing_df['%Missing']>50]['index'].tolist()
columns_to_drop

['Research & Development',
 'Depreciation & Amortization',
 'Abnormal Gains (Losses)',
 'Net Extraordinary Gains (Losses)',
 'Dividends Paid',
 'Cash from (Repurchase of) Equity',
 'Accounts & Notes Receivable',
 'Long Term Investments & Receivables',
 'Short Term Debt']

In [124]:
amazon_df= amazon_df.drop(columns=columns_to_drop)
amazon_df

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Operating Income (Loss),Non-Operating Income (Loss),"Interest Expense, Net","Pretax Income (Loss), Adj.",Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Income,Net Income (Common),Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Change in Accounts Receivable,Change in Inventories,Change in Accounts Payable,Change in Other,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Cash from (Repayment of) Debt,Net Cash from Financing Activities,Net Change in Cash,"Cash, Cash Equivalents & Short Term Investments",Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic"
0,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2016,USD,2016.0,Q4,2/10/2017,2/1/2019,9.560000e+09,9.740000e+09,4.374100e+10,-2.895900e+10,1.478200e+10,-1.352700e+10,-3.230000e+09,1.255000e+09,-8.900000e+07,-104000000.0,1.166000e+09,1.166000e+09,-4.130000e+08,7.490000e+08,7.490000e+08,7.490000e+08,7.490000e+08,7.373000e+09,5.000000e+08,-1.993000e+09,-1.043000e+09,7.282000e+09,-3.746000e+09,1.091900e+10,-2.006000e+09,-1.805000e+09,-3.000000e+06,-3.814000e+09,-5.680000e+08,-5.680000e+08,5.993000e+09,2.598100e+10,1.146100e+10,4.578100e+10,2.911400e+10,8.507000e+09,3.762100e+10,8.340200e+10,3.904800e+10,4.381600e+10,7.694000e+09,2.030100e+10,6.411700e+10,1.719100e+10,-1.837000e+09,4.916000e+09,1.928500e+10,8.340200e+10,0.07835
1,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2017,USD,2017.0,Q1,4/28/2017,4/27/2018,9.540000e+09,9.800000e+09,3.571400e+10,-2.244000e+10,1.327400e+10,-1.226900e+10,-2.715000e+09,1.005000e+09,-5.200000e+07,-100000000.0,9.530000e+08,9.530000e+08,-2.290000e+08,7.240000e+08,7.240000e+08,7.240000e+08,7.240000e+08,7.720000e+08,-5.550000e+09,9.650000e+08,9.470000e+08,-6.865000e+09,-5.970000e+08,-1.619000e+09,-1.861000e+09,5.560000e+08,-4.500000e+07,-1.350000e+09,-8.880000e+08,-8.880000e+08,-3.633000e+09,2.153100e+10,1.060000e+10,3.946000e+10,3.263200e+10,8.877000e+09,4.150900e+10,8.096900e+10,3.194500e+10,3.739900e+10,7.691000e+09,2.189600e+10,5.929500e+10,1.798100e+10,-1.837000e+09,6.327000e+09,2.167400e+10,8.096900e+10,0.07589
2,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2017,USD,2017.0,Q2,7/28/2017,7/27/2018,9.580000e+09,9.840000e+09,3.795500e+10,-2.345100e+10,1.450400e+10,-1.387700e+10,-3.104000e+09,6.270000e+08,3.800000e+07,-99000000.0,6.650000e+08,6.650000e+08,-4.660000e+08,1.970000e+08,1.970000e+08,1.970000e+08,1.970000e+08,1.476000e+09,-4.570000e+08,-1.222000e+09,-6.820000e+08,2.088000e+09,-6.410000e+08,3.849000e+09,-2.501000e+09,-2.140000e+09,-6.330000e+08,-5.274000e+09,-1.275000e+09,-1.275000e+09,-2.450000e+09,2.145100e+10,1.151000e+10,4.100700e+10,3.708300e+10,9.691000e+09,4.677400e+10,8.778100e+10,3.545500e+10,4.052000e+10,7.683000e+09,2.404700e+10,6.456700e+10,1.913400e+10,-1.837000e+09,6.524000e+09,2.321400e+10,8.778100e+10,0.02056
3,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2017,USD,2017.0,Q3,10/27/2017,10/26/2018,9.620000e+09,9.880000e+09,4.374400e+10,-2.754800e+10,1.619600e+10,-1.584900e+10,-3.440000e+09,3.470000e+08,-3.000000e+07,-174000000.0,3.170000e+08,3.170000e+08,-6.000000e+07,2.550000e+08,2.550000e+08,2.550000e+08,2.550000e+08,9.250000e+08,-3.150000e+08,-1.759000e+09,-1.593000e+09,2.974000e+09,6.300000e+07,3.777000e+09,-2.660000e+09,-2.606000e+09,-1.321300e+10,-1.847900e+10,1.466200e+10,1.466200e+10,1.090000e+08,2.431000e+10,1.371100e+10,4.857800e+10,4.533500e+10,2.135400e+10,6.668900e+10,1.152670e+11,4.191900e+10,4.707200e+10,2.471000e+10,4.353700e+10,9.060900e+10,2.021700e+10,-1.837000e+09,6.779000e+09,2.465800e+10,1.152670e+11,0.02651
4,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2017,USD,2017.0,Q4,2/2/2018,1/31/2020,9.660000e+09,9.920000e+09,6.045300e+10,-3.849500e+10,2.195800e+10,-1.983100e+10,-4.484000e+09,2.127000e+09,-2.560000e+08,-273000000.0,1.871000e+09,1.871000e+09,-1.400000e+07,1.857000e+09,1.857000e+09,1.857000e+09,1.857000e+09,9.230000e+08,6.080000e+09,-2.764000e+09,-2.255000e+09,8.903000e+09,2.196000e+09,1.235800e+10,-3.036000e+09,1.136000e+09,-8.100000e+07,-1.981000e+09,-2.571000e+09,-2.571000e+09,7.896000e+09,3.098600e+10,1.604700e+10,6.019700e+10,4.886600e+10,2.224700e+10,7.111300e+10,1.313100e+11,5.278600e+10,5.788300e+10,2.474300e+10,4.571800e+10,1.036010e+11,2.139400e+10,-1.837000e+09,8.636000e+09,2.770900e+10,1.313100e+11,0.19224
5,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2018,USD,2018.0,Q1,4/27/2018,4/26/2019,9.680000e+09,9.960000e+09,5.104200e+10,-3.073500e+10,2.030700e+10,-1.838000e+10,-3.766000e+09,1.927000e+09,-1.100000e+07,-250000000.0,1.916000e+09,1.916000e+09,-2.870000e+08,1.629000e+09,1.629000e+09,1.629000e+09,1.629000e+09,1.195000e+09,-8.286000e+09,1.029000e+09,2.220000e+09,-1.021600e+10,-1.319000e+09,-1.791000e+09,-2.727000e+09,2.207000e+09,-1.300000e+07,-5.330000e+08,-2.164000e+09,-2.164000e+09,-4.240000e+09,2.496300e+10,1.384000e+10,5.082900e+10,5.233100e+10,2.320200e+10,7.553300e+10,1.263620e+11,4.186300e+10,4.804500e+10,2.464000e+10,4.685400e+10,9.489900e+10,2.256800e+10,-1.837000e+09,1.119900e+10,3.146300e+10,1.263620e+11,0.16829
6,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2018,USD,2018.0,Q2,7/27/2018,7/26/2019,9.720000e+09,1.000000e+10,5.288600e+10,-3.063200e+10,2.225400e+10,-1.927000e+10,-4.011000e+09,2.984000e+09,-3.800000e+08,-250000000.0,2.604000e+09,2.604000e+09,-7.400000e+07,2.534000e+09,2.534000e+09,2.534000e+09,2.534000e+09,1.525000e+09,-2.400000e+08,-1.365000e+09,-1.090000e+09,2.703000e+09,-4.880000e+08,7.449000e+09,-2.949000e+09,1.123000e+09,-8.660000e+08,-2.692000e+09,-1.392000e+09,-1.392000e+09,2.920000e+09,2.705000e+10,1.482400e+10,5.448100e+10,5.476800e+10,2.485100e+10,7.961900e+10,1.341000e+11,4.479700e+10,5.080100e+10,2.463800e+10,4.830400e+10,9.910500e+10,2.403300e+10,-1.837000e+09,1.373300e+10,3.499500e+10,1.341000e+11,0.26070
7,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2018,USD,2018.0,Q3,10/26/2018,10/25/2019,9.760000e+09,1.002000e+10,5.657600e+10,-3.300300e+10,2.357300e+10,-1.984900e+10,-4.344000e+09,3.724000e+09,-3.330000e+08,-240000000.0,3.391000e+09,3.391000e+09,-5.090000e+08,2.883000e+09,2.883000e+09,2.883000e+09,2.883000e+09,1.773000e+09,1.540000e+08,-2.884000e+09,-1.094000e+09,3.895000e+09,2.370000e+08,8.588000e+09,-2.527000e+09,-2.069000e+09,-9.760000e+08,-5.572000e+09,-2.369000e+09,-2.369000e+09,4.960000e+08,2.976500e+10,1.586200e+10,5.988500e+10,5.801900e+10,2.579100e+10,8.381000e+10,1.436950e+11,4.932400e+10,5.532400e+10,2.468400e+10,4.924600e+10,1.045700e+11,2.538000e+10,-1.837000e+09,1.661600e+10,3.912500e+10,1.436950e+11,0.29539
8,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2018,USD,2018.0,Q4,2/1/2019,2/3/2021,9.800000e+09,1.002000e+10,7.238300e+10,-4.478600e+10,2.759700e+10,-2.381100e+10,-6.029000e+09,3.786000e+09,-4.360000e+08,-237000000.0,3.350000e+09,3.350000e+09,-3.270000e+08,3.027000e+09,3.027000e+09,3.027000e+09,3.027000e+09,1.859000e+09,7.329000e+09,-1.395000e+09,-1.350000e+09,6.881000e+09,3.193000e+09,1.647700e+10,-3.120000e+09,-1.210000e+08,-3.310000e+08,-3.572000e+09,-1.761000e+09,-1.761000e+09,1.114100e+10,4.125000e+10,1.717400e+10,7.510100e+10,6.179700e+10,2.575000e+10,8.754700e+10,1.626480e+11,6.185500e+10,6.839100e+10,2.349500e+10,5.070800e+10,1.190990e+11,2.679600e+10,-1.837000e+09,1.962500e+10,4.354900e+10,1.626480e+11,0.30888
9,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2019,USD,2019.0,Q1,4/26/2019,5/1/2020,9.820000e+09,1.004000e+10,5.970000e+10,-3.392000e+10,2.578000e+10,-2.136000e+10,-4.837000e+09,4.420000e+09,-1.900000e+07,-183000000.0,4.401000e+09,4.401000e+09,-8.360000e+08,3.561000e+09,3.561000e+09,3.561000e+09,3.561000e+09,1.541000e+09,-8.110000e+09,-4.010000e+08,7.190000e+08,-6.384000e+09,-2.044000e+09,1.846000e+09,-2.721000e+09,-4.233000e+09,-1.169000e+09,-8.123000e+09,-2.377000e+09,-2.377000e+09,-8.666000e+09,3.702000e+10,1.643200e+10,6.943100e+10,6.104800e+10,4.762300e+10,1.086710e+11,1.781020e+11,5.639700e+10,6.369500e+10,2.332200e+10,6.599700e+10,1.296920e+11,2.806400e+10,-1.837000e+09,2.319300e+10,4.841000e+10,1.781020e+11,0.36263
10,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2019,USD,2019.0,Q2,7/26/2019,7/31/2020,9.860000e+09,1.008000e+10,6.340400e+10,-3.633700e+10,2.706700e+10,-2.398300e+10,-5.562000e+09,3.084000e+09,-1.940000e+08,-168000000.0,2.890000e+09,2.890000e+09,-2.580000e+08,2.625000e+09,2.625000e+09,2.625000e+09,2.625000e+09,2.149000e+09,-8.590000e+08,-2.193000e+09,-2.100000e+09,3.668000e+09,-2.340000e+08,9.117000e+09,-2.643000e+09,-4.790000e+09,-1.160000e+08,-7.549000e+09,-2.158000e+09,-2.158000e+09,-5.420000e+08,4.146300e+10,1.858000e+10,7.679000e+10,6.472300e+10,4.983800e+10,1.145610e+11,1.913510e+11,6.220300e+10,6.967800e+10,2.332900e+10,6.861200e+10,1.382900e+11,3.004000e+10,-1.837000e+09,2.581800e+10,5.306100e+10,1.913510e+11,0.26623
11,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2019,USD,2019.0,Q3,10/25/2019,10/30/2020,9.900000e+09,1.006000e+10,6.998200e+10,-4.130200e+10,2.868000e+10,-2.552200e+10,-6.099000e+09,3.158000e+09,-5.260000e+08,-173000000.0,2.632000e+09,2.632000e+09,-4.940000e+08,2.134000e+09,2.134000e+09,2.134000e+09,2.134000e+09,2.306000e+09,-2.111000e+09,-1.182000e+09,-3.810000e+08,2.260000e+08,-7.740000e+08,7.892000e+09,-3.385000e+09,-1.289000e+09,-3.990000e+08,-5.073000e+09,-1.960000e+09,-1.960000e+09,5.890000e+08,4.340100e+10,1.876600e+10,7.905400e+10,6.766200e+10,5.238300e+10,1.200450e+11,1.990990e+11,6.475500e+10,7.213600e+10,2.247200e+10,7.045500e+10,1.425910e+11,3.182200e+10,-1.837000e+09,2.795200e+10,5.650800e+10,1.990990e+11,0.21556
12,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2019,USD,2019.0,Q4,1/31/2020,2/4/2022,9.940000e+09,1.014000e+10,8.743600e+10,-5.397700e+10,3.345900e+10,-2.958000e+10,-7.583000e+09,3.879000e+09,1.740000e+08,-244000000.0,4.053000e+09,4.053000e+09,-7.860000e+08,3.268000e+09,3.268000e+09,3.268000e+09,3.268000e+09,1.579000e+09,8.642000e+09,-3.905000e+09,-1.516000e+09,1.068300e+10,3.380000e+09,1.965900e+10,-3.940000e+09,1.181000e+09,-7.770000e+08,-3.536000e+09,-3.571000e+09,-3.571000e+09,1.285600e+10,5.502100e+10,2.049700e+10,9.633400e+10,7.270500e+10,5.620900e+10,1.289140e+11,2.252480e+11,7.962200e+10,8.781200e+10,2.341400e+10,7.537600e+10,1.631880e+11,3.366300e+10,-1.837000e+09,3.122000e+10,6.206000e+10,2.252480e+11,0.32877
13,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2020,USD,2020.0,Q1,5/1/2020,4/30/2021,9.960000e+09,1.012000e+10,7.545200e+10,-4.425700e+10,3.119500e+10,-2.720600e+10,-6.280000e+09,3.989000e+09,-6.060000e+08,-200000000.0,3.383000e+09,3.383000e+09,-7.440000e+08,2.535000e+09,2.535000e+09,2.535000e+09,2.535000e+09,2.711000e+09,-7.544000e+09,1.262000e+09,1.392000e+09,-8.044000e+09,-2.154000e+09,3.064000e+09,-5.428000e+09,-3.375000e+09,-9.100000e+07,-8.894000e+09,-2.591000e+09,-2.591000e+09,-8.905000e+09,4.929200e+10,1.885700e+10,8.598500e+10,7.777900e+10,5.747400e+10,1.352530e+11,2.212380e+11,7.084700e+10,7.971100e+10,2.343700e+10,7.625500e+10,1.559660e+11,3.541700e+10,-1.837000e+09,3.375500e+10,6.527200e+10,2.212380e+11,0.25452
14,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2020,USD,2020.0,Q2,7/31/2020,7/30/2021,1.000000e+10,1.020000e+10,8.891200e+10,-5.266000e+10,3.625200e+10,-3.040900e+10,-5.925000e+09,5.843000e+09,3.780000e+08,-268000000.0,6.221000e+09,6.221000e+09,-9.850000e+08,5.243000e+09,5.243000e+09,5.243000e+09,5.243000e+09,2.578000e+09,7.036000e+09,-2.854000e+09,-6.720000e+08,8.617000e+09,1.945000e+09,2.060500e+10,-6.614000e+09,-1.107100e+10,-1.190000e+08,-1.780400e+10,7.408000e+09,7.408000e+09,1.033700e+10,7.139100e+10,1.959900e+10,1.109080e+11,8.651700e+10,6.088900e+10,1.474060e+11,2.583140e+11,8.489900e+10,9.389600e+10,3.312800e+10,9.069000e+10,1.845860e+11,3.802200e+10,-1.837000e+09,3.899800e+10,7.372800e+10,2.583140e+11,0.52430
15,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2020,USD,2020.0,Q3,10/30/2020,7/30/2021,1.004000e+10,1.022000e+10,9.614500e+10,-5.710600e+10,3.903900e+10,-3.284500e+10,-7.100000e+09,6.194000e+09,6.150000e+08,-310000000.0,6.809000e+09,6.809000e+09,-5.690000e+08,6.331000e+09,6.331000e+09,6.331000e+09,6.331000e+09,1.600000e+09,-2.490000e+09,-2.016000e+09,-3.898000e+09,3.658000e+09,-2.340000e+08,1.196400e+10,-9.808000e+09,-4.333000e+09,-1.735000e+09,-1.587600e+10,-4.105000e+09,-4.105000e+09,-7.640000e+09,6.840200e+10,2.373500e+10,1.129690e+11,9.998100e+10,6.922900e+10,1.692100e+11,2.821790e+11,9.266100e+10,1.019120e+11,3.292900e+10,9.749200e+10,1.994040e+11,4.031200e+10,-1.837000e+09,4.532900e+10,8.277500e+10,2.821790e+11,0.63058
16,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2020,USD,2020.0,Q4,2/3/2021,10/29/2021,1.000000e+10,1.026000e+10,1.255550e+11,-7.928400e+10,4.627100e+10,-3.939800e+10,-9.371000e+09,6.873000e+09,8.920000e+08,-314000000.0,7.765000e+09,7.765000e+09,-5.650000e+08,7.222000e+09,7.222000e+09,7.222000e+09,7.222000e+09,-8.880000e+08,1.647900e+10,-4.561000e+09,3.290000e+08,1.324900e+10,7.462000e+09,3.043100e+10,-1.319400e+10,-3.463000e+09,-3.800000e+08,-1.703700e+10,-1.816000e+09,-1.816000e+09,1.217500e+10,8.439600e+10,2.379500e+10,1.327330e+11,1.131140e+11,7.534800e+10,1.884620e+11,3.211950e+11,1.166770e+11,1.263850e+11,3.181600e+10,1.014060e+11,2.277910e+11,4.287000e+10,-1.837000e+09,5.255100e+10,9.340400e+10,3.211950e+11,0.72220
17,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2021,USD,2021.0,Q1,4/30/2021,4/29/2022,1.008000e+10,1.026000e+10,1.085180e+11,-6.240300e+10,4.611500e+10,-3.725000e+10,-8.194000e+09,8.865000e+09,1.403000e+09,-294000000.0,1.026800e+10,1.026800e+10,-2.156000e+09,8.107000e+09,8.107000e+09,8.107000e+09,8.107000e+09,2.583000e+09,-1.398500e+10,-2.255000e+09,-3.040000e+08,-8.266000e+09,-3.160000e+09,4.213000e+09,-1.118700e+10,3.151000e+09,-6.300000e+08,-8.666000e+09,-3.476000e+09,-3.476000e+09,-8.222000e+09,7.327000e+10,2.384900e+10,1.214080e+11,1.214610e+11,8.020800e+10,2.016690e+11,3.230770e+11,1.048650e+11,1.154040e+11,3.186800e+10,1.043530e+11,2.197570e+11,4.516500e+10,-1.837000e+09,6.065800e+10,1.033200e+11,3.230770e+11,0.80427
18,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2021,USD,2021.0,Q2,7/30/2021,4/29/2022,1.008000e+10,1.026000e+10,1.130800e+11,-6.417600e+10,4.890400e+10,-4.120200e+10,-9.682000e+09,7.702000e+09,9.320000e+08,-329000000.0,8.634000e+09,8.634000e+09,-8.680000e+08,7.778000e+09,7.778000e+09,7.778000e+09,7.778000e+09,3.052000e+09,-6.153000e+09,-4.462000e+09,-2.090000e+08,4.700000e+07,-1.529000e+09,1.271500e+10,-1.298800e+10,-8.772000e+09,-3.200000e+08,-2.208000e+10,1.564300e+10,1.564300e+10,6.512000e+09,8.989400e+10,2.411900e+10,1.408480e+11,1.335020e+11,8.596900e+10,2.194710e+11,3.603190e+11,1.070970e+11,1.177920e+11,5.027900e+10,1.277240e+11,2.455160e+11,4.872900e+10,-1.837000e+09,6.843600e+10,1.148030e+11,3.603190e+11,0.77163
19,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2021,USD,2021.0,Q3,10/29/2021,10/28/2022,1.010000e+10,1.028000e+10,1.108120e+11,-6.293000e+10,4.788200e+10,-4.303000e+10,-1.016300e+10,4.852000e+09,-5.370000e+08,-374000000.0,4.315000e+09,4.315000e+09,-1.155000e+09,3.156000e+09,3.156000e+09,3.156000e+09,3.156000e+09,4.453000e+09,-9.244000e+09,NaN,NaN,NaN,NaN,7.313000e+09,-1.574800e+10,5.770000e+08,-6.540000e+08,-1.482800e+10,-2.776000e+09,-2.776000e+09,-1.049000e+10,7.898800e+10,3.093300e+10,1.385310e+11,1.471520e+11,9.672300e+10,2.438750e+11,3.824060e+11,1.130200e+11,1.239940e+11,5.005500e+10,1.378480e+11,2.618420e+11,5.188400e+10,-1.837000e+09,7.159200e+10,1.205640e+11,3.824060e+11,0.31248

In [125]:
amazon_df.isnull().sum()

Ticker                                             0
Company Name                                       0
Sector                                             0
Industry                                           0
Report Date                                        0
Currency                                           0
Fiscal Year                                        0
Fiscal Period                                      0
Publish Date                                       0
Restated Date                                      0
Shares (Basic)                                     0
Shares (Diluted)                                   0
Revenue                                            0
Cost of Revenue                                    0
Gross Profit                                       0
Operating Expenses                                 0
Selling, General & Administrative                  0
Operating Income (Loss)                            0
Non-Operating Income (Loss)                        0
Interest Expense, Net                              0
Pretax Income (Loss), Adj.                         0
Pretax Income (Loss)                               0
Income Tax (Expense) Benefit, Net                  0
Income (Loss) from Continuing Operations           0
Net Income                                         0
Net Income (Common)                                0
Net Income/Starting Line                           0
Non-Cash Items                                     0
Change in Working Capital                          0
Change in Accounts Receivable                      1
Change in Inventories                              1
Change in Accounts Payable                         1
Change in Other                                    1
Net Cash from Operating Activities                 0
Change in Fixed Assets & Intangibles               0
Net Change in Long Term Investment                 0
Net Cash from Acquisitions & Divestitures          0
Net Cash from Investing Activities                 0
Cash from (Repayment of) Debt                      0
Net Cash from Financing Activities                 0
Net Change in Cash                                 0
Cash, Cash Equivalents & Short Term Investments    0
Inventories                                        0
Total Current Assets                               0
Property, Plant & Equipment, Net                   0
Other Long Term Assets                             0
Total Noncurrent Assets                            0
Total Assets                                       0
Payables & Accruals                                0
Total Current Liabilities                          0
Long Term Debt                                     0
Total Noncurrent Liabilities                       0
Total Liabilities                                  0
Share Capital & Additional Paid-In Capital         0
Treasury Stock                                     0
Retained Earnings                                  0
Total Equity                                       0
Total Liabilities & Equity                         0
Earnings Per Share, Basic                          0
dtype: int64

In [129]:
amazon_df['Change in Accounts Receivable'].fillna(amazon_df['Change in Accounts Receivable'].median(), inplace= True)
amazon_df['Change in Inventories'].fillna(amazon_df['Change in Inventories'].median(), inplace= True)
amazon_df['Change in Accounts Payable'].fillna(amazon_df['Change in Accounts Payable'].median(), inplace= True)
amazon_df['Change in Other'].fillna(amazon_df['Change in Other'].median(), inplace= True)
amazon_df

C:\Users\shann\AppData\Local\Temp\ipykernel_73988\569419377.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  amazon_df['Change in Accounts Receivable'].fillna(amazon_df['Change in Accounts Receivable'].median(), inplace= True)
C:\Users\shann\AppData\Local\Temp\ipykernel_73988\569419377.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  amazon_df['Change in Inventories'].fillna(amazon_df['Change in Inventories'].median(), inplace= True)
C:\Users\shann\AppData\Local\Temp\ipykernel_73988\569419377.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  amazon_df['Change in Accounts Payable'].fillna(amazon_df['Change in Accounts Payable'].median(), inplace= True)
C:\Users\shann\AppData\Local\Temp\ipykernel_73988\569419377.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  amazon_df['Change in Other'].fillna(amazon_df['Change in Other'].median(), inplace= True)

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Operating Income (Loss),Non-Operating Income (Loss),"Interest Expense, Net","Pretax Income (Loss), Adj.",Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Income,Net Income (Common),Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Change in Accounts Receivable,Change in Inventories,Change in Accounts Payable,Change in Other,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Cash from (Repayment of) Debt,Net Cash from Financing Activities,Net Change in Cash,"Cash, Cash Equivalents & Short Term Investments",Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic"
0,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2016,USD,2016.0,Q4,2/10/2017,2/1/2019,9.560000e+09,9.740000e+09,4.374100e+10,-2.895900e+10,1.478200e+10,-1.352700e+10,-3.230000e+09,1.255000e+09,-8.900000e+07,-104000000.0,1.166000e+09,1.166000e+09,-4.130000e+08,7.490000e+08,7.490000e+08,7.490000e+08,7.490000e+08,7.373000e+09,5.000000e+08,-1.993000e+09,-1.043000e+09,7.282000e+09,-3.746000e+09,1.091900e+10,-2.006000e+09,-1.805000e+09,-3.000000e+06,-3.814000e+09,-5.680000e+08,-5.680000e+08,5.993000e+09,2.598100e+10,1.146100e+10,4.578100e+10,2.911400e+10,8.507000e+09,3.762100e+10,8.340200e+10,3.904800e+10,4.381600e+10,7.694000e+09,2.030100e+10,6.411700e+10,1.719100e+10,-1.837000e+09,4.916000e+09,1.928500e+10,8.340200e+10,0.07835
1,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2017,USD,2017.0,Q1,4/28/2017,4/27/2018,9.540000e+09,9.800000e+09,3.571400e+10,-2.244000e+10,1.327400e+10,-1.226900e+10,-2.715000e+09,1.005000e+09,-5.200000e+07,-100000000.0,9.530000e+08,9.530000e+08,-2.290000e+08,7.240000e+08,7.240000e+08,7.240000e+08,7.240000e+08,7.720000e+08,-5.550000e+09,9.650000e+08,9.470000e+08,-6.865000e+09,-5.970000e+08,-1.619000e+09,-1.861000e+09,5.560000e+08,-4.500000e+07,-1.350000e+09,-8.880000e+08,-8.880000e+08,-3.633000e+09,2.153100e+10,1.060000e+10,3.946000e+10,3.263200e+10,8.877000e+09,4.150900e+10,8.096900e+10,3.194500e+10,3.739900e+10,7.691000e+09,2.189600e+10,5.929500e+10,1.798100e+10,-1.837000e+09,6.327000e+09,2.167400e+10,8.096900e+10,0.07589
2,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2017,USD,2017.0,Q2,7/28/2017,7/27/2018,9.580000e+09,9.840000e+09,3.795500e+10,-2.345100e+10,1.450400e+10,-1.387700e+10,-3.104000e+09,6.270000e+08,3.800000e+07,-99000000.0,6.650000e+08,6.650000e+08,-4.660000e+08,1.970000e+08,1.970000e+08,1.970000e+08,1.970000e+08,1.476000e+09,-4.570000e+08,-1.222000e+09,-6.820000e+08,2.088000e+09,-6.410000e+08,3.849000e+09,-2.501000e+09,-2.140000e+09,-6.330000e+08,-5.274000e+09,-1.275000e+09,-1.275000e+09,-2.450000e+09,2.145100e+10,1.151000e+10,4.100700e+10,3.708300e+10,9.691000e+09,4.677400e+10,8.778100e+10,3.545500e+10,4.052000e+10,7.683000e+09,2.404700e+10,6.456700e+10,1.913400e+10,-1.837000e+09,6.524000e+09,2.321400e+10,8.778100e+10,0.02056
3,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2017,USD,2017.0,Q3,10/27/2017,10/26/2018,9.620000e+09,9.880000e+09,4.374400e+10,-2.754800e+10,1.619600e+10,-1.584900e+10,-3.440000e+09,3.470000e+08,-3.000000e+07,-174000000.0,3.170000e+08,3.170000e+08,-6.000000e+07,2.550000e+08,2.550000e+08,2.550000e+08,2.550000e+08,9.250000e+08,-3.150000e+08,-1.759000e+09,-1.593000e+09,2.974000e+09,6.300000e+07,3.777000e+09,-2.660000e+09,-2.606000e+09,-1.321300e+10,-1.847900e+10,1.466200e+10,1.466200e+10,1.090000e+08,2.431000e+10,1.371100e+10,4.857800e+10,4.533500e+10,2.135400e+10,6.668900e+10,1.152670e+11,4.191900e+10,4.707200e+10,2.471000e+10,4.353700e+10,9.060900e+10,2.021700e+10,-1.837000e+09,6.779000e+09,2.465800e+10,1.152670e+11,0.02651
4,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2017,USD,2017.0,Q4,2/2/2018,1/31/2020,9.660000e+09,9.920000e+09,6.045300e+10,-3.849500e+10,2.195800e+10,-1.983100e+10,-4.484000e+09,2.127000e+09,-2.560000e+08,-273000000.0,1.871000e+09,1.871000e+09,-1.400000e+07,1.857000e+09,1.857000e+09,1.857000e+09,1.857000e+09,9.230000e+08,6.080000e+09,-2.764000e+09,-2.255000e+09,8.903000e+09,2.196000e+09,1.235800e+10,-3.036000e+09,1.136000e+09,-8.100000e+07,-1.981000e+09,-2.571000e+09,-2.571000e+09,7.896000e+09,3.098600e+10,1.604700e+10,6.019700e+10,4.886600e+10,2.224700e+10,7.111300e+10,1.313100e+11,5.278600e+10,5.788300e+10,2.474300e+10,4.571800e+10,1.036010e+11,2.139400e+10,-1.837000e+09,8.636000e+09,2.770900e+10,1.313100e+11,0.19224
5,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2018,USD,2018.0,Q1,4/27/2018,4/26/2019,9.680000e+09,9.960000e+09,5.104200e+10,-3.073500e+10,2.030700e+10,-1.838000e+10,-3.766000e+09,1.927000e+09,-1.100000e+07,-250000000.0,1.916000e+09,1.916000e+09,-2.870000e+08,1.629000e+09,1.629000e+09,1.629000e+09,1.629000e+09,1.195000e+09,-8.286000e+09,1.029000e+09,2.220000e+09,-1.021600e+10,-1.319000e+09,-1.791000e+09,-2.727000e+09,2.207000e+09,-1.300000e+07,-5.330000e+08,-2.164000e+09,-2.164000e+09,-4.240000e+09,2.496300e+10,1.384000e+10,5.082900e+10,5.233100e+10,2.320200e+10,7.553300e+10,1.263620e+11,4.186300e+10,4.804500e+10,2.464000e+10,4.685400e+10,9.489900e+10,2.256800e+10,-1.837000e+09,1.119900e+10,3.146300e+10,1.263620e+11,0.16829
6,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2018,USD,2018.0,Q2,7/27/2018,7/26/2019,9.720000e+09,1.000000e+10,5.288600e+10,-3.063200e+10,2.225400e+10,-1.927000e+10,-4.011000e+09,2.984000e+09,-3.800000e+08,-250000000.0,2.604000e+09,2.604000e+09,-7.400000e+07,2.534000e+09,2.534000e+09,2.534000e+09,2.534000e+09,1.525000e+09,-2.400000e+08,-1.365000e+09,-1.090000e+09,2.703000e+09,-4.880000e+08,7.449000e+09,-2.949000e+09,1.123000e+09,-8.660000e+08,-2.692000e+09,-1.392000e+09,-1.392000e+09,2.920000e+09,2.705000e+10,1.482400e+10,5.448100e+10,5.476800e+10,2.485100e+10,7.961900e+10,1.341000e+11,4.479700e+10,5.080100e+10,2.463800e+10,4.830400e+10,9.910500e+10,2.403300e+10,-1.837000e+09,1.373300e+10,3.499500e+10,1.341000e+11,0.26070
7,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2018,USD,2018.0,Q3,10/26/2018,10/25/2019,9.760000e+09,1.002000e+10,5.657600e+10,-3.300300e+10,2.357300e+10,-1.984900e+10,-4.344000e+09,3.724000e+09,-3.330000e+08,-240000000.0,3.391000e+09,3.391000e+09,-5.090000e+08,2.883000e+09,2.883000e+09,2.883000e+09,2.883000e+09,1.773000e+09,1.540000e+08,-2.884000e+09,-1.094000e+09,3.895000e+09,2.370000e+08,8.588000e+09,-2.527000e+09,-2.069000e+09,-9.760000e+08,-5.572000e+09,-2.369000e+09,-2.369000e+09,4.960000e+08,2.976500e+10,1.586200e+10,5.988500e+10,5.801900e+10,2.579100e+10,8.381000e+10,1.436950e+11,4.932400e+10,5.532400e+10,2.468400e+10,4.924600e+10,1.045700e+11,2.538000e+10,-1.837000e+09,1.661600e+10,3.912500e+10,1.436950e+11,0.29539
8,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2018,USD,2018.0,Q4,2/1/2019,2/3/2021,9.800000e+09,1.002000e+10,7.238300e+10,-4.478600e+10,2.759700e+10,-2.381100e+10,-6.029000e+09,3.786000e+09,-4.360000e+08,-237000000.0,3.350000e+09,3.350000e+09,-3.270000e+08,3.027000e+09,3.027000e+09,3.027000e+09,3.027000e+09,1.859000e+09,7.329000e+09,-1.395000e+09,-1.350000e+09,6.881000e+09,3.193000e+09,1.647700e+10,-3.120000e+09,-1.210000e+08,-3.310000e+08,-3.572000e+09,-1.761000e+09,-1.761000e+09,1.114100e+10,4.125000e+10,1.717400e+10,7.510100e+10,6.179700e+10,2.575000e+10,8.754700e+10,1.626480e+11,6.185500e+10,6.839100e+10,2.349500e+10,5.070800e+10,1.190990e+11,2.679600e+10,-1.837000e+09,1.962500e+10,4.354900e+10,1.626480e+11,0.30888
9,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2019,USD,2019.0,Q1,4/26/2019,5/1/2020,9.820000e+09,1.004000e+10,5.970000e+10,-3.392000e+10,2.578000e+10,-2.136000e+10,-4.837000e+09,4.420000e+09,-1.900000e+07,-183000000.0,4.401000e+09,4.401000e+09,-8.360000e+08,3.561000e+09,3.561000e+09,3.561000e+09,3.561000e+09,1.541000e+09,-8.110000e+09,-4.010000e+08,7.190000e+08,-6.384000e+09,-2.044000e+09,1.846000e+09,-2.721000e+09,-4.233000e+09,-1.169000e+09,-8.123000e+09,-2.377000e+09,-2.377000e+09,-8.666000e+09,3.702000e+10,1.643200e+10,6.943100e+10,6.104800e+10,4.762300e+10,1.086710e+11,1.781020e+11,5.639700e+10,6.369500e+10,2.332200e+10,6.599700e+10,1.296920e+11,2.806400e+10,-1.837000e+09,2.319300e+10,4.841000e+10,1.781020e+11,0.36263
10,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2019,USD,2019.0,Q2,7/26/2019,7/31/2020,9.860000e+09,1.008000e+10,6.340400e+10,-3.633700e+10,2.706700e+10,-2.398300e+10,-5.562000e+09,3.084000e+09,-1.940000e+08,-168000000.0,2.890000e+09,2.890000e+09,-2.580000e+08,2.625000e+09,2.625000e+09,2.625000e+09,2.625000e+09,2.149000e+09,-8.590000e+08,-2.193000e+09,-2.100000e+09,3.668000e+09,-2.340000e+08,9.117000e+09,-2.643000e+09,-4.790000e+09,-1.160000e+08,-7.549000e+09,-2.158000e+09,-2.158000e+09,-5.420000e+08,4.146300e+10,1.858000e+10,7.679000e+10,6.472300e+10,4.983800e+10,1.145610e+11,1.913510e+11,6.220300e+10,6.967800e+10,2.332900e+10,6.861200e+10,1.382900e+11,3.004000e+10,-1.837000e+09,2.581800e+10,5.306100e+10,1.913510e+11,0.26623
11,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2019,USD,2019.0,Q3,10/25/2019,10/30/2020,9.900000e+09,1.006000e+10,6.998200e+10,-4.130200e+10,2.868000e+10,-2.552200e+10,-6.099000e+09,3.158000e+09,-5.260000e+08,-173000000.0,2.632000e+09,2.632000e+09,-4.940000e+08,2.134000e+09,2.134000e+09,2.134000e+09,2.134000e+09,2.306000e+09,-2.111000e+09,-1.182000e+09,-3.810000e+08,2.260000e+08,-7.740000e+08,7.892000e+09,-3.385000e+09,-1.289000e+09,-3.990000e+08,-5.073000e+09,-1.960000e+09,-1.960000e+09,5.890000e+08,4.340100e+10,1.876600e+10,7.905400e+10,6.766200e+10,5.238300e+10,1.200450e+11,1.990990e+11,6.475500e+10,7.213600e+10,2.247200e+10,7.045500e+10,1.425910e+11,3.182200e+10,-1.837000e+09,2.795200e+10,5.650800e+10,1.990990e+11,0.21556
12,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2019,USD,2019.0,Q4,1/31/2020,2/4/2022,9.940000e+09,1.014000e+10,8.743600e+10,-5.397700e+10,3.345900e+10,-2.958000e+10,-7.583000e+09,3.879000e+09,1.740000e+08,-244000000.0,4.053000e+09,4.053000e+09,-7.860000e+08,3.268000e+09,3.268000e+09,3.268000e+09,3.268000e+09,1.579000e+09,8.642000e+09,-3.905000e+09,-1.516000e+09,1.068300e+10,3.380000e+09,1.965900e+10,-3.940000e+09,1.181000e+09,-7.770000e+08,-3.536000e+09,-3.571000e+09,-3.571000e+09,1.285600e+10,5.502100e+10,2.049700e+10,9.633400e+10,7.270500e+10,5.620900e+10,1.289140e+11,2.252480e+11,7.962200e+10,8.781200e+10,2.341400e+10,7.537600e+10,1.631880e+11,3.366300e+10,-1.837000e+09,3.122000e+10,6.206000e+10,2.252480e+11,0.32877
13,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2020,USD,2020.0,Q1,5/1/2020,4/30/2021,9.960000e+09,1.012000e+10,7.545200e+10,-4.425700e+10,3.119500e+10,-2.720600e+10,-6.280000e+09,3.989000e+09,-6.060000e+08,-200000000.0,3.383000e+09,3.383000e+09,-7.440000e+08,2.535000e+09,2.535000e+09,2.535000e+09,2.535000e+09,2.711000e+09,-7.544000e+09,1.262000e+09,1.392000e+09,-8.044000e+09,-2.154000e+09,3.064000e+09,-5.428000e+09,-3.375000e+09,-9.100000e+07,-8.894000e+09,-2.591000e+09,-2.591000e+09,-8.905000e+09,4.929200e+10,1.885700e+10,8.598500e+10,7.777900e+10,5.747400e+10,1.352530e+11,2.212380e+11,7.084700e+10,7.971100e+10,2.343700e+10,7.625500e+10,1.559660e+11,3.541700e+10,-1.837000e+09,3.375500e+10,6.527200e+10,2.212380e+11,0.25452
14,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2020,USD,2020.0,Q2,7/31/2020,7/30/2021,1.000000e+10,1.020000e+10,8.891200e+10,-5.266000e+10,3.625200e+10,-3.040900e+10,-5.925000e+09,5.843000e+09,3.780000e+08,-268000000.0,6.221000e+09,6.221000e+09,-9.850000e+08,5.243000e+09,5.243000e+09,5.243000e+09,5.243000e+09,2.578000e+09,7.036000e+09,-2.854000e+09,-6.720000e+08,8.617000e+09,1.945000e+09,2.060500e+10,-6.614000e+09,-1.107100e+10,-1.190000e+08,-1.780400e+10,7.408000e+09,7.408000e+09,1.033700e+10,7.139100e+10,1.959900e+10,1.109080e+11,8.651700e+10,6.088900e+10,1.474060e+11,2.583140e+11,8.489900e+10,9.389600e+10,3.312800e+10,9.069000e+10,1.845860e+11,3.802200e+10,-1.837000e+09,3.899800e+10,7.372800e+10,2.583140e+11,0.52430
15,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2020,USD,2020.0,Q3,10/30/2020,7/30/2021,1.004000e+10,1.022000e+10,9.614500e+10,-5.710600e+10,3.903900e+10,-3.284500e+10,-7.100000e+09,6.194000e+09,6.150000e+08,-310000000.0,6.809000e+09,6.809000e+09,-5.690000e+08,6.331000e+09,6.331000e+09,6.331000e+09,6.331000e+09,1.600000e+09,-2.490000e+09,-2.016000e+09,-3.898000e+09,3.658000e+09,-2.340000e+08,1.196400e+10,-9.808000e+09,-4.333000e+09,-1.735000e+09,-1.587600e+10,-4.105000e+09,-4.105000e+09,-7.640000e+09,6.840200e+10,2.373500e+10,1.129690e+11,9.998100e+10,6.922900e+10,1.692100e+11,2.821790e+11,9.266100e+10,1.019120e+11,3.292900e+10,9.749200e+10,1.994040e+11,4.031200e+10,-1.837000e+09,4.532900e+10,8.277500e+10,2.821790e+11,0.63058
16,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2020,USD,2020.0,Q4,2/3/2021,10/29/2021,1.000000e+10,1.026000e+10,1.255550e+11,-7.928400e+10,4.627100e+10,-3.939800e+10,-9.371000e+09,6.873000e+09,8.920000e+08,-314000000.0,7.765000e+09,7.765000e+09,-5.650000e+08,7.222000e+09,7.222000e+09,7.222000e+09,7.222000e+09,-8.880000e+08,1.647900e+10,-4.561000e+09,3.290000e+08,1.324900e+10,7.462000e+09,3.043100e+10,-1.319400e+10,-3.463000e+09,-3.800000e+08,-1.703700e+10,-1.816000e+09,-1.816000e+09,1.217500e+10,8.439600e+10,2.379500e+10,1.327330e+11,1.131140e+11,7.534800e+10,1.884620e+11,3.211950e+11,1.166770e+11,1.263850e+11,3.181600e+10,1.014060e+11,2.277910e+11,4.287000e+10,-1.837000e+09,5.255100e+10,9.340400e+10,3.211950e+11,0.72220
17,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2021,USD,2021.0,Q1,4/30/2021,4/29/2022,1.008000e+10,1.026000e+10,1.085180e+11,-6.240300e+10,4.611500e+10,-3.725000e+10,-8.194000e+09,8.865000e+09,1.403000e+09,-294000000.0,1.026800e+10,1.026800e+10,-2.156000e+09,8.107000e+09,8.107000e+09,8.107000e+09,8.107000e+09,2.583000e+09,-1.398500e+10,-2.255000e+09,-3.040000e+08,-8.266000e+09,-3.160000e+09,4.213000e+09,-1.118700e+10,3.151000e+09,-6.300000e+08,-8.666000e+09,-3.476000e+09,-3.476000e+09,-8.222000e+09,7.327000e+10,2.384900e+10,1.214080e+11,1.214610e+11,8.020800e+10,2.016690e+11,3.230770e+11,1.048650e+11,1.154040e+11,3.186800e+10,1.043530e+11,2.197570e+11,4.516500e+10,-1.837000e+09,6.065800e+10,1.033200e+11,3.230770e+11,0.80427
18,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2021,USD,2021.0,Q2,7/30/2021,4/29/2022,1.008000e+10,1.026000e+10,1.130800e+11,-6.417600e+10,4.890400e+10,-4.120200e+10,-9.682000e+09,7.702000e+09,9.320000e+08,-329000000.0,8.634000e+09,8.634000e+09,-8.680000e+08,7.778000e+09,7.778000e+09,7.778000e+09,7.778000e+09,3.052000e+09,-6.153000e+09,-4.462000e+09,-2.090000e+08,4.700000e+07,-1.529000e+09,1.271500e+10,-1.298800e+10,-8.772000e+09,-3.200000e+08,-2.208000e+10,1.564300e+10,1.564300e+10,6.512000e+09,8.989400e+10,2.411900e+10,1.408480e+11,1.335020e+11,8.596900e+10,2.194710e+11,3.603190e+11,1.070970e+11,1.177920e+11,5.027900e+10,1.277240e+11,2.455160e+11,4.872900e+10,-1.837000e+09,6.843600e+10,1.148030e+11,3.603190e+11,0.77163
19,AMZN,AMAZON COM INC,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2021,USD,2021.0,Q3,10/29/2021,10/28/2022,1.010000e+10,1.028000e+10,1.108120e+11,-6.293000e+10,4.788200e+10,-4.303000e+10,-1.016300e+10,4.852000e+09,-5.370000e+08,-374000000.0,4.315000e+09,4.315000e+09,-1.155000e+09,3.156000e+09,3.156000e+09,3.156000e+09,3.156000e+09,4.453000e+09,-9.244000e+09,NaN,NaN,NaN,NaN,7.313000e+09,-1.574800e+10,5.770000e+08,-6.540000e+08,-1.482800e+10,-2.776000e+09,-2.776000e+09,-1.049000e+10,7.898800e+10,3.093300e+10,1.385310e+11,1.471520e+11,9.672300e+10,2.438750e+11,3.824060e+11,1.130200e+11,1.239940e+11,5.005500e+10,1.378480e+11,2.618420e+11,5.188400e+10,-1.837000e+09,7.159200e+10,1.205640e+11,3.824060e+11,0.31248

In [130]:
amazon_df.isnull().sum()

Ticker                                             0
Company Name                                       0
Sector                                             0
Industry                                           0
Report Date                                        0
Currency                                           0
Fiscal Year                                        0
Fiscal Period                                      0
Publish Date                                       0
Restated Date                                      0
Shares (Basic)                                     0
Shares (Diluted)                                   0
Revenue                                            0
Cost of Revenue                                    0
Gross Profit                                       0
Operating Expenses                                 0
Selling, General & Administrative                  0
Operating Income (Loss)                            0
Non-Operating Income (Loss)                        0
Interest Expense, Net                              0
Pretax Income (Loss), Adj.                         0
Pretax Income (Loss)                               0
Income Tax (Expense) Benefit, Net                  0
Income (Loss) from Continuing Operations           0
Net Income                                         0
Net Income (Common)                                0
Net Income/Starting Line                           0
Non-Cash Items                                     0
Change in Working Capital                          0
Change in Accounts Receivable                      1
Change in Inventories                              1
Change in Accounts Payable                         1
Change in Other                                    1
Net Cash from Operating Activities                 0
Change in Fixed Assets & Intangibles               0
Net Change in Long Term Investment                 0
Net Cash from Acquisitions & Divestitures          0
Net Cash from Investing Activities                 0
Cash from (Repayment of) Debt                      0
Net Cash from Financing Activities                 0
Net Change in Cash                                 0
Cash, Cash Equivalents & Short Term Investments    0
Inventories                                        0
Total Current Assets                               0
Property, Plant & Equipment, Net                   0
Other Long Term Assets                             0
Total Noncurrent Assets                            0
Total Assets                                       0
Payables & Accruals                                0
Total Current Liabilities                          0
Long Term Debt                                     0
Total Noncurrent Liabilities                       0
Total Liabilities                                  0
Share Capital & Additional Paid-In Capital         0
Treasury Stock                                     0
Retained Earnings                                  0
Total Equity                                       0
Total Liabilities & Equity                         0
Earnings Per Share, Basic                          0
dtype: int64

In [133]:
#PERFORM ONE-HOT ENCODING

#One hot encoding works by converting categorica data into numeric variables to be used as inputs to machine learning models
#we cannot simply replace some object with integer values 
# we can convert categorical variable into dummy one-hot encoded variables using Pandas pd.get_dummies() method

#lets perform one-hot encoding to the Fiscal Period column

print(apple_df['Fiscal Period'])

0     Q1
1     Q2
2     Q3
3     Q4
4     Q1
5     Q2
6     Q3
7     Q4
8     Q1
9     Q2
10    Q3
11    Q4
12    Q1
13    Q2
14    Q3
15    Q4
16    Q1
17    Q2
18    Q3
19    Q4
Name: Fiscal Period, dtype: str

In [ ]:
#we try to obtain the one-hot encoded version of the 'FIscal Period' column
fiscal_encoded=pd.get_dummies(apple_df['Fiscal Period'])
fiscal_encoded

       Q1     Q2     Q3     Q4
0    True  False  False  False
1   False   True  False  False
2   False  False   True  False
3   False  False  False   True
4    True  False  False  False
5   False   True  False  False
6   False  False   True  False
7   False  False  False   True
8    True  False  False  False
9   False   True  False  False
10  False  False   True  False
11  False  False  False   True
12   True  False  False  False
13  False   True  False  False
14  False  False   True  False
15  False  False  False   True
16   True  False  False  False
17  False   True  False  False
18  False  False   True  False
19  False  False  False   True

In [136]:
#Drop the 'Fiscal Period' column from the original Pandas DataFrame
apple_df= apple_df.drop('Fiscal Period', axis=1)

#concatenate the original DataFrame and the one-hot encoded 'Fiscal Period' Column

apple_df=pd.concat([apple_df, fiscal_encoded], axis=1)
apple_df

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Research & Development,Operating Income (Loss),Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Income,Net Income (Common),Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic",Q1,Q2,Q3,Q4
0,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2016,USD,2017.0,2/1/2017,2/2/2018,2.119464e+10,2.131198e+10,7.835100e+10,-4.817500e+10,3.017600e+10,-6.817000e+09,-3.946000e+09,-2.871000e+09,2.335900e+10,821000000.0,2.418000e+10,2.418000e+10,-6.289000e+09,1.789100e+10,1.789100e+10,1.789100e+10,1.789100e+10,2.708000e+09,3.648000e+09,2.723400e+10,-3.420000e+09,-1.558100e+10,-17000000.0,-1.912200e+10,-3.130000e+09,2.385000e+09,-1.085100e+10,-1.222500e+10,-4.113000e+09,6.045200e+10,1.405700e+10,2.712000e+09,1.033320e+11,2.651000e+10,1.856380e+11,1.566100e+10,2.278090e+11,3.311410e+11,6.224900e+10,1.399200e+10,8.413000e+10,7.355700e+10,1.146210e+11,1.987510e+11,3.214400e+10,1.000010e+11,1.323900e+11,3.311410e+11,0.84413,True,False,False,False
1,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2017,USD,2017.0,5/3/2017,5/2/2018,2.090316e+10,2.104675e+10,5.289600e+10,-3.230500e+10,2.059100e+10,-6.494000e+09,-3.718000e+09,-2.776000e+09,1.409700e+10,587000000.0,1.468400e+10,1.468400e+10,-3.655000e+09,1.102900e+10,1.102900e+10,1.102900e+10,1.102900e+10,2.587000e+09,-3.378000e+09,1.257000e+10,-2.889000e+09,-1.135700e+10,-50000000.0,-1.420200e+10,-3.004000e+09,1.046900e+10,-6.888000e+09,4.180000e+08,-1.214000e+09,6.710100e+10,1.157900e+10,2.910000e+09,1.019900e+11,2.716300e+10,1.897400e+11,1.563900e+10,2.325420e+11,3.345320e+11,5.166900e+10,1.399100e+10,7.334200e+10,8.453100e+10,1.271080e+11,2.004500e+11,3.357900e+10,1.009250e+11,1.340820e+11,3.345320e+11,0.52762,False,True,False,False
2,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2017,USD,2017.0,8/2/2017,8/1/2018,2.078035e+10,2.093400e+10,4.540800e+10,-2.792000e+10,1.748800e+10,-6.720000e+09,-3.783000e+09,-2.937000e+09,1.076800e+10,540000000.0,1.130800e+10,1.130800e+10,-2.591000e+09,8.717000e+09,8.717000e+09,8.717000e+09,8.717000e+09,3.135000e+09,-5.534000e+09,8.672000e+09,-2.277000e+09,-8.360000e+08,-181000000.0,-3.180000e+09,-3.365000e+09,9.237000e+09,-7.092000e+09,-2.078000e+09,3.414000e+09,7.675900e+10,1.239900e+10,3.146000e+09,1.128750e+11,2.928600e+10,1.847570e+11,1.825500e+10,2.322980e+11,3.451730e+11,5.521900e+10,1.847500e+10,8.130200e+10,8.986400e+10,1.314460e+11,2.127480e+11,3.444500e+10,9.852500e+10,1.324250e+11,3.451730e+11,0.41948,False,False,True,False
3,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2017,USD,2017.0,11/3/2017,10/31/2019,2.059771e+10,2.073434e+10,5.257900e+10,-3.264800e+10,1.993100e+10,-6.811000e+09,-3.814000e+09,-2.997000e+09,1.312000e+10,797000000.0,1.391700e+10,1.391700e+10,-3.203000e+09,1.071400e+10,1.071400e+10,1.071400e+10,1.071400e+10,2.376000e+09,1.750000e+08,1.574900e+10,-3.865000e+09,-5.768000e+09,-81000000.0,-9.942000e+09,-3.270000e+09,6.923000e+09,-7.514000e+09,-4.089000e+09,1.718000e+09,7.418100e+10,1.787400e+10,4.855000e+09,1.286450e+11,3.378300e+10,1.947140e+11,1.817700e+10,2.466740e+11,3.753190e+11,4.424200e+10,1.847300e+10,1.008140e+11,9.720700e+10,1.404580e+11,2.412720e+11,3.586700e+10,9.833000e+10,1.340470e+11,3.753190e+11,0.52015,False,False,False,True
4,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2017,USD,2018.0,2/2/2018,1/30/2019,2.045151e+10,2.063115e+10,8.829300e+10,-5.438100e+10,3.391200e+10,-7.638000e+09,-4.231000e+09,-3.407000e+09,2.627400e+10,756000000.0,2.703000e+10,2.703000e+10,-6.965000e+09,2.006500e+10,2.006500e+10,2.006500e+10,2.006500e+10,-3.244100e+10,3.792400e+10,2.829300e+10,-2.810000e+09,-1.056400e+10,-173000000.0,-1.359000e+10,-3.339000e+09,6.971000e+09,-1.009500e+10,-7.501000e+09,7.202000e+09,7.715300e+10,2.344000e+10,4.421000e+09,1.438100e+11,3.367900e+10,2.079440e+11,2.136100e+10,2.629840e+11,4.067940e+11,8.926600e+10,1.847800e+10,1.157880e+11,1.039220e+11,1.508070e+11,2.665950e+11,3.644700e+10,1.045930e+11,1.401990e+11,4.067940e+11,0.98110,True,False,False,False
5,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2018,USD,2018.0,5/2/2018,5/1/2019,2.009951e+10,2.027397e+10,6.113700e+10,-3.771500e+10,2.342200e+10,-7.528000e+09,-4.150000e+09,-3.378000e+09,1.589400e+10,274000000.0,1.616800e+10,1.616800e+10,-2.346000e+09,1.382200e+10,1.382200e+10,1.382200e+10,1.382200e+10,8.500000e+08,-2.281000e+09,1.513000e+10,-4.195000e+09,3.277800e+10,-132000000.0,2.871000e+10,-3.190000e+09,-5.020000e+08,-2.242900e+10,-2.627200e+10,1.756800e+10,8.794000e+10,1.432400e+10,7.662000e+09,1.300530e+11,3.507700e+10,1.792860e+11,2.308600e+10,2.374490e+11,3.675020e+11,6.106700e+10,2.047800e+10,8.932000e+10,1.013620e+11,1.513040e+11,2.406240e+11,3.804400e+10,9.189800e+10,1.268780e+11,3.675020e+11,0.68768,False,True,False,False
6,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2018,USD,2018.0,8/1/2018,7/31/2019,1.952867e+10,1.970644e+10,5.326500e+10,-3.284400e+10,2.042100e+10,-7.809000e+09,-4.108000e+09,-3.701000e+09,1.261200e+10,672000000.0,1.328400e+10,1.328400e+10,-1.765000e+09,1.151900e+10,1.151900e+10,1.151900e+10,1.151900e+10,2.477000e+09,-2.173000e+09,1.448800e+10,-3.267000e+09,8.079000e+09,-126000000.0,3.947000e+09,-3.653000e+09,-6.010000e+09,-2.078200e+10,-3.152300e+10,-1.308800e+10,7.097000e+10,1.410400e+10,5.936000e+09,1.157610e+11,3.811700e+10,1.727730e+11,2.254600e+10,2.334360e+11,3.491970e+11,6.367300e+10,1.747200e+10,8.854800e+10,9.712800e+10,1.457000e+11,2.342480e+11,3.862400e+10,7.943600e+10,1.149490e+11,3.491970e+11,0.58985,False,False,True,False
7,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2018,USD,2018.0,11/5/2018,10/30/2020,1.920635e+10,1.939019e+10,6.290000e+10,-3.881600e+10,2.408400e+10,-7.966000e+09,-4.216000e+09,-3.750000e+09,1.611800e+10,303000000.0,1.642100e+10,1.642100e+10,-2.296000e+09,1.412500e+10,1.412500e+10,1.412500e+10,1.412500e+10,1.864000e+09,7.800000e+08,1.952300e+10,-3.041000e+09,5.520000e+08,-290000000.0,-3.001000e+09,-3.530000e+09,-2.700000e+07,-1.876300e+10,-2.258000e+10,-6.058000e+09,6.630100e+10,2.318600e+10,3.956000e+09,1.313390e+11,4.130400e+10,1.707990e+11,2.228300e+10,2.343860e+11,3.657250e+11,5.588800e+10,2.074800e+10,1.159290e+11,9.373500e+10,1.426490e+11,2.585780e+11,4.020100e+10,7.040000e+10,1.071470e+11,3.657250e+11,0.73543,False,False,False,True
8,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2018,USD,2019.0,1/30/2019,1/29/2020,1.894328e+10,1.909301e+10,8.431000e+10,-5.227900e+10,3.203100e+10,-8.685000e+09,-4.783000e+09,-3.902000e+09,2.334600e+10,560000000.0,2.390600e+10,2.390600e+10,-3.941000e+09,1.996500e+10,1.996500e+10,1.996500e+10,1.996500e+10,1.612000e+09,1.718000e+09,2.669000e+10,-3.355000e+09,9.422000e+09,-167000000.0,5.844000e+09,-3.568000e+09,6.000000e+06,-8.796000e+09,-1.367600e+10,1.885800e+10,8.642700e+10,1.807700e+10,4.988000e+09,1.408280e+11,3.959700e+10,1.586080e+11,3.468600e+10,2.328910e+11,3.737190e+11,4.429300e+10,2.174100e+10,1.082830e+11,9.298900e+10,1.475440e+11,2.558270e+11,4.097000e+10,8.051000e+10,1.178920e+11,3.737190e+11,1.05394,True,False,False,False
9,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2019,USD,2019.0,5/1/2019,5/1/2020,1.869628e+10,1.880258e+10,5.801500e+10,-3.619400e+10,2.182100e+10,-8.406000e+09,-4.458000e+09,-3.948000e+09,1.341500e+10,378000000.0,1.379300e+10,1.379300e+10,-2.232000e+09,1.156100e+10,1.156100e+10,1.156100e+10,1.156100e+10,1.337000e+09,-4.783000e+09,1.115500e+10,-2.363000e+09,1.574900e+10,-124000000.0,1.334800e+10,-3.443000e+09,-2.542000e+09,-2.331200e+10,-2.945700e+10,-4.954000e+09,8.009200e+10,1.508500e+10,4.884000e+09,1.233460e+11,3.874600e+10,1.453190e+11,3.458700e+10,2.186520e+11,3.419980e+11,3.044300e+10,2.242900e+10,9.377200e+10,9.020100e+10,1.423660e+11,2.361380e+11,4.280100e+10,6.455800e+10,1.058600e+11,3.419980e+11,0.61836,False,True,False,False
10,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2019,USD,2019.0,7/31/2019,7/31/2020,1.828254e+10,1.840552e+10,5.380900e+10,-3.358200e+10,2.022700e+10,-8.683000e+09,-4.426000e+09,-4.257000e+09,1.154400e+10,367000000.0,1.191100e+10,1.191100e+10,-1.867000e+09,1.004400e+10,1.004400e+10,1.004400e+10,1.004400e+10,1.582000e+09,-2.923000e+09,1.163600e+10,-2.000000e+09,3.012000e+10,-320000000.0,2.750200e+10,-3.629000e+09,-4.990000e+09,-1.695400e+10,-2.680400e+10,1.233400e+10,9.461400e+10,1.414800e+10,3.355000e+09,1.349730e+11,3.763600e+10,1.159960e+11,3.363400e+10,1.872660e+11,3.222390e+11,2.911500e+10,2.348200e+10,8.970400e+10,8.493600e+10,1.360790e+11,2.257830e+11,4.337100e+10,5.372400e+10,9.645600e+10,3.222390e+11,0.54938,False,False,True,False
11,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2019,USD,2019.0,10/31/2019,10/29/2021,1.796324e+10,1.808150e+10,6.404000e+10,-3.972700e+10,2.431300e+10,-8.688000e+09,-4.578000e+09,-4.110000e+09,1.562500e+10,502000000.0,1.612700e+10,1.612700e+10,-2.441000e+09,1.368600e+10,1.368600e+10,1.368600e+10,1.368600e+10,5.450000e+08,2.500000e+09,1.991000e+10,-2.777000e+09,2.802000e+09,-13000000.0,-7.980000e+08,-3.479000e+09,-2.930000e+08,-1.705400e+10,-2.103900e+10,-1.927000e+09,1.005570e+11,2.292600e+10,4.106000e+09,1.628190e+11,3.737800e+10,1.053410e+11,3.297800e+10,1.756970e+11,3.385160e+11,4.623600e+10,1.624000e+10,1.057180e+11,9.180700e+10,1.423100e+11,2.480280e+11,4.517400e+10,4.589800e+10,9.048800e+10,3.385160e+11,0.76189,False,False,False,True
12,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2019,USD,2020.0,1/29/2020,1/28/2021,1.766016e+10,1.781842e+10,9.181900e+10,-5.660200e+10,3.521700e+10,-9.648000e+09,-5.197000e+09,-4.451000e+09,2.556900e+10,349000000.0,2.591800e+10,2.591800e+10,-3.682000e+09,2.223600e+10,2.223600e+10,2.223600e+10,2.223600e+10,1.219000e+09,4.245000e+09,3.051600e+10,-2.107000e+09,-1.039600e+10,-958000000.0,-1.366800e+10,-3.539000e+09,2.310000e+08,-2.070400e+10,-2.540700e+10,-8.559000e+09,1.071620e+11,2.097000e+10,4.097000e+09,1.632310e+11,3.703100e+10,9.989900e+10,4.045700e+10,1.773870e+11,3.406180e+11,4.511100e+10,1.521400e+10,1.021610e+11,9.307800e+10,1.489260e+11,2.510870e+11,4.597200e+10,4.397700e+10,8.953100e+10,3.406180e+11,1.25911,True,False,False,False
13,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2020,USD,2020.0,5/1/2020,4/29/2021,1.744040e+10,1.761877e+10,5.831300e+10,-3.594300e+10,2.237000e+10,-9.517000e+09,-4.952000e+09,-4.565000e+09,1.285300e+10,282000000.0,1.313500e+10,1.313500e+10,-1.886000e+09,1.124900e+10,1.124900e+10,1.124900e+10,1.124900e+10,1.278000e+09,-2.002000e+09,1.331100e+10,-1.853000e+09,1.140700e+10,-176000000.0,9.013000e+09,-3.375000e+09,-1.753000e+09,-1.814600e+10,-2.094000e+10,1.384000e+09,9.405100e+10,1.572200e+10,3.334000e+09,1.437530e+11,3.588900e+10,9.879300e+10,4.196500e+10,1.766470e+11,3.204000e+11,3.242100e+10,2.042100e+10,9.609400e+10,8.908600e+10,1.458810e+11,2.419750e+11,4.803200e+10,3.318200e+10,7.842500e+10,3.204000e+11,0.64500,False,True,False,False
14,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2020,USD,2020.0,7/31/2020,7/28/2021,1.725029e+10,1.741916e+10,5.968500e+10,-3.700500e+10,2.268000e+10,-9.589000e+09,-4.831000e+09,-4.758000e+09,1.309100e+10,46000000.0,1.313700e+10,1.313700e+10,-1.884000e+09,1.125300e+10,1.125300e+10,1.125300e+10,1.125300e+10,2.696000e+09,-4.300000e+08,1.627100e+10,-1.565000e+09,-2.992000e+09,-339000000.0,-5.165000e+09,-3.656000e+09,-4.410000e+08,-1.589100e+10,-1.911600e+10,-8.010000e+09,9.302500e+10,1.788200e+10,3.978000e+09,1.400650e+11,3.568700e+10,1.005920e+11,4.100000e+10,1.772790e+11,3.173440e+11,3.532500e+10,1.867500e+10,9.531800e+10,9.404800e+10,1.497440e+11,2.450620e+11,4.869600e+10,2.413600e+10,7.228200e+10,3.173440e+11,0.65234,False,False,True,False
15,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2020,USD,2020.0,10/30/2020,7/28/2021,1.705762e+10,1.725652e+10,6.469800e+10,-4.000900e+10,2.468900e+10,-9.914000e+09,-4.936000e+09,-4.978000e+09,1.477500e+10,126000000.0,1.490100e+10,1.490100e+10,-2.228000e+09,1.267300e+10,1.267300e+10,1.267300e+10,1.267300e+10,1.324000e+09,3.877000e+09,2.057600e+10,-1.784000e+09,7.434000e+09,-51000000.0,5.531000e+09,-3.511000e+09,4.462000e+09,-1.761700e+10,-2.135700e+10,4.750000e+09,9.094300e+10,1.612000e+10,4.061000e+09,1.437130e+11,3.676600e+10,1.008870e+11,4.252200e+10,1.801750e+11,3.238880e+11,4.229600e+10,1.376900e+10,1.053920e+11,9.866700e+10,1.531570e+11,2.585490e+11,5.077900e+10,1.496600e+10,6.533900e+10,3.238880e+11,0.74295,False,False,False,True
16,AAPL,APPLE INC,Technology,Computer Hardware,12/31/2020,USD,2021.0,1/28/2021,1/28/2022,1.693512e+10,1.711369e+10,1.114390e+11,-6.711100e+10,4.432800e+10,-1.079400e+10,-5.631000e+09,-5.163000e+09,3.353400e+10,45000000.0,3.357900e+10,3.357900e+10,-4.824000e+09,2.875500e+10,2.875500e+10,2.875500e+10,2.875500e+10,1.987000e+09,5.355000e+09,3.876300e+10,-3.500000e+09,-5.279000e+09,NaN,-8.584000e+09,-3.613000e+09,-9.780000e+08,-2.477500e+10,-3.224900e+10,-2.070000e+09,7.682600e+10,2.710100e+10,4.973000e+09,1.541060e+11,3.793300e+10,1.187450e+11,4.327000e+10,1.999480e+11,3.540540e+11,6.384600e+10,1.276200e+10,1.325070e+11,9.928100e+10,1.553230e+11,2.878300e+11,5.174400e+10,1.430100e+10,6.622400e+10,3.540540e+11,1.69795,True,False,False,False
17,AAPL,APPLE INC,Technology,Computer Hardware,3/31/2021,USD,2021.0,4/29/2021,1/28/2022,1.675348e+10,1.692916e+10,8.958400e+10,-5.150500e+10,3.807900e+10,-1.057600e+10,-5.314000e+09,-5.262000e+09,2.750300e+10,508000000.0,2.801100e+10,2.801100e+10,-4.381000e+09,2.363000e+10,2.363000e+10,2.363000e+10,2.363000e+10,1.333000e+09,-3.779000e+09,2.398100e+10,-2.269000e+09,-7.895000e+09,-9000000.0,-1.036800e+10,-3.447000e+09,1.042300e+10,-1.854800e+10,-1.132600e+10,2.287000e+09,6.983400e+10,1.850300e+10,5.219000e+09,1.214650e+11,3.781500e+10,1.345390e+11,4.333900e+10,2.156930e+11,3.371580e+11,4.012700e+10,1.300300e+10,1.063850e+11,1.086420e+11,1.615950e+11,2.679800e+11,5.420300e+10,1.526100e+10,6.917800e+10,3.371580e+11,1.41045,False,True,False,False
18,AAPL,APPLE INC,Technology,Computer Hardware,6/30/2021,USD,2021.0,7/28/2021,4/29/2022,1.684430e+10,1.702142e+10,8.143400e+10,-4.617900e+10,3.525500e+10,-1.112900e+10,-5.412000e+09,-5.717000e+09,2.412600e+10,243000000.0,2.436900e+10,2.436900e+10,-2.625000e+09,2.174400e+10,2.174400e+10,2.174400e+10,2.174400e+10,1.215000e+09,-4.697000e+09,2.109400e+10,-2.093000e+09,5.747000e+09,-4000000.0,3.572000e+09,-3.767000e+09,0.000000e+00,-2.290000e+10,-2.939600e+10,-4.730000e+09,6.169600e+10,1.747500e+10,5.178000e+09,1.144230e+11,3.861500e+10,1.319480e+11,4.485400e+10,2.154170e+11,3.298400e+11,4.040900e+10,1.603900e+10,1.077540e+11,1.057520e+11,1.578060e+11,2.655600e+11,5.498900e+10,9.233000e+09,6.428000e+10,3.298400e+11,1.29088,False,False,True,False
19,AAPL,APPLE INC,Technology,Computer Hardware,9/30/2021,USD,2021.0,10/29/2021,7/29/2022,1.639172e+10,1.651929e+10,8.336000e+10,-4.818600e+10,3.517400e+10,-1.138800e+10,-5.616000e+09,-5.772000e+09,2.378600e+10,-538000000.0,2.324800e+10,2.324800e+10,-2.697000e+09,2.055100e+10,2.055100e+10,2.055100e+10,2.055100e+10,-1.550000e+09,-1.790000e+09,2.020000e+10,-3.223000e+09,4.352000e+09,-20000000.0,8.350000e+08,-3.640000e+09,3.220000e+09,-1.974800e+10,-2.038200e+10,6.530000e+08,6.263900e+10,2.627800e+10,6.580000e+09,1.348360e+11,3.944000e+10,1.278770e+11,4.884900e+10,2.161660e+11,3.510020e+11,5.476300e+10,6.000000e+09,1.158680e+11,1.187190e+11,1.720440e+11,2.879120e+11,5.736500e+10,5.562000e+09,6.309000e+10,3.510020e+11,1.25374,False,False,False,True

In [137]:
#**PRACTICE OPPORTUNITY:**
#**Write a Python code that performs the following tasks:**
#**Filter rows in "merged_df" Pandas DataFrame to only include Amazon data with Ticker Symbol 'AMZN'. Place the output in a Pandas DataFrame titled "amazon_df"**
#**Perform one-hot encoding to the "Fiscal Period" column in the "amazon_df" using Pandas pd.get_dummies()**

print(amazon_df['Fiscal Period'])

0     Q4
1     Q1
2     Q2
3     Q3
4     Q4
5     Q1
6     Q2
7     Q3
8     Q4
9     Q1
10    Q2
11    Q3
12    Q4
13    Q1
14    Q2
15    Q3
16    Q4
17    Q1
18    Q2
19    Q3
Name: Fiscal Period, dtype: str

In [138]:
amazon_fiscal_encoded=pd.get_dummies(amazon_df['Fiscal Period'])
amazon_fiscal_encoded

       Q1     Q2     Q3     Q4
0   False  False  False   True
1    True  False  False  False
2   False   True  False  False
3   False  False   True  False
4   False  False  False   True
5    True  False  False  False
6   False   True  False  False
7   False  False   True  False
8   False  False  False   True
9    True  False  False  False
10  False   True  False  False
11  False  False   True  False
12  False  False  False   True
13   True  False  False  False
14  False   True  False  False
15  False  False   True  False
16  False  False  False   True
17   True  False  False  False
18  False   True  False  False
19  False  False   True  False

In [139]:
#PERFORM FEATURE ENGINEERING

#Feature engineering involves transforming features in a dataset with the goal of improving the performance of downstream ML models. it involves feature selection, scaling, and creating new features from existing one.
# to calculate percentage Change calculation we can use Pandas .pct_change() method calculates the percentage change between current and prior elements in a Pandas DataFrame

#SYNTAX, For Example
#apple_df['Revenue' + 'change from last quarter']= apple_df['Revenue'].pct_change()

apple_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 62 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Ticker                                           20 non-null     str
 1   Company Name                                     20 non-null     str
 2   Sector                                           20 non-null     str
 3   Industry                                         20 non-null     str
 4   Report Date                                      20 non-null     str
 5   Currency                                         20 non-null     str
 6   Fiscal Year                                      20 non-null     float64
 7   Publish Date                                     20 non-null     str
 8   Restated Date                                    20 non-null     str
 9   Shares (Basic)                                   20 non-null     float64
 10  Shares (Diluted)                                 20 non-null     float64
 11  Revenue                                          20 non-null     float64
 12  Cost of Revenue                                  20 non-null     float64
 13  Gross Profit                                     20 non-null     float64
 14  Operating Expenses                               20 non-null     float64
 15  Selling, General & Administrative                20 non-null     float64
 16  Research & Development                           20 non-null     float64
 17  Operating Income (Loss)                          20 non-null     float64
 18  Non-Operating Income (Loss)                      20 non-null     float64
 19  Pretax Income (Loss), Adj.                       20 non-null     float64
 20  Pretax Income (Loss)                             20 non-null     float64
 21  Income Tax (Expense) Benefit, Net                20 non-null     float64
 22  Income (Loss) from Continuing Operations         20 non-null     float64
 23  Net Income                                       20 non-null     float64
 24  Net Income (Common)                              20 non-null     float64
 25  Net Income/Starting Line                         20 non-null     float64
 26  Non-Cash Items                                   20 non-null     float64
 27  Change in Working Capital                        20 non-null     float64
 28  Net Cash from Operating Activities               20 non-null     float64
 29  Change in Fixed Assets & Intangibles             20 non-null     float64
 30  Net Change in Long Term Investment               20 non-null     float64
 31  Net Cash from Acquisitions & Divestitures        19 non-null     float64
 32  Net Cash from Investing Activities               20 non-null     float64
 33  Dividends Paid                                   20 non-null     float64
 34  Cash from (Repayment of) Debt                    20 non-null     float64
 35  Cash from (Repurchase of) Equity                 20 non-null     float64
 36  Net Cash from Financing Activities               20 non-null     float64
 37  Net Change in Cash                               20 non-null     float64
 38  Cash, Cash Equivalents & Short Term Investments  20 non-null     float64
 39  Accounts & Notes Receivable                      20 non-null     float64
 40  Inventories                                      20 non-null     float64
 41  Total Current Assets                             20 non-null     float64
 42  Property, Plant & Equipment, Net                 20 non-null     float64
 43  Long Term Investments & Receivables              20 non-null     float64
 44  Other Long Term Assets                           20 non-null     float64
 45  Total Noncurrent Assets                          20 non-null     float64
 46  Total Assets                                     20 non-null     float64
 47  Payables & Accruals                              20 non-null     float64
 48  Short Term Debt                                  20 non-null     float64
 49  Total Current Liabilities                        20 non-null     float64
 50  Long Term Debt                                   20 non-null     float64
 51  Total Noncurrent Liabilities                     20 non-null     float64
 52  Total Liabilities                                20 non-null     float64
 53  Share Capital & Additional Paid-In Capital       20 non-null     float64
 54  Retained Earnings                                20 non-null     float64
 55  Total Equity                                     20 non-null     float64
 56  Total Liabilities & Equity                       20 non-null     float64
 57  Earnings Per Share, Basic                        20 non-null     float64
 58  Q1                                               20 non-null     bool
 59  Q2                                               20 non-null     bool
 60  Q3                                               20 non-null     bool
 61  Q4                                               20 non-null     bool
dtypes: bool(4), float64(50), str(8)
memory usage: 9.3 KB

In [146]:
#convert the 'Report Date' column to Datetime. this step is important when we want to sort the Pandas DataFrame and to perform date time operations
apple_df['Report Date']= pd.to_datetime(apple_df['Report Date'], format= '%m/%d/%Y')
apple_df=apple_df.sort_values(by='Report Date').reset_index(drop=True)
apple_df

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Research & Development,Operating Income (Loss),Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Income,Net Income (Common),Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic",Q1,Q2,Q3,Q4
0,AAPL,APPLE INC,Technology,Computer Hardware,2016-12-31,USD,2017.0,2/1/2017,2/2/2018,2.119464e+10,2.131198e+10,7.835100e+10,-4.817500e+10,3.017600e+10,-6.817000e+09,-3.946000e+09,-2.871000e+09,2.335900e+10,821000000.0,2.418000e+10,2.418000e+10,-6.289000e+09,1.789100e+10,1.789100e+10,1.789100e+10,1.789100e+10,2.708000e+09,3.648000e+09,2.723400e+10,-3.420000e+09,-1.558100e+10,-17000000.0,-1.912200e+10,-3.130000e+09,2.385000e+09,-1.085100e+10,-1.222500e+10,-4.113000e+09,6.045200e+10,1.405700e+10,2.712000e+09,1.033320e+11,2.651000e+10,1.856380e+11,1.566100e+10,2.278090e+11,3.311410e+11,6.224900e+10,1.399200e+10,8.413000e+10,7.355700e+10,1.146210e+11,1.987510e+11,3.214400e+10,1.000010e+11,1.323900e+11,3.311410e+11,0.84413,True,False,False,False
1,AAPL,APPLE INC,Technology,Computer Hardware,2017-03-31,USD,2017.0,5/3/2017,5/2/2018,2.090316e+10,2.104675e+10,5.289600e+10,-3.230500e+10,2.059100e+10,-6.494000e+09,-3.718000e+09,-2.776000e+09,1.409700e+10,587000000.0,1.468400e+10,1.468400e+10,-3.655000e+09,1.102900e+10,1.102900e+10,1.102900e+10,1.102900e+10,2.587000e+09,-3.378000e+09,1.257000e+10,-2.889000e+09,-1.135700e+10,-50000000.0,-1.420200e+10,-3.004000e+09,1.046900e+10,-6.888000e+09,4.180000e+08,-1.214000e+09,6.710100e+10,1.157900e+10,2.910000e+09,1.019900e+11,2.716300e+10,1.897400e+11,1.563900e+10,2.325420e+11,3.345320e+11,5.166900e+10,1.399100e+10,7.334200e+10,8.453100e+10,1.271080e+11,2.004500e+11,3.357900e+10,1.009250e+11,1.340820e+11,3.345320e+11,0.52762,False,True,False,False
2,AAPL,APPLE INC,Technology,Computer Hardware,2017-06-30,USD,2017.0,8/2/2017,8/1/2018,2.078035e+10,2.093400e+10,4.540800e+10,-2.792000e+10,1.748800e+10,-6.720000e+09,-3.783000e+09,-2.937000e+09,1.076800e+10,540000000.0,1.130800e+10,1.130800e+10,-2.591000e+09,8.717000e+09,8.717000e+09,8.717000e+09,8.717000e+09,3.135000e+09,-5.534000e+09,8.672000e+09,-2.277000e+09,-8.360000e+08,-181000000.0,-3.180000e+09,-3.365000e+09,9.237000e+09,-7.092000e+09,-2.078000e+09,3.414000e+09,7.675900e+10,1.239900e+10,3.146000e+09,1.128750e+11,2.928600e+10,1.847570e+11,1.825500e+10,2.322980e+11,3.451730e+11,5.521900e+10,1.847500e+10,8.130200e+10,8.986400e+10,1.314460e+11,2.127480e+11,3.444500e+10,9.852500e+10,1.324250e+11,3.451730e+11,0.41948,False,False,True,False
3,AAPL,APPLE INC,Technology,Computer Hardware,2017-09-30,USD,2017.0,11/3/2017,10/31/2019,2.059771e+10,2.073434e+10,5.257900e+10,-3.264800e+10,1.993100e+10,-6.811000e+09,-3.814000e+09,-2.997000e+09,1.312000e+10,797000000.0,1.391700e+10,1.391700e+10,-3.203000e+09,1.071400e+10,1.071400e+10,1.071400e+10,1.071400e+10,2.376000e+09,1.750000e+08,1.574900e+10,-3.865000e+09,-5.768000e+09,-81000000.0,-9.942000e+09,-3.270000e+09,6.923000e+09,-7.514000e+09,-4.089000e+09,1.718000e+09,7.418100e+10,1.787400e+10,4.855000e+09,1.286450e+11,3.378300e+10,1.947140e+11,1.817700e+10,2.466740e+11,3.753190e+11,4.424200e+10,1.847300e+10,1.008140e+11,9.720700e+10,1.404580e+11,2.412720e+11,3.586700e+10,9.833000e+10,1.340470e+11,3.753190e+11,0.52015,False,False,False,True
4,AAPL,APPLE INC,Technology,Computer Hardware,2017-12-31,USD,2018.0,2/2/2018,1/30/2019,2.045151e+10,2.063115e+10,8.829300e+10,-5.438100e+10,3.391200e+10,-7.638000e+09,-4.231000e+09,-3.407000e+09,2.627400e+10,756000000.0,2.703000e+10,2.703000e+10,-6.965000e+09,2.006500e+10,2.006500e+10,2.006500e+10,2.006500e+10,-3.244100e+10,3.792400e+10,2.829300e+10,-2.810000e+09,-1.056400e+10,-173000000.0,-1.359000e+10,-3.339000e+09,6.971000e+09,-1.009500e+10,-7.501000e+09,7.202000e+09,7.715300e+10,2.344000e+10,4.421000e+09,1.438100e+11,3.367900e+10,2.079440e+11,2.136100e+10,2.629840e+11,4.067940e+11,8.926600e+10,1.847800e+10,1.157880e+11,1.039220e+11,1.508070e+11,2.665950e+11,3.644700e+10,1.045930e+11,1.401990e+11,4.067940e+11,0.98110,True,False,False,False
5,AAPL,APPLE INC,Technology,Computer Hardware,2018-03-31,USD,2018.0,5/2/2018,5/1/2019,2.009951e+10,2.027397e+10,6.113700e+10,-3.771500e+10,2.342200e+10,-7.528000e+09,-4.150000e+09,-3.378000e+09,1.589400e+10,274000000.0,1.616800e+10,1.616800e+10,-2.346000e+09,1.382200e+10,1.382200e+10,1.382200e+10,1.382200e+10,8.500000e+08,-2.281000e+09,1.513000e+10,-4.195000e+09,3.277800e+10,-132000000.0,2.871000e+10,-3.190000e+09,-5.020000e+08,-2.242900e+10,-2.627200e+10,1.756800e+10,8.794000e+10,1.432400e+10,7.662000e+09,1.300530e+11,3.507700e+10,1.792860e+11,2.308600e+10,2.374490e+11,3.675020e+11,6.106700e+10,2.047800e+10,8.932000e+10,1.013620e+11,1.513040e+11,2.406240e+11,3.804400e+10,9.189800e+10,1.268780e+11,3.675020e+11,0.68768,False,True,False,False
6,AAPL,APPLE INC,Technology,Computer Hardware,2018-06-30,USD,2018.0,8/1/2018,7/31/2019,1.952867e+10,1.970644e+10,5.326500e+10,-3.284400e+10,2.042100e+10,-7.809000e+09,-4.108000e+09,-3.701000e+09,1.261200e+10,672000000.0,1.328400e+10,1.328400e+10,-1.765000e+09,1.151900e+10,1.151900e+10,1.151900e+10,1.151900e+10,2.477000e+09,-2.173000e+09,1.448800e+10,-3.267000e+09,8.079000e+09,-126000000.0,3.947000e+09,-3.653000e+09,-6.010000e+09,-2.078200e+10,-3.152300e+10,-1.308800e+10,7.097000e+10,1.410400e+10,5.936000e+09,1.157610e+11,3.811700e+10,1.727730e+11,2.254600e+10,2.334360e+11,3.491970e+11,6.367300e+10,1.747200e+10,8.854800e+10,9.712800e+10,1.457000e+11,2.342480e+11,3.862400e+10,7.943600e+10,1.149490e+11,3.491970e+11,0.58985,False,False,True,False
7,AAPL,APPLE INC,Technology,Computer Hardware,2018-09-30,USD,2018.0,11/5/2018,10/30/2020,1.920635e+10,1.939019e+10,6.290000e+10,-3.881600e+10,2.408400e+10,-7.966000e+09,-4.216000e+09,-3.750000e+09,1.611800e+10,303000000.0,1.642100e+10,1.642100e+10,-2.296000e+09,1.412500e+10,1.412500e+10,1.412500e+10,1.412500e+10,1.864000e+09,7.800000e+08,1.952300e+10,-3.041000e+09,5.520000e+08,-290000000.0,-3.001000e+09,-3.530000e+09,-2.700000e+07,-1.876300e+10,-2.258000e+10,-6.058000e+09,6.630100e+10,2.318600e+10,3.956000e+09,1.313390e+11,4.130400e+10,1.707990e+11,2.228300e+10,2.343860e+11,3.657250e+11,5.588800e+10,2.074800e+10,1.159290e+11,9.373500e+10,1.426490e+11,2.585780e+11,4.020100e+10,7.040000e+10,1.071470e+11,3.657250e+11,0.73543,False,False,False,True
8,AAPL,APPLE INC,Technology,Computer Hardware,2018-12-31,USD,2019.0,1/30/2019,1/29/2020,1.894328e+10,1.909301e+10,8.431000e+10,-5.227900e+10,3.203100e+10,-8.685000e+09,-4.783000e+09,-3.902000e+09,2.334600e+10,560000000.0,2.390600e+10,2.390600e+10,-3.941000e+09,1.996500e+10,1.996500e+10,1.996500e+10,1.996500e+10,1.612000e+09,1.718000e+09,2.669000e+10,-3.355000e+09,9.422000e+09,-167000000.0,5.844000e+09,-3.568000e+09,6.000000e+06,-8.796000e+09,-1.367600e+10,1.885800e+10,8.642700e+10,1.807700e+10,4.988000e+09,1.408280e+11,3.959700e+10,1.586080e+11,3.468600e+10,2.328910e+11,3.737190e+11,4.429300e+10,2.174100e+10,1.082830e+11,9.298900e+10,1.475440e+11,2.558270e+11,4.097000e+10,8.051000e+10,1.178920e+11,3.737190e+11,1.05394,True,False,False,False
9,AAPL,APPLE INC,Technology,Computer Hardware,2019-03-31,USD,2019.0,5/1/2019,5/1/2020,1.869628e+10,1.880258e+10,5.801500e+10,-3.619400e+10,2.182100e+10,-8.406000e+09,-4.458000e+09,-3.948000e+09,1.341500e+10,378000000.0,1.379300e+10,1.379300e+10,-2.232000e+09,1.156100e+10,1.156100e+10,1.156100e+10,1.156100e+10,1.337000e+09,-4.783000e+09,1.115500e+10,-2.363000e+09,1.574900e+10,-124000000.0,1.334800e+10,-3.443000e+09,-2.542000e+09,-2.331200e+10,-2.945700e+10,-4.954000e+09,8.009200e+10,1.508500e+10,4.884000e+09,1.233460e+11,3.874600e+10,1.453190e+11,3.458700e+10,2.186520e+11,3.419980e+11,3.044300e+10,2.242900e+10,9.377200e+10,9.020100e+10,1.423660e+11,2.361380e+11,4.280100e+10,6.455800e+10,1.058600e+11,3.419980e+11,0.61836,False,True,False,False
10,AAPL,APPLE INC,Technology,Computer Hardware,2019-06-30,USD,2019.0,7/31/2019,7/31/2020,1.828254e+10,1.840552e+10,5.380900e+10,-3.358200e+10,2.022700e+10,-8.683000e+09,-4.426000e+09,-4.257000e+09,1.154400e+10,367000000.0,1.191100e+10,1.191100e+10,-1.867000e+09,1.004400e+10,1.004400e+10,1.004400e+10,1.004400e+10,1.582000e+09,-2.923000e+09,1.163600e+10,-2.000000e+09,3.012000e+10,-320000000.0,2.750200e+10,-3.629000e+09,-4.990000e+09,-1.695400e+10,-2.680400e+10,1.233400e+10,9.461400e+10,1.414800e+10,3.355000e+09,1.349730e+11,3.763600e+10,1.159960e+11,3.363400e+10,1.872660e+11,3.222390e+11,2.911500e+10,2.348200e+10,8.970400e+10,8.493600e+10,1.360790e+11,2.257830e+11,4.337100e+10,5.372400e+10,9.645600e+10,3.222390e+11,0.54938,False,False,True,False
11,AAPL,APPLE INC,Technology,Computer Hardware,2019-09-30,USD,2019.0,10/31/2019,10/29/2021,1.796324e+10,1.808150e+10,6.404000e+10,-3.972700e+10,2.431300e+10,-8.688000e+09,-4.578000e+09,-4.110000e+09,1.562500e+10,502000000.0,1.612700e+10,1.612700e+10,-2.441000e+09,1.368600e+10,1.368600e+10,1.368600e+10,1.368600e+10,5.450000e+08,2.500000e+09,1.991000e+10,-2.777000e+09,2.802000e+09,-13000000.0,-7.980000e+08,-3.479000e+09,-2.930000e+08,-1.705400e+10,-2.103900e+10,-1.927000e+09,1.005570e+11,2.292600e+10,4.106000e+09,1.628190e+11,3.737800e+10,1.053410e+11,3.297800e+10,1.756970e+11,3.385160e+11,4.623600e+10,1.624000e+10,1.057180e+11,9.180700e+10,1.423100e+11,2.480280e+11,4.517400e+10,4.589800e+10,9.048800e+10,3.385160e+11,0.76189,False,False,False,True
12,AAPL,APPLE INC,Technology,Computer Hardware,2019-12-31,USD,2020.0,1/29/2020,1/28/2021,1.766016e+10,1.781842e+10,9.181900e+10,-5.660200e+10,3.521700e+10,-9.648000e+09,-5.197000e+09,-4.451000e+09,2.556900e+10,349000000.0,2.591800e+10,2.591800e+10,-3.682000e+09,2.223600e+10,2.223600e+10,2.223600e+10,2.223600e+10,1.219000e+09,4.245000e+09,3.051600e+10,-2.107000e+09,-1.039600e+10,-958000000.0,-1.366800e+10,-3.539000e+09,2.310000e+08,-2.070400e+10,-2.540700e+10,-8.559000e+09,1.071620e+11,2.097000e+10,4.097000e+09,1.632310e+11,3.703100e+10,9.989900e+10,4.045700e+10,1.773870e+11,3.406180e+11,4.511100e+10,1.521400e+10,1.021610e+11,9.307800e+10,1.489260e+11,2.510870e+11,4.597200e+10,4.397700e+10,8.953100e+10,3.406180e+11,1.25911,True,False,False,False
13,AAPL,APPLE INC,Technology,Computer Hardware,2020-03-31,USD,2020.0,5/1/2020,4/29/2021,1.744040e+10,1.761877e+10,5.831300e+10,-3.594300e+10,2.237000e+10,-9.517000e+09,-4.952000e+09,-4.565000e+09,1.285300e+10,282000000.0,1.313500e+10,1.313500e+10,-1.886000e+09,1.124900e+10,1.124900e+10,1.124900e+10,1.124900e+10,1.278000e+09,-2.002000e+09,1.331100e+10,-1.853000e+09,1.140700e+10,-176000000.0,9.013000e+09,-3.375000e+09,-1.753000e+09,-1.814600e+10,-2.094000e+10,1.384000e+09,9.405100e+10,1.572200e+10,3.334000e+09,1.437530e+11,3.588900e+10,9.879300e+10,4.196500e+10,1.766470e+11,3.204000e+11,3.242100e+10,2.042100e+10,9.609400e+10,8.908600e+10,1.458810e+11,2.419750e+11,4.803200e+10,3.318200e+10,7.842500e+10,3.204000e+11,0.64500,False,True,False,False
14,AAPL,APPLE INC,Technology,Computer Hardware,2020-06-30,USD,2020.0,7/31/2020,7/28/2021,1.725029e+10,1.741916e+10,5.968500e+10,-3.700500e+10,2.268000e+10,-9.589000e+09,-4.831000e+09,-4.758000e+09,1.309100e+10,46000000.0,1.313700e+10,1.313700e+10,-1.884000e+09,1.125300e+10,1.125300e+10,1.125300e+10,1.125300e+10,2.696000e+09,-4.300000e+08,1.627100e+10,-1.565000e+09,-2.992000e+09,-339000000.0,-5.165000e+09,-3.656000e+09,-4.410000e+08,-1.589100e+10,-1.911600e+10,-8.010000e+09,9.302500e+10,1.788200e+10,3.978000e+09,1.400650e+11,3.568700e+10,1.005920e+11,4.100000e+10,1.772790e+11,3.173440e+11,3.532500e+10,1.867500e+10,9.531800e+10,9.404800e+10,1.497440e+11,2.450620e+11,4.869600e+10,2.413600e+10,7.228200e+10,3.173440e+11,0.65234,False,False,True,False
15,AAPL,APPLE INC,Technology,Computer Hardware,2020-09-30,USD,2020.0,10/30/2020,7/28/2021,1.705762e+10,1.725652e+10,6.469800e+10,-4.000900e+10,2.468900e+10,-9.914000e+09,-4.936000e+09,-4.978000e+09,1.477500e+10,126000000.0,1.490100e+10,1.490100e+10,-2.228000e+09,1.267300e+10,1.267300e+10,1.267300e+10,1.267300e+10,1.324000e+09,3.877000e+09,2.057600e+10,-1.784000e+09,7.434000e+09,-51000000.0,5.531000e+09,-3.511000e+09,4.462000e+09,-1.761700e+10,-2.135700e+10,4.750000e+09,9.094300e+10,1.612000e+10,4.061000e+09,1.437130e+11,3.676600e+10,1.008870e+11,4.252200e+10,1.801750e+11,3.238880e+11,4.229600e+10,1.376900e+10,1.053920e+11,9.866700e+10,1.531570e+11,2.585490e+11,5.077900e+10,1.496600e+10,6.533900e+10,3.238880e+11,0.74295,False,False,False,True
16,AAPL,APPLE INC,Technology,Computer Hardware,2020-12-31,USD,2021.0,1/28/2021,1/28/2022,1.693512e+10,1.711369e+10,1.114390e+11,-6.711100e+10,4.432800e+10,-1.079400e+10,-5.631000e+09,-5.163000e+09,3.353400e+10,45000000.0,3.357900e+10,3.357900e+10,-4.824000e+09,2.875500e+10,2.875500e+10,2.875500e+10,2.875500e+10,1.987000e+09,5.355000e+09,3.876300e+10,-3.500000e+09,-5.279000e+09,NaN,-8.584000e+09,-3.613000e+09,-9.780000e+08,-2.477500e+10,-3.224900e+10,-2.070000e+09,7.682600e+10,2.710100e+10,4.973000e+09,1.541060e+11,3.793300e+10,1.187450e+11,4.327000e+10,1.999480e+11,3.540540e+11,6.384600e+10,1.276200e+10,1.325070e+11,9.928100e+10,1.553230e+11,2.878300e+11,5.174400e+10,1.430100e+10,6.622400e+10,3.540540e+11,1.69795,True,False,False,False
17,AAPL,APPLE INC,Technology,Computer Hardware,2021-03-31,USD,2021.0,4/29/2021,1/28/2022,1.675348e+10,1.692916e+10,8.958400e+10,-5.150500e+10,3.807900e+10,-1.057600e+10,-5.314000e+09,-5.262000e+09,2.750300e+10,508000000.0,2.801100e+10,2.801100e+10,-4.381000e+09,2.363000e+10,2.363000e+10,2.363000e+10,2.363000e+10,1.333000e+09,-3.779000e+09,2.398100e+10,-2.269000e+09,-7.895000e+09,-9000000.0,-1.036800e+10,-3.447000e+09,1.042300e+10,-1.854800e+10,-1.132600e+10,2.287000e+09,6.983400e+10,1.850300e+10,5.219000e+09,1.214650e+11,3.781500e+10,1.345390e+11,4.333900e+10,2.156930e+11,3.371580e+11,4.012700e+10,1.300300e+10,1.063850e+11,1.086420e+11,1.615950e+11,2.679800e+11,5.420300e+10,1.526100e+10,6.917800e+10,3.371580e+11,1.41045,False,True,False,False
18,AAPL,APPLE INC,Technology,Computer Hardware,2021-06-30,USD,2021.0,7/28/2021,4/29/2022,1.684430e+10,1.702142e+10,8.143400e+10,-4.617900e+10,3.525500e+10,-1.112900e+10,-5.412000e+09,-5.717000e+09,2.412600e+10,243000000.0,2.436900e+10,2.436900e+10,-2.625000e+09,2.174400e+10,2.174400e+10,2.174400e+10,2.174400e+10,1.215000e+09,-4.697000e+09,2.109400e+10,-2.093000e+09,5.747000e+09,-4000000.0,3.572000e+09,-3.767000e+09,0.000000e+00,-2.290000e+10,-2.939600e+10,-4.730000e+09,6.169600e+10,1.747500e+10,5.178000e+09,1.144230e+11,3.861500e+10,1.319480e+11,4.485400e+10,2.154170e+11,3.298400e+11,4.040900e+10,1.603900e+10,1.077540e+11,1.057520e+11,1.578060e+11,2.655600e+11,5.498900e+10,9.233000e+09,6.428000e+10,3.298400e+11,1.29088,False,False,True,False
19,AAPL,APPLE INC,Technology,Computer Hardware,2021-09-30,USD,2021.0,10/29/2021,7/29/2022,1.639172e+10,1.651929e+10,8.336000e+10,-4.818600e+10,3.517400e+10,-1.138800e+10,-5.616000e+09,-5.772000e+09,2.378600e+10,-538000000.0,2.324800e+10,2.324800e+10,-2.697000e+09,2.055100e+10,2.055100e+10,2.055100e+10,2.055100e+10,-1.550000e+09,-1.790000e+09,2.020000e+10,-3.223000e+09,4.352000e+09,-20000000.0,8.350000e+08,-3.640000e+09,3.220000e+09,-1.974800e+10,-2.038200e+10,6.530000e+08,6.263900e+10,2.627800e+10,6.580000e+09,1.348360e+11,3.944000e+10,1.278770e+11,4.884900e+10,2.161660e+11,3.510020e+11,5.476300e+10,6.000000e+09,1.158680e+11,1.187190e+11,1.720440e+11,2.879120e+11,5.736500e+10,5.562000e+09,6.309000e+10,3.510020e+11,1.25374,False,False,False,True

In [ ]:
#now we try to perform feature engineering by creating a new feature that can capture the percentage change in quarterly revenue
#pct_change() calculates the change is percentage from last quarter to current quarter
#these new features might provide some insight to the model on how company performance changed form last quarter to this quarter

apple_df['Revenue' + 'change from last quarter']= apple_df['Revenue'].pct_change()
apple_df

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Research & Development,Operating Income (Loss),Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Income,Net Income (Common),Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic",Q1,Q2,Q3,Q4,Revenuechange from last quarter
0,AAPL,APPLE INC,Technology,Computer Hardware,2016-12-31,USD,2017.0,2/1/2017,2/2/2018,2.119464e+10,2.131198e+10,7.835100e+10,-4.817500e+10,3.017600e+10,-6.817000e+09,-3.946000e+09,-2.871000e+09,2.335900e+10,821000000.0,2.418000e+10,2.418000e+10,-6.289000e+09,1.789100e+10,1.789100e+10,1.789100e+10,1.789100e+10,2.708000e+09,3.648000e+09,2.723400e+10,-3.420000e+09,-1.558100e+10,-17000000.0,-1.912200e+10,-3.130000e+09,2.385000e+09,-1.085100e+10,-1.222500e+10,-4.113000e+09,6.045200e+10,1.405700e+10,2.712000e+09,1.033320e+11,2.651000e+10,1.856380e+11,1.566100e+10,2.278090e+11,3.311410e+11,6.224900e+10,1.399200e+10,8.413000e+10,7.355700e+10,1.146210e+11,1.987510e+11,3.214400e+10,1.000010e+11,1.323900e+11,3.311410e+11,0.84413,True,False,False,False,NaN
1,AAPL,APPLE INC,Technology,Computer Hardware,2017-03-31,USD,2017.0,5/3/2017,5/2/2018,2.090316e+10,2.104675e+10,5.289600e+10,-3.230500e+10,2.059100e+10,-6.494000e+09,-3.718000e+09,-2.776000e+09,1.409700e+10,587000000.0,1.468400e+10,1.468400e+10,-3.655000e+09,1.102900e+10,1.102900e+10,1.102900e+10,1.102900e+10,2.587000e+09,-3.378000e+09,1.257000e+10,-2.889000e+09,-1.135700e+10,-50000000.0,-1.420200e+10,-3.004000e+09,1.046900e+10,-6.888000e+09,4.180000e+08,-1.214000e+09,6.710100e+10,1.157900e+10,2.910000e+09,1.019900e+11,2.716300e+10,1.897400e+11,1.563900e+10,2.325420e+11,3.345320e+11,5.166900e+10,1.399100e+10,7.334200e+10,8.453100e+10,1.271080e+11,2.004500e+11,3.357900e+10,1.009250e+11,1.340820e+11,3.345320e+11,0.52762,False,True,False,False,-0.324884
2,AAPL,APPLE INC,Technology,Computer Hardware,2017-06-30,USD,2017.0,8/2/2017,8/1/2018,2.078035e+10,2.093400e+10,4.540800e+10,-2.792000e+10,1.748800e+10,-6.720000e+09,-3.783000e+09,-2.937000e+09,1.076800e+10,540000000.0,1.130800e+10,1.130800e+10,-2.591000e+09,8.717000e+09,8.717000e+09,8.717000e+09,8.717000e+09,3.135000e+09,-5.534000e+09,8.672000e+09,-2.277000e+09,-8.360000e+08,-181000000.0,-3.180000e+09,-3.365000e+09,9.237000e+09,-7.092000e+09,-2.078000e+09,3.414000e+09,7.675900e+10,1.239900e+10,3.146000e+09,1.128750e+11,2.928600e+10,1.847570e+11,1.825500e+10,2.322980e+11,3.451730e+11,5.521900e+10,1.847500e+10,8.130200e+10,8.986400e+10,1.314460e+11,2.127480e+11,3.444500e+10,9.852500e+10,1.324250e+11,3.451730e+11,0.41948,False,False,True,False,-0.141561
3,AAPL,APPLE INC,Technology,Computer Hardware,2017-09-30,USD,2017.0,11/3/2017,10/31/2019,2.059771e+10,2.073434e+10,5.257900e+10,-3.264800e+10,1.993100e+10,-6.811000e+09,-3.814000e+09,-2.997000e+09,1.312000e+10,797000000.0,1.391700e+10,1.391700e+10,-3.203000e+09,1.071400e+10,1.071400e+10,1.071400e+10,1.071400e+10,2.376000e+09,1.750000e+08,1.574900e+10,-3.865000e+09,-5.768000e+09,-81000000.0,-9.942000e+09,-3.270000e+09,6.923000e+09,-7.514000e+09,-4.089000e+09,1.718000e+09,7.418100e+10,1.787400e+10,4.855000e+09,1.286450e+11,3.378300e+10,1.947140e+11,1.817700e+10,2.466740e+11,3.753190e+11,4.424200e+10,1.847300e+10,1.008140e+11,9.720700e+10,1.404580e+11,2.412720e+11,3.586700e+10,9.833000e+10,1.340470e+11,3.753190e+11,0.52015,False,False,False,True,0.157924
4,AAPL,APPLE INC,Technology,Computer Hardware,2017-12-31,USD,2018.0,2/2/2018,1/30/2019,2.045151e+10,2.063115e+10,8.829300e+10,-5.438100e+10,3.391200e+10,-7.638000e+09,-4.231000e+09,-3.407000e+09,2.627400e+10,756000000.0,2.703000e+10,2.703000e+10,-6.965000e+09,2.006500e+10,2.006500e+10,2.006500e+10,2.006500e+10,-3.244100e+10,3.792400e+10,2.829300e+10,-2.810000e+09,-1.056400e+10,-173000000.0,-1.359000e+10,-3.339000e+09,6.971000e+09,-1.009500e+10,-7.501000e+09,7.202000e+09,7.715300e+10,2.344000e+10,4.421000e+09,1.438100e+11,3.367900e+10,2.079440e+11,2.136100e+10,2.629840e+11,4.067940e+11,8.926600e+10,1.847800e+10,1.157880e+11,1.039220e+11,1.508070e+11,2.665950e+11,3.644700e+10,1.045930e+11,1.401990e+11,4.067940e+11,0.98110,True,False,False,False,0.679245
5,AAPL,APPLE INC,Technology,Computer Hardware,2018-03-31,USD,2018.0,5/2/2018,5/1/2019,2.009951e+10,2.027397e+10,6.113700e+10,-3.771500e+10,2.342200e+10,-7.528000e+09,-4.150000e+09,-3.378000e+09,1.589400e+10,274000000.0,1.616800e+10,1.616800e+10,-2.346000e+09,1.382200e+10,1.382200e+10,1.382200e+10,1.382200e+10,8.500000e+08,-2.281000e+09,1.513000e+10,-4.195000e+09,3.277800e+10,-132000000.0,2.871000e+10,-3.190000e+09,-5.020000e+08,-2.242900e+10,-2.627200e+10,1.756800e+10,8.794000e+10,1.432400e+10,7.662000e+09,1.300530e+11,3.507700e+10,1.792860e+11,2.308600e+10,2.374490e+11,3.675020e+11,6.106700e+10,2.047800e+10,8.932000e+10,1.013620e+11,1.513040e+11,2.406240e+11,3.804400e+10,9.189800e+10,1.268780e+11,3.675020e+11,0.68768,False,True,False,False,-0.307567
6,AAPL,APPLE INC,Technology,Computer Hardware,2018-06-30,USD,2018.0,8/1/2018,7/31/2019,1.952867e+10,1.970644e+10,5.326500e+10,-3.284400e+10,2.042100e+10,-7.809000e+09,-4.108000e+09,-3.701000e+09,1.261200e+10,672000000.0,1.328400e+10,1.328400e+10,-1.765000e+09,1.151900e+10,1.151900e+10,1.151900e+10,1.151900e+10,2.477000e+09,-2.173000e+09,1.448800e+10,-3.267000e+09,8.079000e+09,-126000000.0,3.947000e+09,-3.653000e+09,-6.010000e+09,-2.078200e+10,-3.152300e+10,-1.308800e+10,7.097000e+10,1.410400e+10,5.936000e+09,1.157610e+11,3.811700e+10,1.727730e+11,2.254600e+10,2.334360e+11,3.491970e+11,6.367300e+10,1.747200e+10,8.854800e+10,9.712800e+10,1.457000e+11,2.342480e+11,3.862400e+10,7.943600e+10,1.149490e+11,3.491970e+11,0.58985,False,False,True,False,-0.128760
7,AAPL,APPLE INC,Technology,Computer Hardware,2018-09-30,USD,2018.0,11/5/2018,10/30/2020,1.920635e+10,1.939019e+10,6.290000e+10,-3.881600e+10,2.408400e+10,-7.966000e+09,-4.216000e+09,-3.750000e+09,1.611800e+10,303000000.0,1.642100e+10,1.642100e+10,-2.296000e+09,1.412500e+10,1.412500e+10,1.412500e+10,1.412500e+10,1.864000e+09,7.800000e+08,1.952300e+10,-3.041000e+09,5.520000e+08,-290000000.0,-3.001000e+09,-3.530000e+09,-2.700000e+07,-1.876300e+10,-2.258000e+10,-6.058000e+09,6.630100e+10,2.318600e+10,3.956000e+09,1.313390e+11,4.130400e+10,1.707990e+11,2.228300e+10,2.343860e+11,3.657250e+11,5.588800e+10,2.074800e+10,1.159290e+11,9.373500e+10,1.426490e+11,2.585780e+11,4.020100e+10,7.040000e+10,1.071470e+11,3.657250e+11,0.73543,False,False,False,True,0.180888
8,AAPL,APPLE INC,Technology,Computer Hardware,2018-12-31,USD,2019.0,1/30/2019,1/29/2020,1.894328e+10,1.909301e+10,8.431000e+10,-5.227900e+10,3.203100e+10,-8.685000e+09,-4.783000e+09,-3.902000e+09,2.334600e+10,560000000.0,2.390600e+10,2.390600e+10,-3.941000e+09,1.996500e+10,1.996500e+10,1.996500e+10,1.996500e+10,1.612000e+09,1.718000e+09,2.669000e+10,-3.355000e+09,9.422000e+09,-167000000.0,5.844000e+09,-3.568000e+09,6.000000e+06,-8.796000e+09,-1.367600e+10,1.885800e+10,8.642700e+10,1.807700e+10,4.988000e+09,1.408280e+11,3.959700e+10,1.586080e+11,3.468600e+10,2.328910e+11,3.737190e+11,4.429300e+10,2.174100e+10,1.082830e+11,9.298900e+10,1.475440e+11,2.558270e+11,4.097000e+10,8.051000e+10,1.178920e+11,3.737190e+11,1.05394,True,False,False,False,0.340382
9,AAPL,APPLE INC,Technology,Computer Hardware,2019-03-31,USD,2019.0,5/1/2019,5/1/2020,1.869628e+10,1.880258e+10,5.801500e+10,-3.619400e+10,2.182100e+10,-8.406000e+09,-4.458000e+09,-3.948000e+09,1.341500e+10,378000000.0,1.379300e+10,1.379300e+10,-2.232000e+09,1.156100e+10,1.156100e+10,1.156100e+10,1.156100e+10,1.337000e+09,-4.783000e+09,1.115500e+10,-2.363000e+09,1.574900e+10,-124000000.0,1.334800e+10,-3.443000e+09,-2.542000e+09,-2.331200e+10,-2.945700e+10,-4.954000e+09,8.009200e+10,1.508500e+10,4.884000e+09,1.233460e+11,3.874600e+10,1.453190e+11,3.458700e+10,2.186520e+11,3.419980e+11,3.044300e+10,2.242900e+10,9.377200e+10,9.020100e+10,1.423660e+11,2.361380e+11,4.280100e+10,6.455800e+10,1.058600e+11,3.419980e+11,0.61836,False,True,False,False,-0.311885
10,AAPL,APPLE INC,Technology,Computer Hardware,2019-06-30,USD,2019.0,7/31/2019,7/31/2020,1.828254e+10,1.840552e+10,5.380900e+10,-3.358200e+10,2.022700e+10,-8.683000e+09,-4.426000e+09,-4.257000e+09,1.154400e+10,367000000.0,1.191100e+10,1.191100e+10,-1.867000e+09,1.004400e+10,1.004400e+10,1.004400e+10,1.004400e+10,1.582000e+09,-2.923000e+09,1.163600e+10,-2.000000e+09,3.012000e+10,-320000000.0,2.750200e+10,-3.629000e+09,-4.990000e+09,-1.695400e+10,-2.680400e+10,1.233400e+10,9.461400e+10,1.414800e+10,3.355000e+09,1.349730e+11,3.763600e+10,1.159960e+11,3.363400e+10,1.872660e+11,3.222390e+11,2.911500e+10,2.348200e+10,8.970400e+10,8.493600e+10,1.360790e+11,2.257830e+11,4.337100e+10,5.372400e+10,9.645600e+10,3.222390e+11,0.54938,False,False,True,False,-0.072498
11,AAPL,APPLE INC,Technology,Computer Hardware,2019-09-30,USD,2019.0,10/31/2019,10/29/2021,1.796324e+10,1.808150e+10,6.404000e+10,-3.972700e+10,2.431300e+10,-8.688000e+09,-4.578000e+09,-4.110000e+09,1.562500e+10,502000000.0,1.612700e+10,1.612700e+10,-2.441000e+09,1.368600e+10,1.368600e+10,1.368600e+10,1.368600e+10,5.450000e+08,2.500000e+09,1.991000e+10,-2.777000e+09,2.802000e+09,-13000000.0,-7.980000e+08,-3.479000e+09,-2.930000e+08,-1.705400e+10,-2.103900e+10,-1.927000e+09,1.005570e+11,2.292600e+10,4.106000e+09,1.628190e+11,3.737800e+10,1.053410e+11,3.297800e+10,1.756970e+11,3.385160e+11,4.623600e+10,1.624000e+10,1.057180e+11,9.180700e+10,1.423100e+11,2.480280e+11,4.517400e+10,4.589800e+10,9.048800e+10,3.385160e+11,0.76189,False,False,False,True,0.190135
12,AAPL,APPLE INC,Technology,Computer Hardware,2019-12-31,USD,2020.0,1/29/2020,1/28/2021,1.766016e+10,1.781842e+10,9.181900e+10,-5.660200e+10,3.521700e+10,-9.648000e+09,-5.197000e+09,-4.451000e+09,2.556900e+10,349000000.0,2.591800e+10,2.591800e+10,-3.682000e+09,2.223600e+10,2.223600e+10,2.223600e+10,2.223600e+10,1.219000e+09,4.245000e+09,3.051600e+10,-2.107000e+09,-1.039600e+10,-958000000.0,-1.366800e+10,-3.539000e+09,2.310000e+08,-2.070400e+10,-2.540700e+10,-8.559000e+09,1.071620e+11,2.097000e+10,4.097000e+09,1.632310e+11,3.703100e+10,9.989900e+10,4.045700e+10,1.773870e+11,3.406180e+11,4.511100e+10,1.521400e+10,1.021610e+11,9.307800e+10,1.489260e+11,2.510870e+11,4.597200e+10,4.397700e+10,8.953100e+10,3.406180e+11,1.25911,True,False,False,False,0.433776
13,AAPL,APPLE INC,Technology,Computer Hardware,2020-03-31,USD,2020.0,5/1/2020,4/29/2021,1.744040e+10,1.761877e+10,5.831300e+10,-3.594300e+10,2.237000e+10,-9.517000e+09,-4.952000e+09,-4.565000e+09,1.285300e+10,282000000.0,1.313500e+10,1.313500e+10,-1.886000e+09,1.124900e+10,1.124900e+10,1.124900e+10,1.124900e+10,1.278000e+09,-2.002000e+09,1.331100e+10,-1.853000e+09,1.140700e+10,-176000000.0,9.013000e+09,-3.375000e+09,-1.753000e+09,-1.814600e+10,-2.094000e+10,1.384000e+09,9.405100e+10,1.572200e+10,3.334000e+09,1.437530e+11,3.588900e+10,9.879300e+10,4.196500e+10,1.766470e+11,3.204000e+11,3.242100e+10,2.042100e+10,9.609400e+10,8.908600e+10,1.458810e+11,2.419750e+11,4.803200e+10,3.318200e+10,7.842500e+10,3.204000e+11,0.64500,False,True,False,False,-0.364914
14,AAPL,APPLE INC,Technology,Computer Hardware,2020-06-30,USD,2020.0,7/31/2020,7/28/2021,1.725029e+10,1.741916e+10,5.968500e+10,-3.700500e+10,2.268000e+10,-9.589000e+09,-4.831000e+09,-4.758000e+09,1.309100e+10,46000000.0,1.313700e+10,1.313700e+10,-1.884000e+09,1.125300e+10,1.125300e+10,1.125300e+10,1.125300e+10,2.696000e+09,-4.300000e+08,1.627100e+10,-1.565000e+09,-2.992000e+09,-339000000.0,-5.165000e+09,-3.656000e+09,-4.410000e+08,-1.589100e+10,-1.911600e+10,-8.010000e+09,9.302500e+10,1.788200e+10,3.978000e+09,1.400650e+11,3.568700e+10,1.005920e+11,4.100000e+10,1.772790e+11,3.173440e+11,3.532500e+10,1.867500e+10,9.531800e+10,9.404800e+10,1.497440e+11,2.450620e+11,4.869600e+10,2.413600e+10,7.228200e+10,3.173440e+11,0.65234,False,False,True,False,0.023528
15,AAPL,APPLE INC,Technology,Computer Hardware,2020-09-30,USD,2020.0,10/30/2020,7/28/2021,1.705762e+10,1.725652e+10,6.469800e+10,-4.000900e+10,2.468900e+10,-9.914000e+09,-4.936000e+09,-4.978000e+09,1.477500e+10,126000000.0,1.490100e+10,1.490100e+10,-2.228000e+09,1.267300e+10,1.267300e+10,1.267300e+10,1.267300e+10,1.324000e+09,3.877000e+09,2.057600e+10,-1.784000e+09,7.434000e+09,-51000000.0,5.531000e+09,-3.511000e+09,4.462000e+09,-1.761700e+10,-2.135700e+10,4.750000e+09,9.094300e+10,1.612000e+10,4.061000e+09,1.437130e+11,3.676600e+10,1.008870e+11,4.252200e+10,1.801750e+11,3.238880e+11,4.229600e+10,1.376900e+10,1.053920e+11,9.866700e+10,1.531570e+11,2.585490e+11,5.077900e+10,1.496600e+10,6.533900e+10,3.238880e+11,0.74295,False,False,False,True,0.083991
16,AAPL,APPLE INC,Technology,Computer Hardware,2020-12-31,USD,2021.0,1/28/2021,1/28/2022,1.693512e+10,1.711369e+10,1.114390e+11,-6.711100e+10,4.432800e+10,-1.079400e+10,-5.631000e+09,-5.163000e+09,3.353400e+10,45000000.0,3.357900e+10,3.357900e+10,-4.824000e+09,2.875500e+10,2.875500e+10,2.875500e+10,2.875500e+10,1.987000e+09,5.355000e+09,3.876300e+10,-3.500000e+09,-5.279000e+09,NaN,-8.584000e+09,-3.613000e+09,-9.780000e+08,-2.477500e+10,-3.224900e+10,-2.070000e+09,7.682600e+10,2.710100e+10,4.973000e+09,1.541060e+11,3.793300e+10,1.187450e+11,4.327000e+10,1.999480e+11,3.540540e+11,6.384600e+10,1.276200e+10,1.325070e+11,9.928100e+10,1.553230e+11,2.878300e+11,5.174400e+10,1.430100e+10,6.622400e+10,3.540540e+11,1.69795,True,False,False,False,0.722449
17,AAPL,APPLE INC,Technology,Computer Hardware,2021-03-31,USD,2021.0,4/29/2021,1/28/2022,1.675348e+10,1.692916e+10,8.958400e+10,-5.150500e+10,3.807900e+10,-1.057600e+10,-5.314000e+09,-5.262000e+09,2.750300e+10,508000000.0,2.801100e+10,2.801100e+10,-4.381000e+09,2.363000e+10,2.363000e+10,2.363000e+10,2.363000e+10,1.333000e+09,-3.779000e+09,2.398100e+10,-2.269000e+09,-7.895000e+09,-9000000.0,-1.036800e+10,-3.447000e+09,1.042300e+10,-1.854800e+10,-1.132600e+10,2.287000e+09,6.983400e+10,1.850300e+10,5.219000e+09,1.214650e+11,3.781500e+10,1.345390e+11,4.333900e+10,2.156930e+11,3.371580e+11,4.012700e+10,1.300300e+10,1.063850e+11,1.086420e+11,1.615950e+11,2.679800e+11,5.420300e+10,1.526100e+10,6.917800e+10,3.371580e+11,1.41045,False,True,False,False,-0.196116
18,AAPL,APPLE INC,Technology,Computer Hardware,2021-06-30,USD,2021.0,7/28/2021,4/29/2022,1.684430e+10,1.702142e+10,8.143400e+10,-4.617900e+10,3.525500e+10,-1.112900e+10,-5.412000e+09,-5.717000e+09,2.412600e+10,243000000.0,2.436900e+10,2.436900e+10,-2.625000e+09,2.174400e+10,2.174400e+10,2.174400e+10,2.174400e+10,1.215000e+09,-4.697000e+09,2.109400e+10,-2.093000e+09,5.747000e+09,-4000000.0,3.572000e+09,-3.767000e+09,0.000000e+00,-2.290000e+10,-2.939600e+10,-4.730000e+09,6.169600e+10,1.747500e+10,5.178000e+09,1.144230e+11,3.861500e+10,1.319480e+11,4.485400e+10,2.154170e+11,3.298400e+11,4.040900e+10,1.603900e+10,1.077540e+11,1.057520e+11,1.578060e+11,2.655600e+11,5.498900e+10,9.233000e+09,6.428000e+10,3.298400e+11,1.29088,False,False,True,False,-0.090976
19,AAPL,APPLE INC,Technology,Computer Hardware,2021-09-30,USD,2021.0,10/29/2021,7/29/2022,1.639172e+10,1.651929e+10,8.336000e+10,-4.818600e+10,3.517400e+10,-1.138800e+10,-5.616000e+09,-5.772000e+09,2.378600e+10,-538000000.0,2.324800e+10,2.324800e+10,-2.697000e+09,2.055100e+10,2.055100e+10,2.055100e+10,2.055100e+10,-1.550000e+09,-1.790000e+09,2.020000e+10,-3.223000e+09,4.352000e+09,-20000000.0,8.350000e+08,-3.640000e+09,3.220000e+09,-1.974800e+10,-2.038200e+10,6.530000e+08,6.263900e+10,2.627800e+10,6.580000e+09,1.348360e+11,3.944000e+10,1.278770e+11,4.884900e+10,2.161660e+11,3.510020e+11,5.476300e+10,6.000000e+09,1.158680e+11,1.187190e+11,1.720440e+11,2.879120e+11,5.736500e+10,5.562000e+09,6.309000e+10,3.510020e+11,1.25374,False,False,False,True,0.023651

In [149]:
#now we can repeat the same process using additional features and by performing feature engineering by creating new features that capture the change in the net income, operating income, etc

features_to_get_delta = ['Shares (Basic)',
                         'Shares (Diluted)',
                         'Operating Income (Loss)',
                         'Net Income',
                         'Total Liabilities & Equity']
#pct_change() using for syntax
for feature in features_to_get_delta:
    apple_df[feature + 'change from last quarter']= apple_df[feature].pct_change()
apple_df

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Research & Development,Operating Income (Loss),Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Income,Net Income (Common),Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic",Q1,Q2,Q3,Q4,Revenuechange from last quarter,Shares (Basic)change from last quarter,Shares (Diluted)change from last quarter,Operating Income (Loss)change from last quarter,Net Incomechange from last quarter,Total Liabilities & Equitychange from last quarter
0,AAPL,APPLE INC,Technology,Computer Hardware,2016-12-31,USD,2017.0,2/1/2017,2/2/2018,2.119464e+10,2.131198e+10,7.835100e+10,-4.817500e+10,3.017600e+10,-6.817000e+09,-3.946000e+09,-2.871000e+09,2.335900e+10,821000000.0,2.418000e+10,2.418000e+10,-6.289000e+09,1.789100e+10,1.789100e+10,1.789100e+10,1.789100e+10,2.708000e+09,3.648000e+09,2.723400e+10,-3.420000e+09,-1.558100e+10,-17000000.0,-1.912200e+10,-3.130000e+09,2.385000e+09,-1.085100e+10,-1.222500e+10,-4.113000e+09,6.045200e+10,1.405700e+10,2.712000e+09,1.033320e+11,2.651000e+10,1.856380e+11,1.566100e+10,2.278090e+11,3.311410e+11,6.224900e+10,1.399200e+10,8.413000e+10,7.355700e+10,1.146210e+11,1.987510e+11,3.214400e+10,1.000010e+11,1.323900e+11,3.311410e+11,0.84413,True,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
1,AAPL,APPLE INC,Technology,Computer Hardware,2017-03-31,USD,2017.0,5/3/2017,5/2/2018,2.090316e+10,2.104675e+10,5.289600e+10,-3.230500e+10,2.059100e+10,-6.494000e+09,-3.718000e+09,-2.776000e+09,1.409700e+10,587000000.0,1.468400e+10,1.468400e+10,-3.655000e+09,1.102900e+10,1.102900e+10,1.102900e+10,1.102900e+10,2.587000e+09,-3.378000e+09,1.257000e+10,-2.889000e+09,-1.135700e+10,-50000000.0,-1.420200e+10,-3.004000e+09,1.046900e+10,-6.888000e+09,4.180000e+08,-1.214000e+09,6.710100e+10,1.157900e+10,2.910000e+09,1.019900e+11,2.716300e+10,1.897400e+11,1.563900e+10,2.325420e+11,3.345320e+11,5.166900e+10,1.399100e+10,7.334200e+10,8.453100e+10,1.271080e+11,2.004500e+11,3.357900e+10,1.009250e+11,1.340820e+11,3.345320e+11,0.52762,False,True,False,False,-0.324884,-0.013753,-0.012445,-0.396507,-0.383545,0.010240
2,AAPL,APPLE INC,Technology,Computer Hardware,2017-06-30,USD,2017.0,8/2/2017,8/1/2018,2.078035e+10,2.093400e+10,4.540800e+10,-2.792000e+10,1.748800e+10,-6.720000e+09,-3.783000e+09,-2.937000e+09,1.076800e+10,540000000.0,1.130800e+10,1.130800e+10,-2.591000e+09,8.717000e+09,8.717000e+09,8.717000e+09,8.717000e+09,3.135000e+09,-5.534000e+09,8.672000e+09,-2.277000e+09,-8.360000e+08,-181000000.0,-3.180000e+09,-3.365000e+09,9.237000e+09,-7.092000e+09,-2.078000e+09,3.414000e+09,7.675900e+10,1.239900e+10,3.146000e+09,1.128750e+11,2.928600e+10,1.847570e+11,1.825500e+10,2.322980e+11,3.451730e+11,5.521900e+10,1.847500e+10,8.130200e+10,8.986400e+10,1.314460e+11,2.127480e+11,3.444500e+10,9.852500e+10,1.324250e+11,3.451730e+11,0.41948,False,False,True,False,-0.141561,-0.005875,-0.005357,-0.236150,-0.209629,0.031809
3,AAPL,APPLE INC,Technology,Computer Hardware,2017-09-30,USD,2017.0,11/3/2017,10/31/2019,2.059771e+10,2.073434e+10,5.257900e+10,-3.264800e+10,1.993100e+10,-6.811000e+09,-3.814000e+09,-2.997000e+09,1.312000e+10,797000000.0,1.391700e+10,1.391700e+10,-3.203000e+09,1.071400e+10,1.071400e+10,1.071400e+10,1.071400e+10,2.376000e+09,1.750000e+08,1.574900e+10,-3.865000e+09,-5.768000e+09,-81000000.0,-9.942000e+09,-3.270000e+09,6.923000e+09,-7.514000e+09,-4.089000e+09,1.718000e+09,7.418100e+10,1.787400e+10,4.855000e+09,1.286450e+11,3.378300e+10,1.947140e+11,1.817700e+10,2.466740e+11,3.753190e+11,4.424200e+10,1.847300e+10,1.008140e+11,9.720700e+10,1.404580e+11,2.412720e+11,3.586700e+10,9.833000e+10,1.340470e+11,3.753190e+11,0.52015,False,False,False,True,0.157924,-0.008789,-0.009537,0.218425,0.229093,0.087336
4,AAPL,APPLE INC,Technology,Computer Hardware,2017-12-31,USD,2018.0,2/2/2018,1/30/2019,2.045151e+10,2.063115e+10,8.829300e+10,-5.438100e+10,3.391200e+10,-7.638000e+09,-4.231000e+09,-3.407000e+09,2.627400e+10,756000000.0,2.703000e+10,2.703000e+10,-6.965000e+09,2.006500e+10,2.006500e+10,2.006500e+10,2.006500e+10,-3.244100e+10,3.792400e+10,2.829300e+10,-2.810000e+09,-1.056400e+10,-173000000.0,-1.359000e+10,-3.339000e+09,6.971000e+09,-1.009500e+10,-7.501000e+09,7.202000e+09,7.715300e+10,2.344000e+10,4.421000e+09,1.438100e+11,3.367900e+10,2.079440e+11,2.136100e+10,2.629840e+11,4.067940e+11,8.926600e+10,1.847800e+10,1.157880e+11,1.039220e+11,1.508070e+11,2.665950e+11,3.644700e+10,1.045930e+11,1.401990e+11,4.067940e+11,0.98110,True,False,False,False,0.679245,-0.007098,-0.004977,1.002591,0.872783,0.083862
5,AAPL,APPLE INC,Technology,Computer Hardware,2018-03-31,USD,2018.0,5/2/2018,5/1/2019,2.009951e+10,2.027397e+10,6.113700e+10,-3.771500e+10,2.342200e+10,-7.528000e+09,-4.150000e+09,-3.378000e+09,1.589400e+10,274000000.0,1.616800e+10,1.616800e+10,-2.346000e+09,1.382200e+10,1.382200e+10,1.382200e+10,1.382200e+10,8.500000e+08,-2.281000e+09,1.513000e+10,-4.195000e+09,3.277800e+10,-132000000.0,2.871000e+10,-3.190000e+09,-5.020000e+08,-2.242900e+10,-2.627200e+10,1.756800e+10,8.794000e+10,1.432400e+10,7.662000e+09,1.300530e+11,3.507700e+10,1.792860e+11,2.308600e+10,2.374490e+11,3.675020e+11,6.106700e+10,2.047800e+10,8.932000e+10,1.013620e+11,1.513040e+11,2.406240e+11,3.804400e+10,9.189800e+10,1.268780e+11,3.675020e+11,0.68768,False,True,False,False,-0.307567,-0.017211,-0.017312,-0.395067,-0.311139,-0.096589
6,AAPL,APPLE INC,Technology,Computer Hardware,2018-06-30,USD,2018.0,8/1/2018,7/31/2019,1.952867e+10,1.970644e+10,5.326500e+10,-3.284400e+10,2.042100e+10,-7.809000e+09,-4.108000e+09,-3.701000e+09,1.261200e+10,672000000.0,1.328400e+10,1.328400e+10,-1.765000e+09,1.151900e+10,1.151900e+10,1.151900e+10,1.151900e+10,2.477000e+09,-2.173000e+09,1.448800e+10,-3.267000e+09,8.079000e+09,-126000000.0,3.947000e+09,-3.653000e+09,-6.010000e+09,-2.078200e+10,-3.152300e+10,-1.308800e+10,7.097000e+10,1.410400e+10,5.936000e+09,1.157610e+11,3.811700e+10,1.727730e+11,2.254600e+10,2.334360e+11,3.491970e+11,6.367300e+10,1.747200e+10,8.854800e+10,9.712800e+10,1.457000e+11,2.342480e+11,3.862400e+10,7.943600e+10,1.149490e+11,3.491970e+11,0.58985,False,False,True,False,-0.128760,-0.028401,-0.027993,-0.206493,-0.166618,-0.049809
7,AAPL,APPLE INC,Technology,Computer Hardware,2018-09-30,USD,2018.0,11/5/2018,10/30/2020,1.920635e+10,1.939019e+10,6.290000e+10,-3.881600e+10,2.408400e+10,-7.966000e+09,-4.216000e+09,-3.750000e+09,1.611800e+10,303000000.0,1.642100e+10,1.642100e+10,-2.296000e+09,1.412500e+10,1.412500e+10,1.412500e+10,1.412500e+10,1.864000e+09,7.800000e+08,1.952300e+10,-3.041000e+09,5.520000e+08,-290000000.0,-3.001000e+09,-3.530000e+09,-2.700000e+07,-1.876300e+10,-2.258000e+10,-6.058000e+09,6.630100e+10,2.318600e+10,3.956000e+09,1.313390e+11,4.130400e+10,1.707990e+11,2.228300e+10,2.343860e+11,3.657250e+11,5.588800e+10,2.074800e+10,1.159290e+11,9.373500e+10,1.426490e+11,2.585780e+11,4.020100e+10,7.040000e+10,1.071470e+11,3.657250e+11,0.73543,False,False,False,True,0.180888,-0.016505,-0.016048,0.277989,0.226235,0.047331
8,AAPL,APPLE INC,Technology,Computer Hardware,2018-12-31,USD,2019.0,1/30/2019,1/29/2020,1.894328e+10,1.909301e+10,8.431000e+10,-5.227900e+10,3.203100e+10,-8.685000e+09,-4.783000e+09,-3.902000e+09,2.334600e+10,560000000.0,2.390600e+10,2.390600e+10,-3.941000e+09,1.996500e+10,1.996500e+10,1.996500e+10,1.996500e+10,1.612000e+09,1.718000e+09,2.669000e+10,-3.355000e+09,9.422000e+09,-167000000.0,5.844000e+09,-3.568000e+09,6.000000e+06,-8.796000e+09,-1.367600e+10,1.885800e+10,8.642700e+10,1.807700e+10,4.988000e+09,1.408280e+11,3.959700e+10,1.586080e+11,3.468600e+10,2.328910e+11,3.737190e+11,4.429300e+10,2.174100e+10,1.082830e+11,9.298900e+10,1.475440e+11,2.558270e+11,4.097000e+10,8.051000e+10,1.178920e+11,3.737190e+11,1.05394,True,False,False,False,0.340382,-0.013697,-0.015326,0.448443,0.413451,0.021858
9,AAPL,APPLE INC,Technology,Computer Hardware,2019-03-31,USD,2019.0,5/1/2019,5/1/2020,1.869628e+10,1.880258e+10,5.801500e+10,-3.619400e+10,2.182100e+10,-8.406000e+09,-4.458000e+09,-3.948000e+09,1.341500e+10,378000000.0,1.379300e+10,1.379300e+10,-2.232000e+09,1.156100e+10,1.156100e+10,1.156100e+10,1.156100e+10,1.337000e+09,-4.783000e+09,1.115500e+10,-2.363000e+09,1.574900e+10,-124000000.0,1.334800e+10,-3.443000e+09,-2.542000e+09,-2.331200e+10,-2.945700e+10,-4.954000e+09,8.009200e+10,1.508500e+10,4.884000e+09,1.233460e+11,3.874600e+10,1.453190e+11,3.458700e+10,2.186520e+11,3.419980e+11,3.044300e+10,2.242900e+10,9.377200e+10,9.020100e+10,1.423660e+11,2.361380e+11,4.280100e+10,6.455800e+10,1.058600e+11,3.419980e+11,0.61836,False,True,False,False,-0.311885,-0.013039,-0.015211,-0.425383,-0.420937,-0.084879
10,AAPL,APPLE INC,Technology,Computer Hardware,2019-06-30,USD,2019.0,7/31/2019,7/31/2020,1.828254e+10,1.840552e+10,5.380900e+10,-3.358200e+10,2.022700e+10,-8.683000e+09,-4.426000e+09,-4.257000e+09,1.154400e+10,367000000.0,1.191100e+10,1.191100e+10,-1.867000e+09,1.004400e+10,1.004400e+10,1.004400e+10,1.004400e+10,1.582000e+09,-2.923000e+09,1.163600e+10,-2.000000e+09,3.012000e+10,-320000000.0,2.750200e+10,-3.629000e+09,-4.990000e+09,-1.695400e+10,-2.680400e+10,1.233400e+10,9.461400e+10,1.414800e+10,3.355000e+09,1.349730e+11,3.763600e+10,1.159960e+11,3.363400e+10,1.872660e+11,3.222390e+11,2.911500e+10,2.348200e+10,8.970400e+10,8.493600e+10,1.360790e+11,2.257830e+11,4.337100e+10,5.372400e+10,9.645600e+10,3.222390e+11,0.54938,False,False,True,False,-0.072498,-0.022130,-0.021118,-0.139471,-0.131217,-0.057775
11,AAPL,APPLE INC,Technology,Computer Hardware,2019-09-30,USD,2019.0,10/31/2019,10/29/2021,1.796324e+10,1.808150e+10,6.404000e+10,-3.972700e+10,2.431300e+10,-8.688000e+09,-4.578000e+09,-4.110000e+09,1.562500e+10,502000000.0,1.612700e+10,1.612700e+10,-2.441000e+09,1.368600e+10,1.368600e+10,1.368600e+10,1.368600e+10,5.450000e+08,2.500000e+09,1.991000e+10,-2.777000e+09,2.802000e+09,-13000000.0,-7.980000e+08,-3.479000e+09,-2.930000e+08,-1.705400e+10,-2.103900e+10,-1.927000e+09,1.005570e+11,2.292600e+10,4.106000e+09,1.628190e+11,3.737800e+10,1.053410e+11,3.297800e+10,1.756970e+11,3.385160e+11,4.623600e+10,1.624000e+10,1.057180e+11,9.180700e+10,1.423100e+11,2.480280e+11,4.517400e+10,4.589800e+10,9.048800e+10,3.385160e+11,0.76189,False,False,False,True,0.190135,-0.017464,-0.017604,0.353517,0.362605,0.050512
12,AAPL,APPLE INC,Technology,Computer Hardware,2019-12-31,USD,2020.0,1/29/2020,1/28/2021,1.766016e+10,1.781842e+10,9.181900e+10,-5.660200e+10,3.521700e+10,-9.648000e+09,-5.197000e+09,-4.451000e+09,2.556900e+10,349000000.0,2.591800e+10,2.591800e+10,-3.682000e+09,2.223600e+10,2.223600e+10,2.223600e+10,2.223600e+10,1.219000e+09,4.245000e+09,3.051600e+10,-2.107000e+09,-1.039600e+10,-958000000.0,-1.366800e+10,-3.539000e+09,2.310000e+08,-2.070400e+10,-2.540700e+10,-8.559000e+09,1.071620e+11,2.097000e+10,4.097000e+09,1.632310e+11,3.703100e+10,9.989900e+10,4.045700e+10,1.773870e+11,3.406180e+11,4.511100e+10,1.521400e+10,1.021610e+11,9.307800e+10,1.489260e+11,2.510870e+11,4.597200e+10,4.397700e+10,8.953100e+10,3.406180e+11,1.25911,True,False,False,False,0.433776,-0.016872,-0.014550,0.636416,0.624726,0.006209
13,AAPL,APPLE INC,Technology,Computer Hardware,2020-03-31,USD,2020.0,5/1/2020,4/29/2021,1.744040e+10,1.761877e+10,5.831300e+10,-3.594300e+10,2.237000e+10,-9.517000e+09,-4.952000e+09,-4.565000e+09,1.285300e+10,282000000.0,1.313500e+10,1.313500e+10,-1.886000e+09,1.124900e+10,1.124900e+10,1.124900e+10,1.124900e+10,1.278000e+09,-2.002000e+09,1.331100e+10,-1.853000e+09,1.140700e+10,-176000000.0,9.013000e+09,-3.375000e+09,-1.753000e+09,-1.814600e+10,-2.094000e+10,1.384000e+09,9.405100e+10,1.572200e+10,3.334000e+09,1.437530e+11,3.588900e+10,9.879300e+10,4.196500e+10,1.766470e+11,3.204000e+11,3.242100e+10,2.042100e+10,9.609400e+10,8.908600e+10,1.458810e+11,2.419750e+11,4.803200e+10,3.318200e+10,7.842500e+10,3.204000e+11,0.64500,False,True,False,False,-0.364914,-0.012444,-0.011205,-0.497321,-0.494109,-0.059357
14,AAPL,APPLE INC,Technology,Computer Hardware,2020-06-30,USD,2020.0,7/31/2020,7/28/2021,1.725029e+10,1.741916e+10,5.968500e+10,-3.700500e+10,2.268000e+10,-9.589000e+09,-4.831000e+09,-4.758000e+09,1.309100e+10,46000000.0,1.313700e+10,1.313700e+10,-1.884000e+09,1.125300e+10,1.125300e+10,1.125300e+10,1.125300e+10,2.696000e+09,-4.300000e+08,1.627100e+10,-1.565000e+09,-2.992000e+09,-339000000.0,-5.165000e+09,-3.656000e+09,-4.410000e+08,-1.589100e+10,-1.911600e+10,-8.010000e+09,9.302500e+10,1.788200e+10,3.978000e+09,1.400650e+11,3.568700e+10,1.005920e+11,4.100000e+10,1.772790e+11,3.173440e+11,3.532500e+10,1.867500e+10,9.531800e+10,9.404800e+10,1.497440e+11,2.450620e+11,4.869600e+10,2.413600e+10,7.228200e+10,3.173440e+11,0.65234,False,False,True,False,0.023528,-0.010900,-0.011330,0.018517,0.000356,-0.009538
15,AAPL,APPLE INC,Technology,Computer Hardware,2020-09-30,USD,2020.0,10/30/2020,7/28/2021,1.705762e+10,1.725652e+10,6.469800e+10,-4.000900e+10,2.468900e+10,-9.914000e+09,-4.936000e+09,-4.978000e+09,1.477500e+10,126000000.0,1.490100e+10,1.490100e+10,-2.228000e+09,1.267300e+10,1.267300e+10,1.267300e+10,1.267300e+10,1.324000e+09,3.877000e+09,2.057600e+10,-1.784000e+09,7.434000e+09,-51000000.0,5.531000e+09,-3.511000e+09,4.462000e+09,-1.761700e+10,-2.135700e+10,4.750000e+09,9.094300e+10,1.612000e+10,4.061000e+09,1.437130e+11,3.676600e+10,1.008870e+11,4.252200e+10,1.801750e+11,3.238880e+11,4.229600e+10,1.376900e+10,1.053920e+11,9.866700e+10,1.531570e+11,2.585490e+11,5.077900e+10,1.496600e+10,6.533900e+10,3.238880e+11,0.74295,False,False,False,True,0.083991,-0.011169,-0.009337,0.128638,0.126189,0.020621
16,AAPL,APPLE INC,Technology,Computer Hardware,2020-12-31,USD,2021.0,1/28/2021,1/28/2022,1.693512e+10,1.711369e+10,1.114390e+11,-6.711100e+10,4.432800e+10,-1.079400e+10,-5.631000e+09,-5.163000e+09,3.353400e+10,45000000.0,3.357900e+10,3.357900e+10,-4.824000e+09,2.875500e+10,2.875500e+10,2.875500e+10,2.875500e+10,1.987000e+09,5.355000e+09,3.876300e+10,-3.500000e+09,-5.279000e+09,NaN,-8.584000e+09,-3.613000e+09,-9.780000e+08,-2.477500e+10,-3.224900e+10,-2.070000e+09,7.682600e+10,2.710100e+10,4.973000e+09,1.541060e+11,3.793300e+10,1.187450e+11,4.327000e+10,1.999480e+11,3.540540e+11,6.384600e+10,1.276200e+10,1.325070e+11,9.928100e+10,1.553230e+11,2.878300e+11,5.174400e+10,1.430100e+10,6.622400e+10,3.540540e+11,1.69795,True,False,False,False,0.722449,-0.007182,-0.008277,1.269645,1.268997,0.093137
17,AAPL,APPLE INC,Technology,Computer Hardware,2021-03-31,USD,2021.0,4/29/2021,1/28/2022,1.675348e+10,1.692916e+10,8.958400e+10,-5.150500e+10,3.807900e+10,-1.057600e+10,-5.314000e+09,-5.262000e+09,2.750300e+10,508000000.0,2.801100e+10,2.801100e+10,-4.381000e+09,2.363000e+10,2.363000e+10,2.363000e+10,2.363000e+10,1.333000e+09,-3.779000e+09,2.398100e+10,-2.269000e+09,-7.895000e+09,-9000000.0,-1.036800e+10,-3.447000e+09,1.042300e+10,-1.854800e+10,-1.132600e+10,2.287000e+09,6.983400e+10,1.850300e+10,5.219000e+09,1.214650e+11,3.781500e+10,1.345390e+11,4.333900e+10,2.156930e+11,3.371580e+11,4.012700e+10,1.300300e+10,1.063850e+11,1.086420e+11,1.615950e+11,2.679800e+11,5.420300e+10,1.526100e+10,6.917800e+10,3.371580e+11,1.41045,False,True,False,False,-0.196116,-0.010726,-0.010783,-0.179847,-0.178230,-0.047722
18,AAPL,APPLE INC,Technology,Computer Hardware,2021-06-30,USD,2021.0,7/28/2021,4/29/2022,1.684430e+10,1.702142e+10,8.143400e+10,-4.617900e+10,3.525500e+10,-1.112900e+10,-5.412000e+09,-5.717000e+09,2.412600e+10,243000000.0,2.436900e+10,2.436900e+10,-2.625000e+09,2.174400e+10,2.174400e+10,2.174400e+10,2.174400e+10,1.215000e+09,-4.697000e+09,2.109400e+10,-2.093000e+09,5.747000e+09,-4000000.0,3.572000e+09,-3.767000e+09,0.000000e+00,-2.290000e+10,-2.939600e+10,-4.730000e+09,6.169600e+10,1.747500e+10,5.178000e+09,1.144230e+11,3.861500e+10,1.319480e+11,4.485400e+10,2.154170e+11,3.298400e+11,4.040900e+10,1.603900e+10,1.077540e+11,1.057520e+11,1.578060e+11,2.655600e+11,5.498900e+10,9.233000e+09,6.428000e+10,3.298400e+11,1.29088,False,False,True,False,-0.090976,0.005421,0.005450,-0.122787,-0.079814,-0.021705
19,AAPL,APPLE INC,Technology,Computer Hardware,2021-09-30,USD,2021.0,10/29/2021,7/29/2022,1.639172e+10,1.651929e+10,8.336000e+10,-4.818600e+10,3.517400e+10,-1.138800e+10,-5.616000e+09,-5.772000e+09,2.378600e+10,-538000000.0,2.324800e+10,2.324800e+10,-2.697000e+09,2.055100e+10,2.055100e+10,2.055100e+10,2.055100e+10,-1.550000e+09,-1.790000e+09,2.020000e+10,-3.223000e+09,4.352000e+09,-20000000.0,8.350000e+08,-3.640000e+09,3.220000e+09,-1.974800e+10,-2.038200e+10,6.530000e+08,6.263900e+10,2.627800e+10,6.580000e+09,1.348360e+11,3.944000e+10,1.278770e+11,4.884900e+10,2.161660e+11,3.510020e+11,5.476300e+10,6.000000e+09,1.158680e+11,1.187190e+11,1.720440e+11,2.879120e+11,5.736500e+10,5.562000e+09,6.309000e+10,3.510020e+11,1.25374,False,False,False,True,0.023651,-0.026868,-0.029500,-0.014093,-0.054866,0.064158

In [150]:
#PANDAS SHIFT OPERATION

#pandas -shift() method shifts the index by a desired number of periods

#Syntax for pandas shift operation

#apple_df['Next Quarter EPS']= apple_df['Earning Per Share, Basic'].shift(-1)


apple_df['Next Quarter EPS'] = apple_df['Earnings Per Share, Basic'].shift(-1)
apple_df

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Research & Development,Operating Income (Loss),Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Income,Net Income (Common),Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic",Q1,Q2,Q3,Q4,Revenuechange from last quarter,Shares (Basic)change from last quarter,Shares (Diluted)change from last quarter,Operating Income (Loss)change from last quarter,Net Incomechange from last quarter,Total Liabilities & Equitychange from last quarter,Next Quarter EPS
0,AAPL,APPLE INC,Technology,Computer Hardware,2016-12-31,USD,2017.0,2/1/2017,2/2/2018,2.119464e+10,2.131198e+10,7.835100e+10,-4.817500e+10,3.017600e+10,-6.817000e+09,-3.946000e+09,-2.871000e+09,2.335900e+10,821000000.0,2.418000e+10,2.418000e+10,-6.289000e+09,1.789100e+10,1.789100e+10,1.789100e+10,1.789100e+10,2.708000e+09,3.648000e+09,2.723400e+10,-3.420000e+09,-1.558100e+10,-17000000.0,-1.912200e+10,-3.130000e+09,2.385000e+09,-1.085100e+10,-1.222500e+10,-4.113000e+09,6.045200e+10,1.405700e+10,2.712000e+09,1.033320e+11,2.651000e+10,1.856380e+11,1.566100e+10,2.278090e+11,3.311410e+11,6.224900e+10,1.399200e+10,8.413000e+10,7.355700e+10,1.146210e+11,1.987510e+11,3.214400e+10,1.000010e+11,1.323900e+11,3.311410e+11,0.84413,True,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,0.52762
1,AAPL,APPLE INC,Technology,Computer Hardware,2017-03-31,USD,2017.0,5/3/2017,5/2/2018,2.090316e+10,2.104675e+10,5.289600e+10,-3.230500e+10,2.059100e+10,-6.494000e+09,-3.718000e+09,-2.776000e+09,1.409700e+10,587000000.0,1.468400e+10,1.468400e+10,-3.655000e+09,1.102900e+10,1.102900e+10,1.102900e+10,1.102900e+10,2.587000e+09,-3.378000e+09,1.257000e+10,-2.889000e+09,-1.135700e+10,-50000000.0,-1.420200e+10,-3.004000e+09,1.046900e+10,-6.888000e+09,4.180000e+08,-1.214000e+09,6.710100e+10,1.157900e+10,2.910000e+09,1.019900e+11,2.716300e+10,1.897400e+11,1.563900e+10,2.325420e+11,3.345320e+11,5.166900e+10,1.399100e+10,7.334200e+10,8.453100e+10,1.271080e+11,2.004500e+11,3.357900e+10,1.009250e+11,1.340820e+11,3.345320e+11,0.52762,False,True,False,False,-0.324884,-0.013753,-0.012445,-0.396507,-0.383545,0.010240,0.41948
2,AAPL,APPLE INC,Technology,Computer Hardware,2017-06-30,USD,2017.0,8/2/2017,8/1/2018,2.078035e+10,2.093400e+10,4.540800e+10,-2.792000e+10,1.748800e+10,-6.720000e+09,-3.783000e+09,-2.937000e+09,1.076800e+10,540000000.0,1.130800e+10,1.130800e+10,-2.591000e+09,8.717000e+09,8.717000e+09,8.717000e+09,8.717000e+09,3.135000e+09,-5.534000e+09,8.672000e+09,-2.277000e+09,-8.360000e+08,-181000000.0,-3.180000e+09,-3.365000e+09,9.237000e+09,-7.092000e+09,-2.078000e+09,3.414000e+09,7.675900e+10,1.239900e+10,3.146000e+09,1.128750e+11,2.928600e+10,1.847570e+11,1.825500e+10,2.322980e+11,3.451730e+11,5.521900e+10,1.847500e+10,8.130200e+10,8.986400e+10,1.314460e+11,2.127480e+11,3.444500e+10,9.852500e+10,1.324250e+11,3.451730e+11,0.41948,False,False,True,False,-0.141561,-0.005875,-0.005357,-0.236150,-0.209629,0.031809,0.52015
3,AAPL,APPLE INC,Technology,Computer Hardware,2017-09-30,USD,2017.0,11/3/2017,10/31/2019,2.059771e+10,2.073434e+10,5.257900e+10,-3.264800e+10,1.993100e+10,-6.811000e+09,-3.814000e+09,-2.997000e+09,1.312000e+10,797000000.0,1.391700e+10,1.391700e+10,-3.203000e+09,1.071400e+10,1.071400e+10,1.071400e+10,1.071400e+10,2.376000e+09,1.750000e+08,1.574900e+10,-3.865000e+09,-5.768000e+09,-81000000.0,-9.942000e+09,-3.270000e+09,6.923000e+09,-7.514000e+09,-4.089000e+09,1.718000e+09,7.418100e+10,1.787400e+10,4.855000e+09,1.286450e+11,3.378300e+10,1.947140e+11,1.817700e+10,2.466740e+11,3.753190e+11,4.424200e+10,1.847300e+10,1.008140e+11,9.720700e+10,1.404580e+11,2.412720e+11,3.586700e+10,9.833000e+10,1.340470e+11,3.753190e+11,0.52015,False,False,False,True,0.157924,-0.008789,-0.009537,0.218425,0.229093,0.087336,0.98110
4,AAPL,APPLE INC,Technology,Computer Hardware,2017-12-31,USD,2018.0,2/2/2018,1/30/2019,2.045151e+10,2.063115e+10,8.829300e+10,-5.438100e+10,3.391200e+10,-7.638000e+09,-4.231000e+09,-3.407000e+09,2.627400e+10,756000000.0,2.703000e+10,2.703000e+10,-6.965000e+09,2.006500e+10,2.006500e+10,2.006500e+10,2.006500e+10,-3.244100e+10,3.792400e+10,2.829300e+10,-2.810000e+09,-1.056400e+10,-173000000.0,-1.359000e+10,-3.339000e+09,6.971000e+09,-1.009500e+10,-7.501000e+09,7.202000e+09,7.715300e+10,2.344000e+10,4.421000e+09,1.438100e+11,3.367900e+10,2.079440e+11,2.136100e+10,2.629840e+11,4.067940e+11,8.926600e+10,1.847800e+10,1.157880e+11,1.039220e+11,1.508070e+11,2.665950e+11,3.644700e+10,1.045930e+11,1.401990e+11,4.067940e+11,0.98110,True,False,False,False,0.679245,-0.007098,-0.004977,1.002591,0.872783,0.083862,0.68768
5,AAPL,APPLE INC,Technology,Computer Hardware,2018-03-31,USD,2018.0,5/2/2018,5/1/2019,2.009951e+10,2.027397e+10,6.113700e+10,-3.771500e+10,2.342200e+10,-7.528000e+09,-4.150000e+09,-3.378000e+09,1.589400e+10,274000000.0,1.616800e+10,1.616800e+10,-2.346000e+09,1.382200e+10,1.382200e+10,1.382200e+10,1.382200e+10,8.500000e+08,-2.281000e+09,1.513000e+10,-4.195000e+09,3.277800e+10,-132000000.0,2.871000e+10,-3.190000e+09,-5.020000e+08,-2.242900e+10,-2.627200e+10,1.756800e+10,8.794000e+10,1.432400e+10,7.662000e+09,1.300530e+11,3.507700e+10,1.792860e+11,2.308600e+10,2.374490e+11,3.675020e+11,6.106700e+10,2.047800e+10,8.932000e+10,1.013620e+11,1.513040e+11,2.406240e+11,3.804400e+10,9.189800e+10,1.268780e+11,3.675020e+11,0.68768,False,True,False,False,-0.307567,-0.017211,-0.017312,-0.395067,-0.311139,-0.096589,0.58985
6,AAPL,APPLE INC,Technology,Computer Hardware,2018-06-30,USD,2018.0,8/1/2018,7/31/2019,1.952867e+10,1.970644e+10,5.326500e+10,-3.284400e+10,2.042100e+10,-7.809000e+09,-4.108000e+09,-3.701000e+09,1.261200e+10,672000000.0,1.328400e+10,1.328400e+10,-1.765000e+09,1.151900e+10,1.151900e+10,1.151900e+10,1.151900e+10,2.477000e+09,-2.173000e+09,1.448800e+10,-3.267000e+09,8.079000e+09,-126000000.0,3.947000e+09,-3.653000e+09,-6.010000e+09,-2.078200e+10,-3.152300e+10,-1.308800e+10,7.097000e+10,1.410400e+10,5.936000e+09,1.157610e+11,3.811700e+10,1.727730e+11,2.254600e+10,2.334360e+11,3.491970e+11,6.367300e+10,1.747200e+10,8.854800e+10,9.712800e+10,1.457000e+11,2.342480e+11,3.862400e+10,7.943600e+10,1.149490e+11,3.491970e+11,0.58985,False,False,True,False,-0.128760,-0.028401,-0.027993,-0.206493,-0.166618,-0.049809,0.73543
7,AAPL,APPLE INC,Technology,Computer Hardware,2018-09-30,USD,2018.0,11/5/2018,10/30/2020,1.920635e+10,1.939019e+10,6.290000e+10,-3.881600e+10,2.408400e+10,-7.966000e+09,-4.216000e+09,-3.750000e+09,1.611800e+10,303000000.0,1.642100e+10,1.642100e+10,-2.296000e+09,1.412500e+10,1.412500e+10,1.412500e+10,1.412500e+10,1.864000e+09,7.800000e+08,1.952300e+10,-3.041000e+09,5.520000e+08,-290000000.0,-3.001000e+09,-3.530000e+09,-2.700000e+07,-1.876300e+10,-2.258000e+10,-6.058000e+09,6.630100e+10,2.318600e+10,3.956000e+09,1.313390e+11,4.130400e+10,1.707990e+11,2.228300e+10,2.343860e+11,3.657250e+11,5.588800e+10,2.074800e+10,1.159290e+11,9.373500e+10,1.426490e+11,2.585780e+11,4.020100e+10,7.040000e+10,1.071470e+11,3.657250e+11,0.73543,False,False,False,True,0.180888,-0.016505,-0.016048,0.277989,0.226235,0.047331,1.05394
8,AAPL,APPLE INC,Technology,Computer Hardware,2018-12-31,USD,2019.0,1/30/2019,1/29/2020,1.894328e+10,1.909301e+10,8.431000e+10,-5.227900e+10,3.203100e+10,-8.685000e+09,-4.783000e+09,-3.902000e+09,2.334600e+10,560000000.0,2.390600e+10,2.390600e+10,-3.941000e+09,1.996500e+10,1.996500e+10,1.996500e+10,1.996500e+10,1.612000e+09,1.718000e+09,2.669000e+10,-3.355000e+09,9.422000e+09,-167000000.0,5.844000e+09,-3.568000e+09,6.000000e+06,-8.796000e+09,-1.367600e+10,1.885800e+10,8.642700e+10,1.807700e+10,4.988000e+09,1.408280e+11,3.959700e+10,1.586080e+11,3.468600e+10,2.328910e+11,3.737190e+11,4.429300e+10,2.174100e+10,1.082830e+11,9.298900e+10,1.475440e+11,2.558270e+11,4.097000e+10,8.051000e+10,1.178920e+11,3.737190e+11,1.05394,True,False,False,False,0.340382,-0.013697,-0.015326,0.448443,0.413451,0.021858,0.61836
9,AAPL,APPLE INC,Technology,Computer Hardware,2019-03-31,USD,2019.0,5/1/2019,5/1/2020,1.869628e+10,1.880258e+10,5.801500e+10,-3.619400e+10,2.182100e+10,-8.406000e+09,-4.458000e+09,-3.948000e+09,1.341500e+10,378000000.0,1.379300e+10,1.379300e+10,-2.232000e+09,1.156100e+10,1.156100e+10,1.156100e+10,1.156100e+10,1.337000e+09,-4.783000e+09,1.115500e+10,-2.363000e+09,1.574900e+10,-124000000.0,1.334800e+10,-3.443000e+09,-2.542000e+09,-2.331200e+10,-2.945700e+10,-4.954000e+09,8.009200e+10,1.508500e+10,4.884000e+09,1.233460e+11,3.874600e+10,1.453190e+11,3.458700e+10,2.186520e+11,3.419980e+11,3.044300e+10,2.242900e+10,9.377200e+10,9.020100e+10,1.423660e+11,2.361380e+11,4.280100e+10,6.455800e+10,1.058600e+11,3.419980e+11,0.61836,False,True,False,False,-0.311885,-0.013039,-0.015211,-0.425383,-0.420937,-0.084879,0.54938
10,AAPL,APPLE INC,Technology,Computer Hardware,2019-06-30,USD,2019.0,7/31/2019,7/31/2020,1.828254e+10,1.840552e+10,5.380900e+10,-3.358200e+10,2.022700e+10,-8.683000e+09,-4.426000e+09,-4.257000e+09,1.154400e+10,367000000.0,1.191100e+10,1.191100e+10,-1.867000e+09,1.004400e+10,1.004400e+10,1.004400e+10,1.004400e+10,1.582000e+09,-2.923000e+09,1.163600e+10,-2.000000e+09,3.012000e+10,-320000000.0,2.750200e+10,-3.629000e+09,-4.990000e+09,-1.695400e+10,-2.680400e+10,1.233400e+10,9.461400e+10,1.414800e+10,3.355000e+09,1.349730e+11,3.763600e+10,1.159960e+11,3.363400e+10,1.872660e+11,3.222390e+11,2.911500e+10,2.348200e+10,8.970400e+10,8.493600e+10,1.360790e+11,2.257830e+11,4.337100e+10,5.372400e+10,9.645600e+10,3.222390e+11,0.54938,False,False,True,False,-0.072498,-0.022130,-0.021118,-0.139471,-0.131217,-0.057775,0.76189
11,AAPL,APPLE INC,Technology,Computer Hardware,2019-09-30,USD,2019.0,10/31/2019,10/29/2021,1.796324e+10,1.808150e+10,6.404000e+10,-3.972700e+10,2.431300e+10,-8.688000e+09,-4.578000e+09,-4.110000e+09,1.562500e+10,502000000.0,1.612700e+10,1.612700e+10,-2.441000e+09,1.368600e+10,1.368600e+10,1.368600e+10,1.368600e+10,5.450000e+08,2.500000e+09,1.991000e+10,-2.777000e+09,2.802000e+09,-13000000.0,-7.980000e+08,-3.479000e+09,-2.930000e+08,-1.705400e+10,-2.103900e+10,-1.927000e+09,1.005570e+11,2.292600e+10,4.106000e+09,1.628190e+11,3.737800e+10,1.053410e+11,3.297800e+10,1.756970e+11,3.385160e+11,4.623600e+10,1.624000e+10,1.057180e+11,9.180700e+10,1.423100e+11,2.480280e+11,4.517400e+10,4.589800e+10,9.048800e+10,3.385160e+11,0.76189,False,False,False,True,0.190135,-0.017464,-0.017604,0.353517,0.362605,0.050512,1.25911
12,AAPL,APPLE INC,Technology,Computer Hardware,2019-12-31,USD,2020.0,1/29/2020,1/28/2021,1.766016e+10,1.781842e+10,9.181900e+10,-5.660200e+10,3.521700e+10,-9.648000e+09,-5.197000e+09,-4.451000e+09,2.556900e+10,349000000.0,2.591800e+10,2.591800e+10,-3.682000e+09,2.223600e+10,2.223600e+10,2.223600e+10,2.223600e+10,1.219000e+09,4.245000e+09,3.051600e+10,-2.107000e+09,-1.039600e+10,-958000000.0,-1.366800e+10,-3.539000e+09,2.310000e+08,-2.070400e+10,-2.540700e+10,-8.559000e+09,1.071620e+11,2.097000e+10,4.097000e+09,1.632310e+11,3.703100e+10,9.989900e+10,4.045700e+10,1.773870e+11,3.406180e+11,4.511100e+10,1.521400e+10,1.021610e+11,9.307800e+10,1.489260e+11,2.510870e+11,4.597200e+10,4.397700e+10,8.953100e+10,3.406180e+11,1.25911,True,False,False,False,0.433776,-0.016872,-0.014550,0.636416,0.624726,0.006209,0.64500
13,AAPL,APPLE INC,Technology,Computer Hardware,2020-03-31,USD,2020.0,5/1/2020,4/29/2021,1.744040e+10,1.761877e+10,5.831300e+10,-3.594300e+10,2.237000e+10,-9.517000e+09,-4.952000e+09,-4.565000e+09,1.285300e+10,282000000.0,1.313500e+10,1.313500e+10,-1.886000e+09,1.124900e+10,1.124900e+10,1.124900e+10,1.124900e+10,1.278000e+09,-2.002000e+09,1.331100e+10,-1.853000e+09,1.140700e+10,-176000000.0,9.013000e+09,-3.375000e+09,-1.753000e+09,-1.814600e+10,-2.094000e+10,1.384000e+09,9.405100e+10,1.572200e+10,3.334000e+09,1.437530e+11,3.588900e+10,9.879300e+10,4.196500e+10,1.766470e+11,3.204000e+11,3.242100e+10,2.042100e+10,9.609400e+10,8.908600e+10,1.458810e+11,2.419750e+11,4.803200e+10,3.318200e+10,7.842500e+10,3.204000e+11,0.64500,False,True,False,False,-0.364914,-0.012444,-0.011205,-0.497321,-0.494109,-0.059357,0.65234
14,AAPL,APPLE INC,Technology,Computer Hardware,2020-06-30,USD,2020.0,7/31/2020,7/28/2021,1.725029e+10,1.741916e+10,5.968500e+10,-3.700500e+10,2.268000e+10,-9.589000e+09,-4.831000e+09,-4.758000e+09,1.309100e+10,46000000.0,1.313700e+10,1.313700e+10,-1.884000e+09,1.125300e+10,1.125300e+10,1.125300e+10,1.125300e+10,2.696000e+09,-4.300000e+08,1.627100e+10,-1.565000e+09,-2.992000e+09,-339000000.0,-5.165000e+09,-3.656000e+09,-4.410000e+08,-1.589100e+10,-1.911600e+10,-8.010000e+09,9.302500e+10,1.788200e+10,3.978000e+09,1.400650e+11,3.568700e+10,1.005920e+11,4.100000e+10,1.772790e+11,3.173440e+11,3.532500e+10,1.867500e+10,9.531800e+10,9.404800e+10,1.497440e+11,2.450620e+11,4.869600e+10,2.413600e+10,7.228200e+10,3.173440e+11,0.65234,False,False,True,False,0.023528,-0.010900,-0.011330,0.018517,0.000356,-0.009538,0.74295
15,AAPL,APPLE INC,Technology,Computer Hardware,2020-09-30,USD,2020.0,10/30/2020,7/28/2021,1.705762e+10,1.725652e+10,6.469800e+10,-4.000900e+10,2.468900e+10,-9.914000e+09,-4.936000e+09,-4.978000e+09,1.477500e+10,126000000.0,1.490100e+10,1.490100e+10,-2.228000e+09,1.267300e+10,1.267300e+10,1.267300e+10,1.267300e+10,1.324000e+09,3.877000e+09,2.057600e+10,-1.784000e+09,7.434000e+09,-51000000.0,5.531000e+09,-3.511000e+09,4.462000e+09,-1.761700e+10,-2.135700e+10,4.750000e+09,9.094300e+10,1.612000e+10,4.061000e+09,1.437130e+11,3.676600e+10,1.008870e+11,4.252200e+10,1.801750e+11,3.238880e+11,4.229600e+10,1.376900e+10,1.053920e+11,9.866700e+10,1.531570e+11,2.585490e+11,5.077900e+10,1.496600e+10,6.533900e+10,3.238880e+11,0.74295,False,False,False,True,0.083991,-0.011169,-0.009337,0.128638,0.126189,0.020621,1.69795
16,AAPL,APPLE INC,Technology,Computer Hardware,2020-12-31,USD,2021.0,1/28/2021,1/28/2022,1.693512e+10,1.711369e+10,1.114390e+11,-6.711100e+10,4.432800e+10,-1.079400e+10,-5.631000e+09,-5.163000e+09,3.353400e+10,45000000.0,3.357900e+10,3.357900e+10,-4.824000e+09,2.875500e+10,2.875500e+10,2.875500e+10,2.875500e+10,1.987000e+09,5.355000e+09,3.876300e+10,-3.500000e+09,-5.279000e+09,NaN,-8.584000e+09,-3.613000e+09,-9.780000e+08,-2.477500e+10,-3.224900e+10,-2.070000e+09,7.682600e+10,2.710100e+10,4.973000e+09,1.541060e+11,3.793300e+10,1.187450e+11,4.327000e+10,1.999480e+11,3.540540e+11,6.384600e+10,1.276200e+10,1.325070e+11,9.928100e+10,1.553230e+11,2.878300e+11,5.174400e+10,1.430100e+10,6.622400e+10,3.540540e+11,1.69795,True,False,False,False,0.722449,-0.007182,-0.008277,1.269645,1.268997,0.093137,1.41045
17,AAPL,APPLE INC,Technology,Computer Hardware,2021-03-31,USD,2021.0,4/29/2021,1/28/2022,1.675348e+10,1.692916e+10,8.958400e+10,-5.150500e+10,3.807900e+10,-1.057600e+10,-5.314000e+09,-5.262000e+09,2.750300e+10,508000000.0,2.801100e+10,2.801100e+10,-4.381000e+09,2.363000e+10,2.363000e+10,2.363000e+10,2.363000e+10,1.333000e+09,-3.779000e+09,2.398100e+10,-2.269000e+09,-7.895000e+09,-9000000.0,-1.036800e+10,-3.447000e+09,1.042300e+10,-1.854800e+10,-1.132600e+10,2.287000e+09,6.983400e+10,1.850300e+10,5.219000e+09,1.214650e+11,3.781500e+10,1.345390e+11,4.333900e+10,2.156930e+11,3.371580e+11,4.012700e+10,1.300300e+10,1.063850e+11,1.086420e+11,1.615950e+11,2.679800e+11,5.420300e+10,1.526100e+10,6.917800e+10,3.371580e+11,1.41045,False,True,False,False,-0.196116,-0.010726,-0.010783,-0.179847,-0.178230,-0.047722,1.29088
18,AAPL,APPLE INC,Technology,Computer Hardware,2021-06-30,USD,2021.0,7/28/2021,4/29/2022,1.684430e+10,1.702142e+10,8.143400e+10,-4.617900e+10,3.525500e+10,-1.112900e+10,-5.412000e+09,-5.717000e+09,2.412600e+10,243000000.0,2.436900e+10,2.436900e+10,-2.625000e+09,2.174400e+10,2.174400e+10,2.174400e+10,2.174400e+10,1.215000e+09,-4.697000e+09,2.109400e+10,-2.093000e+09,5.747000e+09,-4000000.0,3.572000e+09,-3.767000e+09,0.000000e+00,-2.290000e+10,-2.939600e+10,-4.730000e+09,6.169600e+10,1.747500e+10,5.178000e+09,1.144230e+11,3.861500e+10,1.319480e+11,4.485400e+10,2.154170e+11,3.298400e+11,4.040900e+10,1.603900e+10,1.077540e+11,1.057520e+11,1.578060e+11,2.655600e+11,5.498900e+10,9.233000e+09,6.428000e+10,3.298400e+11,1.29088,False,False,True,False,-0.090976,0.005421,0.005450,-0.122787,-0.079814,-0.021705,1.25374
19,AAPL,APPLE INC,Technology,Computer Hardware,2021-09-30,USD,2021.0,10/29/2021,7/29/2022,1.639172e+10,1.651929e+10,8.336000e+10,-4.818600e+10,3.517400e+10,-1.138800e+10,-5.616000e+09,-5.772000e+09,2.378600e+10,-538000000.0,2.324800e+10,2.324800e+10,-2.697000e+09,2.055100e+10,2.055100e+10,2.055100e+10,2.055100e+10,-1.550000e+09,-1.790000e+09,2.020000e+10,-3.223000e+09,4.352000e+09,-20000000.0,8.350000e+08,-3.640000e+09,3.220000e+09,-1.974800e+10,-2.038200e+10,6.530000e+08,6.263900e+10,2.627800e+10,6.580000e+09,1.348360e+11,3.944000e+10,1.278770e+11,4.884900e+10,2.161660e+11,3.510020e+11,5.476300e+10,6.000000e+09,1.158680e+11,1.187190e+11,1.720440e+11,2.879120e+11,5.736500e+10,5.562000e+09,6.309000e+10,3.510020e+11,1.25374,False,False,False,True,0.023651,-0.026868,-0.029500,-0.014093,-0.054866,0.064158,NaN

In [151]:
#drop NUll elements in Next Quarter EPS (last row)

apple_df = apple_df.dropna(subset = ['Next Quarter EPS']).reset_index(drop = True)
apple_df

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Research & Development,Operating Income (Loss),Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Income,Net Income (Common),Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic",Q1,Q2,Q3,Q4,Revenuechange from last quarter,Shares (Basic)change from last quarter,Shares (Diluted)change from last quarter,Operating Income (Loss)change from last quarter,Net Incomechange from last quarter,Total Liabilities & Equitychange from last quarter,Next Quarter EPS
0,AAPL,APPLE INC,Technology,Computer Hardware,2016-12-31,USD,2017.0,2/1/2017,2/2/2018,2.119464e+10,2.131198e+10,7.835100e+10,-4.817500e+10,3.017600e+10,-6.817000e+09,-3.946000e+09,-2.871000e+09,2.335900e+10,821000000.0,2.418000e+10,2.418000e+10,-6.289000e+09,1.789100e+10,1.789100e+10,1.789100e+10,1.789100e+10,2.708000e+09,3.648000e+09,2.723400e+10,-3.420000e+09,-1.558100e+10,-17000000.0,-1.912200e+10,-3.130000e+09,2.385000e+09,-1.085100e+10,-1.222500e+10,-4.113000e+09,6.045200e+10,1.405700e+10,2.712000e+09,1.033320e+11,2.651000e+10,1.856380e+11,1.566100e+10,2.278090e+11,3.311410e+11,6.224900e+10,1.399200e+10,8.413000e+10,7.355700e+10,1.146210e+11,1.987510e+11,3.214400e+10,1.000010e+11,1.323900e+11,3.311410e+11,0.84413,True,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,0.52762
1,AAPL,APPLE INC,Technology,Computer Hardware,2017-03-31,USD,2017.0,5/3/2017,5/2/2018,2.090316e+10,2.104675e+10,5.289600e+10,-3.230500e+10,2.059100e+10,-6.494000e+09,-3.718000e+09,-2.776000e+09,1.409700e+10,587000000.0,1.468400e+10,1.468400e+10,-3.655000e+09,1.102900e+10,1.102900e+10,1.102900e+10,1.102900e+10,2.587000e+09,-3.378000e+09,1.257000e+10,-2.889000e+09,-1.135700e+10,-50000000.0,-1.420200e+10,-3.004000e+09,1.046900e+10,-6.888000e+09,4.180000e+08,-1.214000e+09,6.710100e+10,1.157900e+10,2.910000e+09,1.019900e+11,2.716300e+10,1.897400e+11,1.563900e+10,2.325420e+11,3.345320e+11,5.166900e+10,1.399100e+10,7.334200e+10,8.453100e+10,1.271080e+11,2.004500e+11,3.357900e+10,1.009250e+11,1.340820e+11,3.345320e+11,0.52762,False,True,False,False,-0.324884,-0.013753,-0.012445,-0.396507,-0.383545,0.010240,0.41948
2,AAPL,APPLE INC,Technology,Computer Hardware,2017-06-30,USD,2017.0,8/2/2017,8/1/2018,2.078035e+10,2.093400e+10,4.540800e+10,-2.792000e+10,1.748800e+10,-6.720000e+09,-3.783000e+09,-2.937000e+09,1.076800e+10,540000000.0,1.130800e+10,1.130800e+10,-2.591000e+09,8.717000e+09,8.717000e+09,8.717000e+09,8.717000e+09,3.135000e+09,-5.534000e+09,8.672000e+09,-2.277000e+09,-8.360000e+08,-181000000.0,-3.180000e+09,-3.365000e+09,9.237000e+09,-7.092000e+09,-2.078000e+09,3.414000e+09,7.675900e+10,1.239900e+10,3.146000e+09,1.128750e+11,2.928600e+10,1.847570e+11,1.825500e+10,2.322980e+11,3.451730e+11,5.521900e+10,1.847500e+10,8.130200e+10,8.986400e+10,1.314460e+11,2.127480e+11,3.444500e+10,9.852500e+10,1.324250e+11,3.451730e+11,0.41948,False,False,True,False,-0.141561,-0.005875,-0.005357,-0.236150,-0.209629,0.031809,0.52015
3,AAPL,APPLE INC,Technology,Computer Hardware,2017-09-30,USD,2017.0,11/3/2017,10/31/2019,2.059771e+10,2.073434e+10,5.257900e+10,-3.264800e+10,1.993100e+10,-6.811000e+09,-3.814000e+09,-2.997000e+09,1.312000e+10,797000000.0,1.391700e+10,1.391700e+10,-3.203000e+09,1.071400e+10,1.071400e+10,1.071400e+10,1.071400e+10,2.376000e+09,1.750000e+08,1.574900e+10,-3.865000e+09,-5.768000e+09,-81000000.0,-9.942000e+09,-3.270000e+09,6.923000e+09,-7.514000e+09,-4.089000e+09,1.718000e+09,7.418100e+10,1.787400e+10,4.855000e+09,1.286450e+11,3.378300e+10,1.947140e+11,1.817700e+10,2.466740e+11,3.753190e+11,4.424200e+10,1.847300e+10,1.008140e+11,9.720700e+10,1.404580e+11,2.412720e+11,3.586700e+10,9.833000e+10,1.340470e+11,3.753190e+11,0.52015,False,False,False,True,0.157924,-0.008789,-0.009537,0.218425,0.229093,0.087336,0.98110
4,AAPL,APPLE INC,Technology,Computer Hardware,2017-12-31,USD,2018.0,2/2/2018,1/30/2019,2.045151e+10,2.063115e+10,8.829300e+10,-5.438100e+10,3.391200e+10,-7.638000e+09,-4.231000e+09,-3.407000e+09,2.627400e+10,756000000.0,2.703000e+10,2.703000e+10,-6.965000e+09,2.006500e+10,2.006500e+10,2.006500e+10,2.006500e+10,-3.244100e+10,3.792400e+10,2.829300e+10,-2.810000e+09,-1.056400e+10,-173000000.0,-1.359000e+10,-3.339000e+09,6.971000e+09,-1.009500e+10,-7.501000e+09,7.202000e+09,7.715300e+10,2.344000e+10,4.421000e+09,1.438100e+11,3.367900e+10,2.079440e+11,2.136100e+10,2.629840e+11,4.067940e+11,8.926600e+10,1.847800e+10,1.157880e+11,1.039220e+11,1.508070e+11,2.665950e+11,3.644700e+10,1.045930e+11,1.401990e+11,4.067940e+11,0.98110,True,False,False,False,0.679245,-0.007098,-0.004977,1.002591,0.872783,0.083862,0.68768
5,AAPL,APPLE INC,Technology,Computer Hardware,2018-03-31,USD,2018.0,5/2/2018,5/1/2019,2.009951e+10,2.027397e+10,6.113700e+10,-3.771500e+10,2.342200e+10,-7.528000e+09,-4.150000e+09,-3.378000e+09,1.589400e+10,274000000.0,1.616800e+10,1.616800e+10,-2.346000e+09,1.382200e+10,1.382200e+10,1.382200e+10,1.382200e+10,8.500000e+08,-2.281000e+09,1.513000e+10,-4.195000e+09,3.277800e+10,-132000000.0,2.871000e+10,-3.190000e+09,-5.020000e+08,-2.242900e+10,-2.627200e+10,1.756800e+10,8.794000e+10,1.432400e+10,7.662000e+09,1.300530e+11,3.507700e+10,1.792860e+11,2.308600e+10,2.374490e+11,3.675020e+11,6.106700e+10,2.047800e+10,8.932000e+10,1.013620e+11,1.513040e+11,2.406240e+11,3.804400e+10,9.189800e+10,1.268780e+11,3.675020e+11,0.68768,False,True,False,False,-0.307567,-0.017211,-0.017312,-0.395067,-0.311139,-0.096589,0.58985
6,AAPL,APPLE INC,Technology,Computer Hardware,2018-06-30,USD,2018.0,8/1/2018,7/31/2019,1.952867e+10,1.970644e+10,5.326500e+10,-3.284400e+10,2.042100e+10,-7.809000e+09,-4.108000e+09,-3.701000e+09,1.261200e+10,672000000.0,1.328400e+10,1.328400e+10,-1.765000e+09,1.151900e+10,1.151900e+10,1.151900e+10,1.151900e+10,2.477000e+09,-2.173000e+09,1.448800e+10,-3.267000e+09,8.079000e+09,-126000000.0,3.947000e+09,-3.653000e+09,-6.010000e+09,-2.078200e+10,-3.152300e+10,-1.308800e+10,7.097000e+10,1.410400e+10,5.936000e+09,1.157610e+11,3.811700e+10,1.727730e+11,2.254600e+10,2.334360e+11,3.491970e+11,6.367300e+10,1.747200e+10,8.854800e+10,9.712800e+10,1.457000e+11,2.342480e+11,3.862400e+10,7.943600e+10,1.149490e+11,3.491970e+11,0.58985,False,False,True,False,-0.128760,-0.028401,-0.027993,-0.206493,-0.166618,-0.049809,0.73543
7,AAPL,APPLE INC,Technology,Computer Hardware,2018-09-30,USD,2018.0,11/5/2018,10/30/2020,1.920635e+10,1.939019e+10,6.290000e+10,-3.881600e+10,2.408400e+10,-7.966000e+09,-4.216000e+09,-3.750000e+09,1.611800e+10,303000000.0,1.642100e+10,1.642100e+10,-2.296000e+09,1.412500e+10,1.412500e+10,1.412500e+10,1.412500e+10,1.864000e+09,7.800000e+08,1.952300e+10,-3.041000e+09,5.520000e+08,-290000000.0,-3.001000e+09,-3.530000e+09,-2.700000e+07,-1.876300e+10,-2.258000e+10,-6.058000e+09,6.630100e+10,2.318600e+10,3.956000e+09,1.313390e+11,4.130400e+10,1.707990e+11,2.228300e+10,2.343860e+11,3.657250e+11,5.588800e+10,2.074800e+10,1.159290e+11,9.373500e+10,1.426490e+11,2.585780e+11,4.020100e+10,7.040000e+10,1.071470e+11,3.657250e+11,0.73543,False,False,False,True,0.180888,-0.016505,-0.016048,0.277989,0.226235,0.047331,1.05394
8,AAPL,APPLE INC,Technology,Computer Hardware,2018-12-31,USD,2019.0,1/30/2019,1/29/2020,1.894328e+10,1.909301e+10,8.431000e+10,-5.227900e+10,3.203100e+10,-8.685000e+09,-4.783000e+09,-3.902000e+09,2.334600e+10,560000000.0,2.390600e+10,2.390600e+10,-3.941000e+09,1.996500e+10,1.996500e+10,1.996500e+10,1.996500e+10,1.612000e+09,1.718000e+09,2.669000e+10,-3.355000e+09,9.422000e+09,-167000000.0,5.844000e+09,-3.568000e+09,6.000000e+06,-8.796000e+09,-1.367600e+10,1.885800e+10,8.642700e+10,1.807700e+10,4.988000e+09,1.408280e+11,3.959700e+10,1.586080e+11,3.468600e+10,2.328910e+11,3.737190e+11,4.429300e+10,2.174100e+10,1.082830e+11,9.298900e+10,1.475440e+11,2.558270e+11,4.097000e+10,8.051000e+10,1.178920e+11,3.737190e+11,1.05394,True,False,False,False,0.340382,-0.013697,-0.015326,0.448443,0.413451,0.021858,0.61836
9,AAPL,APPLE INC,Technology,Computer Hardware,2019-03-31,USD,2019.0,5/1/2019,5/1/2020,1.869628e+10,1.880258e+10,5.801500e+10,-3.619400e+10,2.182100e+10,-8.406000e+09,-4.458000e+09,-3.948000e+09,1.341500e+10,378000000.0,1.379300e+10,1.379300e+10,-2.232000e+09,1.156100e+10,1.156100e+10,1.156100e+10,1.156100e+10,1.337000e+09,-4.783000e+09,1.115500e+10,-2.363000e+09,1.574900e+10,-124000000.0,1.334800e+10,-3.443000e+09,-2.542000e+09,-2.331200e+10,-2.945700e+10,-4.954000e+09,8.009200e+10,1.508500e+10,4.884000e+09,1.233460e+11,3.874600e+10,1.453190e+11,3.458700e+10,2.186520e+11,3.419980e+11,3.044300e+10,2.242900e+10,9.377200e+10,9.020100e+10,1.423660e+11,2.361380e+11,4.280100e+10,6.455800e+10,1.058600e+11,3.419980e+11,0.61836,False,True,False,False,-0.311885,-0.013039,-0.015211,-0.425383,-0.420937,-0.084879,0.54938
10,AAPL,APPLE INC,Technology,Computer Hardware,2019-06-30,USD,2019.0,7/31/2019,7/31/2020,1.828254e+10,1.840552e+10,5.380900e+10,-3.358200e+10,2.022700e+10,-8.683000e+09,-4.426000e+09,-4.257000e+09,1.154400e+10,367000000.0,1.191100e+10,1.191100e+10,-1.867000e+09,1.004400e+10,1.004400e+10,1.004400e+10,1.004400e+10,1.582000e+09,-2.923000e+09,1.163600e+10,-2.000000e+09,3.012000e+10,-320000000.0,2.750200e+10,-3.629000e+09,-4.990000e+09,-1.695400e+10,-2.680400e+10,1.233400e+10,9.461400e+10,1.414800e+10,3.355000e+09,1.349730e+11,3.763600e+10,1.159960e+11,3.363400e+10,1.872660e+11,3.222390e+11,2.911500e+10,2.348200e+10,8.970400e+10,8.493600e+10,1.360790e+11,2.257830e+11,4.337100e+10,5.372400e+10,9.645600e+10,3.222390e+11,0.54938,False,False,True,False,-0.072498,-0.022130,-0.021118,-0.139471,-0.131217,-0.057775,0.76189
11,AAPL,APPLE INC,Technology,Computer Hardware,2019-09-30,USD,2019.0,10/31/2019,10/29/2021,1.796324e+10,1.808150e+10,6.404000e+10,-3.972700e+10,2.431300e+10,-8.688000e+09,-4.578000e+09,-4.110000e+09,1.562500e+10,502000000.0,1.612700e+10,1.612700e+10,-2.441000e+09,1.368600e+10,1.368600e+10,1.368600e+10,1.368600e+10,5.450000e+08,2.500000e+09,1.991000e+10,-2.777000e+09,2.802000e+09,-13000000.0,-7.980000e+08,-3.479000e+09,-2.930000e+08,-1.705400e+10,-2.103900e+10,-1.927000e+09,1.005570e+11,2.292600e+10,4.106000e+09,1.628190e+11,3.737800e+10,1.053410e+11,3.297800e+10,1.756970e+11,3.385160e+11,4.623600e+10,1.624000e+10,1.057180e+11,9.180700e+10,1.423100e+11,2.480280e+11,4.517400e+10,4.589800e+10,9.048800e+10,3.385160e+11,0.76189,False,False,False,True,0.190135,-0.017464,-0.017604,0.353517,0.362605,0.050512,1.25911
12,AAPL,APPLE INC,Technology,Computer Hardware,2019-12-31,USD,2020.0,1/29/2020,1/28/2021,1.766016e+10,1.781842e+10,9.181900e+10,-5.660200e+10,3.521700e+10,-9.648000e+09,-5.197000e+09,-4.451000e+09,2.556900e+10,349000000.0,2.591800e+10,2.591800e+10,-3.682000e+09,2.223600e+10,2.223600e+10,2.223600e+10,2.223600e+10,1.219000e+09,4.245000e+09,3.051600e+10,-2.107000e+09,-1.039600e+10,-958000000.0,-1.366800e+10,-3.539000e+09,2.310000e+08,-2.070400e+10,-2.540700e+10,-8.559000e+09,1.071620e+11,2.097000e+10,4.097000e+09,1.632310e+11,3.703100e+10,9.989900e+10,4.045700e+10,1.773870e+11,3.406180e+11,4.511100e+10,1.521400e+10,1.021610e+11,9.307800e+10,1.489260e+11,2.510870e+11,4.597200e+10,4.397700e+10,8.953100e+10,3.406180e+11,1.25911,True,False,False,False,0.433776,-0.016872,-0.014550,0.636416,0.624726,0.006209,0.64500
13,AAPL,APPLE INC,Technology,Computer Hardware,2020-03-31,USD,2020.0,5/1/2020,4/29/2021,1.744040e+10,1.761877e+10,5.831300e+10,-3.594300e+10,2.237000e+10,-9.517000e+09,-4.952000e+09,-4.565000e+09,1.285300e+10,282000000.0,1.313500e+10,1.313500e+10,-1.886000e+09,1.124900e+10,1.124900e+10,1.124900e+10,1.124900e+10,1.278000e+09,-2.002000e+09,1.331100e+10,-1.853000e+09,1.140700e+10,-176000000.0,9.013000e+09,-3.375000e+09,-1.753000e+09,-1.814600e+10,-2.094000e+10,1.384000e+09,9.405100e+10,1.572200e+10,3.334000e+09,1.437530e+11,3.588900e+10,9.879300e+10,4.196500e+10,1.766470e+11,3.204000e+11,3.242100e+10,2.042100e+10,9.609400e+10,8.908600e+10,1.458810e+11,2.419750e+11,4.803200e+10,3.318200e+10,7.842500e+10,3.204000e+11,0.64500,False,True,False,False,-0.364914,-0.012444,-0.011205,-0.497321,-0.494109,-0.059357,0.65234
14,AAPL,APPLE INC,Technology,Computer Hardware,2020-06-30,USD,2020.0,7/31/2020,7/28/2021,1.725029e+10,1.741916e+10,5.968500e+10,-3.700500e+10,2.268000e+10,-9.589000e+09,-4.831000e+09,-4.758000e+09,1.309100e+10,46000000.0,1.313700e+10,1.313700e+10,-1.884000e+09,1.125300e+10,1.125300e+10,1.125300e+10,1.125300e+10,2.696000e+09,-4.300000e+08,1.627100e+10,-1.565000e+09,-2.992000e+09,-339000000.0,-5.165000e+09,-3.656000e+09,-4.410000e+08,-1.589100e+10,-1.911600e+10,-8.010000e+09,9.302500e+10,1.788200e+10,3.978000e+09,1.400650e+11,3.568700e+10,1.005920e+11,4.100000e+10,1.772790e+11,3.173440e+11,3.532500e+10,1.867500e+10,9.531800e+10,9.404800e+10,1.497440e+11,2.450620e+11,4.869600e+10,2.413600e+10,7.228200e+10,3.173440e+11,0.65234,False,False,True,False,0.023528,-0.010900,-0.011330,0.018517,0.000356,-0.009538,0.74295
15,AAPL,APPLE INC,Technology,Computer Hardware,2020-09-30,USD,2020.0,10/30/2020,7/28/2021,1.705762e+10,1.725652e+10,6.469800e+10,-4.000900e+10,2.468900e+10,-9.914000e+09,-4.936000e+09,-4.978000e+09,1.477500e+10,126000000.0,1.490100e+10,1.490100e+10,-2.228000e+09,1.267300e+10,1.267300e+10,1.267300e+10,1.267300e+10,1.324000e+09,3.877000e+09,2.057600e+10,-1.784000e+09,7.434000e+09,-51000000.0,5.531000e+09,-3.511000e+09,4.462000e+09,-1.761700e+10,-2.135700e+10,4.750000e+09,9.094300e+10,1.612000e+10,4.061000e+09,1.437130e+11,3.676600e+10,1.008870e+11,4.252200e+10,1.801750e+11,3.238880e+11,4.229600e+10,1.376900e+10,1.053920e+11,9.866700e+10,1.531570e+11,2.585490e+11,5.077900e+10,1.496600e+10,6.533900e+10,3.238880e+11,0.74295,False,False,False,True,0.083991,-0.011169,-0.009337,0.128638,0.126189,0.020621,1.69795
16,AAPL,APPLE INC,Technology,Computer Hardware,2020-12-31,USD,2021.0,1/28/2021,1/28/2022,1.693512e+10,1.711369e+10,1.114390e+11,-6.711100e+10,4.432800e+10,-1.079400e+10,-5.631000e+09,-5.163000e+09,3.353400e+10,45000000.0,3.357900e+10,3.357900e+10,-4.824000e+09,2.875500e+10,2.875500e+10,2.875500e+10,2.875500e+10,1.987000e+09,5.355000e+09,3.876300e+10,-3.500000e+09,-5.279000e+09,NaN,-8.584000e+09,-3.613000e+09,-9.780000e+08,-2.477500e+10,-3.224900e+10,-2.070000e+09,7.682600e+10,2.710100e+10,4.973000e+09,1.541060e+11,3.793300e+10,1.187450e+11,4.327000e+10,1.999480e+11,3.540540e+11,6.384600e+10,1.276200e+10,1.325070e+11,9.928100e+10,1.553230e+11,2.878300e+11,5.174400e+10,1.430100e+10,6.622400e+10,3.540540e+11,1.69795,True,False,False,False,0.722449,-0.007182,-0.008277,1.269645,1.268997,0.093137,1.41045
17,AAPL,APPLE INC,Technology,Computer Hardware,2021-03-31,USD,2021.0,4/29/2021,1/28/2022,1.675348e+10,1.692916e+10,8.958400e+10,-5.150500e+10,3.807900e+10,-1.057600e+10,-5.314000e+09,-5.262000e+09,2.750300e+10,508000000.0,2.801100e+10,2.801100e+10,-4.381000e+09,2.363000e+10,2.363000e+10,2.363000e+10,2.363000e+10,1.333000e+09,-3.779000e+09,2.398100e+10,-2.269000e+09,-7.895000e+09,-9000000.0,-1.036800e+10,-3.447000e+09,1.042300e+10,-1.854800e+10,-1.132600e+10,2.287000e+09,6.983400e+10,1.850300e+10,5.219000e+09,1.214650e+11,3.781500e+10,1.345390e+11,4.333900e+10,2.156930e+11,3.371580e+11,4.012700e+10,1.300300e+10,1.063850e+11,1.086420e+11,1.615950e+11,2.679800e+11,5.420300e+10,1.526100e+10,6.917800e+10,3.371580e+11,1.41045,False,True,False,False,-0.196116,-0.010726,-0.010783,-0.179847,-0.178230,-0.047722,1.29088
18,AAPL,APPLE INC,Technology,Computer Hardware,2021-06-30,USD,2021.0,7/28/2021,4/29/2022,1.684430e+10,1.702142e+10,8.143400e+10,-4.617900e+10,3.525500e+10,-1.112900e+10,-5.412000e+09,-5.717000e+09,2.412600e+10,243000000.0,2.436900e+10,2.436900e+10,-2.625000e+09,2.174400e+10,2.174400e+10,2.174400e+10,2.174400e+10,1.215000e+09,-4.697000e+09,2.109400e+10,-2.093000e+09,5.747000e+09,-4000000.0,3.572000e+09,-3.767000e+09,0.000000e+00,-2.290000e+10,-2.939600e+10,-4.730000e+09,6.169600e+10,1.747500e+10,5.178000e+09,1.144230e+11,3.861500e+10,1.319480e+11,4.485400e+10,2.154170e+11,3.298400e+11,4.040900e+10,1.603900e+10,1.077540e+11,1.057520e+11,1.578060e+11,2.655600e+11,5.498900e+10,9.233000e+09,6.428000e+10,3.298400e+11,1.29088,False,False,True,False,-0.090976,0.005421,0.005450,-0.122787,-0.079814,-0.021705,1.25374

In [152]:
# Drop rows containing Null or missing values (first row)
apple_df = apple_df.dropna().reset_index(drop = True)
apple_df

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Research & Development,Operating Income (Loss),Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Income,Net Income (Common),Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic",Q1,Q2,Q3,Q4,Revenuechange from last quarter,Shares (Basic)change from last quarter,Shares (Diluted)change from last quarter,Operating Income (Loss)change from last quarter,Net Incomechange from last quarter,Total Liabilities & Equitychange from last quarter,Next Quarter EPS
0,AAPL,APPLE INC,Technology,Computer Hardware,2017-03-31,USD,2017.0,5/3/2017,5/2/2018,2.090316e+10,2.104675e+10,5.289600e+10,-3.230500e+10,2.059100e+10,-6.494000e+09,-3.718000e+09,-2.776000e+09,1.409700e+10,587000000.0,1.468400e+10,1.468400e+10,-3.655000e+09,1.102900e+10,1.102900e+10,1.102900e+10,1.102900e+10,2.587000e+09,-3.378000e+09,1.257000e+10,-2.889000e+09,-1.135700e+10,-50000000.0,-1.420200e+10,-3.004000e+09,1.046900e+10,-6.888000e+09,4.180000e+08,-1.214000e+09,6.710100e+10,1.157900e+10,2.910000e+09,1.019900e+11,2.716300e+10,1.897400e+11,1.563900e+10,2.325420e+11,3.345320e+11,5.166900e+10,1.399100e+10,7.334200e+10,8.453100e+10,1.271080e+11,2.004500e+11,3.357900e+10,1.009250e+11,1.340820e+11,3.345320e+11,0.52762,False,True,False,False,-0.324884,-0.013753,-0.012445,-0.396507,-0.383545,0.010240,0.41948
1,AAPL,APPLE INC,Technology,Computer Hardware,2017-06-30,USD,2017.0,8/2/2017,8/1/2018,2.078035e+10,2.093400e+10,4.540800e+10,-2.792000e+10,1.748800e+10,-6.720000e+09,-3.783000e+09,-2.937000e+09,1.076800e+10,540000000.0,1.130800e+10,1.130800e+10,-2.591000e+09,8.717000e+09,8.717000e+09,8.717000e+09,8.717000e+09,3.135000e+09,-5.534000e+09,8.672000e+09,-2.277000e+09,-8.360000e+08,-181000000.0,-3.180000e+09,-3.365000e+09,9.237000e+09,-7.092000e+09,-2.078000e+09,3.414000e+09,7.675900e+10,1.239900e+10,3.146000e+09,1.128750e+11,2.928600e+10,1.847570e+11,1.825500e+10,2.322980e+11,3.451730e+11,5.521900e+10,1.847500e+10,8.130200e+10,8.986400e+10,1.314460e+11,2.127480e+11,3.444500e+10,9.852500e+10,1.324250e+11,3.451730e+11,0.41948,False,False,True,False,-0.141561,-0.005875,-0.005357,-0.236150,-0.209629,0.031809,0.52015
2,AAPL,APPLE INC,Technology,Computer Hardware,2017-09-30,USD,2017.0,11/3/2017,10/31/2019,2.059771e+10,2.073434e+10,5.257900e+10,-3.264800e+10,1.993100e+10,-6.811000e+09,-3.814000e+09,-2.997000e+09,1.312000e+10,797000000.0,1.391700e+10,1.391700e+10,-3.203000e+09,1.071400e+10,1.071400e+10,1.071400e+10,1.071400e+10,2.376000e+09,1.750000e+08,1.574900e+10,-3.865000e+09,-5.768000e+09,-81000000.0,-9.942000e+09,-3.270000e+09,6.923000e+09,-7.514000e+09,-4.089000e+09,1.718000e+09,7.418100e+10,1.787400e+10,4.855000e+09,1.286450e+11,3.378300e+10,1.947140e+11,1.817700e+10,2.466740e+11,3.753190e+11,4.424200e+10,1.847300e+10,1.008140e+11,9.720700e+10,1.404580e+11,2.412720e+11,3.586700e+10,9.833000e+10,1.340470e+11,3.753190e+11,0.52015,False,False,False,True,0.157924,-0.008789,-0.009537,0.218425,0.229093,0.087336,0.98110
3,AAPL,APPLE INC,Technology,Computer Hardware,2017-12-31,USD,2018.0,2/2/2018,1/30/2019,2.045151e+10,2.063115e+10,8.829300e+10,-5.438100e+10,3.391200e+10,-7.638000e+09,-4.231000e+09,-3.407000e+09,2.627400e+10,756000000.0,2.703000e+10,2.703000e+10,-6.965000e+09,2.006500e+10,2.006500e+10,2.006500e+10,2.006500e+10,-3.244100e+10,3.792400e+10,2.829300e+10,-2.810000e+09,-1.056400e+10,-173000000.0,-1.359000e+10,-3.339000e+09,6.971000e+09,-1.009500e+10,-7.501000e+09,7.202000e+09,7.715300e+10,2.344000e+10,4.421000e+09,1.438100e+11,3.367900e+10,2.079440e+11,2.136100e+10,2.629840e+11,4.067940e+11,8.926600e+10,1.847800e+10,1.157880e+11,1.039220e+11,1.508070e+11,2.665950e+11,3.644700e+10,1.045930e+11,1.401990e+11,4.067940e+11,0.98110,True,False,False,False,0.679245,-0.007098,-0.004977,1.002591,0.872783,0.083862,0.68768
4,AAPL,APPLE INC,Technology,Computer Hardware,2018-03-31,USD,2018.0,5/2/2018,5/1/2019,2.009951e+10,2.027397e+10,6.113700e+10,-3.771500e+10,2.342200e+10,-7.528000e+09,-4.150000e+09,-3.378000e+09,1.589400e+10,274000000.0,1.616800e+10,1.616800e+10,-2.346000e+09,1.382200e+10,1.382200e+10,1.382200e+10,1.382200e+10,8.500000e+08,-2.281000e+09,1.513000e+10,-4.195000e+09,3.277800e+10,-132000000.0,2.871000e+10,-3.190000e+09,-5.020000e+08,-2.242900e+10,-2.627200e+10,1.756800e+10,8.794000e+10,1.432400e+10,7.662000e+09,1.300530e+11,3.507700e+10,1.792860e+11,2.308600e+10,2.374490e+11,3.675020e+11,6.106700e+10,2.047800e+10,8.932000e+10,1.013620e+11,1.513040e+11,2.406240e+11,3.804400e+10,9.189800e+10,1.268780e+11,3.675020e+11,0.68768,False,True,False,False,-0.307567,-0.017211,-0.017312,-0.395067,-0.311139,-0.096589,0.58985
5,AAPL,APPLE INC,Technology,Computer Hardware,2018-06-30,USD,2018.0,8/1/2018,7/31/2019,1.952867e+10,1.970644e+10,5.326500e+10,-3.284400e+10,2.042100e+10,-7.809000e+09,-4.108000e+09,-3.701000e+09,1.261200e+10,672000000.0,1.328400e+10,1.328400e+10,-1.765000e+09,1.151900e+10,1.151900e+10,1.151900e+10,1.151900e+10,2.477000e+09,-2.173000e+09,1.448800e+10,-3.267000e+09,8.079000e+09,-126000000.0,3.947000e+09,-3.653000e+09,-6.010000e+09,-2.078200e+10,-3.152300e+10,-1.308800e+10,7.097000e+10,1.410400e+10,5.936000e+09,1.157610e+11,3.811700e+10,1.727730e+11,2.254600e+10,2.334360e+11,3.491970e+11,6.367300e+10,1.747200e+10,8.854800e+10,9.712800e+10,1.457000e+11,2.342480e+11,3.862400e+10,7.943600e+10,1.149490e+11,3.491970e+11,0.58985,False,False,True,False,-0.128760,-0.028401,-0.027993,-0.206493,-0.166618,-0.049809,0.73543
6,AAPL,APPLE INC,Technology,Computer Hardware,2018-09-30,USD,2018.0,11/5/2018,10/30/2020,1.920635e+10,1.939019e+10,6.290000e+10,-3.881600e+10,2.408400e+10,-7.966000e+09,-4.216000e+09,-3.750000e+09,1.611800e+10,303000000.0,1.642100e+10,1.642100e+10,-2.296000e+09,1.412500e+10,1.412500e+10,1.412500e+10,1.412500e+10,1.864000e+09,7.800000e+08,1.952300e+10,-3.041000e+09,5.520000e+08,-290000000.0,-3.001000e+09,-3.530000e+09,-2.700000e+07,-1.876300e+10,-2.258000e+10,-6.058000e+09,6.630100e+10,2.318600e+10,3.956000e+09,1.313390e+11,4.130400e+10,1.707990e+11,2.228300e+10,2.343860e+11,3.657250e+11,5.588800e+10,2.074800e+10,1.159290e+11,9.373500e+10,1.426490e+11,2.585780e+11,4.020100e+10,7.040000e+10,1.071470e+11,3.657250e+11,0.73543,False,False,False,True,0.180888,-0.016505,-0.016048,0.277989,0.226235,0.047331,1.05394
7,AAPL,APPLE INC,Technology,Computer Hardware,2018-12-31,USD,2019.0,1/30/2019,1/29/2020,1.894328e+10,1.909301e+10,8.431000e+10,-5.227900e+10,3.203100e+10,-8.685000e+09,-4.783000e+09,-3.902000e+09,2.334600e+10,560000000.0,2.390600e+10,2.390600e+10,-3.941000e+09,1.996500e+10,1.996500e+10,1.996500e+10,1.996500e+10,1.612000e+09,1.718000e+09,2.669000e+10,-3.355000e+09,9.422000e+09,-167000000.0,5.844000e+09,-3.568000e+09,6.000000e+06,-8.796000e+09,-1.367600e+10,1.885800e+10,8.642700e+10,1.807700e+10,4.988000e+09,1.408280e+11,3.959700e+10,1.586080e+11,3.468600e+10,2.328910e+11,3.737190e+11,4.429300e+10,2.174100e+10,1.082830e+11,9.298900e+10,1.475440e+11,2.558270e+11,4.097000e+10,8.051000e+10,1.178920e+11,3.737190e+11,1.05394,True,False,False,False,0.340382,-0.013697,-0.015326,0.448443,0.413451,0.021858,0.61836
8,AAPL,APPLE INC,Technology,Computer Hardware,2019-03-31,USD,2019.0,5/1/2019,5/1/2020,1.869628e+10,1.880258e+10,5.801500e+10,-3.619400e+10,2.182100e+10,-8.406000e+09,-4.458000e+09,-3.948000e+09,1.341500e+10,378000000.0,1.379300e+10,1.379300e+10,-2.232000e+09,1.156100e+10,1.156100e+10,1.156100e+10,1.156100e+10,1.337000e+09,-4.783000e+09,1.115500e+10,-2.363000e+09,1.574900e+10,-124000000.0,1.334800e+10,-3.443000e+09,-2.542000e+09,-2.331200e+10,-2.945700e+10,-4.954000e+09,8.009200e+10,1.508500e+10,4.884000e+09,1.233460e+11,3.874600e+10,1.453190e+11,3.458700e+10,2.186520e+11,3.419980e+11,3.044300e+10,2.242900e+10,9.377200e+10,9.020100e+10,1.423660e+11,2.361380e+11,4.280100e+10,6.455800e+10,1.058600e+11,3.419980e+11,0.61836,False,True,False,False,-0.311885,-0.013039,-0.015211,-0.425383,-0.420937,-0.084879,0.54938
9,AAPL,APPLE INC,Technology,Computer Hardware,2019-06-30,USD,2019.0,7/31/2019,7/31/2020,1.828254e+10,1.840552e+10,5.380900e+10,-3.358200e+10,2.022700e+10,-8.683000e+09,-4.426000e+09,-4.257000e+09,1.154400e+10,367000000.0,1.191100e+10,1.191100e+10,-1.867000e+09,1.004400e+10,1.004400e+10,1.004400e+10,1.004400e+10,1.582000e+09,-2.923000e+09,1.163600e+10,-2.000000e+09,3.012000e+10,-320000000.0,2.750200e+10,-3.629000e+09,-4.990000e+09,-1.695400e+10,-2.680400e+10,1.233400e+10,9.461400e+10,1.414800e+10,3.355000e+09,1.349730e+11,3.763600e+10,1.159960e+11,3.363400e+10,1.872660e+11,3.222390e+11,2.911500e+10,2.348200e+10,8.970400e+10,8.493600e+10,1.360790e+11,2.257830e+11,4.337100e+10,5.372400e+10,9.645600e+10,3.222390e+11,0.54938,False,False,True,False,-0.072498,-0.022130,-0.021118,-0.139471,-0.131217,-0.057775,0.76189
10,AAPL,APPLE INC,Technology,Computer Hardware,2019-09-30,USD,2019.0,10/31/2019,10/29/2021,1.796324e+10,1.808150e+10,6.404000e+10,-3.972700e+10,2.431300e+10,-8.688000e+09,-4.578000e+09,-4.110000e+09,1.562500e+10,502000000.0,1.612700e+10,1.612700e+10,-2.441000e+09,1.368600e+10,1.368600e+10,1.368600e+10,1.368600e+10,5.450000e+08,2.500000e+09,1.991000e+10,-2.777000e+09,2.802000e+09,-13000000.0,-7.980000e+08,-3.479000e+09,-2.930000e+08,-1.705400e+10,-2.103900e+10,-1.927000e+09,1.005570e+11,2.292600e+10,4.106000e+09,1.628190e+11,3.737800e+10,1.053410e+11,3.297800e+10,1.756970e+11,3.385160e+11,4.623600e+10,1.624000e+10,1.057180e+11,9.180700e+10,1.423100e+11,2.480280e+11,4.517400e+10,4.589800e+10,9.048800e+10,3.385160e+11,0.76189,False,False,False,True,0.190135,-0.017464,-0.017604,0.353517,0.362605,0.050512,1.25911
11,AAPL,APPLE INC,Technology,Computer Hardware,2019-12-31,USD,2020.0,1/29/2020,1/28/2021,1.766016e+10,1.781842e+10,9.181900e+10,-5.660200e+10,3.521700e+10,-9.648000e+09,-5.197000e+09,-4.451000e+09,2.556900e+10,349000000.0,2.591800e+10,2.591800e+10,-3.682000e+09,2.223600e+10,2.223600e+10,2.223600e+10,2.223600e+10,1.219000e+09,4.245000e+09,3.051600e+10,-2.107000e+09,-1.039600e+10,-958000000.0,-1.366800e+10,-3.539000e+09,2.310000e+08,-2.070400e+10,-2.540700e+10,-8.559000e+09,1.071620e+11,2.097000e+10,4.097000e+09,1.632310e+11,3.703100e+10,9.989900e+10,4.045700e+10,1.773870e+11,3.406180e+11,4.511100e+10,1.521400e+10,1.021610e+11,9.307800e+10,1.489260e+11,2.510870e+11,4.597200e+10,4.397700e+10,8.953100e+10,3.406180e+11,1.25911,True,False,False,False,0.433776,-0.016872,-0.014550,0.636416,0.624726,0.006209,0.64500
12,AAPL,APPLE INC,Technology,Computer Hardware,2020-03-31,USD,2020.0,5/1/2020,4/29/2021,1.744040e+10,1.761877e+10,5.831300e+10,-3.594300e+10,2.237000e+10,-9.517000e+09,-4.952000e+09,-4.565000e+09,1.285300e+10,282000000.0,1.313500e+10,1.313500e+10,-1.886000e+09,1.124900e+10,1.124900e+10,1.124900e+10,1.124900e+10,1.278000e+09,-2.002000e+09,1.331100e+10,-1.853000e+09,1.140700e+10,-176000000.0,9.013000e+09,-3.375000e+09,-1.753000e+09,-1.814600e+10,-2.094000e+10,1.384000e+09,9.405100e+10,1.572200e+10,3.334000e+09,1.437530e+11,3.588900e+10,9.879300e+10,4.196500e+10,1.766470e+11,3.204000e+11,3.242100e+10,2.042100e+10,9.609400e+10,8.908600e+10,1.458810e+11,2.419750e+11,4.803200e+10,3.318200e+10,7.842500e+10,3.204000e+11,0.64500,False,True,False,False,-0.364914,-0.012444,-0.011205,-0.497321,-0.494109,-0.059357,0.65234
13,AAPL,APPLE INC,Technology,Computer Hardware,2020-06-30,USD,2020.0,7/31/2020,7/28/2021,1.725029e+10,1.741916e+10,5.968500e+10,-3.700500e+10,2.268000e+10,-9.589000e+09,-4.831000e+09,-4.758000e+09,1.309100e+10,46000000.0,1.313700e+10,1.313700e+10,-1.884000e+09,1.125300e+10,1.125300e+10,1.125300e+10,1.125300e+10,2.696000e+09,-4.300000e+08,1.627100e+10,-1.565000e+09,-2.992000e+09,-339000000.0,-5.165000e+09,-3.656000e+09,-4.410000e+08,-1.589100e+10,-1.911600e+10,-8.010000e+09,9.302500e+10,1.788200e+10,3.978000e+09,1.400650e+11,3.568700e+10,1.005920e+11,4.100000e+10,1.772790e+11,3.173440e+11,3.532500e+10,1.867500e+10,9.531800e+10,9.404800e+10,1.497440e+11,2.450620e+11,4.869600e+10,2.413600e+10,7.228200e+10,3.173440e+11,0.65234,False,False,True,False,0.023528,-0.010900,-0.011330,0.018517,0.000356,-0.009538,0.74295
14,AAPL,APPLE INC,Technology,Computer Hardware,2020-09-30,USD,2020.0,10/30/2020,7/28/2021,1.705762e+10,1.725652e+10,6.469800e+10,-4.000900e+10,2.468900e+10,-9.914000e+09,-4.936000e+09,-4.978000e+09,1.477500e+10,126000000.0,1.490100e+10,1.490100e+10,-2.228000e+09,1.267300e+10,1.267300e+10,1.267300e+10,1.267300e+10,1.324000e+09,3.877000e+09,2.057600e+10,-1.784000e+09,7.434000e+09,-51000000.0,5.531000e+09,-3.511000e+09,4.462000e+09,-1.761700e+10,-2.135700e+10,4.750000e+09,9.094300e+10,1.612000e+10,4.061000e+09,1.437130e+11,3.676600e+10,1.008870e+11,4.252200e+10,1.801750e+11,3.238880e+11,4.229600e+10,1.376900e+10,1.053920e+11,9.866700e+10,1.531570e+11,2.585490e+11,5.077900e+10,1.496600e+10,6.533900e+10,3.238880e+11,0.74295,False,False,False,True,0.083991,-0.011169,-0.009337,0.128638,0.126189,0.020621,1.69795
15,AAPL,APPLE INC,Technology,Computer Hardware,2021-03-31,USD,2021.0,4/29/2021,1/28/2022,1.675348e+10,1.692916e+10,8.958400e+10,-5.150500e+10,3.807900e+10,-1.057600e+10,-5.314000e+09,-5.262000e+09,2.750300e+10,508000000.0,2.801100e+10,2.801100e+10,-4.381000e+09,2.363000e+10,2.363000e+10,2.363000e+10,2.363000e+10,1.333000e+09,-3.779000e+09,2.398100e+10,-2.269000e+09,-7.895000e+09,-9000000.0,-1.036800e+10,-3.447000e+09,1.042300e+10,-1.854800e+10,-1.132600e+10,2.287000e+09,6.983400e+10,1.850300e+10,5.219000e+09,1.214650e+11,3.781500e+10,1.345390e+11,4.333900e+10,2.156930e+11,3.371580e+11,4.012700e+10,1.300300e+10,1.063850e+11,1.086420e+11,1.615950e+11,2.679800e+11,5.420300e+10,1.526100e+10,6.917800e+10,3.371580e+11,1.41045,False,True,False,False,-0.196116,-0.010726,-0.010783,-0.179847,-0.178230,-0.047722,1.29088
16,AAPL,APPLE INC,Technology,Computer Hardware,2021-06-30,USD,2021.0,7/28/2021,4/29/2022,1.684430e+10,1.702142e+10,8.143400e+10,-4.617900e+10,3.525500e+10,-1.112900e+10,-5.412000e+09,-5.717000e+09,2.412600e+10,243000000.0,2.436900e+10,2.436900e+10,-2.625000e+09,2.174400e+10,2.174400e+10,2.174400e+10,2.174400e+10,1.215000e+09,-4.697000e+09,2.109400e+10,-2.093000e+09,5.747000e+09,-4000000.0,3.572000e+09,-3.767000e+09,0.000000e+00,-2.290000e+10,-2.939600e+10,-4.730000e+09,6.169600e+10,1.747500e+10,5.178000e+09,1.144230e+11,3.861500e+10,1.319480e+11,4.485400e+10,2.154170e+11,3.298400e+11,4.040900e+10,1.603900e+10,1.077540e+11,1.057520e+11,1.578060e+11,2.655600e+11,5.498900e+10,9.233000e+09,6.428000e+10,3.298400e+11,1.29088,False,False,True,False,-0.090976,0.005421,0.005450,-0.122787,-0.079814,-0.021705,1.25374

In [153]:
# The target label for the machine learning regression model is the quarterly percentage change in EPS

# Create a function that calculates the change in next quarter's EPS
def create_regression_label(next_quarter, current_quarter):
    
    # If the current quarter EPS value is zero, we set the label to zero 
    # Calculating the % change would result in an infinite number
    if abs(current_quarter) == 0:
        return 0
    return (next_quarter - current_quarter) / abs(current_quarter)

apple_df['% Quarterly Change in EPS (Regression Label)'] =\
apple_df.apply(lambda row: create_regression_label(row['Next Quarter EPS'], row['Earnings Per Share, Basic']), axis = 1)

apple_df

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Research & Development,Operating Income (Loss),Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Income,Net Income (Common),Net Income/Starting Line,Non-Cash Items,Change in Working Capital,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic",Q1,Q2,Q3,Q4,Revenuechange from last quarter,Shares (Basic)change from last quarter,Shares (Diluted)change from last quarter,Operating Income (Loss)change from last quarter,Net Incomechange from last quarter,Total Liabilities & Equitychange from last quarter,Next Quarter EPS,% Quarterly Change in EPS (Regression Label)
0,AAPL,APPLE INC,Technology,Computer Hardware,2017-03-31,USD,2017.0,5/3/2017,5/2/2018,2.090316e+10,2.104675e+10,5.289600e+10,-3.230500e+10,2.059100e+10,-6.494000e+09,-3.718000e+09,-2.776000e+09,1.409700e+10,587000000.0,1.468400e+10,1.468400e+10,-3.655000e+09,1.102900e+10,1.102900e+10,1.102900e+10,1.102900e+10,2.587000e+09,-3.378000e+09,1.257000e+10,-2.889000e+09,-1.135700e+10,-50000000.0,-1.420200e+10,-3.004000e+09,1.046900e+10,-6.888000e+09,4.180000e+08,-1.214000e+09,6.710100e+10,1.157900e+10,2.910000e+09,1.019900e+11,2.716300e+10,1.897400e+11,1.563900e+10,2.325420e+11,3.345320e+11,5.166900e+10,1.399100e+10,7.334200e+10,8.453100e+10,1.271080e+11,2.004500e+11,3.357900e+10,1.009250e+11,1.340820e+11,3.345320e+11,0.52762,False,True,False,False,-0.324884,-0.013753,-0.012445,-0.396507,-0.383545,0.010240,0.41948,-0.204958
1,AAPL,APPLE INC,Technology,Computer Hardware,2017-06-30,USD,2017.0,8/2/2017,8/1/2018,2.078035e+10,2.093400e+10,4.540800e+10,-2.792000e+10,1.748800e+10,-6.720000e+09,-3.783000e+09,-2.937000e+09,1.076800e+10,540000000.0,1.130800e+10,1.130800e+10,-2.591000e+09,8.717000e+09,8.717000e+09,8.717000e+09,8.717000e+09,3.135000e+09,-5.534000e+09,8.672000e+09,-2.277000e+09,-8.360000e+08,-181000000.0,-3.180000e+09,-3.365000e+09,9.237000e+09,-7.092000e+09,-2.078000e+09,3.414000e+09,7.675900e+10,1.239900e+10,3.146000e+09,1.128750e+11,2.928600e+10,1.847570e+11,1.825500e+10,2.322980e+11,3.451730e+11,5.521900e+10,1.847500e+10,8.130200e+10,8.986400e+10,1.314460e+11,2.127480e+11,3.444500e+10,9.852500e+10,1.324250e+11,3.451730e+11,0.41948,False,False,True,False,-0.141561,-0.005875,-0.005357,-0.236150,-0.209629,0.031809,0.52015,0.239988
2,AAPL,APPLE INC,Technology,Computer Hardware,2017-09-30,USD,2017.0,11/3/2017,10/31/2019,2.059771e+10,2.073434e+10,5.257900e+10,-3.264800e+10,1.993100e+10,-6.811000e+09,-3.814000e+09,-2.997000e+09,1.312000e+10,797000000.0,1.391700e+10,1.391700e+10,-3.203000e+09,1.071400e+10,1.071400e+10,1.071400e+10,1.071400e+10,2.376000e+09,1.750000e+08,1.574900e+10,-3.865000e+09,-5.768000e+09,-81000000.0,-9.942000e+09,-3.270000e+09,6.923000e+09,-7.514000e+09,-4.089000e+09,1.718000e+09,7.418100e+10,1.787400e+10,4.855000e+09,1.286450e+11,3.378300e+10,1.947140e+11,1.817700e+10,2.466740e+11,3.753190e+11,4.424200e+10,1.847300e+10,1.008140e+11,9.720700e+10,1.404580e+11,2.412720e+11,3.586700e+10,9.833000e+10,1.340470e+11,3.753190e+11,0.52015,False,False,False,True,0.157924,-0.008789,-0.009537,0.218425,0.229093,0.087336,0.98110,0.886187
3,AAPL,APPLE INC,Technology,Computer Hardware,2017-12-31,USD,2018.0,2/2/2018,1/30/2019,2.045151e+10,2.063115e+10,8.829300e+10,-5.438100e+10,3.391200e+10,-7.638000e+09,-4.231000e+09,-3.407000e+09,2.627400e+10,756000000.0,2.703000e+10,2.703000e+10,-6.965000e+09,2.006500e+10,2.006500e+10,2.006500e+10,2.006500e+10,-3.244100e+10,3.792400e+10,2.829300e+10,-2.810000e+09,-1.056400e+10,-173000000.0,-1.359000e+10,-3.339000e+09,6.971000e+09,-1.009500e+10,-7.501000e+09,7.202000e+09,7.715300e+10,2.344000e+10,4.421000e+09,1.438100e+11,3.367900e+10,2.079440e+11,2.136100e+10,2.629840e+11,4.067940e+11,8.926600e+10,1.847800e+10,1.157880e+11,1.039220e+11,1.508070e+11,2.665950e+11,3.644700e+10,1.045930e+11,1.401990e+11,4.067940e+11,0.98110,True,False,False,False,0.679245,-0.007098,-0.004977,1.002591,0.872783,0.083862,0.68768,-0.299072
4,AAPL,APPLE INC,Technology,Computer Hardware,2018-03-31,USD,2018.0,5/2/2018,5/1/2019,2.009951e+10,2.027397e+10,6.113700e+10,-3.771500e+10,2.342200e+10,-7.528000e+09,-4.150000e+09,-3.378000e+09,1.589400e+10,274000000.0,1.616800e+10,1.616800e+10,-2.346000e+09,1.382200e+10,1.382200e+10,1.382200e+10,1.382200e+10,8.500000e+08,-2.281000e+09,1.513000e+10,-4.195000e+09,3.277800e+10,-132000000.0,2.871000e+10,-3.190000e+09,-5.020000e+08,-2.242900e+10,-2.627200e+10,1.756800e+10,8.794000e+10,1.432400e+10,7.662000e+09,1.300530e+11,3.507700e+10,1.792860e+11,2.308600e+10,2.374490e+11,3.675020e+11,6.106700e+10,2.047800e+10,8.932000e+10,1.013620e+11,1.513040e+11,2.406240e+11,3.804400e+10,9.189800e+10,1.268780e+11,3.675020e+11,0.68768,False,True,False,False,-0.307567,-0.017211,-0.017312,-0.395067,-0.311139,-0.096589,0.58985,-0.142261
5,AAPL,APPLE INC,Technology,Computer Hardware,2018-06-30,USD,2018.0,8/1/2018,7/31/2019,1.952867e+10,1.970644e+10,5.326500e+10,-3.284400e+10,2.042100e+10,-7.809000e+09,-4.108000e+09,-3.701000e+09,1.261200e+10,672000000.0,1.328400e+10,1.328400e+10,-1.765000e+09,1.151900e+10,1.151900e+10,1.151900e+10,1.151900e+10,2.477000e+09,-2.173000e+09,1.448800e+10,-3.267000e+09,8.079000e+09,-126000000.0,3.947000e+09,-3.653000e+09,-6.010000e+09,-2.078200e+10,-3.152300e+10,-1.308800e+10,7.097000e+10,1.410400e+10,5.936000e+09,1.157610e+11,3.811700e+10,1.727730e+11,2.254600e+10,2.334360e+11,3.491970e+11,6.367300e+10,1.747200e+10,8.854800e+10,9.712800e+10,1.457000e+11,2.342480e+11,3.862400e+10,7.943600e+10,1.149490e+11,3.491970e+11,0.58985,False,False,True,False,-0.128760,-0.028401,-0.027993,-0.206493,-0.166618,-0.049809,0.73543,0.246809
6,AAPL,APPLE INC,Technology,Computer Hardware,2018-09-30,USD,2018.0,11/5/2018,10/30/2020,1.920635e+10,1.939019e+10,6.290000e+10,-3.881600e+10,2.408400e+10,-7.966000e+09,-4.216000e+09,-3.750000e+09,1.611800e+10,303000000.0,1.642100e+10,1.642100e+10,-2.296000e+09,1.412500e+10,1.412500e+10,1.412500e+10,1.412500e+10,1.864000e+09,7.800000e+08,1.952300e+10,-3.041000e+09,5.520000e+08,-290000000.0,-3.001000e+09,-3.530000e+09,-2.700000e+07,-1.876300e+10,-2.258000e+10,-6.058000e+09,6.630100e+10,2.318600e+10,3.956000e+09,1.313390e+11,4.130400e+10,1.707990e+11,2.228300e+10,2.343860e+11,3.657250e+11,5.588800e+10,2.074800e+10,1.159290e+11,9.373500e+10,1.426490e+11,2.585780e+11,4.020100e+10,7.040000e+10,1.071470e+11,3.657250e+11,0.73543,False,False,False,True,0.180888,-0.016505,-0.016048,0.277989,0.226235,0.047331,1.05394,0.433094
7,AAPL,APPLE INC,Technology,Computer Hardware,2018-12-31,USD,2019.0,1/30/2019,1/29/2020,1.894328e+10,1.909301e+10,8.431000e+10,-5.227900e+10,3.203100e+10,-8.685000e+09,-4.783000e+09,-3.902000e+09,2.334600e+10,560000000.0,2.390600e+10,2.390600e+10,-3.941000e+09,1.996500e+10,1.996500e+10,1.996500e+10,1.996500e+10,1.612000e+09,1.718000e+09,2.669000e+10,-3.355000e+09,9.422000e+09,-167000000.0,5.844000e+09,-3.568000e+09,6.000000e+06,-8.796000e+09,-1.367600e+10,1.885800e+10,8.642700e+10,1.807700e+10,4.988000e+09,1.408280e+11,3.959700e+10,1.586080e+11,3.468600e+10,2.328910e+11,3.737190e+11,4.429300e+10,2.174100e+10,1.082830e+11,9.298900e+10,1.475440e+11,2.558270e+11,4.097000e+10,8.051000e+10,1.178920e+11,3.737190e+11,1.05394,True,False,False,False,0.340382,-0.013697,-0.015326,0.448443,0.413451,0.021858,0.61836,-0.413287
8,AAPL,APPLE INC,Technology,Computer Hardware,2019-03-31,USD,2019.0,5/1/2019,5/1/2020,1.869628e+10,1.880258e+10,5.801500e+10,-3.619400e+10,2.182100e+10,-8.406000e+09,-4.458000e+09,-3.948000e+09,1.341500e+10,378000000.0,1.379300e+10,1.379300e+10,-2.232000e+09,1.156100e+10,1.156100e+10,1.156100e+10,1.156100e+10,1.337000e+09,-4.783000e+09,1.115500e+10,-2.363000e+09,1.574900e+10,-124000000.0,1.334800e+10,-3.443000e+09,-2.542000e+09,-2.331200e+10,-2.945700e+10,-4.954000e+09,8.009200e+10,1.508500e+10,4.884000e+09,1.233460e+11,3.874600e+10,1.453190e+11,3.458700e+10,2.186520e+11,3.419980e+11,3.044300e+10,2.242900e+10,9.377200e+10,9.020100e+10,1.423660e+11,2.361380e+11,4.280100e+10,6.455800e+10,1.058600e+11,3.419980e+11,0.61836,False,True,False,False,-0.311885,-0.013039,-0.015211,-0.425383,-0.420937,-0.084879,0.54938,-0.111553
9,AAPL,APPLE INC,Technology,Computer Hardware,2019-06-30,USD,2019.0,7/31/2019,7/31/2020,1.828254e+10,1.840552e+10,5.380900e+10,-3.358200e+10,2.022700e+10,-8.683000e+09,-4.426000e+09,-4.257000e+09,1.154400e+10,367000000.0,1.191100e+10,1.191100e+10,-1.867000e+09,1.004400e+10,1.004400e+10,1.004400e+10,1.004400e+10,1.582000e+09,-2.923000e+09,1.163600e+10,-2.000000e+09,3.012000e+10,-320000000.0,2.750200e+10,-3.629000e+09,-4.990000e+09,-1.695400e+10,-2.680400e+10,1.233400e+10,9.461400e+10,1.414800e+10,3.355000e+09,1.349730e+11,3.763600e+10,1.159960e+11,3.363400e+10,1.872660e+11,3.222390e+11,2.911500e+10,2.348200e+10,8.970400e+10,8.493600e+10,1.360790e+11,2.257830e+11,4.337100e+10,5.372400e+10,9.645600e+10,3.222390e+11,0.54938,False,False,True,False,-0.072498,-0.022130,-0.021118,-0.139471,-0.131217,-0.057775,0.76189,0.386818
10,AAPL,APPLE INC,Technology,Computer Hardware,2019-09-30,USD,2019.0,10/31/2019,10/29/2021,1.796324e+10,1.808150e+10,6.404000e+10,-3.972700e+10,2.431300e+10,-8.688000e+09,-4.578000e+09,-4.110000e+09,1.562500e+10,502000000.0,1.612700e+10,1.612700e+10,-2.441000e+09,1.368600e+10,1.368600e+10,1.368600e+10,1.368600e+10,5.450000e+08,2.500000e+09,1.991000e+10,-2.777000e+09,2.802000e+09,-13000000.0,-7.980000e+08,-3.479000e+09,-2.930000e+08,-1.705400e+10,-2.103900e+10,-1.927000e+09,1.005570e+11,2.292600e+10,4.106000e+09,1.628190e+11,3.737800e+10,1.053410e+11,3.297800e+10,1.756970e+11,3.385160e+11,4.623600e+10,1.624000e+10,1.057180e+11,9.180700e+10,1.423100e+11,2.480280e+11,4.517400e+10,4.589800e+10,9.048800e+10,3.385160e+11,0.76189,False,False,False,True,0.190135,-0.017464,-0.017604,0.353517,0.362605,0.050512,1.25911,0.652614
11,AAPL,APPLE INC,Technology,Computer Hardware,2019-12-31,USD,2020.0,1/29/2020,1/28/2021,1.766016e+10,1.781842e+10,9.181900e+10,-5.660200e+10,3.521700e+10,-9.648000e+09,-5.197000e+09,-4.451000e+09,2.556900e+10,349000000.0,2.591800e+10,2.591800e+10,-3.682000e+09,2.223600e+10,2.223600e+10,2.223600e+10,2.223600e+10,1.219000e+09,4.245000e+09,3.051600e+10,-2.107000e+09,-1.039600e+10,-958000000.0,-1.366800e+10,-3.539000e+09,2.310000e+08,-2.070400e+10,-2.540700e+10,-8.559000e+09,1.071620e+11,2.097000e+10,4.097000e+09,1.632310e+11,3.703100e+10,9.989900e+10,4.045700e+10,1.773870e+11,3.406180e+11,4.511100e+10,1.521400e+10,1.021610e+11,9.307800e+10,1.489260e+11,2.510870e+11,4.597200e+10,4.397700e+10,8.953100e+10,3.406180e+11,1.25911,True,False,False,False,0.433776,-0.016872,-0.014550,0.636416,0.624726,0.006209,0.64500,-0.487733
12,AAPL,APPLE INC,Technology,Computer Hardware,2020-03-31,USD,2020.0,5/1/2020,4/29/2021,1.744040e+10,1.761877e+10,5.831300e+10,-3.594300e+10,2.237000e+10,-9.517000e+09,-4.952000e+09,-4.565000e+09,1.285300e+10,282000000.0,1.313500e+10,1.313500e+10,-1.886000e+09,1.124900e+10,1.124900e+10,1.124900e+10,1.124900e+10,1.278000e+09,-2.002000e+09,1.331100e+10,-1.853000e+09,1.140700e+10,-176000000.0,9.013000e+09,-3.375000e+09,-1.753000e+09,-1.814600e+10,-2.094000e+10,1.384000e+09,9.405100e+10,1.572200e+10,3.334000e+09,1.437530e+11,3.588900e+10,9.879300e+10,4.196500e+10,1.766470e+11,3.204000e+11,3.242100e+10,2.042100e+10,9.609400e+10,8.908600e+10,1.458810e+11,2.419750e+11,4.803200e+10,3.318200e+10,7.842500e+10,3.204000e+11,0.64500,False,True,False,False,-0.364914,-0.012444,-0.011205,-0.497321,-0.494109,-0.059357,0.65234,0.011380
13,AAPL,APPLE INC,Technology,Computer Hardware,2020-06-30,USD,2020.0,7/31/2020,7/28/2021,1.725029e+10,1.741916e+10,5.968500e+10,-3.700500e+10,2.268000e+10,-9.589000e+09,-4.831000e+09,-4.758000e+09,1.309100e+10,46000000.0,1.313700e+10,1.313700e+10,-1.884000e+09,1.125300e+10,1.125300e+10,1.125300e+10,1.125300e+10,2.696000e+09,-4.300000e+08,1.627100e+10,-1.565000e+09,-2.992000e+09,-339000000.0,-5.165000e+09,-3.656000e+09,-4.410000e+08,-1.589100e+10,-1.911600e+10,-8.010000e+09,9.302500e+10,1.788200e+10,3.978000e+09,1.400650e+11,3.568700e+10,1.005920e+11,4.100000e+10,1.772790e+11,3.173440e+11,3.532500e+10,1.867500e+10,9.531800e+10,9.404800e+10,1.497440e+11,2.450620e+11,4.869600e+10,2.413600e+10,7.228200e+10,3.173440e+11,0.65234,False,False,True,False,0.023528,-0.010900,-0.011330,0.018517,0.000356,-0.009538,0.74295,0.138900
14,AAPL,APPLE INC,Technology,Computer Hardware,2020-09-30,USD,2020.0,10/30/2020,7/28/2021,1.705762e+10,1.725652e+10,6.469800e+10,-4.000900e+10,2.468900e+10,-9.914000e+09,-4.936000e+09,-4.978000e+09,1.477500e+10,126000000.0,1.490100e+10,1.490100e+10,-2.228000e+09,1.267300e+10,1.267300e+10,1.267300e+10,1.267300e+10,1.324000e+09,3.877000e+09,2.057600e+10,-1.784000e+09,7.434000e+09,-51000000.0,5.531000e+09,-3.511000e+09,4.462000e+09,-1.761700e+10,-2.135700e+10,4.750000e+09,9.094300e+10,1.612000e+10,4.061000e+09,1.437130e+11,3.676600e+10,1.008870e+11,4.252200e+10,1.801750e+11,3.238880e+11,4.229600e+10,1.376900e+10,1.053920e+11,9.866700e+10,1.531570e+11,2.585490e+11,5.077900e+10,1.496600e+10,6.533900e+10,3.238880e+11,0.74295,False,False,False,True,0.083991,-0.011169,-0.009337,0.128638,0.126189,0.020621,1.69795,1.285416
15,AAPL,APPLE INC,Technology,Computer Hardware,2021-03-31,USD,2021.0,4/29/2021,1/28/2022,1.675348e+10,1.692916e+10,8.958400e+10,-5.150500e+10,3.807900e+10,-1.057600e+10,-5.314000e+09,-5.262000e+09,2.750300e+10,508000000.0,2.801100e+10,2.801100e+10,-4.381000e+09,2.363000e+10,2.363000e+10,2.363000e+10,2.363000e+10,1.333000e+09,-3.779000e+09,2.398100e+10,-2.269000e+09,-7.895000e+09,-9000000.0,-1.036800e+10,-3.447000e+09,1.042300e+10,-1.854800e+10,-1.132600e+10,2.287000e+09,6.983400e+10,1.850300e+10,5.219000e+09,1.214650e+11,3.781500e+10,1.345390e+11,4.333900e+10,2.156930e+11,3.371580e+11,4.012700e+10,1.300300e+10,1.063850e+11,1.086420e+11,1.615950e+11,2.679800e+11,5.420300e+10,1.526100e+10,6.917800e+10,3.371580e+11,1.41045,False,True,False,False,-0.196116,-0.010726,-0.010783,-0.179847,-0.178230,-0.047722,1.29088,-0.084774
16,AAPL,APPLE INC,Technology,Computer Hardware,2021-06-30,USD,2021.0,7/28/2021,4/29/2022,1.684430e+10,1.702142e+10,8.143400e+10,-4.617900e+10,3.525500e+10,-1.112900e+10,-5.412000e+09,-5.717000e+09,2.412600e+10,243000000.0,2.436900e+10,2.436900e+10,-2.625000e+09,2.174400e+10,2.174400e+10,2.174400e+10,2.174400e+10,1.215000e+09,-4.697000e+09,2.109400e+10,-2.093000e+09,5.747000e+09,-4000000.0,3.572000e+09,-3.767000e+09,0.000000e+00,-2.290000e+10,-2.939600e+10,-4.730000e+09,6.169600e+10,1.747500e+10,5.178000e+09,1.144230e+11,3.861500e+10,1.319480e+11,4.485400e+10,2.154170e+11,3.298400e+11,4.040900e+10,1.603900e+10,1.077540e+11,1.057520e+11,1.578060e+11,2.655600e+11,5.498900e+10,9.233000e+09,6.428000e+10,3.298400e+11,1.29088,False,False,True,False,-0.090976,0.005421,0.005450,-0.122787,-0.079814,-0.021705,1.25374,-0.028771